In [290]:
from glob import glob
import pandas as pd

In [291]:


def num_sort_key(s):
    s_original = s
    if "/" in s:
        s = s.split("/")[-1]
    if len(s) > 1 and s[0] == "P":
        s = s[1:]
    if s.isdigit():
        return int(s)
    else:
        return s_original
    

    
for peptide_num_path in sorted(glob("../cellranger-vdj-outputs/*"), key=num_sort_key):
    peptide_num = peptide_num_path.split("/")[-1]
    print(peptide_num, peptide_num_path)

P1 ../cellranger-vdj-outputs/P1
P2 ../cellranger-vdj-outputs/P2
P3 ../cellranger-vdj-outputs/P3
P4 ../cellranger-vdj-outputs/P4
P5 ../cellranger-vdj-outputs/P5
P6 ../cellranger-vdj-outputs/P6
P7 ../cellranger-vdj-outputs/P7
P8 ../cellranger-vdj-outputs/P8
P9 ../cellranger-vdj-outputs/P9
P10 ../cellranger-vdj-outputs/P10
P11 ../cellranger-vdj-outputs/P11
P12 ../cellranger-vdj-outputs/P12
P13 ../cellranger-vdj-outputs/P13
P14 ../cellranger-vdj-outputs/P14
P15 ../cellranger-vdj-outputs/P15

In [292]:
ls ../cellranger-vdj-outputs/P1

all_contig.fasta                 consensus.fasta
all_contig.fasta.fai             consensus.fasta.fai
all_contig_annotations.csv       consensus_annotations.csv
clonotypes.csv                   filtered_contig.fasta
concat_ref.fasta                 filtered_contig_annotations.csv
concat_ref.fasta.fai             metrics_summary.csv

In [293]:
!head ../cellranger-vdj-outputs/P1/clonotypes.csv

clonotype_id,frequency,proportion,cdr3s_aa,cdr3s_nt,inkt_evidence,mait_evidence
clonotype1,83,0.017667092379736057,TRB:CASSIPGTGSVTGELFF;TRA:CAATETSYDKVIF,TRB:TGTGCCAGCAGCATCCCCGGGACAGGGTCCGTCACCGGGGAGCTGTTTTTT;TRA:TGTGCAGCAACGGAAACCTCCTACGACAAGGTGATATTT,,
clonotype2,60,0.01277139208173691,TRB:CASRGGGSTDTQYF;TRA:CAALETSYDKVIF,TRB:TGTGCCAGCAGAGGGGGTGGGAGCACAGATACGCAGTATTTT;TRA:TGTGCAGCTCTGGAAACCTCCTACGACAAGGTGATATTT,,
clonotype3,38,0.008088548318433376,TRB:CSVDQTSEGSNTEAFF;TRA:CAPVAGGSYIPTF,TRB:TGCAGCGTTGACCAAACCTCGGAAGGGTCAAACACTGAAGCTTTCTTT;TRA:TGTGCTCCGGTAGCAGGAGGAAGCTACATACCTACATTT,,
clonotype4,36,0.007662835249042145,TRB:CASSRANSNQPQHF;TRA:CAMREGKGAGNMLTF,TRB:TGTGCCAGCAGCCGGGCAAATAGCAATCAGCCCCAGCATTTT;TRA:TGTGCAATGAGAGAGGGCAAGGGTGCAGGCAACATGCTCACCTTT,,
clonotype5,22,0.004682843763303533,TRB:CASSPGLAGPEQYF;TRA:CAVSHTGNQFYF,TRB:TGCGCCAGCAGCCCGGGACTAGCGGGGCCCGAGCAGTACTTC;TRA:TGTGCTGTGTCCCATACCGGTAACCAGTTCTATTTT,,
clonotype6,22,0.004682843763303533,TRB:CASSFLGQGNTEAFF,TRB:TGTGCCAGCAGCTTCCTGGGACAGGGGAACACTGAAGCTTTCTTT,,
clonotype7,22,0.004682843763303533,TRB:CASSPTGPGGRNTIYF;TRA:CAVGASGTYKYIF,TRB:TGTGCCAGCAGCCCGACGGGCCCAGGGGGAAGAAACACCATATATTTT;TRA:TGTGCTGTGGGTGCCTCAGGAACCTACAAATACATCTTT,,
clonotype8,21,0.004469987228607918,TRB:CASSFRAGASEQFF;TRA:CAIAYNNNDMRF,TRB:TGCGCCAGCAGCTTCCGAGCAGGGGCATCGGAGCAGTTCTTC;TRA:TGTGCTATAGCGTACAATAACAATGACATGCGCTTT,,
clonotype9,21,0.004469987228607918,TRB:CASSFLGQGNTEAFF;TRA:CAESGETSYDKVIF,TRB:TGTGCCAGCAGCTTCCTGGGACAGGGGAACACTGAAGCTTTCTTT;TRA:TGTGCAGAGAGTGGGGAAACCTCCTACGACAAGGTGATATTT,,

In [294]:
!head ../cellranger-vdj-outputs/P1/consensus.fasta

>clonotype1_consensus_1
ACAGTGATCCTGATCTGGTAAAGCTCCCATCCTGCCCTGACCCTGCCATGGGCACCAGGCTCCTCTTCTGGGTGGCCTTCTGTCTCCTGGGGGCAGATCACACAGGAGCTGGAGTCTCCCAGTCCCCCAGTAACAAGGTCACAGAGAAGGGAAAGGATGTAGAGCTCAGGTGTGATCCAATTTCAGGTCATACTGCCCTTTACTGGTACCGACAGAGCCTGGGGCAGGGCCTGGAGTTTTTAATTTACTTCCAAGGCAACAGTGCACCAGACAAATCAGGGCTGCCCAGTGATCGCTTCTCTGCAGAGAGGACTGGGGGATCCGTCTCCACTCTGACGATCCAGCGCACACAGCAGGAGGACTCGGCCGTGTATCTCTGTGCCAGCAGCATCCCCGGGACAGGGTCCGTCACCGGGGAGCTGTTTTTTGGAGAAGGCTCTAGGCTGACCGTACTGGAGGACCTGAAAAACGTGTTCCCACCCGAGGTCGCTGTGTTTGAGCCATCAGA
>clonotype1_consensus_2
GATCTTAATTGGGAAGAACAAGGATGACATCCATTCGAGCTGTATTTATATTCCTGTGGCTGCAGCTGGACTTGGTGAATGGAGAGAATGTGGAGCAGCATCCTTCAACCCTGAGTGTCCAGGAGGGAGACAGCGCTGTTATCAAGTGTACTTATTCAGACAGTGCCTCAAACTACTTCCCTTGGTATAAGCAAGAACTTGGAAAAGGACCTCAGCTTATTATAGACATTCGTTCAAATGTGGGCGAAAAGAAAGACCAACGAATTGCTGTTACATTGAACAAGACAGCCAAACATTTCTCCCTGCACATCACAGAGACCCAACCTGAAGACTCGGCTGTCTACTTCTGTGCAGCAACGGAAACCTCCTACGACAAGGTGATATTTGGGCCAGGGACAAGCTTATCAGTCATTCCAAATATCCAGAACCCTGACCCTGCCGTGTACCAGCTGAGAGACT
>clonotype2_consensus_1
AAAATGCCCCTCCTTTCCTCCACAGGACCAGATGCCTGAGCTAGGAAAGGCCTCATTCCTGCTGTGATCCTGCCATGGATACCTGGCTCGTATGCTGGGCAATTTTTAGTCTCTTGAAAGCAGGACTCACAGAACCTGAAGTCACCCAGACTCCCAGCCATCAGGTCACACAGATGGGACAGGAAGTGATCTTGCGCTGTGTCCCCATCTCTAATCACTTATACTTCTATTGGTACAGACAAATCTTGGGGCAGAAAGTCGAGTTTCTGGTTTCCTTTTATAATAATGAAATCTCAGAGAAGTCTGAAATATTCGATGATCAATTCTCAGTTGAAAGGCCTGATGGATCAAATTTCACTCTGAAGATCCGGTCCACAAAGCTGGAGGACTCAGCCATGTACTTCTGTGCCAGCAGAGGGGGTGGGAGCACAGATACGCAGTATTTTGGCCCAGGCACCCGGCTGACAGTGCTCGAGGACCTGAAAAACGTGTTCCCACCCGAGGTCGCTGTGTTTGAGCCATCAGA
>clonotype2_consensus_2
GATCTTAATTGGGAAGAACAAGGATGACATCCATTCGAGCTGTATTTATATTCCTGTGGCTGCAGCTGGACTTGGTGAATGGAGAGAATGTGGAGCAGCATCCTTCAACCCTGAGTGTCCAGGAGGGAGACAGCGCTGTTATCAAGTGTACTTATTCAGACAGTGCCTCAAACTACTTCCCTTGGTATAAGCAAGAACTTGGAAAAAGACCTCAGCTTATTATAGACATTCGTTCAAATGTGGGCGAAAAGAAAGACCAACGAATTGCTGTTACATTGAACAAGACAGCCAAACATTTCTCCCTGCACATCACAGAGACCCAACCTGAAGACTCGGCTGTCTACTTCTGTGCAGCTCTGGAAACCTCCTACGACAAGGTGATATTTGGGCCAGGGACAAGCTTATCAGTCATTCCAAATATCCAGAAGCCTGACCCTGCCGTGTACCAGCTGAGAGACT
>clonotype3_consensus_1
GAAGGAAAGATGAACTTGAGTTTCACTTCTTAGTGCCTTTTCTCAGGGGAGAGGCCATCACTTGAAGATGCTGAGTCTTCTGCTCCTTCTCCTGGGACTAGGCTCTGTGTTCAGTGCTGTCATCTCTCAAAAGCCAAGCAGGGATATCTGTCAACGTGGAACCTCCCTGACGATCCAGTGTCAAGTCGATAGCCAAGTCACCATGATGTTCTGGTACCGTCAGCAACCTGGACAGAGCCTGACACTGATCGCAACTGCAAATCAGGGCTCTGAGGCCACATATGAGAGTGGATTTGTCATTGACAAGTTTCCCATCAGCCGCCCAAACCTAACATTCTCAACTCTGACTGTGAGCAACATGAGCCCTGAAGACAGCAGCATATATCTCTGCAGCGTTGACCAAACCTCGGAAGGGTCAAACACTGAAGCTTTCTTTGGACAAGGCACCAGACTCACAGTTGTAGAGGACCTGAACAAGGTGTTCCCACCCGAGGTCGCTGTGTTTGAGCCATCAGA

In [295]:
!head ../cellranger-vdj-outputs/P1/clonotypes.csv

clonotype_id,frequency,proportion,cdr3s_aa,cdr3s_nt,inkt_evidence,mait_evidence
clonotype1,83,0.017667092379736057,TRB:CASSIPGTGSVTGELFF;TRA:CAATETSYDKVIF,TRB:TGTGCCAGCAGCATCCCCGGGACAGGGTCCGTCACCGGGGAGCTGTTTTTT;TRA:TGTGCAGCAACGGAAACCTCCTACGACAAGGTGATATTT,,
clonotype2,60,0.01277139208173691,TRB:CASRGGGSTDTQYF;TRA:CAALETSYDKVIF,TRB:TGTGCCAGCAGAGGGGGTGGGAGCACAGATACGCAGTATTTT;TRA:TGTGCAGCTCTGGAAACCTCCTACGACAAGGTGATATTT,,
clonotype3,38,0.008088548318433376,TRB:CSVDQTSEGSNTEAFF;TRA:CAPVAGGSYIPTF,TRB:TGCAGCGTTGACCAAACCTCGGAAGGGTCAAACACTGAAGCTTTCTTT;TRA:TGTGCTCCGGTAGCAGGAGGAAGCTACATACCTACATTT,,
clonotype4,36,0.007662835249042145,TRB:CASSRANSNQPQHF;TRA:CAMREGKGAGNMLTF,TRB:TGTGCCAGCAGCCGGGCAAATAGCAATCAGCCCCAGCATTTT;TRA:TGTGCAATGAGAGAGGGCAAGGGTGCAGGCAACATGCTCACCTTT,,
clonotype5,22,0.004682843763303533,TRB:CASSPGLAGPEQYF;TRA:CAVSHTGNQFYF,TRB:TGCGCCAGCAGCCCGGGACTAGCGGGGCCCGAGCAGTACTTC;TRA:TGTGCTGTGTCCCATACCGGTAACCAGTTCTATTTT,,
clonotype6,22,0.004682843763303533,TRB:CASSFLGQGNTEAFF,TRB:TGTGCCAGCAGCTTCCTGGGACAGGGGAACACTGAAGCTTTCTTT,,
clonotype7,22,0.004682843763303533,TRB:CASSPTGPGGRNTIYF;TRA:CAVGASGTYKYIF,TRB:TGTGCCAGCAGCCCGACGGGCCCAGGGGGAAGAAACACCATATATTTT;TRA:TGTGCTGTGGGTGCCTCAGGAACCTACAAATACATCTTT,,
clonotype8,21,0.004469987228607918,TRB:CASSFRAGASEQFF;TRA:CAIAYNNNDMRF,TRB:TGCGCCAGCAGCTTCCGAGCAGGGGCATCGGAGCAGTTCTTC;TRA:TGTGCTATAGCGTACAATAACAATGACATGCGCTTT,,
clonotype9,21,0.004469987228607918,TRB:CASSFLGQGNTEAFF;TRA:CAESGETSYDKVIF,TRB:TGTGCCAGCAGCTTCCTGGGACAGGGGAACACTGAAGCTTTCTTT;TRA:TGTGCAGAGAGTGGGGAAACCTCCTACGACAAGGTGATATTT,,

In [296]:
!head ../cellranger-vdj-outputs/P1/filtered_contig_annotations.csv

barcode,is_cell,contig_id,high_confidence,length,chain,v_gene,d_gene,j_gene,c_gene,full_length,productive,fwr1,fwr1_nt,cdr1,cdr1_nt,fwr2,fwr2_nt,cdr2,cdr2_nt,fwr3,fwr3_nt,cdr3,cdr3_nt,fwr4,fwr4_nt,reads,umis,raw_clonotype_id,raw_consensus_id,exact_subclonotype_id
AAACCTGAGAACTCGG-1,true,AAACCTGAGAACTCGG-1_contig_1,true,507,TRB,TRBV6-2,,TRBJ2-7,TRBC2,true,true,NAGVTQTPKFRVLKTGQSMTLLCAQD,AATGCTGGTGTCACTCAGACCCCAAAATTCCGGGTCCTGAAGACAGGACAGAGCATGACACTGCTGTGTGCCCAGGAT,MNHEY,ATGAACCATGAATAC,MYWYRQDPGMGLRLIHY,ATGTACTGGTATCGACAAGACCCAGGCATGGGGCTGAGGCTGATTCATTAC,SVGEGT,TCAGTTGGTGAGGGTACA,TAKGEVPDGYNVSRLKKQNFLLGLESAAPSQTSVYF,ACTGCCAAAGGAGAGGTCCCTGATGGCTACAATGTCTCCAGATTAAAAAAACAGAATTTCCTGCTGGGGTTGGAGTCGGCTGCTCCCTCCCAAACATCTGTGTACTTC,CASSYSSGLLVGEQYF,TGTGCCAGCAGTTACAGCTCCGGGCTCCTGGTGGGCGAGCAGTACTTC,GPGTRLTVT,GGGCCGGGCACCAGGCTCACGGTCACAG,3246,5,clonotype2556,clonotype2556_consensus_1,1
AAACCTGAGCGTGAAC-1,true,AAACCTGAGCGTGAAC-1_contig_1,true,488,TRA,TRAV36/DV7,,TRAJ18,TRAC,true,true,EDKVVQSPLSLVVHEGDTVTLNCSYE,GAAGACAAGGTGGTACAAAGCCCTCTATCTCTGGTTGTCCACGAGGGAGACACTGTAACTCTCAATTGCAGTTATGAA,VTNFRS,GTGACTAACTTTCGAAGC,LLWYKQEKKAPTFLFM,CTACTATGGTACAAGCAGGAAAAGAAAGCTCCCACATTTCTATTTATG,LTSSGIE,CTAACTTCAAGTGGAATTGAA,KKSGRLSSILDKKELFSILNITATQTGDSAVYL,AAGAAGTCAGGAAGACTAAGTAGCATATTAGATAAGAAAGAACTTTTCAGCATCCTGAACATCACAGCCACCCAGACCGGAGACTCGGCCGTCTACCTC,CAVAGGSTLGRLYF,TGTGCTGTGGCCGGAGGCTCAACCCTGGGGAGGCTATACTTT,GRGTQLTVWP,GGAAGAGGAACTCAGTTGACTGTCTGGCCTG,1020,3,clonotype2340,clonotype2340_consensus_2,1
AAACCTGAGCGTGAAC-1,true,AAACCTGAGCGTGAAC-1_contig_2,true,533,TRB,TRBV18,,TRBJ1-5,TRBC1,true,true,NAGVMQNPRHLVRRRGQEARLRCSPM,AATGCCGGCGTCATGCAGAACCCAAGACACCTGGTCAGGAGGAGGGGACAGGAGGCAAGACTGAGATGCAGCCCAATG,KGHSH,AAAGGACACAGTCAT,VYWYRQLPEEGLKFMVY,GTTTACTGGTATCGGCAGCTCCCAGAGGAAGGTCTGAAATTCATGGTTTAT,LQKENI,CTCCAGAAAGAAAATATC,IDESGMPKERFSAEFPKEGPSILRIQQVVRGDSAAYF,ATAGATGAGTCAGGAATGCCAAAGGAACGATTTTCTGCTGAATTTCCCAAAGAGGGCCCCAGCATCCTGAGGATCCAGCAGGTAGTGCGAGGAGATTCGGCAGCTTATTTC,CASSPLQVDQPQHF,TGTGCCAGCTCACCACTGCAGGTCGATCAGCCCCAGCATTTT,GDGTRLSIL,GGTGATGGGACTCGACTCTCCATCCTAG,4764,6,clonotype2340,clonotype2340_consensus_1,1
AAACCTGCAAAGGCGT-1,true,AAACCTGCAAAGGCGT-1_contig_1,true,491,TRA,TRAV38-2/DV8,,TRAJ30,TRAC,true,true,AQTVTQSQPEMSVQEAETVTLSCTYD,GCTCAGACAGTCACTCAGTCTCAACCAGAGATGTCTGTGCAGGAGGCAGAGACCGTGACCCTGAGCTGCACATATGAC,TSESDYY,ACCAGTGAGAGTGATTATTAT,LFWYKQPPSRQMILVIR,TTATTCTGGTACAAGCAGCCTCCCAGCAGGCAGATGATTCTCGTTATTCGC,QEAYKQQN,CAAGAAGCTTATAAGCAACAGAAT,ATENRFSVNFQKAAKSFSLKISDSQLGDAAMYF,GCAACAGAGAATCGTTTCTCTGTGAACTTCCAGAAAGCAGCCAAATCCTTCAGTCTCAAGATCTCAGACTCACAGCTGGGGGATGCCGCGATGTATTTC,CAYRSAGDDKIIF,TGTGCTTATAGGAGCGCGGGAGATGACAAGATCATCTTT,GKGTRLHILP,GGAAAAGGGACACGACTTCATATTCTCCCCA,1884,4,clonotype59,clonotype59_consensus_2,1
AAACCTGCAAAGGCGT-1,true,AAACCTGCAAAGGCGT-1_contig_2,true,507,TRB,TRBV6-2,,TRBJ2-7,TRBC2,true,true,NAGVTQTPKFRVLKTGQSMTLLCAQD,AATGCTGGTGTCACTCAGACCCCAAAATTCCGGGTCCTGAAGACAGGACAGAGCATGACACTGCTGTGTGCCCAGGAT,MNHEY,ATGAACCATGAATAC,MYWYRQDPGMGLRLIHY,ATGTACTGGTATCGACAAGACCCAGGCATGGGGCTGAGGCTGATTCATTAC,SVGEGT,TCAGTTGGTGAGGGTACA,TAKGEVPDGYNVSRLKKQNFLLGLESAAPSQTSVYF,ACTGCCAAAGGAGAGGTCCCTGATGGCTACAATGTCTCCAGATTAAAAAAACAGAATTTCCTGCTGGGGTTGGAGTCGGCTGCTCCCTCCCAAACATCTGTGTACTTC,CASSYSSGLLVGEQYF,TGTGCCAGCAGTTACAGCTCCGGGCTCCTGGTGGGCGAGCAGTACTTC,GPGTRLTVT,GGGCCGGGCACCAGGCTCACGGTCACAG,6224,8,clonotype59,clonotype59_consensus_1,1
AAACCTGCAAGGTTTC-1,true,AAACCTGCAAGGTTTC-1_contig_1,true,557,TRA,TRAV26-2,,TRAJ48,TRAC,true,true,DAKTTQPNSMESNEEEPVHLPCNHS,GATGCTAAGACCACACAGCCAAATTCAATGGAGAGTAACGAAGAAGAGCCTGTTCACTTGCCTTGTAACCACTCC,TISGTDY,ACAATCAGTGGAACTGATTAC,IHWYRQLPSQGPEYVIH,ATACATTGGTATCGACAGCTTCCCTCCCAGGGTCCAGAGTACGTGATTCAT,GLTSN,GGTCTTACAAGCAAT,VNNRMASLAIAEDRKSSTLILHRATLRDAAVYY,GTGAACAACAGAATGGCCTCTCTGGCAATCGCTGAAGACAGAAAGTCCAGTACCTTGATCCTGCACCGTGCTACCTTGAGAGATGCTGCTGTGTACTAC,CILRDRSFGNEKLTF,TGCATCCTGAGAGACAGGAGCTTTGGAAATGAGAAATTAACCTTT,GTGTRLTIIP,GGGACTGGAACAAGACTCACCATCATACCCA,9461,13,clonotype76,clonotype76_consensus_2,1
AAACCTGCAAGGTTTC-1,true,AAACCTGCAAGGTTTC-1_contig_2,true,511,TRB,TRBV12-4,,TRBJ1-1,TRBC1,true,true,DAGVIQSPRHEVTEMGQEVTLRCKPI,GATGCTGGAGTTATCCAGTCACCCCGGCACGAGGTGACAGAGATGGGACAAGAAGTGACTCTGAGATGTAAACCAATT,SGHDY,TCAGGACACGACTAC,LFWYRQTMMRGLELLIY,CTTTTCTGGTACAGACAGACCATGATGCGGGGACTGGAGTTGCTCATTTAC,FNNNVP,TTTAACAACAACGTTCCG,IDDSGMPEDRFSAKMPNASFSTLKIQPSEPRDSAVYF,ATAGATGATTCAGGGATGCCCGAGGATCGATTCTCAGCTAAGATGCCTAATGCATCATTCTCCACTCTGAAGATCCAGCCCTCAGAACCCAGGGACTCAGCTGTGTACTTC,CASSLNRMNTEAFF,TGTGCCAGCAGTTTGAACAGGATGAACACTGAAGCTTTCTTT,GQGTRLTVV,GGACAAGGCACCAGACTCACAGTTGTAG,19735,28,clonotype76,clonotype76_consensus_1,1
AAACCTGGTGATGCCC-1,true,AAACCTGGTGATGCCC-1_contig_1,true,456,TRA,TRAV13-1,,TRAJ49,TRAC,true,true,GENVEQHPSTLSVQEGDSAVIKCTYS,GGAGAGAATGTGGAGCAGCATCCTTCAACCCTGAGTGTCCAGGAGGGAGACAGCGCTGTTATCAAGTGTACTTATTCA,DSASNY,GACAGTGCCTCAAACTAC,FPWYKQELGKGPQLIID,TTCCCTTGGTATAAGCAAGAACTTGGAAAAGGACCTCAGCTTATTATAGAC,IRSNVGE,ATTCGTTCAAATGTGGGCGAA,KKDQRIAVTLNKTAKHFSLHITETQPEDSAVYF,AAGAAAGACCAACGAATTGCTGTTACATTGAACAAGACAGCCAAACATTTCTCCCTGCACATCACAGAGACCCAACCTGAAGACTCGGCTGTCTACTTC,CAAPPTGNQFYF,TGTGCAGCACCTCCCACCGGTAACCAGTTCTATTTT,GTGTSLTVIP,GGGACAGGGACAAGTTTGACGGTCATTCCAA,1700,3,clonotype959,clonotype959_consensus_2,1
AAACCTGGTGATGCCC-1,true,AAACCTGGTGATGCCC-1_contig_2,true,470,TRB,TRBV10-3,,TRBJ1-1,TRBC1,true,true,DAGITQSPRHKVTETGTPVTLRCHQT,GATGCTGGAATCACCCAGAGCCCAAGACACAAGGTCACAGAGACAGGAACACCAGTGACTCTGAGATGTCACCAGACT,ENHRY,GAGAACCACCGCTAT,MYWYRQDPGHGLRLIHY,ATGTACTGGTATCGACAAGACCCGGGGCATGGGCTGAGGCTGATCCATTAC,SYGVKD,TCATATGGTGTTAAAGAT,TDKGEVSDGYSVSRSKTEDFLLTLESATSSQTSVYF,ACTGACAAAGGAGAAGTCTCAGATGGCTATAGTGTCTCTAGATCAAAGACAGAGGATTTCCTCCTCACTCTGGAGTCCGCTACCAGCTCCCAGACATCTGTGTACTTC,CAIRASLNTEAFF,TGTGCCATCAGGGCCTCCCTGAACACTGAAGCTTTCTTT,GQGTRLTVV,GGACAAGGCACCAGACTCACAGTTGTAG,2604,4,clonotype959,clonotype959_consensus_1,1

In [297]:

def num_sort_key(s):
    s_original = s
    if "/" in s:
        s = s.split("/")[-1]
    if len(s) > 1 and s[0] == "P":
        s = s[1:]
    if s.isdigit():
        return int(s)
    else:
        return s_original

peptide_num_to_filtered_contig_annots = {}
for peptide_num_path in sorted(glob("../cellranger-vdj-outputs/*"), key=num_sort_key):
    peptide_num = peptide_num_path.split("/")[-1]
    df_filtered_contig_annots = pd.read_csv("../cellranger-vdj-outputs/%s/filtered_contig_annotations.csv" % peptide_num)
    df_filtered_contig_annots["sample_peptide"] = peptide_num
    df_filtered_contig_annots["sample_path"] = peptide_num_path
    peptide_num_to_filtered_contig_annots[peptide_num] = df_filtered_contig_annots
    print(peptide_num, len(df_filtered_contig_annots))

df = pd.concat(list(peptide_num_to_filtered_contig_annots.values()))
df

P1 9099
P2 8644
P3 16044
P4 5658
P5 14558
P6 11103
P7 15232
P8 6491
P9 10784
P10 8292
P11 7545
P12 22433
P13 10035
P14 18130
P15 17754

,barcode,is_cell,contig_id,high_confidence,length,chain,v_gene,d_gene,j_gene,c_gene,...,cdr3_nt,fwr4,fwr4_nt,reads,umis,raw_clonotype_id,raw_consensus_id,exact_subclonotype_id,sample_peptide,sample_path
0,AAACCTGAGAACTCGG-1,True,AAACCTGAGAACTCGG-1_contig_1,True,507,TRB,TRBV6-2,NaN,TRBJ2-7,TRBC2,...,TGTGCCAGCAGTTACAGCTCCGGGCTCCTGGTGGGCGAGCAGTACTTC,GPGTRLTVT,GGGCCGGGCACCAGGCTCACGGTCACAG,3246,5,clonotype2556,clonotype2556_consensus_1,1,P1,../cellranger-vdj-outputs/P1
1,AAACCTGAGCGTGAAC-1,True,AAACCTGAGCGTGAAC-1_contig_1,True,488,TRA,TRAV36/DV7,NaN,TRAJ18,TRAC,...,TGTGCTGTGGCCGGAGGCTCAACCCTGGGGAGGCTATACTTT,GRGTQLTVWP,GGAAGAGGAACTCAGTTGACTGTCTGGCCTG,1020,3,clonotype2340,clonotype2340_consensus_2,1,P1,../cellranger-vdj-outputs/P1
2,AAACCTGAGCGTGAAC-1,True,AAACCTGAGCGTGAAC-1_contig_2,True,533,TRB,TRBV18,NaN,TRBJ1-5,TRBC1,...,TGTGCCAGCTCACCACTGCAGGTCGATCAGCCCCAGCATTTT,GDGTRLSIL,GGTGATGGGACTCGACTCTCCATCCTAG,4764,6,clonotype2340,clonotype2340_consensus_1,1,P1,../cellranger-vdj-outputs/P1
3,AAACCTGCAAAGGCGT-1,True,AAACCTGCAAAGGCGT-1_contig_1,True,491,TRA,TRAV38-2/DV8,NaN,TRAJ30,TRAC,...,TGTGCTTATAGGAGCGCGGGAGATGACAAGATCATCTTT,GKGTRLHILP,GGAAAAGGGACACGACTTCATATTCTCCCCA,1884,4,clonotype59,clonotype59_consensus_2,1,P1,../cellranger-vdj-outputs/P1
4,AAACCTGCAAAGGCGT-1,True,AAACCTGCAAAGGCGT-1_contig_2,True,507,TRB,TRBV6-2,NaN,TRBJ2-7,TRBC2,...,TGTGCCAGCAGTTACAGCTCCGGGCTCCTGGTGGGCGAGCAGTACTTC,GPGTRLTVT,GGGCCGGGCACCAGGCTCACGGTCACAG,6224,8,clonotype59,clonotype59_consensus_1,1,P1,../cellranger-vdj-outputs/P1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17749,TTTGTCAGTTTGGGCC-1,True,TTTGTCAGTTTGGGCC-1_contig_1,True,502,TRB,TRBV7-2,NaN,TRBJ2-7,TRBC2,...,TGTGCCAGCAGCTTAATAGGGACTAGCGATTACGAGCAGTACTTC,GPGTRLTVT,GGGCCGGGCACCAGGCTCACGGTCACAG,214,4,clonotype5041,clonotype5041_consensus_1,1,P15,../cellranger-vdj-outputs/P15
17750,TTTGTCATCAGCCTAA-1,True,TTTGTCATCAGCCTAA-1_contig_1,True,503,TRB,TRBV5-1,TRBD1,TRBJ1-1,TRBC1,...,TGCGCCAGCACCCGGGACAGGGGGCTGAACACTGAAGCTTTCTTT,GQGTRLTVV,GGACAAGGCACCAGACTCACAGTTGTAG,393,8,clonotype4025,clonotype4025_consensus_1,1,P15,../cellranger-vdj-outputs/P15
17751,TTTGTCATCCCAAGTA-1,True,TTTGTCATCCCAAGTA-1_contig_1,True,505,TRB,TRBV6-5,TRBD1,TRBJ1-4,TRBC1,...,TGTGCCAGCAGTGTACGGGGGGCTTCTAATGAAAAACTGTTTTTT,GSGTQLSVL,GGCAGTGGAACCCAGCTCTCTGTCTTGG,200,5,clonotype16,clonotype16_consensus_1,1,P15,../cellranger-vdj-outputs/P15
17752,TTTGTCATCTTCAACT-1,True,TTTGTCATCTTCAACT-1_contig_1,True,489,TRA,TRAV38-2/DV8,NaN,TRAJ53,TRAC,...,TGTGCTTATAGGAGCGCGGATAGCAACTATAAACTGACATTT,GKGTLLTVNP,GGAAAAGGAACTCTCTTAACCGTGAATCCAA,149,2,clonotype222,clonotype222_consensus_2,1,P15,../cellranger-vdj-outputs/P15
17753,TTTGTCATCTTCAACT-1,True,TTTGTCATCTTCAACT-1_contig_2,True,475,TRB,TRBV2,NaN,TRBJ2-3,TRBC2,...,TGTGCCAGCAGAGGGGGTGGGAGCACAGATACGCAGTATTTT,GPGTRLTVL,GGCCCAGGCACCCGGCTGACAGTGCTCG,115,3,clonotype222,clonotype222_consensus_1,1,P15,../cellranger-vdj-outputs/P15

In [298]:


def translate_dna(dna_seq, codon_table = {
        'ATA':'I', 'ATC':'I', 'ATT':'I', 'ATG':'M',
        'ACA':'T', 'ACC':'T', 'ACG':'T', 'ACT':'T',
        'AAC':'N', 'AAT':'N', 'AAA':'K', 'AAG':'K',
        'AGC':'S', 'AGT':'S', 'AGA':'R', 'AGG':'R',
        'CTA':'L', 'CTC':'L', 'CTG':'L', 'CTT':'L',
        'CCA':'P', 'CCC':'P', 'CCG':'P', 'CCT':'P',
        'CAC':'H', 'CAT':'H', 'CAA':'Q', 'CAG':'Q',
        'CGA':'R', 'CGC':'R', 'CGG':'R', 'CGT':'R',
        'GTA':'V', 'GTC':'V', 'GTG':'V', 'GTT':'V',
        'GCA':'A', 'GCC':'A', 'GCG':'A', 'GCT':'A',
        'GAC':'D', 'GAT':'D', 'GAA':'E', 'GAG':'E',
        'GGA':'G', 'GGC':'G', 'GGG':'G', 'GGT':'G',
        'TCA':'S', 'TCC':'S', 'TCG':'S', 'TCT':'S',
        'TTC':'F', 'TTT':'F', 'TTA':'L', 'TTG':'L',
        'TAC':'Y', 'TAT':'Y', 'TAA':'*', 'TAG':'*',
        'TGC':'C', 'TGT':'C', 'TGA':'*', 'TGG':'W'}):
    seq_len = len(dna_seq) 
    seq_len_trimmed = (seq_len // 3) * 3
    
    if seq_len != seq_len_trimmed:
        ragged_nt = dna_seq[seq_len_trimmed:]
        dna_seq = dna_seq[:seq_len_trimmed]
    else:
        ragged_nt = ""
        
    aa_seq = "".join([
            codon_table.get(dna_seq[i:i+3], 'X')
            for i in range(0, len(dna_seq), 3)
        ]
    )
    assert "X" not in aa_seq
    if "*" in aa_seq:
        ragged_nt = ""
        aa_seq = aa_seq[:aa_seq.index("*")]
        
    return aa_seq, ragged_nt

In [300]:
# combine TCR sequence parts into full sequence
tcr_segment_aa_cols = ["fwr1", "cdr1", "fwr2", "cdr2", "fwr3", "cdr3", "fwr4"]
tcr_segment_nt_cols = [c + "_nt" for c in tcr_segment_aa_cols]

df["combined_vdj_aa_sequence"] = df[tcr_segment_aa_cols].agg(''.join, axis=1)
df["combined_vdj_nt_sequence"] = df[tcr_segment_nt_cols].agg(''.join, axis=1)

df

,barcode,is_cell,contig_id,high_confidence,length,chain,v_gene,d_gene,j_gene,c_gene,...,fwr4_nt,reads,umis,raw_clonotype_id,raw_consensus_id,exact_subclonotype_id,sample_peptide,sample_path,combined_vdj_aa_sequence,combined_vdj_nt_sequence
0,AAACCTGAGAACTCGG-1,True,AAACCTGAGAACTCGG-1_contig_1,True,507,TRB,TRBV6-2,NaN,TRBJ2-7,TRBC2,...,GGGCCGGGCACCAGGCTCACGGTCACAG,3246,5,clonotype2556,clonotype2556_consensus_1,1,P1,../cellranger-vdj-outputs/P1,NAGVTQTPKFRVLKTGQSMTLLCAQDMNHEYMYWYRQDPGMGLRLI...,AATGCTGGTGTCACTCAGACCCCAAAATTCCGGGTCCTGAAGACAG...
1,AAACCTGAGCGTGAAC-1,True,AAACCTGAGCGTGAAC-1_contig_1,True,488,TRA,TRAV36/DV7,NaN,TRAJ18,TRAC,...,GGAAGAGGAACTCAGTTGACTGTCTGGCCTG,1020,3,clonotype2340,clonotype2340_consensus_2,1,P1,../cellranger-vdj-outputs/P1,EDKVVQSPLSLVVHEGDTVTLNCSYEVTNFRSLLWYKQEKKAPTFL...,GAAGACAAGGTGGTACAAAGCCCTCTATCTCTGGTTGTCCACGAGG...
2,AAACCTGAGCGTGAAC-1,True,AAACCTGAGCGTGAAC-1_contig_2,True,533,TRB,TRBV18,NaN,TRBJ1-5,TRBC1,...,GGTGATGGGACTCGACTCTCCATCCTAG,4764,6,clonotype2340,clonotype2340_consensus_1,1,P1,../cellranger-vdj-outputs/P1,NAGVMQNPRHLVRRRGQEARLRCSPMKGHSHVYWYRQLPEEGLKFM...,AATGCCGGCGTCATGCAGAACCCAAGACACCTGGTCAGGAGGAGGG...
3,AAACCTGCAAAGGCGT-1,True,AAACCTGCAAAGGCGT-1_contig_1,True,491,TRA,TRAV38-2/DV8,NaN,TRAJ30,TRAC,...,GGAAAAGGGACACGACTTCATATTCTCCCCA,1884,4,clonotype59,clonotype59_consensus_2,1,P1,../cellranger-vdj-outputs/P1,AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMI...,GCTCAGACAGTCACTCAGTCTCAACCAGAGATGTCTGTGCAGGAGG...
4,AAACCTGCAAAGGCGT-1,True,AAACCTGCAAAGGCGT-1_contig_2,True,507,TRB,TRBV6-2,NaN,TRBJ2-7,TRBC2,...,GGGCCGGGCACCAGGCTCACGGTCACAG,6224,8,clonotype59,clonotype59_consensus_1,1,P1,../cellranger-vdj-outputs/P1,NAGVTQTPKFRVLKTGQSMTLLCAQDMNHEYMYWYRQDPGMGLRLI...,AATGCTGGTGTCACTCAGACCCCAAAATTCCGGGTCCTGAAGACAG...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17749,TTTGTCAGTTTGGGCC-1,True,TTTGTCAGTTTGGGCC-1_contig_1,True,502,TRB,TRBV7-2,NaN,TRBJ2-7,TRBC2,...,GGGCCGGGCACCAGGCTCACGGTCACAG,214,4,clonotype5041,clonotype5041_consensus_1,1,P15,../cellranger-vdj-outputs/P15,GAGVSQSPSNKVTEKGKDVELRCDPISGHTALYWYRQSLGQGLEFL...,GGAGCTGGAGTCTCCCAGTCCCCCAGTAACAAGGTCACAGAGAAGG...
17750,TTTGTCATCAGCCTAA-1,True,TTTGTCATCAGCCTAA-1_contig_1,True,503,TRB,TRBV5-1,TRBD1,TRBJ1-1,TRBC1,...,GGACAAGGCACCAGACTCACAGTTGTAG,393,8,clonotype4025,clonotype4025_consensus_1,1,P15,../cellranger-vdj-outputs/P15,KAGVTQTPRYLIKTRGQQVTLSCSPISGHRSVSWYQQTPGQGLQFL...,AAGGCTGGAGTCACTCAAACTCCAAGATATCTGATCAAAACGAGAG...
17751,TTTGTCATCCCAAGTA-1,True,TTTGTCATCCCAAGTA-1_contig_1,True,505,TRB,TRBV6-5,TRBD1,TRBJ1-4,TRBC1,...,GGCAGTGGAACCCAGCTCTCTGTCTTGG,200,5,clonotype16,clonotype16_consensus_1,1,P15,../cellranger-vdj-outputs/P15,NAGVTQTPKFQVLKTGQSMTLQCAQDMNHEYMSWYRQDPGMGLRLI...,AATGCTGGTGTCACTCAGACCCCAAAATTCCAGGTCCTGAAGACAG...
17752,TTTGTCATCTTCAACT-1,True,TTTGTCATCTTCAACT-1_contig_1,True,489,TRA,TRAV38-2/DV8,NaN,TRAJ53,TRAC,...,GGAAAAGGAACTCTCTTAACCGTGAATCCAA,149,2,clonotype222,clonotype222_consensus_2,1,P15,../cellranger-vdj-outputs/P15,AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMI...,GCTCAGACAGTCACTCAGTCTCAACCAGAGATGTCTGTGCAGGAGG...
17753,TTTGTCATCTTCAACT-1,True,TTTGTCATCTTCAACT-1_contig_2,True,475,TRB,TRBV2,NaN,TRBJ2-3,TRBC2,...,GGCCCAGGCACCCGGCTGACAGTGCTCG,115,3,clonotype222,clonotype222_consensus_1,1,P15,../cellranger-vdj-outputs/P15,EPEVTQTPSHQVTQMGQEVILRCVPISNHLYFYWYRQILGQKVEFL...,GAACCTGAAGTCACCCAGACTCCCAGCCATCAGGTCACACAGATGG...

In [301]:
from tqdm import tqdm
aa_seqs = []
ragged_nts = []
for nt_seq in tqdm(df["combined_vdj_nt_sequence"]):
    aa_seq, ragged_nt = translate_dna(nt_seq)
    aa_seqs.append(aa_seq)
    ragged_nts.append(ragged_nt)
df["combined_vdj_translated_sequence"] = aa_seqs
df["combined_vdj_ragged_3p_nt"] = ragged_nt

100%|█████████████████████████████████████████████| 181802/181802 [00:01<00:00, 104725.38it/s]

In [302]:

assert 1.0 == (df["combined_vdj_aa_sequence"] == df["combined_vdj_translated_sequence"]).mean()

In [303]:
for a, b, in zip(df["combined_vdj_aa_sequence"], df['combined_vdj_translated_sequence']):
    print("---")
    print(a)
    print(b)
    break

---
NAGVTQTPKFRVLKTGQSMTLLCAQDMNHEYMYWYRQDPGMGLRLIHYSVGEGTTAKGEVPDGYNVSRLKKQNFLLGLESAAPSQTSVYFCASSYSSGLLVGEQYFGPGTRLTVT
NAGVTQTPKFRVLKTGQSMTLLCAQDMNHEYMYWYRQDPGMGLRLIHYSVGEGTTAKGEVPDGYNVSRLKKQNFLLGLESAAPSQTSVYFCASSYSSGLLVGEQYFGPGTRLTVT

In [304]:

# Are there doublets? (yes!)
index_cols = ['sample_path', 'sample_peptide', 'barcode']
index_cols_with_chain = index_cols + ['chain']
df[index_cols].value_counts()

sample_path                    sample_peptide  barcode
../cellranger-vdj-outputs/P9   P9              GAATGAACACACGCTG-1    4
../cellranger-vdj-outputs/P5   P5              GTTACAGGTACTTCTT-1    4
../cellranger-vdj-outputs/P15  P15             CATGCCTAGATCTGCT-1    4
../cellranger-vdj-outputs/P14  P14             ACTGTCCTCTCTAAGG-1    4
../cellranger-vdj-outputs/P5   P5              GTTCGGGAGAAGCCCA-1    4
                                                                    ..
../cellranger-vdj-outputs/P3   P3              TAGAGCTCAGTCGATT-1    1
                                               TAGAGCTCATTTCAGG-1    1
                                               TAGAGCTGTAAGTAGT-1    1
                                               TAGAGCTGTCTAACGT-1    1
../cellranger-vdj-outputs/P1   P1              AAACCTGAGAACTCGG-1    1
Name: count, Length: 98493, dtype: int64

In [305]:
# sort the dataframe to get chains with more UMIs on top


# Assuming your original dataframe is named 'df'
# and the columns include 'barcode', 'chain_type', 'umis', 'reads', and other TCR-related columns

# Step 1: Sort entries within each barcode and chain_type by UMI count

sort_keys = index_cols_with_chain + ["umis", "reads"]
sort_ascending = [True] * len(index_cols_with_chain) + [False, False]
df = df.sort_values(sort_keys, ascending=sort_ascending)
df[sort_keys]

,sample_path,sample_peptide,barcode,chain,umis,reads
0,../cellranger-vdj-outputs/P1,P1,AAACCTGAGAACTCGG-1,TRB,5,3246
1,../cellranger-vdj-outputs/P1,P1,AAACCTGAGCGTGAAC-1,TRA,3,1020
2,../cellranger-vdj-outputs/P1,P1,AAACCTGAGCGTGAAC-1,TRB,6,4764
3,../cellranger-vdj-outputs/P1,P1,AAACCTGCAAAGGCGT-1,TRA,4,1884
4,../cellranger-vdj-outputs/P1,P1,AAACCTGCAAAGGCGT-1,TRB,8,6224
...,...,...,...,...,...,...
10778,../cellranger-vdj-outputs/P9,P9,TTTGTCACATGCCACG-1,TRB,8,1637
10780,../cellranger-vdj-outputs/P9,P9,TTTGTCATCGACCAGC-1,TRA,8,1180
10781,../cellranger-vdj-outputs/P9,P9,TTTGTCATCGACCAGC-1,TRB,22,3939
10783,../cellranger-vdj-outputs/P9,P9,TTTGTCATCGCGTAGC-1,TRA,6,205
10782,../cellranger-vdj-outputs/P9,P9,TTTGTCATCGCGTAGC-1,TRB,29,1429

In [306]:

# Create a unique identifier for each TRA/TRB entry, now sorted by UMI count
df['entry_id'] = df.groupby(index_cols_with_chain).cumcount() + 1
df

,barcode,is_cell,contig_id,high_confidence,length,chain,v_gene,d_gene,j_gene,c_gene,...,raw_clonotype_id,raw_consensus_id,exact_subclonotype_id,sample_peptide,sample_path,combined_vdj_aa_sequence,combined_vdj_nt_sequence,combined_vdj_translated_sequence,combined_vdj_ragged_3p_nt,entry_id
0,AAACCTGAGAACTCGG-1,True,AAACCTGAGAACTCGG-1_contig_1,True,507,TRB,TRBV6-2,NaN,TRBJ2-7,TRBC2,...,clonotype2556,clonotype2556_consensus_1,1,P1,../cellranger-vdj-outputs/P1,NAGVTQTPKFRVLKTGQSMTLLCAQDMNHEYMYWYRQDPGMGLRLI...,AATGCTGGTGTCACTCAGACCCCAAAATTCCGGGTCCTGAAGACAG...,NAGVTQTPKFRVLKTGQSMTLLCAQDMNHEYMYWYRQDPGMGLRLI...,G,1
1,AAACCTGAGCGTGAAC-1,True,AAACCTGAGCGTGAAC-1_contig_1,True,488,TRA,TRAV36/DV7,NaN,TRAJ18,TRAC,...,clonotype2340,clonotype2340_consensus_2,1,P1,../cellranger-vdj-outputs/P1,EDKVVQSPLSLVVHEGDTVTLNCSYEVTNFRSLLWYKQEKKAPTFL...,GAAGACAAGGTGGTACAAAGCCCTCTATCTCTGGTTGTCCACGAGG...,EDKVVQSPLSLVVHEGDTVTLNCSYEVTNFRSLLWYKQEKKAPTFL...,G,1
2,AAACCTGAGCGTGAAC-1,True,AAACCTGAGCGTGAAC-1_contig_2,True,533,TRB,TRBV18,NaN,TRBJ1-5,TRBC1,...,clonotype2340,clonotype2340_consensus_1,1,P1,../cellranger-vdj-outputs/P1,NAGVMQNPRHLVRRRGQEARLRCSPMKGHSHVYWYRQLPEEGLKFM...,AATGCCGGCGTCATGCAGAACCCAAGACACCTGGTCAGGAGGAGGG...,NAGVMQNPRHLVRRRGQEARLRCSPMKGHSHVYWYRQLPEEGLKFM...,G,1
3,AAACCTGCAAAGGCGT-1,True,AAACCTGCAAAGGCGT-1_contig_1,True,491,TRA,TRAV38-2/DV8,NaN,TRAJ30,TRAC,...,clonotype59,clonotype59_consensus_2,1,P1,../cellranger-vdj-outputs/P1,AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMI...,GCTCAGACAGTCACTCAGTCTCAACCAGAGATGTCTGTGCAGGAGG...,AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMI...,G,1
4,AAACCTGCAAAGGCGT-1,True,AAACCTGCAAAGGCGT-1_contig_2,True,507,TRB,TRBV6-2,NaN,TRBJ2-7,TRBC2,...,clonotype59,clonotype59_consensus_1,1,P1,../cellranger-vdj-outputs/P1,NAGVTQTPKFRVLKTGQSMTLLCAQDMNHEYMYWYRQDPGMGLRLI...,AATGCTGGTGTCACTCAGACCCCAAAATTCCGGGTCCTGAAGACAG...,NAGVTQTPKFRVLKTGQSMTLLCAQDMNHEYMYWYRQDPGMGLRLI...,G,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10778,TTTGTCACATGCCACG-1,True,TTTGTCACATGCCACG-1_contig_1,True,502,TRB,TRBV7-2,TRBD1,TRBJ1-3,TRBC1,...,clonotype3066,clonotype3066_consensus_1,1,P9,../cellranger-vdj-outputs/P9,GAGVSQSPSNKVTEKGKDVELRCDPISGHTALYWYRQSLGQGLEFL...,GGAGCTGGAGTCTCCCAGTCCCCCAGTAACAAGGTCACAGAGAAGG...,GAGVSQSPSNKVTEKGKDVELRCDPISGHTALYWYRQSLGQGLEFL...,G,1
10780,TTTGTCATCGACCAGC-1,True,TTTGTCATCGACCAGC-1_contig_1,True,571,TRA,TRAV29/DV5,NaN,TRAJ54,TRAC,...,clonotype98,clonotype98_consensus_3,2,P9,../cellranger-vdj-outputs/P9,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,GACCAGCAAGTTAAGCAAAATTCACCATCCCTGAGCGTCCAGGAAG...,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,G,1
10781,TTTGTCATCGACCAGC-1,True,TTTGTCATCGACCAGC-1_contig_2,True,541,TRB,TRBV6-2,NaN,TRBJ2-4,TRBC2,...,clonotype98,clonotype98_consensus_1,2,P9,../cellranger-vdj-outputs/P9,NAGVTQTPKFRVLKTGQSMTLLCAQDMNHEYMYWYRQDPGMGLRLI...,AATGCTGGTGTCACTCAGACCCCAAAATTCCGGGTCCTGAAGACAG...,NAGVTQTPKFRVLKTGQSMTLLCAQDMNHEYMYWYRQDPGMGLRLI...,G,1
10783,TTTGTCATCGCGTAGC-1,True,TTTGTCATCGCGTAGC-1_contig_2,True,570,TRA,TRAV41,NaN,TRAJ49,TRAC,...,clonotype2790,clonotype2790_consensus_2,1,P9,../cellranger-vdj-outputs/P9,KNEVEQSPQNLTAQEGEFITINCSYSVGISALHWLQQHPGGGIVSL...,AAAAATGAAGTGGAGCAGAGTCCTCAGAACCTGACTGCCCAGGAAG...,KNEVEQSPQNLTAQEGEFITINCSYSVGISALHWLQQHPGGGIVSL...,G,1
10782,TTTGTCATCGCGTAGC-1,True,TTTGTCATCGCGTAGC-1_contig_1,True,502,TRB,TRBV7-2,NaN,TRBJ2-1,TRBC2,...,clonotype2790,clonotype2790_consensus_1,1,P9,../cellranger-vdj-outputs/P9,GAGVSQSPSNKVTEKGKDVELRCDPISGHTALYWYRQSLGQGLEFL...,GGAGCTGGAGTCTCCCAGTCCCCCAGTAACAAGGTCACAGAGAAGG...,GAGVSQSPSNKVTEKGKDVELRCDPISGHTALYWYRQSLGQGLEFL...,G,1

In [307]:
df[index_cols].value_counts()

sample_path                    sample_peptide  barcode
../cellranger-vdj-outputs/P9   P9              GAATGAACACACGCTG-1    4
../cellranger-vdj-outputs/P5   P5              GTTACAGGTACTTCTT-1    4
../cellranger-vdj-outputs/P15  P15             CATGCCTAGATCTGCT-1    4
../cellranger-vdj-outputs/P14  P14             ACTGTCCTCTCTAAGG-1    4
../cellranger-vdj-outputs/P5   P5              GTTCGGGAGAAGCCCA-1    4
                                                                    ..
../cellranger-vdj-outputs/P3   P3              TAGAGCTCAGTCGATT-1    1
                                               TAGAGCTCATTTCAGG-1    1
                                               TAGAGCTGTAAGTAGT-1    1
                                               TAGAGCTGTCTAACGT-1    1
../cellranger-vdj-outputs/P1   P1              AAACCTGAGAACTCGG-1    1
Name: count, Length: 98493, dtype: int64

In [308]:
index_cols_with_chain_and_entry = index_cols + ['chain', 'entry_id']
df_pivoted = df.pivot_table(
    index=index_cols, 
    columns=['chain', 'entry_id'],
    values=[col for col in df.columns if col not in index_cols_with_chain_and_entry],
    aggfunc='first'  # In case of any duplicates
)
df_pivoted

                                                               c_gene       \
chain                                                             TRA
entry_id                                                            1    2
sample_path                  sample_peptide barcode
../cellranger-vdj-outputs/P1 P1             AAACCTGAGAACTCGG-1    NaN  NaN
                                            AAACCTGAGCGTGAAC-1   TRAC  NaN
                                            AAACCTGCAAAGGCGT-1   TRAC  NaN
                                            AAACCTGCAAGGTTTC-1   TRAC  NaN
                                            AAACCTGGTGATGCCC-1   TRAC  NaN
...                                                               ...  ...
../cellranger-vdj-outputs/P9 P9             TTTGTCACAGATGGCA-1   TRAC  NaN
                                            TTTGTCACATCACGAT-1   TRAC  NaN
                                            TTTGTCACATGCCACG-1   TRAC  NaN
                                            TTTGTCATCGACCAGC-1   TRAC  NaN
                                            TTTGTCATCGCGTAGC-1   TRAC  NaN

                                                                            \
chain                                                             TRB
entry_id                                                            1    2
sample_path                  sample_peptide barcode
../cellranger-vdj-outputs/P1 P1             AAACCTGAGAACTCGG-1  TRBC2  NaN
                                            AAACCTGAGCGTGAAC-1  TRBC1  NaN
                                            AAACCTGCAAAGGCGT-1  TRBC2  NaN
                                            AAACCTGCAAGGTTTC-1  TRBC1  NaN
                                            AAACCTGGTGATGCCC-1  TRBC1  NaN
...                                                               ...  ...
../cellranger-vdj-outputs/P9 P9             TTTGTCACAGATGGCA-1  TRBC2  NaN
                                            TTTGTCACATCACGAT-1  TRBC2  NaN
                                            TTTGTCACATGCCACG-1  TRBC1  NaN
                                            TTTGTCATCGACCAGC-1  TRBC2  NaN
                                            TTTGTCATCGCGTAGC-1  TRBC2  NaN

                                                                   cdr1       \
chain                                                               TRA
entry_id                                                              1    2
sample_path                  sample_peptide barcode
../cellranger-vdj-outputs/P1 P1             AAACCTGAGAACTCGG-1      NaN  NaN
                                            AAACCTGAGCGTGAAC-1   VTNFRS  NaN
                                            AAACCTGCAAAGGCGT-1  TSESDYY  NaN
                                            AAACCTGCAAGGTTTC-1  TISGTDY  NaN
                                            AAACCTGGTGATGCCC-1   DSASNY  NaN
...                                                                 ...  ...
../cellranger-vdj-outputs/P9 P9             TTTGTCACAGATGGCA-1  GNEYVYW  NaN
                                            TTTGTCACATCACGAT-1   DSAIYN  NaN
                                            TTTGTCACATGCCACG-1   VSGNPY  NaN
                                            TTTGTCATCGACCAGC-1   NSMFDY  NaN
                                            TTTGTCATCGCGTAGC-1    VGISA  NaN

                                                                             \
chain                                                              TRB
entry_id                                                             1    2
sample_path                  sample_peptide barcode
../cellranger-vdj-outputs/P1 P1             AAACCTGAGAACTCGG-1   MNHEY  NaN
                                            AAACCTGAGCGTGAAC-1   KGHSH  NaN
                                            AAACCTGCAAAGGCGT-1   MNHEY  NaN
                                            AAACCTGCAAGGTTTC-1   SGHDY  NaN
                                            AAACCTGGTGATGCCC-1   ENHRY  NaN
...                                                                ...  ...
../cellranger-vdj-outputs/P9 P9             TTTGTCACAGATGGCA-1   LNHDA  NaN
                                            TTTGTCACATCACGAT-1  GTSNPN  NaN
                                            TTTGTCACATGCCACG-1   SGHTA  NaN
                                            TTTGTCATCGACCAGC-1   MNHEY  NaN
                                            TTTGTCATCGCGTAGC-1   SGHTA  NaN

                                                                              cdr1_nt  \
chain                                                                             TRA
entry_id                                                                            1
sample_path                  sample_peptide barcode
../cellranger-vdj-outputs/P1 P1             AAACCTGAGAACTCGG-1                    NaN
                                            AAACCTGAGCGTGAAC-1     GTGACTAACTTTCGAAGC
                                            AAACCTGCAAAGGCGT-1  ACCAGTGAGAGTGATTATTAT
                                            AAACCTGCAAGGTTTC-1  ACAATCAGTGGAACTGATTAC
                                            AAACCTGGTGATGCCC-1     GACAGTGCCTCAAACTAC
...                                                                               ...
../cellranger-vdj-outputs/P9 P9             TTTGTCACAGATGGCA-1  GGAAATGAGTATGTGTATTGG
                                            TTTGTCACATCACGAT-1     GATAGCGCTATTTACAAC
                                            TTTGTCACATGCCACG-1     GTCTCTGGAAACCCTTAT
                                            TTTGTCATCGACCAGC-1     AACAGCATGTTTGATTAT
                                            TTTGTCATCGCGTAGC-1        GTAGGAATAAGTGCC

                                                                     ...  \
chain                                                                ...
entry_id                                                          2  ...
sample_path                  sample_peptide barcode                  ...
../cellranger-vdj-outputs/P1 P1             AAACCTGAGAACTCGG-1  NaN  ...
                                            AAACCTGAGCGTGAAC-1  NaN  ...
                                            AAACCTGCAAAGGCGT-1  NaN  ...
                                            AAACCTGCAAGGTTTC-1  NaN  ...
                                            AAACCTGGTGATGCCC-1  NaN  ...
...                                                             ...  ...
../cellranger-vdj-outputs/P9 P9             TTTGTCACAGATGGCA-1  NaN  ...
                                            TTTGTCACATCACGAT-1  NaN  ...
                                            TTTGTCACATGCCACG-1  NaN  ...
                                            TTTGTCATCGACCAGC-1  NaN  ...
                                            TTTGTCATCGCGTAGC-1  NaN  ...

                                                                  reads      \
chain                                                               TRB
entry_id                                                              1   2
sample_path                  sample_peptide barcode
../cellranger-vdj-outputs/P1 P1             AAACCTGAGAACTCGG-1   3246.0 NaN
                                            AAACCTGAGCGTGAAC-1   4764.0 NaN
                                            AAACCTGCAAAGGCGT-1   6224.0 NaN
                                            AAACCTGCAAGGTTTC-1  19735.0 NaN
                                            AAACCTGGTGATGCCC-1   2604.0 NaN
...                                                                 ...  ..
../cellranger-vdj-outputs/P9 P9             TTTGTCACAGATGGCA-1    868.0 NaN
                                            TTTGTCACATCACGAT-1   9096.0 NaN
                                            TTTGTCACATGCCACG-1   1637.0 NaN
                                            TTTGTCATCGACCAGC-1   3939.0 NaN
                                            TTTGTCATCGCGTAGC-1   1429.0 NaN

                                                                umis      \
chain                                                            TRA
entry_id                                                           1   2
sample_path                  sample_peptide barcode
../cellranger-vdj-outputs/P1 P1             AAACCTGAGAACTCGG-1   NaN NaN
                                            AAACCTGAGCGTGAAC-1   3.0 NaN
                                            AAACCTGCAAAGGCGT-1   4.0 NaN
                                            AAACCTGCAAGGTTTC-1  13.0 NaN
                                            AAACCTGGTGATGCCC-1   3.0 NaN
...                                                              ...  ..
../cellranger-vdj-outputs/P9 P9             TTTGTCACAGATGGCA-1   4.0 NaN
                                            TTTGTCACATCACGAT-1  13.0 NaN
                                            TTTGTCACATGCCACG-1   4.0 NaN
                                            TTTGTCATCGACCAGC-1   8.0 NaN
                                            TTTGTCATCGCGTAGC-1   6.0 NaN

                                                                          \
chain                                                            TRB
entry_id                                                           1   2
sample_path                  sample_peptide barcode
../cellranger-vdj-outputs/P1 P1             AAACCTGAGAACTCGG-1   5.0 NaN
                                            AAACCTGAGCGTGAAC-1   6.0 NaN
                                            AAACCTGCAAAGGCGT-1   8.0 NaN
                                            AAACCTGCAAGGTTTC-1  28.0 NaN
                                            AAACCTGGTGATGCCC-1   4.0 NaN
...                                                              ...  ..
../cellranger-vdj-outputs/P9 P9             TTTGTCACAGATGGCA-1   8.0 NaN
                                            TTTGTCACATCACGAT-1  67.0 NaN
                                            TTTGTCACATGCCACG-1   8.0 NaN
                                            TTTGTCATCGACCAGC-1  22.0 NaN
                                            TTTGTCATCGCGTAGC-1  29.0 NaN

                                                                      v_gene  \
chain                                                                    TRA
entry_id                                                                   1
sample_path                  sample_peptide barcode
../cellranger-vdj-outputs/P1 P1             AAACCTGAGAACTCGG-1           NaN
                                            AAACCTGAGCGTGAAC-1    TRAV36/DV7
                                            AAACCTGCAAAGGCGT-1  TRAV38-2/DV8
                                            AAACCTGCAAGGTTTC-1      TRAV26-2
                                            AAACCTGGTGATGCCC-1      TRAV13-1
...                                                                      ...
../cellranger-vdj-outputs/P9 P9             TTTGTCACAGATGGCA-1      TRAV26-1
                                            TTTGTCACATCACGAT-1        TRAV21
                                            TTTGTCACATGCCACG-1         TRAV3
                                            TTTGTCATCGACCAGC-1    TRAV29/DV5
                                            TTTGTCATCGCGTAGC-1        TRAV41

                                                                               \
chain                                                                     TRB
entry_id                                                          2         1
sample_path                  sample_peptide barcode
../cellranger-vdj-outputs/P1 P1             AAACCTGAGAACTCGG-1  NaN   TRBV6-2
                                            AAACCTGAGCGTGAAC-1  NaN    TRBV18
                                            AAACCTGCAAAGGCGT-1  NaN   TRBV6-2
                                            AAACCTGCAAGGTTTC-1  NaN  TRBV12-4
                                            AAACCTGGTGATGCCC-1  NaN  TRBV10-3
...                                                             ...       ...
../cellranger-vdj-outputs/P9 P9             TTTGTCACAGATGGCA-1  NaN    TRBV19
                                            TTTGTCACATCACGAT-1  NaN    TRBV30
                                            TTTGTCACATGCCACG-1  NaN   TRBV7-2
                                            TTTGTCATCGACCAGC-1  NaN   TRBV6-2
                                            TTTGTCATCGCGTAGC-1  NaN   TRBV7-2


chain
entry_id                                                          2
sample_path                  sample_peptide barcode
../cellranger-vdj-outputs/P1 P1             AAACCTGAGAACTCGG-1  NaN
                                            AAACCTGAGCGTGAAC-1  NaN
                                            AAACCTGCAAAGGCGT-1  NaN
                                            AAACCTGCAAGGTTTC-1  NaN
                                            AAACCTGGTGATGCCC-1  NaN
...                                                             ...
../cellranger-vdj-outputs/P9 P9             TTTGTCACAGATGGCA-1  NaN
                                            TTTGTCACATCACGAT-1  NaN
                                            TTTGTCACATGCCACG-1  NaN
                                            TTTGTCATCGACCAGC-1  NaN
                                            TTTGTCATCGCGTAGC-1  NaN

[98493 rows x 130 columns]

In [309]:

# Flatten and clean up the column names
df_pivoted.columns = [f'{col[1]}_{col[2]}_{col[0]}'.strip() for col in df_pivoted.columns.values]
df_pivoted

                                                               TRA_1_c_gene  \
sample_path                  sample_peptide barcode
../cellranger-vdj-outputs/P1 P1             AAACCTGAGAACTCGG-1          NaN
                                            AAACCTGAGCGTGAAC-1         TRAC
                                            AAACCTGCAAAGGCGT-1         TRAC
                                            AAACCTGCAAGGTTTC-1         TRAC
                                            AAACCTGGTGATGCCC-1         TRAC
...                                                                     ...
../cellranger-vdj-outputs/P9 P9             TTTGTCACAGATGGCA-1         TRAC
                                            TTTGTCACATCACGAT-1         TRAC
                                            TTTGTCACATGCCACG-1         TRAC
                                            TTTGTCATCGACCAGC-1         TRAC
                                            TTTGTCATCGCGTAGC-1         TRAC

                                                               TRA_2_c_gene  \
sample_path                  sample_peptide barcode
../cellranger-vdj-outputs/P1 P1             AAACCTGAGAACTCGG-1          NaN
                                            AAACCTGAGCGTGAAC-1          NaN
                                            AAACCTGCAAAGGCGT-1          NaN
                                            AAACCTGCAAGGTTTC-1          NaN
                                            AAACCTGGTGATGCCC-1          NaN
...                                                                     ...
../cellranger-vdj-outputs/P9 P9             TTTGTCACAGATGGCA-1          NaN
                                            TTTGTCACATCACGAT-1          NaN
                                            TTTGTCACATGCCACG-1          NaN
                                            TTTGTCATCGACCAGC-1          NaN
                                            TTTGTCATCGCGTAGC-1          NaN

                                                               TRB_1_c_gene  \
sample_path                  sample_peptide barcode
../cellranger-vdj-outputs/P1 P1             AAACCTGAGAACTCGG-1        TRBC2
                                            AAACCTGAGCGTGAAC-1        TRBC1
                                            AAACCTGCAAAGGCGT-1        TRBC2
                                            AAACCTGCAAGGTTTC-1        TRBC1
                                            AAACCTGGTGATGCCC-1        TRBC1
...                                                                     ...
../cellranger-vdj-outputs/P9 P9             TTTGTCACAGATGGCA-1        TRBC2
                                            TTTGTCACATCACGAT-1        TRBC2
                                            TTTGTCACATGCCACG-1        TRBC1
                                            TTTGTCATCGACCAGC-1        TRBC2
                                            TTTGTCATCGCGTAGC-1        TRBC2

                                                               TRB_2_c_gene  \
sample_path                  sample_peptide barcode
../cellranger-vdj-outputs/P1 P1             AAACCTGAGAACTCGG-1          NaN
                                            AAACCTGAGCGTGAAC-1          NaN
                                            AAACCTGCAAAGGCGT-1          NaN
                                            AAACCTGCAAGGTTTC-1          NaN
                                            AAACCTGGTGATGCCC-1          NaN
...                                                                     ...
../cellranger-vdj-outputs/P9 P9             TTTGTCACAGATGGCA-1          NaN
                                            TTTGTCACATCACGAT-1          NaN
                                            TTTGTCACATGCCACG-1          NaN
                                            TTTGTCATCGACCAGC-1          NaN
                                            TTTGTCATCGCGTAGC-1          NaN

                                                               TRA_1_cdr1  \
sample_path                  sample_peptide barcode
../cellranger-vdj-outputs/P1 P1             AAACCTGAGAACTCGG-1        NaN
                                            AAACCTGAGCGTGAAC-1     VTNFRS
                                            AAACCTGCAAAGGCGT-1    TSESDYY
                                            AAACCTGCAAGGTTTC-1    TISGTDY
                                            AAACCTGGTGATGCCC-1     DSASNY
...                                                                   ...
../cellranger-vdj-outputs/P9 P9             TTTGTCACAGATGGCA-1    GNEYVYW
                                            TTTGTCACATCACGAT-1     DSAIYN
                                            TTTGTCACATGCCACG-1     VSGNPY
                                            TTTGTCATCGACCAGC-1     NSMFDY
                                            TTTGTCATCGCGTAGC-1      VGISA

                                                               TRA_2_cdr1  \
sample_path                  sample_peptide barcode
../cellranger-vdj-outputs/P1 P1             AAACCTGAGAACTCGG-1        NaN
                                            AAACCTGAGCGTGAAC-1        NaN
                                            AAACCTGCAAAGGCGT-1        NaN
                                            AAACCTGCAAGGTTTC-1        NaN
                                            AAACCTGGTGATGCCC-1        NaN
...                                                                   ...
../cellranger-vdj-outputs/P9 P9             TTTGTCACAGATGGCA-1        NaN
                                            TTTGTCACATCACGAT-1        NaN
                                            TTTGTCACATGCCACG-1        NaN
                                            TTTGTCATCGACCAGC-1        NaN
                                            TTTGTCATCGCGTAGC-1        NaN

                                                               TRB_1_cdr1  \
sample_path                  sample_peptide barcode
../cellranger-vdj-outputs/P1 P1             AAACCTGAGAACTCGG-1      MNHEY
                                            AAACCTGAGCGTGAAC-1      KGHSH
                                            AAACCTGCAAAGGCGT-1      MNHEY
                                            AAACCTGCAAGGTTTC-1      SGHDY
                                            AAACCTGGTGATGCCC-1      ENHRY
...                                                                   ...
../cellranger-vdj-outputs/P9 P9             TTTGTCACAGATGGCA-1      LNHDA
                                            TTTGTCACATCACGAT-1     GTSNPN
                                            TTTGTCACATGCCACG-1      SGHTA
                                            TTTGTCATCGACCAGC-1      MNHEY
                                            TTTGTCATCGCGTAGC-1      SGHTA

                                                               TRB_2_cdr1  \
sample_path                  sample_peptide barcode
../cellranger-vdj-outputs/P1 P1             AAACCTGAGAACTCGG-1        NaN
                                            AAACCTGAGCGTGAAC-1        NaN
                                            AAACCTGCAAAGGCGT-1        NaN
                                            AAACCTGCAAGGTTTC-1        NaN
                                            AAACCTGGTGATGCCC-1        NaN
...                                                                   ...
../cellranger-vdj-outputs/P9 P9             TTTGTCACAGATGGCA-1        NaN
                                            TTTGTCACATCACGAT-1        NaN
                                            TTTGTCACATGCCACG-1        NaN
                                            TTTGTCATCGACCAGC-1        NaN
                                            TTTGTCATCGCGTAGC-1        NaN

                                                                        TRA_1_cdr1_nt  \
sample_path                  sample_peptide barcode
../cellranger-vdj-outputs/P1 P1             AAACCTGAGAACTCGG-1                    NaN
                                            AAACCTGAGCGTGAAC-1     GTGACTAACTTTCGAAGC
                                            AAACCTGCAAAGGCGT-1  ACCAGTGAGAGTGATTATTAT
                                            AAACCTGCAAGGTTTC-1  ACAATCAGTGGAACTGATTAC
                                            AAACCTGGTGATGCCC-1     GACAGTGCCTCAAACTAC
...                                                                               ...
../cellranger-vdj-outputs/P9 P9             TTTGTCACAGATGGCA-1  GGAAATGAGTATGTGTATTGG
                                            TTTGTCACATCACGAT-1     GATAGCGCTATTTACAAC
                                            TTTGTCACATGCCACG-1     GTCTCTGGAAACCCTTAT
                                            TTTGTCATCGACCAGC-1     AACAGCATGTTTGATTAT
                                            TTTGTCATCGCGTAGC-1        GTAGGAATAAGTGCC

                                                               TRA_2_cdr1_nt  \
sample_path                  sample_peptide barcode
../cellranger-vdj-outputs/P1 P1             AAACCTGAGAACTCGG-1           NaN
                                            AAACCTGAGCGTGAAC-1           NaN
                                            AAACCTGCAAAGGCGT-1           NaN
                                            AAACCTGCAAGGTTTC-1           NaN
                                            AAACCTGGTGATGCCC-1           NaN
...                                                                      ...
../cellranger-vdj-outputs/P9 P9             TTTGTCACAGATGGCA-1           NaN
                                            TTTGTCACATCACGAT-1           NaN
                                            TTTGTCACATGCCACG-1           NaN
                                            TTTGTCATCGACCAGC-1           NaN
                                            TTTGTCATCGCGTAGC-1           NaN

                                                                ...  \
sample_path                  sample_peptide barcode             ...
../cellranger-vdj-outputs/P1 P1             AAACCTGAGAACTCGG-1  ...
                                            AAACCTGAGCGTGAAC-1  ...
                                            AAACCTGCAAAGGCGT-1  ...
                                            AAACCTGCAAGGTTTC-1  ...
                                            AAACCTGGTGATGCCC-1  ...
...                                                             ...
../cellranger-vdj-outputs/P9 P9             TTTGTCACAGATGGCA-1  ...
                                            TTTGTCACATCACGAT-1  ...
                                            TTTGTCACATGCCACG-1  ...
                                            TTTGTCATCGACCAGC-1  ...
                                            TTTGTCATCGCGTAGC-1  ...

                                                               TRB_1_reads  \
sample_path                  sample_peptide barcode
../cellranger-vdj-outputs/P1 P1             AAACCTGAGAACTCGG-1      3246.0
                                            AAACCTGAGCGTGAAC-1      4764.0
                                            AAACCTGCAAAGGCGT-1      6224.0
                                            AAACCTGCAAGGTTTC-1     19735.0
                                            AAACCTGGTGATGCCC-1      2604.0
...                                                                    ...
../cellranger-vdj-outputs/P9 P9             TTTGTCACAGATGGCA-1       868.0
                                            TTTGTCACATCACGAT-1      9096.0
                                            TTTGTCACATGCCACG-1      1637.0
                                            TTTGTCATCGACCAGC-1      3939.0
                                            TTTGTCATCGCGTAGC-1      1429.0

                                                               TRB_2_reads  \
sample_path                  sample_peptide barcode
../cellranger-vdj-outputs/P1 P1             AAACCTGAGAACTCGG-1         NaN
                                            AAACCTGAGCGTGAAC-1         NaN
                                            AAACCTGCAAAGGCGT-1         NaN
                                            AAACCTGCAAGGTTTC-1         NaN
                                            AAACCTGGTGATGCCC-1         NaN
...                                                                    ...
../cellranger-vdj-outputs/P9 P9             TTTGTCACAGATGGCA-1         NaN
                                            TTTGTCACATCACGAT-1         NaN
                                            TTTGTCACATGCCACG-1         NaN
                                            TTTGTCATCGACCAGC-1         NaN
                                            TTTGTCATCGCGTAGC-1         NaN

                                                               TRA_1_umis  \
sample_path                  sample_peptide barcode
../cellranger-vdj-outputs/P1 P1             AAACCTGAGAACTCGG-1        NaN
                                            AAACCTGAGCGTGAAC-1        3.0
                                            AAACCTGCAAAGGCGT-1        4.0
                                            AAACCTGCAAGGTTTC-1       13.0
                                            AAACCTGGTGATGCCC-1        3.0
...                                                                   ...
../cellranger-vdj-outputs/P9 P9             TTTGTCACAGATGGCA-1        4.0
                                            TTTGTCACATCACGAT-1       13.0
                                            TTTGTCACATGCCACG-1        4.0
                                            TTTGTCATCGACCAGC-1        8.0
                                            TTTGTCATCGCGTAGC-1        6.0

                                                               TRA_2_umis  \
sample_path                  sample_peptide barcode
../cellranger-vdj-outputs/P1 P1             AAACCTGAGAACTCGG-1        NaN
                                            AAACCTGAGCGTGAAC-1        NaN
                                            AAACCTGCAAAGGCGT-1        NaN
                                            AAACCTGCAAGGTTTC-1        NaN
                                            AAACCTGGTGATGCCC-1        NaN
...                                                                   ...
../cellranger-vdj-outputs/P9 P9             TTTGTCACAGATGGCA-1        NaN
                                            TTTGTCACATCACGAT-1        NaN
                                            TTTGTCACATGCCACG-1        NaN
                                            TTTGTCATCGACCAGC-1        NaN
                                            TTTGTCATCGCGTAGC-1        NaN

                                                               TRB_1_umis  \
sample_path                  sample_peptide barcode
../cellranger-vdj-outputs/P1 P1             AAACCTGAGAACTCGG-1        5.0
                                            AAACCTGAGCGTGAAC-1        6.0
                                            AAACCTGCAAAGGCGT-1        8.0
                                            AAACCTGCAAGGTTTC-1       28.0
                                            AAACCTGGTGATGCCC-1        4.0
...                                                                   ...
../cellranger-vdj-outputs/P9 P9             TTTGTCACAGATGGCA-1        8.0
                                            TTTGTCACATCACGAT-1       67.0
                                            TTTGTCACATGCCACG-1        8.0
                                            TTTGTCATCGACCAGC-1       22.0
                                            TTTGTCATCGCGTAGC-1       29.0

                                                               TRB_2_umis  \
sample_path                  sample_peptide barcode
../cellranger-vdj-outputs/P1 P1             AAACCTGAGAACTCGG-1        NaN
                                            AAACCTGAGCGTGAAC-1        NaN
                                            AAACCTGCAAAGGCGT-1        NaN
                                            AAACCTGCAAGGTTTC-1        NaN
                                            AAACCTGGTGATGCCC-1        NaN
...                                                                   ...
../cellranger-vdj-outputs/P9 P9             TTTGTCACAGATGGCA-1        NaN
                                            TTTGTCACATCACGAT-1        NaN
                                            TTTGTCACATGCCACG-1        NaN
                                            TTTGTCATCGACCAGC-1        NaN
                                            TTTGTCATCGCGTAGC-1        NaN

                                                                TRA_1_v_gene  \
sample_path                  sample_peptide barcode
../cellranger-vdj-outputs/P1 P1             AAACCTGAGAACTCGG-1           NaN
                                            AAACCTGAGCGTGAAC-1    TRAV36/DV7
                                            AAACCTGCAAAGGCGT-1  TRAV38-2/DV8
                                            AAACCTGCAAGGTTTC-1      TRAV26-2
                                            AAACCTGGTGATGCCC-1      TRAV13-1
...                                                                      ...
../cellranger-vdj-outputs/P9 P9             TTTGTCACAGATGGCA-1      TRAV26-1
                                            TTTGTCACATCACGAT-1        TRAV21
                                            TTTGTCACATGCCACG-1         TRAV3
                                            TTTGTCATCGACCAGC-1    TRAV29/DV5
                                            TTTGTCATCGCGTAGC-1        TRAV41

                                                               TRA_2_v_gene  \
sample_path                  sample_peptide barcode
../cellranger-vdj-outputs/P1 P1             AAACCTGAGAACTCGG-1          NaN
                                            AAACCTGAGCGTGAAC-1          NaN
                                            AAACCTGCAAAGGCGT-1          NaN
                                            AAACCTGCAAGGTTTC-1          NaN
                                            AAACCTGGTGATGCCC-1          NaN
...                                                                     ...
../cellranger-vdj-outputs/P9 P9             TTTGTCACAGATGGCA-1          NaN
                                            TTTGTCACATCACGAT-1          NaN
                                            TTTGTCACATGCCACG-1          NaN
                                            TTTGTCATCGACCAGC-1          NaN
                                            TTTGTCATCGCGTAGC-1          NaN

                                                               TRB_1_v_gene  \
sample_path                  sample_peptide barcode
../cellranger-vdj-outputs/P1 P1             AAACCTGAGAACTCGG-1      TRBV6-2
                                            AAACCTGAGCGTGAAC-1       TRBV18
                                            AAACCTGCAAAGGCGT-1      TRBV6-2
                                            AAACCTGCAAGGTTTC-1     TRBV12-4
                                            AAACCTGGTGATGCCC-1     TRBV10-3
...                                                                     ...
../cellranger-vdj-outputs/P9 P9             TTTGTCACAGATGGCA-1       TRBV19
                                            TTTGTCACATCACGAT-1       TRBV30
                                            TTTGTCACATGCCACG-1      TRBV7-2
                                            TTTGTCATCGACCAGC-1      TRBV6-2
                                            TTTGTCATCGCGTAGC-1      TRBV7-2

                                                               TRB_2_v_gene
sample_path                  sample_peptide barcode
../cellranger-vdj-outputs/P1 P1             AAACCTGAGAACTCGG-1          NaN
                                            AAACCTGAGCGTGAAC-1          NaN
                                            AAACCTGCAAAGGCGT-1          NaN
                                            AAACCTGCAAGGTTTC-1          NaN
                                            AAACCTGGTGATGCCC-1          NaN
...                                                                     ...
../cellranger-vdj-outputs/P9 P9             TTTGTCACAGATGGCA-1          NaN
                                            TTTGTCACATCACGAT-1          NaN

In [310]:

# Add boolean flags for TRA and TRB presence

# Count the number of TRA and TRB entries
df_pivoted['TRA_count'] = df_pivoted[["TRA_1_umis", "TRA_2_umis"]].notna().sum(axis=1)
df_pivoted['TRB_count'] = df_pivoted[["TRB_1_umis", "TRB_2_umis"]].notna().sum(axis=1)

# Note the presence of any TRA and TRB chains as well as a separate boolean flag for doublets
df_pivoted['has_TRA'] = df_pivoted['TRA_count'] > 0
df_pivoted['has_TRB'] = df_pivoted['TRB_count'] > 0

df_pivoted['multi_TRA'] = df_pivoted['TRA_count'] > 1
df_pivoted['multi_TRB'] = df_pivoted['TRB_count'] > 1
df_pivoted['multi_either_TRA_or_TRB'] = df_pivoted['multi_TRA']  | df_pivoted['multi_TRB']


# Reset the index to make 'barcode' a regular column
df_final = df_pivoted.reset_index()
df_final

,sample_path,sample_peptide,barcode,TRA_1_c_gene,TRA_2_c_gene,TRB_1_c_gene,TRB_2_c_gene,TRA_1_cdr1,TRA_2_cdr1,TRB_1_cdr1,...,TRA_2_v_gene,TRB_1_v_gene,TRB_2_v_gene,TRA_count,TRB_count,has_TRA,has_TRB,multi_TRA,multi_TRB,multi_either_TRA_or_TRB
0,../cellranger-vdj-outputs/P1,P1,AAACCTGAGAACTCGG-1,NaN,NaN,TRBC2,NaN,NaN,NaN,MNHEY,...,NaN,TRBV6-2,NaN,0,1,False,True,False,False,False
1,../cellranger-vdj-outputs/P1,P1,AAACCTGAGCGTGAAC-1,TRAC,NaN,TRBC1,NaN,VTNFRS,NaN,KGHSH,...,NaN,TRBV18,NaN,1,1,True,True,False,False,False
2,../cellranger-vdj-outputs/P1,P1,AAACCTGCAAAGGCGT-1,TRAC,NaN,TRBC2,NaN,TSESDYY,NaN,MNHEY,...,NaN,TRBV6-2,NaN,1,1,True,True,False,False,False
3,../cellranger-vdj-outputs/P1,P1,AAACCTGCAAGGTTTC-1,TRAC,NaN,TRBC1,NaN,TISGTDY,NaN,SGHDY,...,NaN,TRBV12-4,NaN,1,1,True,True,False,False,False
4,../cellranger-vdj-outputs/P1,P1,AAACCTGGTGATGCCC-1,TRAC,NaN,TRBC1,NaN,DSASNY,NaN,ENHRY,...,NaN,TRBV10-3,NaN,1,1,True,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98488,../cellranger-vdj-outputs/P9,P9,TTTGTCACAGATGGCA-1,TRAC,NaN,TRBC2,NaN,GNEYVYW,NaN,LNHDA,...,NaN,TRBV19,NaN,1,1,True,True,False,False,False
98489,../cellranger-vdj-outputs/P9,P9,TTTGTCACATCACGAT-1,TRAC,NaN,TRBC2,NaN,DSAIYN,NaN,GTSNPN,...,NaN,TRBV30,NaN,1,1,True,True,False,False,False
98490,../cellranger-vdj-outputs/P9,P9,TTTGTCACATGCCACG-1,TRAC,NaN,TRBC1,NaN,VSGNPY,NaN,SGHTA,...,NaN,TRBV7-2,NaN,1,1,True,True,False,False,False
98491,../cellranger-vdj-outputs/P9,P9,TTTGTCATCGACCAGC-1,TRAC,NaN,TRBC2,NaN,NSMFDY,NaN,MNHEY,...,NaN,TRBV6-2,NaN,1,1,True,True,False,False,False
98492,../cellranger-vdj-outputs/P9,P9,TTTGTCATCGCGTAGC-1,TRAC,NaN,TRBC2,NaN,VGISA,NaN,SGHTA,...,NaN,TRBV7-2,NaN,1,1,True,True,False,False,False

In [311]:
list(df_final.columns)

['sample_path',
 'sample_peptide',
 'barcode',
 'TRA_1_c_gene',
 'TRA_2_c_gene',
 'TRB_1_c_gene',
 'TRB_2_c_gene',
 'TRA_1_cdr1',
 'TRA_2_cdr1',
 'TRB_1_cdr1',
 'TRB_2_cdr1',
 'TRA_1_cdr1_nt',
 'TRA_2_cdr1_nt',
 'TRB_1_cdr1_nt',
 'TRB_2_cdr1_nt',
 'TRA_1_cdr2',
 'TRA_2_cdr2',
 'TRB_1_cdr2',
 'TRB_2_cdr2',
 'TRA_1_cdr2_nt',
 'TRA_2_cdr2_nt',
 'TRB_1_cdr2_nt',
 'TRB_2_cdr2_nt',
 'TRA_1_cdr3',
 'TRA_2_cdr3',
 'TRB_1_cdr3',
 'TRB_2_cdr3',
 'TRA_1_cdr3_nt',
 'TRA_2_cdr3_nt',
 'TRB_1_cdr3_nt',
 'TRB_2_cdr3_nt',
 'TRA_1_combined_vdj_aa_sequence',
 'TRA_2_combined_vdj_aa_sequence',
 'TRB_1_combined_vdj_aa_sequence',
 'TRB_2_combined_vdj_aa_sequence',
 'TRA_1_combined_vdj_nt_sequence',
 'TRA_2_combined_vdj_nt_sequence',
 'TRB_1_combined_vdj_nt_sequence',
 'TRB_2_combined_vdj_nt_sequence',
 'TRA_1_combined_vdj_ragged_3p_nt',
 'TRA_2_combined_vdj_ragged_3p_nt',
 'TRB_1_combined_vdj_ragged_3p_nt',
 'TRB_2_combined_vdj_ragged_3p_nt',
 'TRA_1_combined_vdj_translated_sequence',
 'TRA_2_combined_vdj_translated_sequence',
 'TRB_1_combined_vdj_translated_sequence',
 'TRB_2_combined_vdj_translated_sequence',
 'TRA_1_contig_id',
 'TRA_2_contig_id',
 'TRB_1_contig_id',
 'TRB_2_contig_id',
 'TRB_1_d_gene',
 'TRB_2_d_gene',
 'TRA_1_exact_subclonotype_id',
 'TRA_2_exact_subclonotype_id',
 'TRB_1_exact_subclonotype_id',
 'TRB_2_exact_subclonotype_id',
 'TRA_1_full_length',
 'TRA_2_full_length',
 'TRB_1_full_length',
 'TRB_2_full_length',
 'TRA_1_fwr1',
 'TRA_2_fwr1',
 'TRB_1_fwr1',
 'TRB_2_fwr1',
 'TRA_1_fwr1_nt',
 'TRA_2_fwr1_nt',
 'TRB_1_fwr1_nt',
 'TRB_2_fwr1_nt',
 'TRA_1_fwr2',
 'TRA_2_fwr2',
 'TRB_1_fwr2',
 'TRB_2_fwr2',
 'TRA_1_fwr2_nt',
 'TRA_2_fwr2_nt',
 'TRB_1_fwr2_nt',
 'TRB_2_fwr2_nt',
 'TRA_1_fwr3',
 'TRA_2_fwr3',
 'TRB_1_fwr3',
 'TRB_2_fwr3',
 'TRA_1_fwr3_nt',
 'TRA_2_fwr3_nt',
 'TRB_1_fwr3_nt',
 'TRB_2_fwr3_nt',
 'TRA_1_fwr4',
 'TRA_2_fwr4',
 'TRB_1_fwr4',
 'TRB_2_fwr4',
 'TRA_1_fwr4_nt',
 'TRA_2_fwr4_nt',
 'TRB_1_fwr4_nt',
 'TRB_2_fwr4_nt',
 'TRA_1_high_confidence',
 'TRA_2_high_confidence',
 'TRB_1_high_confidence',
 'TRB_2_high_confidence',
 'TRA_1_is_cell',
 'TRA_2_is_cell',
 'TRB_1_is_cell',
 'TRB_2_is_cell',
 'TRA_1_j_gene',
 'TRA_2_j_gene',
 'TRB_1_j_gene',
 'TRB_2_j_gene',
 'TRA_1_length',
 'TRA_2_length',
 'TRB_1_length',
 'TRB_2_length',
 'TRA_1_productive',
 'TRA_2_productive',
 'TRB_1_productive',
 'TRB_2_productive',
 'TRA_1_raw_clonotype_id',
 'TRA_2_raw_clonotype_id',
 'TRB_1_raw_clonotype_id',
 'TRB_2_raw_clonotype_id',
 'TRA_1_raw_consensus_id',
 'TRA_2_raw_consensus_id',
 'TRB_1_raw_consensus_id',
 'TRB_2_raw_consensus_id',
 'TRA_1_reads',
 'TRA_2_reads',
 'TRB_1_reads',
 'TRB_2_reads',
 'TRA_1_umis',
 'TRA_2_umis',
 'TRB_1_umis',
 'TRB_2_umis',
 'TRA_1_v_gene',
 'TRA_2_v_gene',
 'TRB_1_v_gene',
 'TRB_2_v_gene',
 'TRA_count',
 'TRB_count',
 'has_TRA',
 'has_TRB',
 'multi_TRA',
 'multi_TRB',
 'multi_either_TRA_or_TRB']

In [312]:
df_final.TRA_1_combined_vdj_nt_sequence

0                                                      NaN
1        GAAGACAAGGTGGTACAAAGCCCTCTATCTCTGGTTGTCCACGAGG...
2        GCTCAGACAGTCACTCAGTCTCAACCAGAGATGTCTGTGCAGGAGG...
3        GATGCTAAGACCACACAGCCAAATTCAATGGAGAGTAACGAAGAAG...
4        GGAGAGAATGTGGAGCAGCATCCTTCAACCCTGAGTGTCCAGGAGG...
                               ...
98488    GATGCTAAGCCCCCCTCCATGGATTGCGCTGAAGGAAGAGCTGCAA...
98489    AAACAGGAGGTGACACAGATTCCTGCAGCTCTGAGTGTCCCAGAAG...
98490    GCTCAGTCAGTGGCTCAGCCGGAAGATCAGGTCAACGTTGCTGAAG...
98491    GACCAGCAAGTTAAGCAAAATTCACCATCCCTGAGCGTCCAGGAAG...
98492    AAAAATGAAGTGGAGCAGAGTCCTCAGAACCTGACTGCCCAGGAAG...
Name: TRA_1_combined_vdj_nt_sequence, Length: 98493, dtype: object

In [313]:
cols_to_save = [c for c in df_final.columns if not c.endswith("_nt")]
print(cols_to_save)
df_final.to_csv("PFO004.vdj-tcr-sequences.aa-only.no-leader.no-constant.csv")

for (tra_count, trb_count), sub_df in df_final.groupby(["TRA_count", "TRB_count"]):
    sub_df.to_csv("PFO004.vdj-tcr-sequences.%d-tra.%d-trb.no-leader.no-constant.csv" % (tra_count, trb_count))

['sample_path', 'sample_peptide', 'barcode', 'TRA_1_c_gene', 'TRA_2_c_gene', 'TRB_1_c_gene', 'TRB_2_c_gene', 'TRA_1_cdr1', 'TRA_2_cdr1', 'TRB_1_cdr1', 'TRB_2_cdr1', 'TRA_1_cdr2', 'TRA_2_cdr2', 'TRB_1_cdr2', 'TRB_2_cdr2', 'TRA_1_cdr3', 'TRA_2_cdr3', 'TRB_1_cdr3', 'TRB_2_cdr3', 'TRA_1_combined_vdj_aa_sequence', 'TRA_2_combined_vdj_aa_sequence', 'TRB_1_combined_vdj_aa_sequence', 'TRB_2_combined_vdj_aa_sequence', 'TRA_1_combined_vdj_nt_sequence', 'TRA_2_combined_vdj_nt_sequence', 'TRB_1_combined_vdj_nt_sequence', 'TRB_2_combined_vdj_nt_sequence', 'TRA_1_combined_vdj_translated_sequence', 'TRA_2_combined_vdj_translated_sequence', 'TRB_1_combined_vdj_translated_sequence', 'TRB_2_combined_vdj_translated_sequence', 'TRA_1_contig_id', 'TRA_2_contig_id', 'TRB_1_contig_id', 'TRB_2_contig_id', 'TRB_1_d_gene', 'TRB_2_d_gene', 'TRA_1_exact_subclonotype_id', 'TRA_2_exact_subclonotype_id', 'TRB_1_exact_subclonotype_id', 'TRB_2_exact_subclonotype_id', 'TRA_1_full_length', 'TRA_2_full_length', 'TRB_1_full_length', 'TRB_2_full_length', 'TRA_1_fwr1', 'TRA_2_fwr1', 'TRB_1_fwr1', 'TRB_2_fwr1', 'TRA_1_fwr2', 'TRA_2_fwr2', 'TRB_1_fwr2', 'TRB_2_fwr2', 'TRA_1_fwr3', 'TRA_2_fwr3', 'TRB_1_fwr3', 'TRB_2_fwr3', 'TRA_1_fwr4', 'TRA_2_fwr4', 'TRB_1_fwr4', 'TRB_2_fwr4', 'TRA_1_high_confidence', 'TRA_2_high_confidence', 'TRB_1_high_confidence', 'TRB_2_high_confidence', 'TRA_1_is_cell', 'TRA_2_is_cell', 'TRB_1_is_cell', 'TRB_2_is_cell', 'TRA_1_j_gene', 'TRA_2_j_gene', 'TRB_1_j_gene', 'TRB_2_j_gene', 'TRA_1_length', 'TRA_2_length', 'TRB_1_length', 'TRB_2_length', 'TRA_1_productive', 'TRA_2_productive', 'TRB_1_productive', 'TRB_2_productive', 'TRA_1_raw_clonotype_id', 'TRA_2_raw_clonotype_id', 'TRB_1_raw_clonotype_id', 'TRB_2_raw_clonotype_id', 'TRA_1_raw_consensus_id', 'TRA_2_raw_consensus_id', 'TRB_1_raw_consensus_id', 'TRB_2_raw_consensus_id', 'TRA_1_reads', 'TRA_2_reads', 'TRB_1_reads', 'TRB_2_reads', 'TRA_1_umis', 'TRA_2_umis', 'TRB_1_umis', 'TRB_2_umis', 'TRA_1_v_gene', 'TRA_2_v_gene', 'TRB_1_v_gene', 'TRB_2_v_gene', 'TRA_count', 'TRB_count', 'has_TRA', 'has_TRB', 'multi_TRA', 'multi_TRB', 'multi_either_TRA_or_TRB']

In [314]:
ls ../../tcr-selection-cdr3-ab/v4/*.txt

../../tcr-selection-cdr3-ab/v4/PFO004.chosen-tcrs.cd4.complete-multi.tier1.preferred-fdr-0.0001.txt
../../tcr-selection-cdr3-ab/v4/PFO004.chosen-tcrs.cd4.complete-multi.tier2.preferred-fdr-0.001.txt
../../tcr-selection-cdr3-ab/v4/PFO004.chosen-tcrs.cd4.complete-multi.tier3.preferred-fdr-0.01.txt
../../tcr-selection-cdr3-ab/v4/PFO004.chosen-tcrs.cd4.complete-multi.tier4.preferred-fdr-0.1.txt
../../tcr-selection-cdr3-ab/v4/PFO004.chosen-tcrs.cd4.complete-multi.tier5.preferred-fdr-0.15.txt
../../tcr-selection-cdr3-ab/v4/PFO004.chosen-tcrs.cd4.complete-single.tier1.preferred-fdr-0.0001.txt
../../tcr-selection-cdr3-ab/v4/PFO004.chosen-tcrs.cd4.complete-single.tier2.preferred-fdr-0.001.txt
../../tcr-selection-cdr3-ab/v4/PFO004.chosen-tcrs.cd4.complete-single.tier3.preferred-fdr-0.01.txt
../../tcr-selection-cdr3-ab/v4/PFO004.chosen-tcrs.cd4.complete-single.tier4.preferred-fdr-0.1.txt
../../tcr-selection-cdr3-ab/v4/PFO004.chosen-tcrs.cd4.complete-single.tier5.preferred-fdr-0.15.txt
../../tcr-selection-cdr3-ab/v4/PFO004.chosen-tcrs.cd4.partial-cdr3b.tier1.preferred-fdr-0.0001.txt
../../tcr-selection-cdr3-ab/v4/PFO004.chosen-tcrs.cd4.partial-cdr3b.tier2.preferred-fdr-0.001.txt
../../tcr-selection-cdr3-ab/v4/PFO004.chosen-tcrs.cd4.partial-cdr3b.tier3.preferred-fdr-0.01.txt
../../tcr-selection-cdr3-ab/v4/PFO004.chosen-tcrs.cd4.partial-cdr3b.tier4.preferred-fdr-0.1.txt
../../tcr-selection-cdr3-ab/v4/PFO004.chosen-tcrs.cd4.partial-cdr3b.tier5.preferred-fdr-0.15.txt
../../tcr-selection-cdr3-ab/v4/PFO004.chosen-tcrs.cd8.complete-multi.tier1.preferred-fdr-0.0001.txt
../../tcr-selection-cdr3-ab/v4/PFO004.chosen-tcrs.cd8.complete-multi.tier2.preferred-fdr-0.001.txt
../../tcr-selection-cdr3-ab/v4/PFO004.chosen-tcrs.cd8.complete-multi.tier3.preferred-fdr-0.01.txt
../../tcr-selection-cdr3-ab/v4/PFO004.chosen-tcrs.cd8.complete-multi.tier4.preferred-fdr-0.1.txt
../../tcr-selection-cdr3-ab/v4/PFO004.chosen-tcrs.cd8.complete-multi.tier5.preferred-fdr-0.15.txt
../../tcr-selection-cdr3-ab/v4/PFO004.chosen-tcrs.cd8.complete-single.tier1.preferred-fdr-0.0001.txt
../../tcr-selection-cdr3-ab/v4/PFO004.chosen-tcrs.cd8.complete-single.tier2.preferred-fdr-0.001.txt
../../tcr-selection-cdr3-ab/v4/PFO004.chosen-tcrs.cd8.complete-single.tier3.preferred-fdr-0.01.txt
../../tcr-selection-cdr3-ab/v4/PFO004.chosen-tcrs.cd8.complete-single.tier4.preferred-fdr-0.1.txt
../../tcr-selection-cdr3-ab/v4/PFO004.chosen-tcrs.cd8.complete-single.tier5.preferred-fdr-0.15.txt
../../tcr-selection-cdr3-ab/v4/PFO004.chosen-tcrs.cd8.partial-cdr3b.tier1.preferred-fdr-0.0001.txt
../../tcr-selection-cdr3-ab/v4/PFO004.chosen-tcrs.cd8.partial-cdr3b.tier2.preferred-fdr-0.001.txt
../../tcr-selection-cdr3-ab/v4/PFO004.chosen-tcrs.cd8.partial-cdr3b.tier3.preferred-fdr-0.01.txt
../../tcr-selection-cdr3-ab/v4/PFO004.chosen-tcrs.cd8.partial-cdr3b.tier4.preferred-fdr-0.1.txt
../../tcr-selection-cdr3-ab/v4/PFO004.chosen-tcrs.cd8.partial-cdr3b.tier5.preferred-fdr-0.15.txt
../../tcr-selection-cdr3-ab/v4/cd4-selected-tcrs-union-of-all-counting-methods.txt
../../tcr-selection-cdr3-ab/v4/cd8-selected-tcrs-union-of-all-counting-methods.txt

In [315]:
selected_tcr_cdr3_abs = []
cols = {"alpha": [], "beta": []}
with open("../../tcr-selection-cdr3-ab/v4/cd8-selected-tcrs-union-of-all-counting-methods.txt") as f:
    for l in f:
        l = l.strip()
        if l:
            a, b = l.split("/")
            selected_tcr_cdr3_abs.append((a,b))
            cols["alpha"].append(a)
            cols["beta"].append(b)
df_selected_cd8_cdr3_ab = pd.DataFrame(cols)

In [316]:
"""
pd.merge(
    left: 'DataFrame | Series',
    right: 'DataFrame | Series',
    how: 'MergeHow' = 'inner',
    on: 'IndexLabel | AnyArrayLike | None' = None,
    left_on: 'IndexLabel | AnyArrayLike | None' = None,
    right_on: 'IndexLabel | AnyArrayLike | None' = None,
    left_index: 'bool' = False,
    right_index: 'bool' = False,
    sort: 'bool' = False,
    suffixes: 'Suffixes' = ('_x', '_y'),
    copy: 'bool | None' = None,
    indicator: 'str | bool' = False,
    validate: 'str | None' = None,
) -> 'DataFrame'
"""

df_join = pd.merge(
    left=df_final, 
    right=df_selected_cd8_cdr3_ab, 
    how='inner', 
    left_on=['TRA_1_cdr3', 'TRB_1_cdr3'], 
    right_on=['alpha', 'beta'])
df_join

,sample_path,sample_peptide,barcode,TRA_1_c_gene,TRA_2_c_gene,TRB_1_c_gene,TRB_2_c_gene,TRA_1_cdr1,TRA_2_cdr1,TRB_1_cdr1,...,TRB_2_v_gene,TRA_count,TRB_count,has_TRA,has_TRB,multi_TRA,multi_TRB,multi_either_TRA_or_TRB,alpha,beta
0,../cellranger-vdj-outputs/P1,P1,AACTCCCGTCGGGTCT-1,TRAC,NaN,TRBC1,NaN,TSDQSYG,NaN,LGHDT,...,NaN,1,1,True,True,False,False,False,CAMREGKGAGNMLTF,CASSRANSNQPQHF
1,../cellranger-vdj-outputs/P1,P1,ACGGGCTTCTGGAGCC-1,TRAC,NaN,TRBC1,NaN,TSDQSYG,NaN,LGHDT,...,NaN,1,1,True,True,False,False,False,CAMREGKGAGNMLTF,CASSRANSNQPQHF
2,../cellranger-vdj-outputs/P1,P1,ACTGATGCAACACGCC-1,TRAC,NaN,TRBC1,NaN,TSDQSYG,NaN,LGHDT,...,NaN,1,1,True,True,False,False,False,CAMREGKGAGNMLTF,CASSRANSNQPQHF
3,../cellranger-vdj-outputs/P1,P1,ACTGCTCTCGGATGTT-1,TRAC,NaN,TRBC1,TRBC2,TSDQSYG,NaN,LGHDT,...,TRBV20-1,1,2,True,True,False,True,True,CAMREGKGAGNMLTF,CASSRANSNQPQHF
4,../cellranger-vdj-outputs/P1,P1,AGAGCGACAGAGTGTG-1,TRAC,NaN,TRBC1,NaN,TSDQSYG,NaN,LGHDT,...,NaN,1,1,True,True,False,False,False,CAMREGKGAGNMLTF,CASSRANSNQPQHF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,../cellranger-vdj-outputs/P7,P7,TGAGCCGGTGTTTGGT-1,TRAC,NaN,TRBC2,NaN,TSINN,NaN,KGHSH,...,NaN,1,1,True,True,False,False,False,CATDSGGYQKVTF,CASSEGGHTGELFF
499,../cellranger-vdj-outputs/P7,P7,TGGCCAGGTAGGAGTC-1,TRAC,NaN,TRBC2,NaN,TSINN,NaN,KGHSH,...,NaN,1,1,True,True,False,False,False,CATDSGGYQKVTF,CASSEGGHTGELFF
500,../cellranger-vdj-outputs/P7,P7,TGGCTGGCACTGAAGG-1,TRAC,NaN,TRBC2,NaN,TSINN,NaN,KGHSH,...,NaN,1,1,True,True,False,False,False,CATDSGGYQKVTF,CASSEGGHTGELFF
501,../cellranger-vdj-outputs/P7,P7,TTTGCGCTCTTTAGGG-1,TRAC,NaN,TRBC2,NaN,KTLYG,NaN,SGHAT,...,NaN,1,1,True,True,False,False,False,CGADTNFGNEKLTF,CASSPGLATQYF
502,../cellranger-vdj-outputs/P7,P7,TTTGGTTCATCGGTTA-1,TRAC,NaN,TRBC2,NaN,TSINN,NaN,KGHSH,...,NaN,1,1,True,True,False,False,False,CATDSGGYQKVTF,CASSEGGHTGELFF

In [317]:
df_join[[c for c in df_join.columns if "gene" in c]]

,TRA_1_c_gene,TRA_2_c_gene,TRB_1_c_gene,TRB_2_c_gene,TRB_1_d_gene,TRB_2_d_gene,TRA_1_j_gene,TRA_2_j_gene,TRB_1_j_gene,TRB_2_j_gene,TRA_1_v_gene,TRA_2_v_gene,TRB_1_v_gene,TRB_2_v_gene
0,TRAC,NaN,TRBC1,NaN,None,NaN,TRAJ39,NaN,TRBJ1-5,NaN,TRAV14/DV4,NaN,TRBV3-1,NaN
1,TRAC,NaN,TRBC1,NaN,None,NaN,TRAJ39,NaN,TRBJ1-5,NaN,TRAV14/DV4,NaN,TRBV3-1,NaN
2,TRAC,NaN,TRBC1,NaN,None,NaN,TRAJ39,NaN,TRBJ1-5,NaN,TRAV14/DV4,NaN,TRBV3-1,NaN
3,TRAC,NaN,TRBC1,TRBC2,None,None,TRAJ39,NaN,TRBJ1-5,TRBJ2-7,TRAV14/DV4,NaN,TRBV3-1,TRBV20-1
4,TRAC,NaN,TRBC1,NaN,None,NaN,TRAJ39,NaN,TRBJ1-5,NaN,TRAV14/DV4,NaN,TRBV3-1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,TRAC,NaN,TRBC2,NaN,TRBD1,NaN,TRAJ13,NaN,TRBJ2-2,NaN,TRAV17,NaN,TRBV18,NaN
499,TRAC,NaN,TRBC2,NaN,TRBD1,NaN,TRAJ13,NaN,TRBJ2-2,NaN,TRAV17,NaN,TRBV18,NaN
500,TRAC,NaN,TRBC2,NaN,TRBD1,NaN,TRAJ13,NaN,TRBJ2-2,NaN,TRAV17,NaN,TRBV18,NaN
501,TRAC,NaN,TRBC2,NaN,None,NaN,TRAJ48,NaN,TRBJ2-3,NaN,TRAV34,NaN,TRBV11-2,NaN
502,TRAC,NaN,TRBC2,NaN,TRBD1,NaN,TRAJ13,NaN,TRBJ2-2,NaN,TRAV17,NaN,TRBV18,NaN

In [318]:
from collections import defaultdict
selected_cols = defaultdict(list)

for i, ((a, b), sub_df) in enumerate(df_join.sort_values("sample_peptide").groupby(['TRA_1_cdr3', 'TRB_1_cdr3'])):
    selected_cols["CDR3_alpha"] += [a]
    selected_cols["CDR3_beta"] += [b]
    peptide = sub_df["sample_peptide"].mode().iloc[0]
    selected_cols["Peptide"] += [peptide]
    
    sub_df_peptide = sub_df[sub_df.sample_peptide == peptide]
    
    
    full_alphas = sub_df_peptide["TRA_1_combined_vdj_aa_sequence"]
    full_betas = sub_df_peptide["TRB_1_combined_vdj_aa_sequence"]

    full_combined = full_alphas + "/" + full_betas
    most_common_combined = full_combined.mode().iloc[0]
    
    selected_cols["VDJ_alpha_beta_aa"] += [most_common_combined]
    alpha_aa = most_common_combined.split("/")[0]
    selected_cols["VDJ_alpha_aa"] += [alpha_aa]
    beta_aa = most_common_combined.split("/")[1]
    selected_cols["VDJ_beta_aa"] += [beta_aa]
    
    #### 
    # get the subset of cells that have the most common alpha/beta pairing
    ###
    mask = (full_combined == most_common_combined)
    sub_df_most_common = sub_df_peptide[mask]


    # counts for cells that support this alpha/beta CDR3
    selected_cols["Cell_Count"] += [len(sub_df_most_common)]
    selected_cols["Cell_Barcodes"] += [list(sub_df_most_common.barcode)]
    selected_cols["Alpha_Contig_IDs"] += [list(sub_df_most_common.TRA_1_contig_id)] 
    selected_cols["Beta_Contig_IDs"] += [list(sub_df_most_common.TRB_1_contig_id)] 

    selected_cols["Alpha_Reads_Mean"] += [sub_df_most_common.TRA_1_reads.mean()]
    selected_cols["Beta_Reads_Mean"] += [sub_df_most_common.TRB_1_reads.mean()]
    selected_cols["Alpha_UMIs_Mean"] += [sub_df_most_common.TRA_1_umis.mean()]
    selected_cols["Beta_UMIs_Mean"] += [sub_df_most_common.TRB_1_umis.mean()]
    
    # make sure alpha chain DNA sequence gets us back the same amino acid seq
    def modal_value(column):
        """Returns most common value for a column in the subset of cells that match
        the alpha/beta CDR3 we have grouped on"""
        col_values = sub_df_most_common[column]
        if col_values.isnull().all():
            return None
        return col_values.mode().iloc[0]
        
    alpha_dna = modal_value("TRA_1_combined_vdj_nt_sequence")
    selected_cols["VDJ_alpha_dna"] += [alpha_dna]
    alpha_dna_translated, alpha_dna_ragged_nt = translate_dna(alpha_dna)
    assert alpha_dna_translated == alpha_aa
    selected_cols["VDJ_alpha_dna_ragged_3p_nt"] += [alpha_dna_ragged_nt]

    # make sure beta chain DNA sequence gets us back the same amino acid seq
    beta_dna = modal_value("TRB_1_combined_vdj_nt_sequence")
    
    selected_cols["VDJ_beta_dna"] += [beta_dna]
    beta_dna_translated, beta_dna_ragged_nt = translate_dna(beta_dna)
    assert beta_dna_translated == beta_aa
    selected_cols["VDJ_beta_dna_ragged_3p_nt"] += [beta_dna_ragged_nt]


    
    for chain, prefix in [("alpha", "TRA_1"), ("beta", "TRB_1")]:
        # CDR1 and CDR2 for alpha/beta chains
        for other_cdr in ["cdr1", "cdr2"]:
            selected_cols["%s_%s" % (other_cdr.upper(), chain)] += [modal_value("%s_%s" % (prefix, other_cdr))]
        # include gene usage
        for gene in "vdjc":
            if gene == "d" and chain == "alpha":
                # no D gene / diversity segments in the alpha chain of the TCR
                continue 
            col_name = "%s_%s_gene" % (prefix, gene)
         
            selected_cols["%s_%s_gene" % (chain, gene)] += [modal_value(col_name)]
df_selected_full_seqs = pd.DataFrame(selected_cols);
df_selected_full_seqs

,CDR3_alpha,CDR3_beta,Peptide,VDJ_alpha_beta_aa,VDJ_alpha_aa,VDJ_beta_aa,Cell_Count,Cell_Barcodes,Alpha_Contig_IDs,Beta_Contig_IDs,...,CDR2_alpha,alpha_v_gene,alpha_j_gene,alpha_c_gene,CDR1_beta,CDR2_beta,beta_v_gene,beta_d_gene,beta_j_gene,beta_c_gene
0,CAAAYIDNLFF,CASSPDRVNTGELFF,P5,QKEVEQNSGPLSVPEGAIASLNCTYSDRGSQSFFWYRQYSGKSPEL...,QKEVEQNSGPLSVPEGAIASLNCTYSDRGSQSFFWYRQYSGKSPEL...,EAGVVQSPRYKIIEKKQPVAFWCNPISGHNTLYWYLQNLGQGPELL...,27,"[GTCACGGCAAGCCGTC-1, GTCAAGTTCCGCGTTT-1, GTCAA...","[GTCACGGCAAGCCGTC-1_contig_1, GTCAAGTTCCGCGTTT...","[GTCACGGCAAGCCGTC-1_contig_2, GTCAAGTTCCGCGTTT...",...,IYSNGD,TRAV12-2,TRAJ36,TRAC,SGHNT,YENEEA,TRBV11-3,None,TRBJ2-2,TRBC2
1,CAADNAGNMLTF,CASSSEYLGEQFF,P15,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,ETGVTQSPTHLIKTRGQQVTLRCSSQSGHNTVSWYQQALGQGPQFI...,3,"[TAAGTGCCATGTTCCC-1, AACTTTCAGTTGAGTA-1, CAACC...","[TAAGTGCCATGTTCCC-1_contig_1, AACTTTCAGTTGAGTA...","[TAAGTGCCATGTTCCC-1_contig_2, AACTTTCAGTTGAGTA...",...,ISSIKDK,TRAV29/DV5,TRAJ39,TRAC,SGHNT,YYREEE,TRBV5-4,None,TRBJ2-1,TRBC2
2,CAAIKNQFYF,CASSRAGGQETQYF,P11,GENVEQHPSTLSVQEGDSAVIKCTYSDSASNYFPWYKQELGKGPQL...,GENVEQHPSTLSVQEGDSAVIKCTYSDSASNYFPWYKQELGKGPQL...,GAGVSQTPSNKVTEKGKYVELRCDPISGHTALYWYRQSLGQGPEFL...,26,"[GTCTTCGCATCTCGCT-1, GTCCTCACAGGCGATA-1, TTGCG...","[GTCTTCGCATCTCGCT-1_contig_2, GTCCTCACAGGCGATA...","[GTCTTCGCATCTCGCT-1_contig_1, GTCCTCACAGGCGATA...",...,IRSNVGE,TRAV13-1,TRAJ49,TRAC,SGHTA,FQGTGA,TRBV7-3,None,TRBJ2-5,TRBC2
3,CAASARETSGSRLTF,CASSPIGAYEQYF,P15,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,NAGVMQNPRHLVRRRGQEARLRCSPMKGHSHVYWYRQLPEEGLKFM...,44,"[GTACTTTCAGGACCCT-1, GTAACGTTCCTGCAGG-1, GGTGT...","[GTACTTTCAGGACCCT-1_contig_2, GTAACGTTCCTGCAGG...","[GTACTTTCAGGACCCT-1_contig_1, GTAACGTTCCTGCAGG...",...,ISSIKDK,TRAV29/DV5,TRAJ58,TRAC,KGHSH,LQKENI,TRBV18,None,TRBJ2-7,TRBC2
4,CAASAWEGQNFVF,CASSLLDQPQHF,P5,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,EAQVTQNPRYLITVTGKKLTVTCSQNMNHEYMSWYRQDPGLGLRQI...,12,"[GTGCGGTAGCCACGTC-1, GCGCCAAAGTGTTGAA-1, GTTCA...","[GTGCGGTAGCCACGTC-1_contig_2, GCGCCAAAGTGTTGAA...","[GTGCGGTAGCCACGTC-1_contig_1, GCGCCAAAGTGTTGAA...",...,ISSIKDK,TRAV29/DV5,TRAJ26,TRAC,MNHEY,SMNVEV,TRBV27,None,TRBJ1-5,TRBC1
5,CAASDTGGFKTIF,CASSSRARGQETQYF,P15,GQQVMQIPQYQHVQEGEDFTTYCNSSTTLSNIQWYKQRPGGHPVFL...,GQQVMQIPQYQHVQEGEDFTTYCNSSTTLSNIQWYKQRPGGHPVFL...,GAGVSQSPSNKVTEKGKDVELRCDPISGHTALYWYRQSLGQGLEFL...,1,[AGTGTCAAGCTCAACT-1],[AGTGTCAAGCTCAACT-1_contig_2],[AGTGTCAAGCTCAACT-1_contig_1],...,LVKSGEV,TRAV25,TRAJ9,TRAC,SGHTA,FQGNSA,TRBV7-2,None,TRBJ2-5,TRBC2
6,CAATPGSYNTDKLIF,CAISGGTGKGTQYF,P15,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,DAGITQSPRHKVTETGTPVTLRCHQTENHRYMYWYRQDPGHGLRLI...,7,"[GGACATTCATTCTCAT-1, GCTCCTAAGTCCGGTC-1, TGTGT...","[GGACATTCATTCTCAT-1_contig_1, GCTCCTAAGTCCGGTC...","[GGACATTCATTCTCAT-1_contig_2, GCTCCTAAGTCCGGTC...",...,ISSIKDK,TRAV29/DV5,TRAJ34,TRAC,ENHRY,SYGVKD,TRBV10-3,None,TRBJ2-5,TRBC2
7,CAETGFSDGQKLLF,CASSLDAEEGHYEQYF,P2,GEDVEQSLFLSVREGDSSVINCTYTDSSSTYLYWYKQEPGAGLQLL...,GEDVEQSLFLSVREGDSSVINCTYTDSSSTYLYWYKQEPGAGLQLL...,KAGVTQTPRYLIKTRGQQVTLSCSPISGHRSVSWYQQTPGQGLQFL...,7,"[GTCGGGTTCAACACTG-1, TATTACCTCGGAGGTA-1, CTGTT...","[GTCGGGTTCAACACTG-1_contig_2, TATTACCTCGGAGGTA...","[GTCGGGTTCAACACTG-1_contig_1, TATTACCTCGGAGGTA...",...,IFSNMDM,TRAV5,TRAJ16,TRAC,SGHRS,YFSETQ,TRBV5-1,None,TRBJ2-7,TRBC2
8,CAGHSAGGTSYGKLTF,CASSLYAGAWSYTF,P11,GQQLNQSPQSMFIQEGEDVSMNCTSSSIFNTWLWYKQDPGEGPVLL...,GQQLNQSPQSMFIQEGEDVSMNCTSSSIFNTWLWYKQDPGEGPVLL...,EAQVTQNPRYLITVTGKKLTVTCSQNMNHEYMSWYRQDPGLGLRQI...,23,"[TACTCATAGATCGGGT-1, GTCACAATCGATAGAA-1, GACCA...","[TACTCATAGATCGGGT-1_contig_1, GTCACAATCGATAGAA...","[TACTCATAGATCGGGT-1_contig_2, GTCACAATCGATAGAA...",...,LYKAGEL,TRAV35,TRAJ52,TRAC,MNHEY,SMNVEV,TRBV27,None,TRBJ1-2,TRBC1
9,CAGQPGSSNYKLTF,CASSVQGATEAFF,P12,GQQLNQSPQSMFIQEGEDVSMNCTSSSIFNTWLWYKQDPGEGPVLL...,GQQLNQSPQSMFIQEGEDVSMNCTSSSIFNTWLWYKQDPGEGPVLL...,EPEVTQTPSHQVTQMGQEVILRCVPISNHLYFYWYRQILGQKVEFL...,43,"[GTCTTCGGTTAGTGGG-1, GTCGTAAAGTGGAGAA-1, GTACT...","[GTCTTCGGTTAGTGGG-1_contig_1, GTCGTAAAGTGGAGAA...","[GTCTTCGGTTAGTGGG-1_contig_2, GTCGTAAAGTGGAGAA...",...,LYKAGEL,TRAV35,TRAJ53,TRAC,SNHLY,FYNNEI,TRBV2,TRBD1,TRBJ1-1,TRBC1
10,CALDIDSNYQLIW,CAISERVNEQFF,P15,SQKIEQNSEALNIQEGKTATLTCNYTNYSPAYLQWYRQDPGRGPVF...,SQKIEQNSEALNIQEGKTATLTCNYTNYSPAYLQWYRQDPGRGPVF...,DAGITQSPRHKVTETGTPVTLRCHQTENHRYMYWYRQDPGHGLRLI...,11,"[GGCTCGATCTTGTCAT-1, GACTGCGCATTGGGCC-1, GAATG...","[GGCTCGATCTTGTCAT-1_contig_2, GACTGCGCATTGGGCC...","[GGCTCGATCTTGTCAT-1_contig_1, GACTGCGCATTGGGCC...",...,IRENEKE,TRAV6,TRAJ33,TRAC,ENHRY,SYGVKD,TRBV10-3,None,TRBJ2-1,TRBC2
11,CAMREGKGAGNMLTF,CASSRANSNQPQHF,P1,AQKITQTQPGMFVQEKEAVTLDCTYDTSDQSYGLFWYKQPSSGEMI...,AQKITQTQPGMFVQEKEAVTLDCTYDTSDQSYGLFWYKQPSSGEMI...,DTAVSQTPKYLVTQMGNDKSIKCEQNLGHDTMYWYKQDSKKFLKIM...,38,"[AACTCCCGTCGGGTCT-1, GGCGACTGTAGCGATG-1, GGCTG...","[AACTCCCGTCGGGTCT-1_contig_2, GGCGACTGTAGCGATG...","[AACTCCCGTCGGGTCT-1_contig_1, GGCGACTGTAGCGATG...",...,QGSYDEQN,TRAV14/DV4,TRAJ39,TRAC,LGHDT,YNNKEL,TRBV3-1,None,TRBJ1-5,TRBC1
12,CASERGSARQLTF,CASSFGTEDTQYF,P15,QKEVEQNSGPLSVPEGAIASLNCTYSDRGSQSFFWYRQYSGKSPEL...,QKEVEQNSGPLSVPEGAIASLNCTYSDRGSQSFFWYRQYSGKSPEL...,EAGVAQSPRYKIIEKRQSVAFWCNPISGHATLYWYQQILGQGPKLL...,6,"[GCGCCAAAGACTGGGT-1, GCAGCCATCCTCTAGC-1, CTTAG...","[GCGCCAAAGACTGGGT-1_contig_1, GCAGCCATCCTCTAGC...","[GCGCCAAAGACTGGGT-1_contig_2, GCAGCCATCCTCTAGC...",...,IYSNGD,TRAV12-2,TRAJ22,TRAC,SGHAT,FQNNGV,TRBV11-2,None,TRBJ2-3,TRBC2
13,CATDSGGYQKVTF,CASSEGGHTGELFF,P7,SQQGEEDPQALSIQEGENATMNCSYKTSINNLQWYRQNSGRGLVHL...,SQQGEEDPQALSIQEGENATMNCSYKTSINNLQWYRQNSGRGLVHL...,NAGVMQNPRHLVRRRGQEARLRCSPMKGHSHVYWYRQLPEEGLKFM...,41,"[GTAACTGGTGTGGCTC-1, GCTCTGTTCTTTACAC-1, GACAC...","[GTAACTGGTGTGGCTC-1_contig_2, GCTCTGTTCTTTACAC...","[GTAACTGGTGTGGCTC-1_contig_1, GCTCTGTTCTTTACAC...",...,IRSNERE,TRAV17,TRAJ13,TRAC,KGHSH,LQKENI,TRBV18,TRBD1,TRBJ2-2,TRBC2
14,CATVSVGGFGNVLHC,CASSPDRVNTGELFF,P5,GENVEQHPSTLSVQEGDSAVIKCTYSDSASNYFPWYKQELGKGPQL...,GENVEQHPSTLSVQEGDSAVIKCTYSDSASNYFPWYKQELGKGPQL...,EAGVVQSPRYKIIEKKQPVAFWCNPISGHNTLYWYLQNLGQGPELL...,21,"[GTACTCCTCCAAGTAC-1, GGTGTTATCTTGTACT-1, GCTTG...","[GTACTCCTCCAAGTAC-1_contig_3, GGTGTTATCTTGTACT...","[GTACTCCTCCAAGTAC-1_contig_2, GGTGTTATCTTGTACT...",...,IRSNVGE,TRAV13-1,TRAJ35,TRAC,SGHNT,YENEEA,TRBV11-3,None,TRBJ2-2,TRBC2
15,CAVGASNAGGTSYGKLTF,CASSLARYDEQYF,P15,AQSVTQPDIHITVSEGASLELRCNYSYGATPYLFWYVQSPGQGLQL...,AQSVTQPDIHITVSEGASLELRCNYSYGATPYLFWYVQSPGQGLQL...,DTGVSQNPRHKITKRGQNVTFRCDPISEHNRLYWYRQTLGQGPEFL...,2,"[TACCTTACACTGTCGG-1, ATCACGATCATCTGTT-1]","[TACCTTACACTGTCGG-1_contig_2, ATCACGATCATCTGTT...","[TACCTTACACTGTCGG-1_contig_1, ATCACGATCATCTGTT...",...,YFSGDTLV,TRAV8-3,TRAJ52,TRAC,SEHNR,FQNEAQ,TRBV7-9,None,TRBJ2-7,TRBC2
16,CAVLYNTDKLIF,CASSSTRGYGANVLTF,P15,KQEVTQIPAALSVPEGENLVLNCSFTDSAIYNLQWFRQDPGKGLTS...,KQEVTQIPAALSVPEGENLVLNCSFTDSAIYNLQWFRQDPGKGLTS...,GAGVSQSPSNKVTEKGKDVELRCDPISGHTALYWYRQSLGQGLEFL...,3,"[GCTGGGTCATTGTGCA-1, GCTGCGATCATCGCTC-1, CCGGG...","[GCTGGGTCATTGTGCA-1_contig_2, GCTGCGATCATCGCTC...","[GCTGGGTCATTGTGCA-1_contig_1, GCTGCGATCATCGCTC...",...,IQSSQRE,TRAV21,TRAJ34,TRAC,SGHTA,FQGNSA,TRBV7-2,TRBD1,TRBJ2-6,TRBC2
17,CAVRDGKAAGNKLTF,CASSLVTGAFDEQFF,P13,AQSVAQPEDQVNVAEGNPLTVKCTYSVSGNPYLFWYVQYPNRGLQF...,AQSVAQPEDQVNVAEGNPLTVKCTYSVSGNPYLFWYVQYPNRGLQF...,DTGVSQNPRHKITKRGQNVTFRCDPISEHNRLYWYRQTLGQGPEFL...,66,"[GGATTACTCATTTGGG-1, GGACAAGTCATCGATG-1, GGACA...","[GGATTACTCATTTGGG-1_contig_1, GGACAAGTCATCGATG...","[GGATTACTCATTTGGG-1_contig_2, GGACAAGTCATCGATG...",...,YITGDNLV,TRAV3,TRAJ17,TRAC,SEHNR,FQNEAQ,TRBV7-9,TRBD1,TRBJ2-1,TRBC2
18,CAVSVRRGGGSQGNLIF,CASSYSRGYEQYF,P15,AQSVTQLDSQVPVFEEAPVELRCNYSSSVSVYLFWYVQYPNQGLQL...,AQSVTQLDSQVPVFEEAPVELRCNYSSSVSVYLFWYVQYPNQGLQL...,NAGVTQTPKFQVLKTGQSMTLQCAQDMNHEYMSWYRQDPGMGLRLI...,2,"[ATCTGCCTCAGTGCAT-1, CTCACACAGGGAACGG-1]","[ATCTGCCTCAGTGCAT-1_contig_1, CTCACACAGGGAACGG...","[ATCTGCCTCAGTGCAT-1_contig_2, CTCACACAGGGAACGG...",...,YLSGSTLV,TRAV8-6,TRAJ42,TRAC,MNHEY,SVGAGI,TRBV6-5,None,TRBJ2-7,TRBC2
19,CAVVRGNDYKLSF,CASSPRQDSYEQYF,P3,EDQVTQSPEALRLQEGESSSLNCSYTVSGLRGLFWYRQDPGKGPEF...,EDQVTQSPEALRLQEGESSSLNCSYTVSGLRGLFWYRQDPGKGPEF...,NAGVMQNPRHLVRRRGQEARLRCSPMKGHSHVYWYRQLPEEGLKFM...,1,[GGACAAGGTGCACGAA-1],[GGACAAGGTGCACGAA-1_contig_2],[GGACAAGGTGCACGAA-1_contig_1],...,LYSAGEE,TRAV20,TRAJ20,TRAC,KGHSH,LQKENI,TRBV18,None,TRBJ2-7,TRBC2
20,CAVYNNARLMF,CASLGRGGLAKNIQYF,P12,GQQVMQIPQYQHVQEGEDFTTYCNSSTTLSNIQWYKQRPGGHPVFL...,GQQVMQIPQYQHVQEGEDFTTYCNSSTTLSNIQWYKQRPGGHPVFL...,EPEVTQTPSHQVTQMGQEVILRCVPISNHLYFYWYRQILGQKVEFL...,12,"[GGGAATGGTAGCTAAA-1, CTTACCGAGCTCAACT-1, TCTGA...","[GGGAATGGTAGCTAAA-1_contig_2, CTTACCGAGCTCAACT...","[GGGAATGGTAGCTAAA-1_contig_1, CTTACCGAGCTCAACT...",...,LVKSGEV,TRAV25,TRAJ31,TRAC,SNHLY,FYNNEI,TRBV2,None,TRBJ2-4,TRBC2
21,CAYRDSNYQLIW,CASSPTGDSGNTIYF,P10,AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMI...,AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMI...,NAGVMQNPRHLVRRRGQEARLRCSPMKGHSHVYWYRQLPEEGLKFM...,41,"[GGTGCGTTCGGAAATA-1, GGCTGGTGTTCGCTAA-1, GCTTC...","[GGTGCGTTCGGAAATA-1_contig_2, GGCTGGTGTTCGCTAA...","[GGTGCGTTCGGAAATA-1_contig_1, GGCTGGTGTTCGCTAA...",...,QEAYKQQN,TRAV38-2/DV8,TRAJ33,TRAC,KGHSH,LQKENI,TRBV18,None,TRBJ1-3,TRBC1
22,CAYRSAKGNDMRF,CASSFYFGQGYEQYF,P15,AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMI...,AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMI...,GAGVSQSPSNKVTEKGKDVELRCDPISGHTALYWYRQSLGQGLEFL...,3,"[ACACCGGGTTCGGCAC-1, AACCGCGAGTAACCCT-1, CGAGA...","[ACACCGGGTTCGGCAC-1_contig_2, AACCGCGAGTAACCCT...","[ACACCGGGTTCGGCAC-1_contig_1, AACCGCGAGTAACCCT...",...,QEAYKQQN,TRAV38-2/DV8,TRAJ43,TRAC,SGHTA,FQGNSA,TRBV7-2,None,TRBJ2-7,TRBC2
23,CAYWVGGGGADGLTF,CASSLTPGGVKETQYF,P12,AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMI...,AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMI...,GAGVSQSPRYKVAKRGQDVALRCDPISGHVSLFWYQQALGQGPEFL...,33,"[GTGCATATCCGATATG-1, GACGTTACAGGTCGTC-1, GACGC...","[GTGCATATCCGATATG-1_contig_1, GACGTTACAGGTCGTC...","[GTGCATATCCGATATG-1_contig_2, GACGTTACAGGTCGTC...",...,QEAYKQQN,TRAV38-2/DV8,TRAJ45,TRAC,SGHVS,FQNEAQ,TRBV7-8,None,TRBJ2-5,TRBC2
24,CGADTNFGNEKLTF,CASSPGLATQYF,P7,SQELEQSPQSLIVQEGKNLTINCTSSKTLYGLYWYKQKYGEGLIFL...,SQELEQSPQSLIVQEGKNLTINCTSSKTLYGLYWYKQKYGEGLIFL...,EAGVAQSPRYKIIEKRQSVAFWCNPISGHATLYWYQQILGQGPKLL...,26,"[GGGTTGCTCCGTCATC-1, GGAATAACATGTAGTC-1, GCATG...","[GGGTTGCTCCGTCATC-1_contig_1, GGAATAACATGTAGTC...","[GGGTTGCTCCGTCATC-1_contig_2, GGAATAACATGTAGTC...",...,LQKGGEE,TRAV34,TRAJ48,TRAC,SGHAT,FQNNGV,TRBV11-2,None,TRBJ2-3,TRBC2
25,CGTETGNNRLAF,CASSKKGTGTDTQYF,P15,QQPVQSPQAVILREGEDAVINCSSSKALYSVHWYRQKHGEAPVFLM...,QQPVQSPQAVILREGEDAVINCSSSKALYSVHWYRQKHGEAPVFLM...,GAGVSQSPRYKVAKRGQDVALRCDPISGHVSLFWYQQALGQGPEFL...,1,[CGATGGCCATACCATG-1],[CGATGGCCATACCATG-1_contig_3],[CGATGGCCATACCATG-1_contig_1],...,LLKGGEQ,TRAV30,TRAJ7,TRAC,SGHVS,FQNEAQ,TRBV7-8,None,TRBJ2-3,TRBC2

In [319]:
df_selected_full_seqs.Cell_Barcodes

0     [GTCACGGCAAGCCGTC-1, GTCAAGTTCCGCGTTT-1, GTCAA...
1     [TAAGTGCCATGTTCCC-1, AACTTTCAGTTGAGTA-1, CAACC...
2     [GTCTTCGCATCTCGCT-1, GTCCTCACAGGCGATA-1, TTGCG...
3     [GTACTTTCAGGACCCT-1, GTAACGTTCCTGCAGG-1, GGTGT...
4     [GTGCGGTAGCCACGTC-1, GCGCCAAAGTGTTGAA-1, GTTCA...
5                                  [AGTGTCAAGCTCAACT-1]
6     [GGACATTCATTCTCAT-1, GCTCCTAAGTCCGGTC-1, TGTGT...
7     [GTCGGGTTCAACACTG-1, TATTACCTCGGAGGTA-1, CTGTT...
8     [TACTCATAGATCGGGT-1, GTCACAATCGATAGAA-1, GACCA...
9     [GTCTTCGGTTAGTGGG-1, GTCGTAAAGTGGAGAA-1, GTACT...
10    [GGCTCGATCTTGTCAT-1, GACTGCGCATTGGGCC-1, GAATG...
11    [AACTCCCGTCGGGTCT-1, GGCGACTGTAGCGATG-1, GGCTG...
12    [GCGCCAAAGACTGGGT-1, GCAGCCATCCTCTAGC-1, CTTAG...
13    [GTAACTGGTGTGGCTC-1, GCTCTGTTCTTTACAC-1, GACAC...
14    [GTACTCCTCCAAGTAC-1, GGTGTTATCTTGTACT-1, GCTTG...
15             [TACCTTACACTGTCGG-1, ATCACGATCATCTGTT-1]
16    [GCTGGGTCATTGTGCA-1, GCTGCGATCATCGCTC-1, CCGGG...
17    [GGATTACTCATTTGGG-1, GGACAAGTCATCGATG-1, GGACA...
18             [ATCTGCCTCAGTGCAT-1, CTCACACAGGGAACGG-1]
19                                 [GGACAAGGTGCACGAA-1]
20    [GGGAATGGTAGCTAAA-1, CTTACCGAGCTCAACT-1, TCTGA...
21    [GGTGCGTTCGGAAATA-1, GGCTGGTGTTCGCTAA-1, GCTTC...
22    [ACACCGGGTTCGGCAC-1, AACCGCGAGTAACCCT-1, CGAGA...
23    [GTGCATATCCGATATG-1, GACGTTACAGGTCGTC-1, GACGC...
24    [GGGTTGCTCCGTCATC-1, GGAATAACATGTAGTC-1, GCATG...
25                                 [CGATGGCCATACCATG-1]
Name: Cell_Barcodes, dtype: object

In [320]:
sub_df_peptide

,sample_path,sample_peptide,barcode,TRA_1_c_gene,TRA_2_c_gene,TRB_1_c_gene,TRB_2_c_gene,TRA_1_cdr1,TRA_2_cdr1,TRB_1_cdr1,...,TRB_2_v_gene,TRA_count,TRB_count,has_TRA,has_TRB,multi_TRA,multi_TRB,multi_either_TRA_or_TRB,alpha,beta
315,../cellranger-vdj-outputs/P15,P15,CGATGGCCATACCATG-1,TRAC,NaN,TRBC2,TRBC1,KALYS,NaN,SGHVS,...,TRBV20-1,1,2,True,True,False,True,True,CGTETGNNRLAF,CASSKKGTGTDTQYF

In [321]:
df_selected_full_seqs["Cell_Count"].describe()

count    26.000000
mean     19.230769
std      17.947273
min       1.000000
25%       3.000000
50%      12.000000
75%      31.500000
max      66.000000
Name: Cell_Count, dtype: float64

In [322]:
df_selected_full_seqs.to_csv("PFO004.selected.CD8.vdj-tcr-sequences.no-leader.no-constant.csv")

In [323]:
df_final[["TRA_count", "TRB_count"]].value_counts()

TRA_count  TRB_count
1          1            62613
0          1            21089
2          1             5509
1          0             5053
           2             3009
2          2             1220
Name: count, dtype: int64

In [324]:
from collections import Counter
counter = Counter()

for _, row in df_final[["TRA_1_combined_vdj_aa_sequence", "TRA_2_combined_vdj_aa_sequence", "TRB_1_combined_vdj_aa_sequence", "TRB_2_combined_vdj_aa_sequence"]].iterrows():
    xs = row.values
    if all([type(x) is str for x in xs]):
        key = tuple(sorted(xs))
        counter[key] += 1

In [325]:
counter.most_common(10)

[(('AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMILVIRQEAYKQQNATENRFSVNFQKAAKSFSLKISDSQLGDAAMYFCAYRSARGGSEKLVFGKGTKLTVNP',
   'EAQVTQNPRYLITVTGKKLTVTCSQNMNHEYMSWYRQDPGLGLRQIYYSMNVEVTDKGDVPEGYKVSRKEKRNFPLILESPSPNQTSLYFCASRASGGRETQYFGPGTRLLVL',
   'SAVISQKPSRDICQRGTSLTIQCQVDSQVTMMFWYRQQPGQSLTLIATANQGSEATYESGFVIDKFPISRPNLTFSTLTVSNMSPEDSSIYLCSVDYPRQGLSPLHFGNGTRLTVT',
   'SNSVKQTGQITVSEGASVTMNCTYTSTGYPTLFWYVEYPSKPLQLLQRETMENSKNFGGGNIKDKNSPIVKYSVQVSDSAVYYCLLGDDRGGSEKLVFGKGTKLTVNP'),
  41),
 (('AQRVTQPEKLLSVFKGAPVELKCNYSYSGSPELFWYVQYSRQRLQLLLRHISRESIKGFTADLNKGETSFHLKKPFAQEEDSAMYYCALKSTDGQKLLFARGTMLKVDL',
   'DGGITQSPKYLFRKEGQNVTLSCEQNLNHDAMYWYRQDPGQGLRLIYYSQIVNDFQKGDIAEGYSVSREKKESFPLTVTSAQKNPTAFYLCATSSGMAEAFFGQGTRLTVV',
   'ETGVTQSPTHLIKTRGQQVTLRCSSQSGHNTVSWYQQALGQGPQFIFQYYREEENGRGNFPPRFSGLQFPNYSSELNVNALELDDSALYLCASSPPPNTFGSGTRLTVV',
   'GQNIDQPTEMTATEGAIVQINCTYQTSGFNGLFWYQQHAGEAPTFLSYNVLDGLEEKGRFSSFLSRSKGYSYLLLKELQMKDSASYLCAVPDNYGQNFVFGPGTRLSVLP'),
  5),
 (('DGGITQSPKYLFRKEGQNVTLSCEQNLNHDAMYWYRQDPGQGLRLIYYSQIVNDFQKGDIAEGYSVSREKKESFPLTVTSAQKNPTAFYLCASSIRGSPHEQYFGPGTRLTVT',
   'EAGVTQSPTHLIKTRGQQVTLRCSPISGHTSVYWYQQALGLGLQFLLWYDEGEERNRGNFPPRFSGRQFPNYSSELNVNALELEDSALYLCASSPRQVGDEQFFGPGTRLTVL',
   'GDSVTQMEGPVTLSEEAFLTINCTYTATGYPSLFWYVQYPGEGLQLLLKATKADDKGSNKGFEATYRKETTSFHLEKGSVQVSDSAVYFCALGGDTGRRALTFGSGTRLQVQP',
   'SQQGEEDPQALSIQEGENATMNCSYKTSINNLQWYRQNSGRGLVHLILIRSNEREKHSGRLRVTLDTSKKSSSLLITASRAADTASYFCATDMSSGSARQLTFGSGTQLTVLP'),
  4),
 (('DAGVIQSPRHEVTEMGQEVTLRCKPISGHNSLFWYRQTMMRGLELLIYFNNNVPIDDSGMPEDRFSAKMPNASFSTLKIQPSEPRDSAVYFCASSEQFLGLGEQYFGPGTRLTVT',
   'GAGVSQSPSNKVTEKGKDVELRCDPISGHTALYWYRQSLGQGLEFLIYFQGNSAPDKSGLPSDRFSAERTGGSVSTLTIQRTQQEDSAVYLCASSFSSGDTQYFGPGTRLTVL',
   'KQEVTQIPAALSVPEGENLVLNCSFTDSAIYNLQWFRQDPGKGLTSLLLIQSSQREQTSGRLNASLDKSSGRSTLYIAASQPGDSATYLCAVTPDSWGKLQFGAGTQVVVTP',
   'QQQVKQSPQSLIVQKGGISIINCAYENTAFDYFPWYQQFPGKGPALLIAIRPDVSEKKEGRFTISFNKSAKQFSLHIMDSQPGDSATYFCAARGLAGSARQLTFGSGTQLTVLP'),
  3),
 (('AQKVTQAQTEISVVEKEDVTLDCVYETRDTTYYLFWYKQPPSGELVFLIRRNSFDEQNEISGRYSWNFQKSTSSFNFTITASQVVDSAVYFCALARGRDDKIIFGKGTRLHILP',
   'EPEVTQTPSHQVTQMGQEVILRCVPISNHLYFYWYRQILGQKVEFLVSFYNNEISEKSEIFDDQFSVERPDGSNFTLKIRSTKLEDSAMYFCASARRGVEGEKLFFGSGTQLSVL',
   'GDSVTQMEGPVTLSEEAFLTINCTYTATGYPSLFWYVQYPGEGLQLLLKATKADDKGSNKGFEATYRKETTSFHLEKGSVQVSDSAVYFCALSGDMRFGAGTRLTVKP',
   'NAGVTQTPKFQVLKTGQSMTLQCAQDMNHNSMYWYRQDPGMGLRLIYYSASEGTTDKGEVPNGYNVSRLNKREFSLRLESAAPSQTSVYFCASSEALGGRPYEQYFGPGTRLTVT'),
  2),
 (('GESVGLHLPTLSVQEGDNSIINCAYSNSASDYFIWYKQESGKGPQFIIDIRSNMDKRQGQRVTVLLNKTVKHLSLQIAATQPGDSAVYFCADPRRPWTGQLTFGSGTQLTVLP',
   'NAGVTQTPKFHILKTGQSMTLQCAQDMNHGYLSWYRQDPGMGLRRIHYSVAAGITDKGEVPDGYNVSRSNTEDFPLRLESAAPSQTSVYFCASTGSNTSGANVLTFGAGSRLTVL',
   'NAGVTQTPKFQVLKTGQSMTLQCAQDMNHNSMYWYRQDPGMGLRLIYYSASEGTTDKGEVPNGYNVSRLNKREFSLRLESAAPSQTSVYFCASTDQRGGGNTIYFGEGSWLTVV',
   'QKEVEQNSGPLSVPEGAIASLNCTYSDRGSQSFFWYRQYSGKSPELIMFIYSNGDKEDGRFTAQLNKASQYVSLLIRDSQPSDSATYLCAVDRGSTLGRLYFGRGTQLTVWP'),
  2),
 (('AQSVAQPEDQVNVAEGNPLTVKCTYSVSGNPYLFWYVQYPNRGLQFLLKYITGDNLVKGSYGFEAEFNKSQTSFHLKKPSALVSDSALYFCAVREGTGRRALTFGSGTRLQVQP',
   'DAGVIQSPRHEVTEMGQEVTLRCKPISGHNSLFWYRQTMMRGLELLIYFNNNVPIDDSGMPEDRFSAKMPNASFSTLKIQPSEPRDSAVYFCASSLAPRGRFFGPGTRLTVL',
   'EAQVTQNPRYLITVTGKKLTVTCSQNMNHEYMSWYRQDPGLGLRQIYYSMNVEVTDKGDVPEGYKVSRKEKRNFPLILESPSPNQTSLYFCASSLHGTGVNTGELFFGEGSRLTVL',
   'GESVGLHLPTLSVQEGDNSIINCAYSNSASDYFIWYKQESGKGPQFIIDIRSNMDKRQGQRVTVLLNKTVKHLSLQIAATQPGDSAVYFCAENSTGGGNKLTFGTGTQLKVEL'),
  2),
 (('AQSVTQPDIHITVSEGASLELRCNYSYGATPYLFWYVQSPGQGLQLLLKYFSGDTLVQGIKGFEAEFKRSQSSFNLRKPSVHWSDAAEYFCAVGMYSGGGADGLTFGKGTHLIIQP',
   'AQTVTQSQPEMSVQEAETVTLSCTYDTSENNYYLFWYKQPPSRQMILVIRQEAYKQQNATENRFSVNFQKAAKSFSLKISDSQLGDTAMYFCAFMTPNFGNEKLTFGTGTRLTIIP',
   'DVKVTQSSRYLVKRTGEKVFLECVQDMDHENMFWYRQDPGLGLRLIYFSYDVKMKEKGDIPEGYSVSREKKERFSLILESASTNQTSMYLCATVRDLTDTQYFGPGTRLTVL',
   'GAGVSQSPSNKVTEKGKDVELRCDPISGHTALYWYRQSLGQGLEFLIYFQGNSAPDKSGLPSDRFSAERTGGSVSTLTIQRTQQEDSAVYLCASSSQPARVYTGELFFGEGSRLTVL'),
  2),
 (('AQSVTQPDIHITVSEGASLELRCNYSYGATPYLFWYVQSPGQGLQLLLKYFSGDTLVQGIKGFEAEFKRSQSSFNLRKPSVHWSDAAEYFCAVALSYNTDKLIFGTGTRLQVFP',
   'KAGVTQTPRYLIKTRGQQVTLSCSPISGHRSVSWYQQTPGQGLQFLFEYFSETQRNKGNFPGRFSGRQFSNSRSEMNVSTLELGDSALYLCASSLDPGNEQFFGPGTRLTVL',
   'RKEVEQDPGPFNVPEGATVAFNCTYSNSASQSFFWYRQDCRKEPKLLMSVYSSGNEDGRFTAQLNRASQYISLLIRDSKLSDSATYLCVVNRLRANTGTASKLTFGTGTRLQVTL',
   'SAVISQKPSRDICQRGTSLTIQCQVDSQVTMMFWYRQQPGQSLTLIATANQGSEATYESGFVIDKFPISRPNLTFSTLTVSNMSPEDSSIYLCSPRRGGPNNQPQHFGDGTRLSIL'),
  2),
 (('AAGVIQSPRHLIKEKRETATLKCYPIPRHDTVYWYQQGPGQDPQFLISFYEKMQSDKGSIPDRFSAQQFSDYHSELNMSSLELGDSALYFCASHRRAAGTEAFFGQGTRLTVV',
   'DAGITQSPRHKVTETGTPVTLRCHQTENHRYMYWYRQDPGHGLRLIHYSYGVKDTDKGEVSDGYSVSRSKTEDFLLTLESATSSQTSVYFCAIRRLMRPGKETQYFGPGTRLLVL',
   'DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTFLISISSIKDKNEDGRFTVFLNKSAKHLSLHIVPSQPGDSAVYFCAATTTYSGGGADGLTFGKGTHLIIQP',
   'KQEVTQIPAALSVPEGENLVLNCSFTDSAIYNLQWFRQDPGKGLTSLLLIQSSQREQTSGRLNASLDKSSGRSTLYIAASQPGDSATYLCAVQDNTDKLIFGTGTRLQVFP'),
  2)]

In [326]:
df_final[
    df_final.TRA_1_combined_vdj_aa_sequence == "AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMILVIRQEAYKQQNATENRFSVNFQKAAKSFSLKISDSQLGDAAMYFCAYRSARGGSEKLVFGKGTKLTVNP"
]

,sample_path,sample_peptide,barcode,TRA_1_c_gene,TRA_2_c_gene,TRB_1_c_gene,TRB_2_c_gene,TRA_1_cdr1,TRA_2_cdr1,TRB_1_cdr1,...,TRA_2_v_gene,TRB_1_v_gene,TRB_2_v_gene,TRA_count,TRB_count,has_TRA,has_TRB,multi_TRA,multi_TRB,multi_either_TRA_or_TRB
24707,../cellranger-vdj-outputs/P13,P13,AAGGAGCGTTTGACAC-1,TRAC,TRAC,TRBC2,TRBC1,TSESDYY,STGYPT,MNHEY,...,TRAV40,TRBV27,TRBV29-1,2,2,True,True,True,True,True
24746,../cellranger-vdj-outputs/P13,P13,AAGTCTGCACGGTAGA-1,TRAC,TRAC,TRBC2,TRBC1,TSESDYY,STGYPT,MNHEY,...,TRAV40,TRBV27,TRBV29-1,2,2,True,True,True,True,True
24918,../cellranger-vdj-outputs/P13,P13,ACGATACAGACTGGGT-1,TRAC,TRAC,TRBC2,TRBC1,TSESDYY,STGYPT,MNHEY,...,TRAV40,TRBV27,TRBV29-1,2,2,True,True,True,True,True
24967,../cellranger-vdj-outputs/P13,P13,ACGCCGAAGTGGTAAT-1,TRAC,NaN,TRBC2,TRBC1,TSESDYY,NaN,MNHEY,...,NaN,TRBV27,TRBV29-1,1,2,True,True,False,True,True
24991,../cellranger-vdj-outputs/P13,P13,ACGGCCATCGGTGTCG-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
25036,../cellranger-vdj-outputs/P13,P13,ACTATCTTCTTCATGT-1,TRAC,NaN,TRBC1,TRBC2,TSESDYY,NaN,SQVTM,...,NaN,TRBV29-1,TRBV27,1,2,True,True,False,True,True
25124,../cellranger-vdj-outputs/P13,P13,AGACGTTTCCACGACG-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
25241,../cellranger-vdj-outputs/P13,P13,AGCTCCTGTAGCAAAT-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
25246,../cellranger-vdj-outputs/P13,P13,AGCTCCTTCGGCGCTA-1,TRAC,NaN,TRBC1,TRBC2,TSESDYY,NaN,SQVTM,...,NaN,TRBV29-1,TRBV27,1,2,True,True,False,True,True
25273,../cellranger-vdj-outputs/P13,P13,AGGCCACAGTCGTACT-1,TRAC,TRAC,TRBC2,TRBC1,TSESDYY,STGYPT,MNHEY,...,TRAV40,TRBV27,TRBV29-1,2,2,True,True,True,True,True
25277,../cellranger-vdj-outputs/P13,P13,AGGCCACGTGGGTCAA-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
25401,../cellranger-vdj-outputs/P13,P13,AGTGGGATCATATCGG-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
25550,../cellranger-vdj-outputs/P13,P13,ATCTGCCAGAACAACT-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
25573,../cellranger-vdj-outputs/P13,P13,ATGAGGGGTATGCTTG-1,TRAC,TRAC,TRBC2,TRBC1,TSESDYY,STGYPT,MNHEY,...,TRAV40,TRBV27,TRBV29-1,2,2,True,True,True,True,True
25693,../cellranger-vdj-outputs/P13,P13,CAACCTCGTCGCATAT-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
25710,../cellranger-vdj-outputs/P13,P13,CAACTAGTCTGTCTCG-1,TRAC,NaN,TRBC2,TRBC1,TSESDYY,NaN,MNHEY,...,NaN,TRBV27,TRBV29-1,1,2,True,True,False,True,True
25868,../cellranger-vdj-outputs/P13,P13,CACCACTTCTACTCAT-1,TRAC,NaN,TRBC1,TRBC2,TSESDYY,NaN,SQVTM,...,NaN,TRBV29-1,TRBV27,1,2,True,True,False,True,True
25996,../cellranger-vdj-outputs/P13,P13,CAGTAACAGTGGAGTC-1,TRAC,NaN,TRBC1,TRBC2,TSESDYY,NaN,SQVTM,...,NaN,TRBV29-1,TRBV27,1,2,True,True,False,True,True
26083,../cellranger-vdj-outputs/P13,P13,CATCGGGGTTAAGATG-1,TRAC,TRAC,TRBC2,TRBC1,TSESDYY,STGYPT,MNHEY,...,TRAV40,TRBV27,TRBV29-1,2,2,True,True,True,True,True
26207,../cellranger-vdj-outputs/P13,P13,CCATGTCCATGGTCTA-1,TRAC,NaN,TRBC2,TRBC1,TSESDYY,NaN,MNHEY,...,NaN,TRBV27,TRBV29-1,1,2,True,True,False,True,True
26223,../cellranger-vdj-outputs/P13,P13,CCCAATCCAACACCTA-1,TRAC,NaN,TRBC1,TRBC1,TSESDYY,NaN,SGDLS,...,NaN,TRBV9,TRBV29-1,1,2,True,True,False,True,True
26410,../cellranger-vdj-outputs/P13,P13,CCTTACGGTGAAAGAG-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
26594,../cellranger-vdj-outputs/P13,P13,CGCGGTACAAGGACTG-1,TRAC,TRAC,TRBC2,TRBC1,TSESDYY,STGYPT,MNHEY,...,TRAV40,TRBV27,TRBV29-1,2,2,True,True,True,True,True
26629,../cellranger-vdj-outputs/P13,P13,CGCTGGATCTAAGCCA-1,TRAC,NaN,TRBC2,TRBC1,TSESDYY,NaN,MNHEY,...,NaN,TRBV27,TRBV29-1,1,2,True,True,False,True,True
26838,../cellranger-vdj-outputs/P13,P13,CGTTGGGGTTCACCTC-1,TRAC,TRAC,TRBC2,TRBC1,TSESDYY,STGYPT,MNHEY,...,TRAV40,TRBV27,TRBV29-1,2,2,True,True,True,True,True
26851,../cellranger-vdj-outputs/P13,P13,CTAACTTTCAACACAC-1,TRAC,NaN,NaN,NaN,TSESDYY,NaN,NaN,...,NaN,NaN,NaN,1,0,True,False,False,False,False
26899,../cellranger-vdj-outputs/P13,P13,CTACATTTCGTGACAT-1,TRAC,NaN,TRBC2,TRBC1,TSESDYY,NaN,SGHNT,...,NaN,TRBV5-4,TRBV5-5,1,2,True,True,False,True,True
27165,../cellranger-vdj-outputs/P13,P13,CTGCGGAAGTCACGCC-1,TRAC,NaN,TRBC2,NaN,TSESDYY,NaN,MNHEY,...,NaN,TRBV27,NaN,1,1,True,True,False,False,False
27181,../cellranger-vdj-outputs/P13,P13,CTGCTGTGTCGAACAG-1,TRAC,NaN,TRBC1,TRBC2,TSESDYY,NaN,SQVTM,...,NaN,TRBV29-1,TRBV27,1,2,True,True,False,True,True
27217,../cellranger-vdj-outputs/P13,P13,CTGTTTAGTTACGGAG-1,TRAC,TRAC,TRBC2,TRBC1,TSESDYY,STGYPT,MNHEY,...,TRAV40,TRBV27,TRBV29-1,2,2,True,True,True,True,True
27237,../cellranger-vdj-outputs/P13,P13,CTTACCGAGCTGCCCA-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
27351,../cellranger-vdj-outputs/P13,P13,GAAGCAGAGCACCGCT-1,TRAC,NaN,TRBC1,NaN,TSESDYY,NaN,SQVTM,...,NaN,TRBV29-1,NaN,1,1,True,True,False,False,False
27407,../cellranger-vdj-outputs/P13,P13,GACCAATGTAGCTGCC-1,TRAC,TRAC,TRBC2,TRBC1,TSESDYY,STGYPT,MNHEY,...,TRAV40,TRBV27,TRBV29-1,2,2,True,True,True,True,True
27576,../cellranger-vdj-outputs/P13,P13,GATGAGGCAAACTGTC-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
27624,../cellranger-vdj-outputs/P13,P13,GCAAACTCAGGCTGAA-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
27774,../cellranger-vdj-outputs/P13,P13,GCGCAACAGCCTTGAT-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
27803,../cellranger-vdj-outputs/P13,P13,GCGCCAAAGTGTCCCG-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
27812,../cellranger-vdj-outputs/P13,P13,GCGCGATAGTTCCACA-1,TRAC,TRAC,TRBC2,TRBC1,TSESDYY,STGYPT,MNHEY,...,TRAV40,TRBV27,TRBV29-1,2,2,True,True,True,True,True
28014,../cellranger-vdj-outputs/P13,P13,GGAGCAATCACTGGGC-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
28141,../cellranger-vdj-outputs/P13,P13,GGGCACTTCGCCATAA-1,TRAC,NaN,TRBC1,NaN,TSESDYY,NaN,SGDLS,...,NaN,TRBV9,NaN,1,1,True,True,False,False,False
28171,../cellranger-vdj-outputs/P13,P13,GGGTTGCGTACGACCC-1,TRAC,TRAC,TRBC2,TRBC1,TSESDYY,STGYPT,MNHEY,...,TRAV40,TRBV27,TRBV29-1,2,2,True,True,True,True,True
28234,../cellranger-vdj-outputs/P13,P13,GTAACTGGTCATGCCG-1,TRAC,NaN,TRBC1,TRBC2,TSESDYY,NaN,SQVTM,...,NaN,TRBV29-1,TRBV27,1,2,True,True,False,True,True
28300,../cellranger-vdj-outputs/P13,P13,GTATTCTCACGAGGTA-1,TRAC,NaN,TRBC1,TRBC2,TSESDYY,NaN,SQVTM,...,NaN,TRBV29-1,TRBV27,1,2,True,True,False,True,True
28390,../cellranger-vdj-outputs/P13,P13,GTCTCGTAGTTCGATC-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
28493,../cellranger-vdj-outputs/P13,P13,GTTAAGCCATGCCACG-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
28559,../cellranger-vdj-outputs/P13,P13,TAAACCGCATACTCTT-1,TRAC,NaN,TRBC2,TRBC1,TSESDYY,NaN,MNHEY,...,NaN,TRBV27,TRBV29-1,1,2,True,True,False,True,True
28649,../cellranger-vdj-outputs/P13,P13,TACGGATAGCAACGGT-1,TRAC,NaN,TRBC1,NaN,TSESDYY,NaN,SQVTM,...,NaN,TRBV29-1,NaN,1,1,True,True,False,False,False
28724,../cellranger-vdj-outputs/P13,P13,TACTTGTCAAACCCAT-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
28848,../cellranger-vdj-outputs/P13,P13,TCAATCTCAATCGAAA-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
29066,../cellranger-vdj-outputs/P13,P13,TCGTAGATCGGTCTAA-1,TRAC,NaN,TRBC1,TRBC2,TSESDYY,NaN,SQVTM,...,NaN,TRBV29-1,TRBV27,1,2,True,True,False,True,True
29113,../cellranger-vdj-outputs/P13,P13,TCTGGAAAGAATGTTG-1,TRAC,NaN,TRBC2,TRBC1,TSESDYY,NaN,MNHEY,...,NaN,TRBV27,TRBV29-1,1,2,True,True,False,True,True
29222,../cellranger-vdj-outputs/P13,P13,TGAGCATCAAAGGCGT-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
29323,../cellranger-vdj-outputs/P13,P13,TGCGGGTAGGCGATAC-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
29377,../cellranger-vdj-outputs/P13,P13,TGGACGCTCGCTTAGA-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
29434,../cellranger-vdj-outputs/P13,P13,TGGTTAGAGTACGCGA-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
29566,../cellranger-vdj-outputs/P13,P13,TTCGGTCAGAGTAATC-1,TRAC,TRAC,TRBC2,TRBC1,TSESDYY,STGYPT,MNHEY,...,TRAV40,TRBV27,TRBV29-1,2,2,True,True,True,True,True
29582,../cellranger-vdj-outputs/P13,P13,TTCTACAGTCAAGCGA-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
29670,../cellranger-vdj-outputs/P13,P13,TTGGAACGTACAGTTC-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True

In [327]:
df_final[
    df_final.TRB_1_combined_vdj_aa_sequence == "SAVISQKPSRDICQRGTSLTIQCQVDSQVTMMFWYRQQPGQSLTLIATANQGSEATYESGFVIDKFPISRPNLTFSTLTVSNMSPEDSSIYLCSVDYPRQGLSPLHFGNGTRLTVT"
]

,sample_path,sample_peptide,barcode,TRA_1_c_gene,TRA_2_c_gene,TRB_1_c_gene,TRB_2_c_gene,TRA_1_cdr1,TRA_2_cdr1,TRB_1_cdr1,...,TRA_2_v_gene,TRB_1_v_gene,TRB_2_v_gene,TRA_count,TRB_count,has_TRA,has_TRB,multi_TRA,multi_TRB,multi_either_TRA_or_TRB
24713,../cellranger-vdj-outputs/P13,P13,AAGGCAGCACCGGAAA-1,TRAC,TRAC,TRBC1,TRBC2,STGYPT,TSESDYY,SQVTM,...,TRAV38-2/DV8,TRBV29-1,TRBV27,2,2,True,True,True,True,True
24991,../cellranger-vdj-outputs/P13,P13,ACGGCCATCGGTGTCG-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
25036,../cellranger-vdj-outputs/P13,P13,ACTATCTTCTTCATGT-1,TRAC,NaN,TRBC1,TRBC2,TSESDYY,NaN,SQVTM,...,NaN,TRBV29-1,TRBV27,1,2,True,True,False,True,True
25124,../cellranger-vdj-outputs/P13,P13,AGACGTTTCCACGACG-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
25241,../cellranger-vdj-outputs/P13,P13,AGCTCCTGTAGCAAAT-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
25246,../cellranger-vdj-outputs/P13,P13,AGCTCCTTCGGCGCTA-1,TRAC,NaN,TRBC1,TRBC2,TSESDYY,NaN,SQVTM,...,NaN,TRBV29-1,TRBV27,1,2,True,True,False,True,True
25277,../cellranger-vdj-outputs/P13,P13,AGGCCACGTGGGTCAA-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
25401,../cellranger-vdj-outputs/P13,P13,AGTGGGATCATATCGG-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
25550,../cellranger-vdj-outputs/P13,P13,ATCTGCCAGAACAACT-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
25693,../cellranger-vdj-outputs/P13,P13,CAACCTCGTCGCATAT-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
25868,../cellranger-vdj-outputs/P13,P13,CACCACTTCTACTCAT-1,TRAC,NaN,TRBC1,TRBC2,TSESDYY,NaN,SQVTM,...,NaN,TRBV29-1,TRBV27,1,2,True,True,False,True,True
25996,../cellranger-vdj-outputs/P13,P13,CAGTAACAGTGGAGTC-1,TRAC,NaN,TRBC1,TRBC2,TSESDYY,NaN,SQVTM,...,NaN,TRBV29-1,TRBV27,1,2,True,True,False,True,True
26181,../cellranger-vdj-outputs/P13,P13,CCAGCGAAGCCATCGC-1,TRAC,TRAC,TRBC1,TRBC2,STGYPT,TSESDYY,SQVTM,...,TRAV38-2/DV8,TRBV29-1,TRBV27,2,2,True,True,True,True,True
26410,../cellranger-vdj-outputs/P13,P13,CCTTACGGTGAAAGAG-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
27181,../cellranger-vdj-outputs/P13,P13,CTGCTGTGTCGAACAG-1,TRAC,NaN,TRBC1,TRBC2,TSESDYY,NaN,SQVTM,...,NaN,TRBV29-1,TRBV27,1,2,True,True,False,True,True
27237,../cellranger-vdj-outputs/P13,P13,CTTACCGAGCTGCCCA-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
27351,../cellranger-vdj-outputs/P13,P13,GAAGCAGAGCACCGCT-1,TRAC,NaN,TRBC1,NaN,TSESDYY,NaN,SQVTM,...,NaN,TRBV29-1,NaN,1,1,True,True,False,False,False
27576,../cellranger-vdj-outputs/P13,P13,GATGAGGCAAACTGTC-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
27624,../cellranger-vdj-outputs/P13,P13,GCAAACTCAGGCTGAA-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
27774,../cellranger-vdj-outputs/P13,P13,GCGCAACAGCCTTGAT-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
27803,../cellranger-vdj-outputs/P13,P13,GCGCCAAAGTGTCCCG-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
27916,../cellranger-vdj-outputs/P13,P13,GCTTGAACATTGCGGC-1,TRAC,TRAC,TRBC1,TRBC2,STGYPT,TSESDYY,SQVTM,...,TRAV38-2/DV8,TRBV29-1,TRBV27,2,2,True,True,True,True,True
28014,../cellranger-vdj-outputs/P13,P13,GGAGCAATCACTGGGC-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
28234,../cellranger-vdj-outputs/P13,P13,GTAACTGGTCATGCCG-1,TRAC,NaN,TRBC1,TRBC2,TSESDYY,NaN,SQVTM,...,NaN,TRBV29-1,TRBV27,1,2,True,True,False,True,True
28300,../cellranger-vdj-outputs/P13,P13,GTATTCTCACGAGGTA-1,TRAC,NaN,TRBC1,TRBC2,TSESDYY,NaN,SQVTM,...,NaN,TRBV29-1,TRBV27,1,2,True,True,False,True,True
28390,../cellranger-vdj-outputs/P13,P13,GTCTCGTAGTTCGATC-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
28493,../cellranger-vdj-outputs/P13,P13,GTTAAGCCATGCCACG-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
28649,../cellranger-vdj-outputs/P13,P13,TACGGATAGCAACGGT-1,TRAC,NaN,TRBC1,NaN,TSESDYY,NaN,SQVTM,...,NaN,TRBV29-1,NaN,1,1,True,True,False,False,False
28724,../cellranger-vdj-outputs/P13,P13,TACTTGTCAAACCCAT-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
28763,../cellranger-vdj-outputs/P13,P13,TAGGCATCACCCAGTG-1,TRAC,TRAC,TRBC1,TRBC2,STGYPT,TSESDYY,SQVTM,...,TRAV38-2/DV8,TRBV29-1,TRBV27,2,2,True,True,True,True,True
28848,../cellranger-vdj-outputs/P13,P13,TCAATCTCAATCGAAA-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
29066,../cellranger-vdj-outputs/P13,P13,TCGTAGATCGGTCTAA-1,TRAC,NaN,TRBC1,TRBC2,TSESDYY,NaN,SQVTM,...,NaN,TRBV29-1,TRBV27,1,2,True,True,False,True,True
29222,../cellranger-vdj-outputs/P13,P13,TGAGCATCAAAGGCGT-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
29323,../cellranger-vdj-outputs/P13,P13,TGCGGGTAGGCGATAC-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
29377,../cellranger-vdj-outputs/P13,P13,TGGACGCTCGCTTAGA-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
29434,../cellranger-vdj-outputs/P13,P13,TGGTTAGAGTACGCGA-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
29582,../cellranger-vdj-outputs/P13,P13,TTCTACAGTCAAGCGA-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True
29670,../cellranger-vdj-outputs/P13,P13,TTGGAACGTACAGTTC-1,TRAC,TRAC,TRBC1,TRBC2,TSESDYY,STGYPT,SQVTM,...,TRAV40,TRBV29-1,TRBV27,2,2,True,True,True,True,True

In [328]:
df_selected_full_seqs

,CDR3_alpha,CDR3_beta,Peptide,VDJ_alpha_beta_aa,VDJ_alpha_aa,VDJ_beta_aa,Cell_Count,Cell_Barcodes,Alpha_Contig_IDs,Beta_Contig_IDs,...,CDR2_alpha,alpha_v_gene,alpha_j_gene,alpha_c_gene,CDR1_beta,CDR2_beta,beta_v_gene,beta_d_gene,beta_j_gene,beta_c_gene
0,CAAAYIDNLFF,CASSPDRVNTGELFF,P5,QKEVEQNSGPLSVPEGAIASLNCTYSDRGSQSFFWYRQYSGKSPEL...,QKEVEQNSGPLSVPEGAIASLNCTYSDRGSQSFFWYRQYSGKSPEL...,EAGVVQSPRYKIIEKKQPVAFWCNPISGHNTLYWYLQNLGQGPELL...,27,"[GTCACGGCAAGCCGTC-1, GTCAAGTTCCGCGTTT-1, GTCAA...","[GTCACGGCAAGCCGTC-1_contig_1, GTCAAGTTCCGCGTTT...","[GTCACGGCAAGCCGTC-1_contig_2, GTCAAGTTCCGCGTTT...",...,IYSNGD,TRAV12-2,TRAJ36,TRAC,SGHNT,YENEEA,TRBV11-3,None,TRBJ2-2,TRBC2
1,CAADNAGNMLTF,CASSSEYLGEQFF,P15,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,ETGVTQSPTHLIKTRGQQVTLRCSSQSGHNTVSWYQQALGQGPQFI...,3,"[TAAGTGCCATGTTCCC-1, AACTTTCAGTTGAGTA-1, CAACC...","[TAAGTGCCATGTTCCC-1_contig_1, AACTTTCAGTTGAGTA...","[TAAGTGCCATGTTCCC-1_contig_2, AACTTTCAGTTGAGTA...",...,ISSIKDK,TRAV29/DV5,TRAJ39,TRAC,SGHNT,YYREEE,TRBV5-4,None,TRBJ2-1,TRBC2
2,CAAIKNQFYF,CASSRAGGQETQYF,P11,GENVEQHPSTLSVQEGDSAVIKCTYSDSASNYFPWYKQELGKGPQL...,GENVEQHPSTLSVQEGDSAVIKCTYSDSASNYFPWYKQELGKGPQL...,GAGVSQTPSNKVTEKGKYVELRCDPISGHTALYWYRQSLGQGPEFL...,26,"[GTCTTCGCATCTCGCT-1, GTCCTCACAGGCGATA-1, TTGCG...","[GTCTTCGCATCTCGCT-1_contig_2, GTCCTCACAGGCGATA...","[GTCTTCGCATCTCGCT-1_contig_1, GTCCTCACAGGCGATA...",...,IRSNVGE,TRAV13-1,TRAJ49,TRAC,SGHTA,FQGTGA,TRBV7-3,None,TRBJ2-5,TRBC2
3,CAASARETSGSRLTF,CASSPIGAYEQYF,P15,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,NAGVMQNPRHLVRRRGQEARLRCSPMKGHSHVYWYRQLPEEGLKFM...,44,"[GTACTTTCAGGACCCT-1, GTAACGTTCCTGCAGG-1, GGTGT...","[GTACTTTCAGGACCCT-1_contig_2, GTAACGTTCCTGCAGG...","[GTACTTTCAGGACCCT-1_contig_1, GTAACGTTCCTGCAGG...",...,ISSIKDK,TRAV29/DV5,TRAJ58,TRAC,KGHSH,LQKENI,TRBV18,None,TRBJ2-7,TRBC2
4,CAASAWEGQNFVF,CASSLLDQPQHF,P5,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,EAQVTQNPRYLITVTGKKLTVTCSQNMNHEYMSWYRQDPGLGLRQI...,12,"[GTGCGGTAGCCACGTC-1, GCGCCAAAGTGTTGAA-1, GTTCA...","[GTGCGGTAGCCACGTC-1_contig_2, GCGCCAAAGTGTTGAA...","[GTGCGGTAGCCACGTC-1_contig_1, GCGCCAAAGTGTTGAA...",...,ISSIKDK,TRAV29/DV5,TRAJ26,TRAC,MNHEY,SMNVEV,TRBV27,None,TRBJ1-5,TRBC1
5,CAASDTGGFKTIF,CASSSRARGQETQYF,P15,GQQVMQIPQYQHVQEGEDFTTYCNSSTTLSNIQWYKQRPGGHPVFL...,GQQVMQIPQYQHVQEGEDFTTYCNSSTTLSNIQWYKQRPGGHPVFL...,GAGVSQSPSNKVTEKGKDVELRCDPISGHTALYWYRQSLGQGLEFL...,1,[AGTGTCAAGCTCAACT-1],[AGTGTCAAGCTCAACT-1_contig_2],[AGTGTCAAGCTCAACT-1_contig_1],...,LVKSGEV,TRAV25,TRAJ9,TRAC,SGHTA,FQGNSA,TRBV7-2,None,TRBJ2-5,TRBC2
6,CAATPGSYNTDKLIF,CAISGGTGKGTQYF,P15,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,DAGITQSPRHKVTETGTPVTLRCHQTENHRYMYWYRQDPGHGLRLI...,7,"[GGACATTCATTCTCAT-1, GCTCCTAAGTCCGGTC-1, TGTGT...","[GGACATTCATTCTCAT-1_contig_1, GCTCCTAAGTCCGGTC...","[GGACATTCATTCTCAT-1_contig_2, GCTCCTAAGTCCGGTC...",...,ISSIKDK,TRAV29/DV5,TRAJ34,TRAC,ENHRY,SYGVKD,TRBV10-3,None,TRBJ2-5,TRBC2
7,CAETGFSDGQKLLF,CASSLDAEEGHYEQYF,P2,GEDVEQSLFLSVREGDSSVINCTYTDSSSTYLYWYKQEPGAGLQLL...,GEDVEQSLFLSVREGDSSVINCTYTDSSSTYLYWYKQEPGAGLQLL...,KAGVTQTPRYLIKTRGQQVTLSCSPISGHRSVSWYQQTPGQGLQFL...,7,"[GTCGGGTTCAACACTG-1, TATTACCTCGGAGGTA-1, CTGTT...","[GTCGGGTTCAACACTG-1_contig_2, TATTACCTCGGAGGTA...","[GTCGGGTTCAACACTG-1_contig_1, TATTACCTCGGAGGTA...",...,IFSNMDM,TRAV5,TRAJ16,TRAC,SGHRS,YFSETQ,TRBV5-1,None,TRBJ2-7,TRBC2
8,CAGHSAGGTSYGKLTF,CASSLYAGAWSYTF,P11,GQQLNQSPQSMFIQEGEDVSMNCTSSSIFNTWLWYKQDPGEGPVLL...,GQQLNQSPQSMFIQEGEDVSMNCTSSSIFNTWLWYKQDPGEGPVLL...,EAQVTQNPRYLITVTGKKLTVTCSQNMNHEYMSWYRQDPGLGLRQI...,23,"[TACTCATAGATCGGGT-1, GTCACAATCGATAGAA-1, GACCA...","[TACTCATAGATCGGGT-1_contig_1, GTCACAATCGATAGAA...","[TACTCATAGATCGGGT-1_contig_2, GTCACAATCGATAGAA...",...,LYKAGEL,TRAV35,TRAJ52,TRAC,MNHEY,SMNVEV,TRBV27,None,TRBJ1-2,TRBC1
9,CAGQPGSSNYKLTF,CASSVQGATEAFF,P12,GQQLNQSPQSMFIQEGEDVSMNCTSSSIFNTWLWYKQDPGEGPVLL...,GQQLNQSPQSMFIQEGEDVSMNCTSSSIFNTWLWYKQDPGEGPVLL...,EPEVTQTPSHQVTQMGQEVILRCVPISNHLYFYWYRQILGQKVEFL...,43,"[GTCTTCGGTTAGTGGG-1, GTCGTAAAGTGGAGAA-1, GTACT...","[GTCTTCGGTTAGTGGG-1_contig_1, GTCGTAAAGTGGAGAA...","[GTCTTCGGTTAGTGGG-1_contig_2, GTCGTAAAGTGGAGAA...",...,LYKAGEL,TRAV35,TRAJ53,TRAC,SNHLY,FYNNEI,TRBV2,TRBD1,TRBJ1-1,TRBC1
10,CALDIDSNYQLIW,CAISERVNEQFF,P15,SQKIEQNSEALNIQEGKTATLTCNYTNYSPAYLQWYRQDPGRGPVF...,SQKIEQNSEALNIQEGKTATLTCNYTNYSPAYLQWYRQDPGRGPVF...,DAGITQSPRHKVTETGTPVTLRCHQTENHRYMYWYRQDPGHGLRLI...,11,"[GGCTCGATCTTGTCAT-1, GACTGCGCATTGGGCC-1, GAATG...","[GGCTCGATCTTGTCAT-1_contig_2, GACTGCGCATTGGGCC...","[GGCTCGATCTTGTCAT-1_contig_1, GACTGCGCATTGGGCC...",...,IRENEKE,TRAV6,TRAJ33,TRAC,ENHRY,SYGVKD,TRBV10-3,None,TRBJ2-1,TRBC2
11,CAMREGKGAGNMLTF,CASSRANSNQPQHF,P1,AQKITQTQPGMFVQEKEAVTLDCTYDTSDQSYGLFWYKQPSSGEMI...,AQKITQTQPGMFVQEKEAVTLDCTYDTSDQSYGLFWYKQPSSGEMI...,DTAVSQTPKYLVTQMGNDKSIKCEQNLGHDTMYWYKQDSKKFLKIM...,38,"[AACTCCCGTCGGGTCT-1, GGCGACTGTAGCGATG-1, GGCTG...","[AACTCCCGTCGGGTCT-1_contig_2, GGCGACTGTAGCGATG...","[AACTCCCGTCGGGTCT-1_contig_1, GGCGACTGTAGCGATG...",...,QGSYDEQN,TRAV14/DV4,TRAJ39,TRAC,LGHDT,YNNKEL,TRBV3-1,None,TRBJ1-5,TRBC1
12,CASERGSARQLTF,CASSFGTEDTQYF,P15,QKEVEQNSGPLSVPEGAIASLNCTYSDRGSQSFFWYRQYSGKSPEL...,QKEVEQNSGPLSVPEGAIASLNCTYSDRGSQSFFWYRQYSGKSPEL...,EAGVAQSPRYKIIEKRQSVAFWCNPISGHATLYWYQQILGQGPKLL...,6,"[GCGCCAAAGACTGGGT-1, GCAGCCATCCTCTAGC-1, CTTAG...","[GCGCCAAAGACTGGGT-1_contig_1, GCAGCCATCCTCTAGC...","[GCGCCAAAGACTGGGT-1_contig_2, GCAGCCATCCTCTAGC...",...,IYSNGD,TRAV12-2,TRAJ22,TRAC,SGHAT,FQNNGV,TRBV11-2,None,TRBJ2-3,TRBC2
13,CATDSGGYQKVTF,CASSEGGHTGELFF,P7,SQQGEEDPQALSIQEGENATMNCSYKTSINNLQWYRQNSGRGLVHL...,SQQGEEDPQALSIQEGENATMNCSYKTSINNLQWYRQNSGRGLVHL...,NAGVMQNPRHLVRRRGQEARLRCSPMKGHSHVYWYRQLPEEGLKFM...,41,"[GTAACTGGTGTGGCTC-1, GCTCTGTTCTTTACAC-1, GACAC...","[GTAACTGGTGTGGCTC-1_contig_2, GCTCTGTTCTTTACAC...","[GTAACTGGTGTGGCTC-1_contig_1, GCTCTGTTCTTTACAC...",...,IRSNERE,TRAV17,TRAJ13,TRAC,KGHSH,LQKENI,TRBV18,TRBD1,TRBJ2-2,TRBC2
14,CATVSVGGFGNVLHC,CASSPDRVNTGELFF,P5,GENVEQHPSTLSVQEGDSAVIKCTYSDSASNYFPWYKQELGKGPQL...,GENVEQHPSTLSVQEGDSAVIKCTYSDSASNYFPWYKQELGKGPQL...,EAGVVQSPRYKIIEKKQPVAFWCNPISGHNTLYWYLQNLGQGPELL...,21,"[GTACTCCTCCAAGTAC-1, GGTGTTATCTTGTACT-1, GCTTG...","[GTACTCCTCCAAGTAC-1_contig_3, GGTGTTATCTTGTACT...","[GTACTCCTCCAAGTAC-1_contig_2, GGTGTTATCTTGTACT...",...,IRSNVGE,TRAV13-1,TRAJ35,TRAC,SGHNT,YENEEA,TRBV11-3,None,TRBJ2-2,TRBC2
15,CAVGASNAGGTSYGKLTF,CASSLARYDEQYF,P15,AQSVTQPDIHITVSEGASLELRCNYSYGATPYLFWYVQSPGQGLQL...,AQSVTQPDIHITVSEGASLELRCNYSYGATPYLFWYVQSPGQGLQL...,DTGVSQNPRHKITKRGQNVTFRCDPISEHNRLYWYRQTLGQGPEFL...,2,"[TACCTTACACTGTCGG-1, ATCACGATCATCTGTT-1]","[TACCTTACACTGTCGG-1_contig_2, ATCACGATCATCTGTT...","[TACCTTACACTGTCGG-1_contig_1, ATCACGATCATCTGTT...",...,YFSGDTLV,TRAV8-3,TRAJ52,TRAC,SEHNR,FQNEAQ,TRBV7-9,None,TRBJ2-7,TRBC2
16,CAVLYNTDKLIF,CASSSTRGYGANVLTF,P15,KQEVTQIPAALSVPEGENLVLNCSFTDSAIYNLQWFRQDPGKGLTS...,KQEVTQIPAALSVPEGENLVLNCSFTDSAIYNLQWFRQDPGKGLTS...,GAGVSQSPSNKVTEKGKDVELRCDPISGHTALYWYRQSLGQGLEFL...,3,"[GCTGGGTCATTGTGCA-1, GCTGCGATCATCGCTC-1, CCGGG...","[GCTGGGTCATTGTGCA-1_contig_2, GCTGCGATCATCGCTC...","[GCTGGGTCATTGTGCA-1_contig_1, GCTGCGATCATCGCTC...",...,IQSSQRE,TRAV21,TRAJ34,TRAC,SGHTA,FQGNSA,TRBV7-2,TRBD1,TRBJ2-6,TRBC2
17,CAVRDGKAAGNKLTF,CASSLVTGAFDEQFF,P13,AQSVAQPEDQVNVAEGNPLTVKCTYSVSGNPYLFWYVQYPNRGLQF...,AQSVAQPEDQVNVAEGNPLTVKCTYSVSGNPYLFWYVQYPNRGLQF...,DTGVSQNPRHKITKRGQNVTFRCDPISEHNRLYWYRQTLGQGPEFL...,66,"[GGATTACTCATTTGGG-1, GGACAAGTCATCGATG-1, GGACA...","[GGATTACTCATTTGGG-1_contig_1, GGACAAGTCATCGATG...","[GGATTACTCATTTGGG-1_contig_2, GGACAAGTCATCGATG...",...,YITGDNLV,TRAV3,TRAJ17,TRAC,SEHNR,FQNEAQ,TRBV7-9,TRBD1,TRBJ2-1,TRBC2
18,CAVSVRRGGGSQGNLIF,CASSYSRGYEQYF,P15,AQSVTQLDSQVPVFEEAPVELRCNYSSSVSVYLFWYVQYPNQGLQL...,AQSVTQLDSQVPVFEEAPVELRCNYSSSVSVYLFWYVQYPNQGLQL...,NAGVTQTPKFQVLKTGQSMTLQCAQDMNHEYMSWYRQDPGMGLRLI...,2,"[ATCTGCCTCAGTGCAT-1, CTCACACAGGGAACGG-1]","[ATCTGCCTCAGTGCAT-1_contig_1, CTCACACAGGGAACGG...","[ATCTGCCTCAGTGCAT-1_contig_2, CTCACACAGGGAACGG...",...,YLSGSTLV,TRAV8-6,TRAJ42,TRAC,MNHEY,SVGAGI,TRBV6-5,None,TRBJ2-7,TRBC2
19,CAVVRGNDYKLSF,CASSPRQDSYEQYF,P3,EDQVTQSPEALRLQEGESSSLNCSYTVSGLRGLFWYRQDPGKGPEF...,EDQVTQSPEALRLQEGESSSLNCSYTVSGLRGLFWYRQDPGKGPEF...,NAGVMQNPRHLVRRRGQEARLRCSPMKGHSHVYWYRQLPEEGLKFM...,1,[GGACAAGGTGCACGAA-1],[GGACAAGGTGCACGAA-1_contig_2],[GGACAAGGTGCACGAA-1_contig_1],...,LYSAGEE,TRAV20,TRAJ20,TRAC,KGHSH,LQKENI,TRBV18,None,TRBJ2-7,TRBC2
20,CAVYNNARLMF,CASLGRGGLAKNIQYF,P12,GQQVMQIPQYQHVQEGEDFTTYCNSSTTLSNIQWYKQRPGGHPVFL...,GQQVMQIPQYQHVQEGEDFTTYCNSSTTLSNIQWYKQRPGGHPVFL...,EPEVTQTPSHQVTQMGQEVILRCVPISNHLYFYWYRQILGQKVEFL...,12,"[GGGAATGGTAGCTAAA-1, CTTACCGAGCTCAACT-1, TCTGA...","[GGGAATGGTAGCTAAA-1_contig_2, CTTACCGAGCTCAACT...","[GGGAATGGTAGCTAAA-1_contig_1, CTTACCGAGCTCAACT...",...,LVKSGEV,TRAV25,TRAJ31,TRAC,SNHLY,FYNNEI,TRBV2,None,TRBJ2-4,TRBC2
21,CAYRDSNYQLIW,CASSPTGDSGNTIYF,P10,AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMI...,AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMI...,NAGVMQNPRHLVRRRGQEARLRCSPMKGHSHVYWYRQLPEEGLKFM...,41,"[GGTGCGTTCGGAAATA-1, GGCTGGTGTTCGCTAA-1, GCTTC...","[GGTGCGTTCGGAAATA-1_contig_2, GGCTGGTGTTCGCTAA...","[GGTGCGTTCGGAAATA-1_contig_1, GGCTGGTGTTCGCTAA...",...,QEAYKQQN,TRAV38-2/DV8,TRAJ33,TRAC,KGHSH,LQKENI,TRBV18,None,TRBJ1-3,TRBC1
22,CAYRSAKGNDMRF,CASSFYFGQGYEQYF,P15,AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMI...,AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMI...,GAGVSQSPSNKVTEKGKDVELRCDPISGHTALYWYRQSLGQGLEFL...,3,"[ACACCGGGTTCGGCAC-1, AACCGCGAGTAACCCT-1, CGAGA...","[ACACCGGGTTCGGCAC-1_contig_2, AACCGCGAGTAACCCT...","[ACACCGGGTTCGGCAC-1_contig_1, AACCGCGAGTAACCCT...",...,QEAYKQQN,TRAV38-2/DV8,TRAJ43,TRAC,SGHTA,FQGNSA,TRBV7-2,None,TRBJ2-7,TRBC2
23,CAYWVGGGGADGLTF,CASSLTPGGVKETQYF,P12,AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMI...,AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMI...,GAGVSQSPRYKVAKRGQDVALRCDPISGHVSLFWYQQALGQGPEFL...,33,"[GTGCATATCCGATATG-1, GACGTTACAGGTCGTC-1, GACGC...","[GTGCATATCCGATATG-1_contig_1, GACGTTACAGGTCGTC...","[GTGCATATCCGATATG-1_contig_2, GACGTTACAGGTCGTC...",...,QEAYKQQN,TRAV38-2/DV8,TRAJ45,TRAC,SGHVS,FQNEAQ,TRBV7-8,None,TRBJ2-5,TRBC2
24,CGADTNFGNEKLTF,CASSPGLATQYF,P7,SQELEQSPQSLIVQEGKNLTINCTSSKTLYGLYWYKQKYGEGLIFL...,SQELEQSPQSLIVQEGKNLTINCTSSKTLYGLYWYKQKYGEGLIFL...,EAGVAQSPRYKIIEKRQSVAFWCNPISGHATLYWYQQILGQGPKLL...,26,"[GGGTTGCTCCGTCATC-1, GGAATAACATGTAGTC-1, GCATG...","[GGGTTGCTCCGTCATC-1_contig_1, GGAATAACATGTAGTC...","[GGGTTGCTCCGTCATC-1_contig_2, GGAATAACATGTAGTC...",...,LQKGGEE,TRAV34,TRAJ48,TRAC,SGHAT,FQNNGV,TRBV11-2,None,TRBJ2-3,TRBC2
25,CGTETGNNRLAF,CASSKKGTGTDTQYF,P15,QQPVQSPQAVILREGEDAVINCSSSKALYSVHWYRQKHGEAPVFLM...,QQPVQSPQAVILREGEDAVINCSSSKALYSVHWYRQKHGEAPVFLM...,GAGVSQSPRYKVAKRGQDVALRCDPISGHVSLFWYQQALGQGPEFL...,1,[CGATGGCCATACCATG-1],[CGATGGCCATACCATG-1_contig_3],[CGATGGCCATACCATG-1_contig_1],...,LLKGGEQ,TRAV30,TRAJ7,TRAC,SGHVS,FQNEAQ,TRBV7-8,None,TRBJ2-3,TRBC2

In [329]:

def num_sort_key(s):
    s_original = s
    if "/" in s:
        s = s.split("/")[-1]
    if len(s) > 1 and s[0] == "P":
        s = s[1:]
    if s.isdigit():
        return int(s)
    else:
        return s_original

peptide_num_to_clonotypes = {}
for peptide_num_path in sorted(glob("../cellranger-vdj-outputs/*"), key=num_sort_key):
    peptide_num = peptide_num_path.split("/")[-1]
    df_peptide_clonotypes = pd.read_csv("../cellranger-vdj-outputs/%s/clonotypes.csv" % peptide_num)
    df_peptide_clonotypes["sample_peptide"] = peptide_num
    df_peptide_clonotypes["sample_path"] = peptide_num_path
    peptide_num_to_clonotypes[peptide_num] = df_peptide_clonotypes
    print(peptide_num, len(df_peptide_clonotypes))

df_clonotypes = pd.concat(list(peptide_num_to_clonotypes.values()))
df_clonotypes

P1 3612
P2 2962
P3 4022
P4 2359
P5 5718
P6 4398
P7 5957
P8 2472
P9 3723
P10 3118
P11 2782
P12 8919
P13 4046
P14 6900
P15 6514

,clonotype_id,frequency,proportion,cdr3s_aa,cdr3s_nt,inkt_evidence,mait_evidence,sample_peptide,sample_path
0,clonotype1,83,0.017667,TRB:CASSIPGTGSVTGELFF;TRA:CAATETSYDKVIF,TRB:TGTGCCAGCAGCATCCCCGGGACAGGGTCCGTCACCGGGGAG...,NaN,NaN,P1,../cellranger-vdj-outputs/P1
1,clonotype2,60,0.012771,TRB:CASRGGGSTDTQYF;TRA:CAALETSYDKVIF,TRB:TGTGCCAGCAGAGGGGGTGGGAGCACAGATACGCAGTATTTT...,NaN,NaN,P1,../cellranger-vdj-outputs/P1
2,clonotype3,38,0.008089,TRB:CSVDQTSEGSNTEAFF;TRA:CAPVAGGSYIPTF,TRB:TGCAGCGTTGACCAAACCTCGGAAGGGTCAAACACTGAAGCT...,NaN,NaN,P1,../cellranger-vdj-outputs/P1
3,clonotype4,36,0.007663,TRB:CASSRANSNQPQHF;TRA:CAMREGKGAGNMLTF,TRB:TGTGCCAGCAGCCGGGCAAATAGCAATCAGCCCCAGCATTTT...,NaN,NaN,P1,../cellranger-vdj-outputs/P1
4,clonotype5,22,0.004683,TRB:CASSPGLAGPEQYF;TRA:CAVSHTGNQFYF,TRB:TGCGCCAGCAGCCCGGGACTAGCGGGGCCCGAGCAGTACTTC...,NaN,NaN,P1,../cellranger-vdj-outputs/P1
...,...,...,...,...,...,...,...,...,...
6509,clonotype6510,1,0.000085,TRA:CAPEGTGGFKTIF,TRA:TGTGCTCCTGAGGGTACTGGAGGCTTCAAAACTATCTTT,NaN,NaN,P15,../cellranger-vdj-outputs/P15
6510,clonotype6511,1,0.000085,TRA:CALVGGSNYKLTF,TRA:TGTGCTCTAGTTGGAGGTAGCAACTATAAACTGACATTT,NaN,NaN,P15,../cellranger-vdj-outputs/P15
6511,clonotype6512,1,0.000085,TRA:CALVAGGGNKLTF,TRA:TGTGCTCTAGTCGCGGGAGGAGGAAACAAACTCACCTTT,NaN,NaN,P15,../cellranger-vdj-outputs/P15
6512,clonotype6513,1,0.000085,TRA:CALVAGGGNKLTF,TRA:TGTGCTCTAGTCGCGGGAGGAGGAAACAAACTCACCTTT,NaN,NaN,P15,../cellranger-vdj-outputs/P15
6513,clonotype6514,1,0.000085,TRA:CALGTSGNTGKLIF,TRA:TGTGCTCTAGGAACCTCTGGCAACACAGGCAAACTAATCTTT,NaN,NaN,P15,../cellranger-vdj-outputs/P15

In [330]:
df_clonotypes.inkt_evidence.isnull().mean()

0.9941186927794732

In [331]:
df_clonotypes.mait_evidence.isnull().mean()

0.7812509258984919

In [332]:
df_clonotypes[~df_clonotypes.mait_evidence.isnull()]

,clonotype_id,frequency,proportion,cdr3s_aa,cdr3s_nt,inkt_evidence,mait_evidence,sample_peptide,sample_path
11,clonotype12,16,0.003406,TRB:CSARDPNPSSGGDTGELFF;TRA:CASMDSNYQLIW,TRB:TGCAGTGCTAGAGACCCCAACCCCTCTAGCGGGGGGGACACC...,NaN,TRA:gene+junction;TRB:gene,P1,../cellranger-vdj-outputs/P1
23,clonotype24,9,0.001916,TRB:CASSSPDSSYNEQFF;TRA:CAEMETSYDKVIF,TRB:TGTGCCAGCAGTTCCCCGGATAGCTCCTACAATGAGCAGTTC...,NaN,TRB:gene,P1,../cellranger-vdj-outputs/P1
26,clonotype27,8,0.001703,TRB:CASSGRDHYNEQFF;TRA:CALFNTNAGKSTF,TRB:TGTGCCAGCAGCGGCCGGGACCATTACAATGAGCAGTTCTTC...,NaN,TRB:gene,P1,../cellranger-vdj-outputs/P1
27,clonotype28,8,0.001703,TRB:CATTDLGGQADTQYF;TRA:CAMSSGGYQKVTF;TRA:CLSN...,TRB:TGTGCCACCACCGACCTAGGGGGTCAGGCAGATACGCAGTAT...,NaN,TRB:gene,P1,../cellranger-vdj-outputs/P1
29,clonotype30,7,0.001490,TRB:CSARDDSYNSPLHF;TRA:CATDAQGGADGLTF;TRA:CATD...,TRB:TGCAGTGCGAGAGACGACTCCTATAATTCACCCCTCCACTTT...,NaN,TRB:gene,P1,../cellranger-vdj-outputs/P1
...,...,...,...,...,...,...,...,...,...
6352,clonotype6353,1,0.000085,TRB:CASSSQLAGDRDSNTGELFF;TRA:CAESIDRGSTLGRLYF,TRB:TGTGCCAGCAGTTCCCAACTAGCGGGGGACCGAGACTCGAAC...,NaN,TRB:gene,P15,../cellranger-vdj-outputs/P15
6355,clonotype6356,1,0.000085,TRB:CASSSQLAGDRDSNTGELFF;TRA:CAESIDRGSTLGRLYF,TRB:TGTGCCAGCAGTTCCCAACTAGCGGGGGACCGAGACTCGAAC...,NaN,TRB:gene,P15,../cellranger-vdj-outputs/P15
6357,clonotype6358,1,0.000085,TRB:CSARDPSPRDLTRPSTTDTQYF;TRA:CAVTPGLFYNQGGKLIF,TRB:TGCAGTGCTAGAGATCCCTCGCCCCGGGACCTCACGCGACCC...,NaN,TRB:gene,P15,../cellranger-vdj-outputs/P15
6358,clonotype6359,1,0.000085,TRB:CSARGPLVGLAGAQTRADTQYF;TRA:CALEDTGKLIF,TRB:TGCAGTGCTAGAGGTCCACTGGTTGGGCTAGCGGGGGCTCAG...,NaN,TRB:gene,P15,../cellranger-vdj-outputs/P15
6470,clonotype6471,1,0.000085,TRB:CSAREPTKGLSLAGGISSSSYNEQFF;TRA:CAVSPMMDSSY...,TRB:TGCAGTGCTAGAGAGCCGACCAAAGGCCTATCGCTAGCGGGG...,NaN,TRB:gene,P15,../cellranger-vdj-outputs/P15

In [333]:
!ls ../cellranger-vdj-outputs/P1/

all_contig.fasta                consensus.fasta
all_contig.fasta.fai            consensus.fasta.fai
all_contig_annotations.csv      consensus_annotations.csv
clonotypes.csv                  filtered_contig.fasta
concat_ref.fasta                filtered_contig_annotations.csv
concat_ref.fasta.fai            metrics_summary.csv

In [334]:
!head ../cellranger-vdj-outputs/P1/filtered_contig.fasta

>AAACCTGAGAACTCGG-1_contig_1
CTTTTCACCAATGCACAGACCCAGAGGACCCCTCCATCCTGCAGTTCCTGCCATGAGCCTCGGGCTCCTGTGCTGTGGGGCCTTTTCTCTCCTGTGGGCAGGTCCAGTGAATGCTGGTGTCACTCAGACCCCAAAATTCCGGGTCCTGAAGACAGGACAGAGCATGACACTGCTGTGTGCCCAGGATATGAACCATGAATACATGTACTGGTATCGACAAGACCCAGGCATGGGGCTGAGGCTGATTCATTACTCAGTTGGTGAGGGTACAACTGCCAAAGGAGAGGTCCCTGATGGCTACAATGTCTCCAGATTAAAAAAACAGAATTTCCTGCTGGGGTTGGAGTCGGCTGCTCCCTCCCAAACATCTGTGTACTTCTGTGCCAGCAGTTACAGCTCCGGGCTCCTGGTGGGCGAGCAGTACTTCGGGCCGGGCACCAGGCTCACGGTCACAGAGGACCTGAAAAACGTGTTCCCACCCGAGGTCGCTGTGTTTGAGCCATCAGA
>AAACCTGAGCGTGAAC-1_contig_1
GAGTGAATCACGTTTTGCCCAGGAAAACACACTTGATAACTGAAGGATGATGAAGTGTCCACAGGCTTTACTAGCTATCTTTTGGCTTCTACTGAGCTGGGTGAGCAGTGAAGACAAGGTGGTACAAAGCCCTCTATCTCTGGTTGTCCACGAGGGAGACACTGTAACTCTCAATTGCAGTTATGAAGTGACTAACTTTCGAAGCCTACTATGGTACAAGCAGGAAAAGAAAGCTCCCACATTTCTATTTATGCTAACTTCAAGTGGAATTGAAAAGAAGTCAGGAAGACTAAGTAGCATATTAGATAAGAAAGAACTTTTCAGCATCCTGAACATCACAGCCACCCAGACCGGAGACTCGGCCGTCTACCTCTGTGCTGTGGCCGGAGGCTCAACCCTGGGGAGGCTATACTTTGGAAGAGGAACTCAGTTGACTGTCTGGCCTGATATCCAGAACCCTGACCCTGCCGTGTACCAGCTGAGAGACT
>AAACCTGAGCGTGAAC-1_contig_2
AGCTGTGAGGTCTGGTTCCCCGACGTGCTGCAGCAAGTGCCTTTGCCCTGCCTGTGGGCTCCCTCCATGGCCAACTCTGCTATGGACACCAGAGTACTCTGCTGTGCGGTCATCTGTCTTCTGGGGGCAGGTCTCTCAAATGCCGGCGTCATGCAGAACCCAAGACACCTGGTCAGGAGGAGGGGACAGGAGGCAAGACTGAGATGCAGCCCAATGAAAGGACACAGTCATGTTTACTGGTATCGGCAGCTCCCAGAGGAAGGTCTGAAATTCATGGTTTATCTCCAGAAAGAAAATATCATAGATGAGTCAGGAATGCCAAAGGAACGATTTTCTGCTGAATTTCCCAAAGAGGGCCCCAGCATCCTGAGGATCCAGCAGGTAGTGCGAGGAGATTCGGCAGCTTATTTCTGTGCCAGCTCACCACTGCAGGTCGATCAGCCCCAGCATTTTGGTGATGGGACTCGACTCTCCATCCTAGAGGACCTGAACAAGGTGTTCCCACCCGAGGTCGCTGTGTTTGAGCCATCAGA
>AAACCTGCAAAGGCGT-1_contig_1
AGATCAGAAGAGGAGGCTTCTCACCCTGCAGCAGGGACCTGTGAGCATGGCATGCCCTGGCTTCCTGTGGGCACTTGTGATCTCCACCTGTCTTGAATTTAGCATGGCTCAGACAGTCACTCAGTCTCAACCAGAGATGTCTGTGCAGGAGGCAGAGACCGTGACCCTGAGCTGCACATATGACACCAGTGAGAGTGATTATTATTTATTCTGGTACAAGCAGCCTCCCAGCAGGCAGATGATTCTCGTTATTCGCCAAGAAGCTTATAAGCAACAGAATGCAACAGAGAATCGTTTCTCTGTGAACTTCCAGAAAGCAGCCAAATCCTTCAGTCTCAAGATCTCAGACTCACAGCTGGGGGATGCCGCGATGTATTTCTGTGCTTATAGGAGCGCGGGAGATGACAAGATCATCTTTGGAAAAGGGACACGACTTCATATTCTCCCCAATATCCAGAACCCTGACCCTGCCGTGTACCAGCTGAGAGACT
>AAACCTGCAAAGGCGT-1_contig_2
CTTTTCACCAATGCACAGACCCAGAGGACCCCTCCATCCTGCAGTTCCTGCCATGAGCCTCGGGCTCCTGTGCTGTGGGGCCTTTTCTCTCCTGTGGGCAGGTCCAGTGAATGCTGGTGTCACTCAGACCCCAAAATTCCGGGTCCTGAAGACAGGACAGAGCATGACACTGCTGTGTGCCCAGGATATGAACCATGAATACATGTACTGGTATCGACAAGACCCAGGCATGGGGCTGAGGCTGATTCATTACTCAGTTGGTGAGGGTACAACTGCCAAAGGAGAGGTCCCTGATGGCTACAATGTCTCCAGATTAAAAAAACAGAATTTCCTGCTGGGGTTGGAGTCGGCTGCTCCCTCCCAAACATCTGTGTACTTCTGTGCCAGCAGTTACAGCTCCGGGCTCCTGGTGGGCGAGCAGTACTTCGGGCCGGGCACCAGGCTCACGGTCACAGAGGACCTGAAAAACGTGTTCCCACCCGAGGTCGCTGTGTTTGAGCCATCAGA

In [335]:
from tqdm import tqdm 

def num_sort_key(s):
    s_original = s
    if "/" in s:
        s = s.split("/")[-1]
    if len(s) > 1 and s[0] == "P":
        s = s[1:]
    if s.isdigit():
        return int(s)
    else:
        return s_original

def parse_fasta(path):
    results = {}
    curr_id = None
    lines = []
    def add_entry():
      
        if lines and curr_id:
            assert curr_id not in results
            results[curr_id] = "".join(lines)
            lines.clear()
        
    with open(path) as f:
        for l in tqdm(f.read().split("\n")):
            l = l.strip()
            if l.startswith(">"):
                if lines and curr_id:
                    add_entry()
                curr_id = l[1:]
            else:
                lines.append(l)
    add_entry()
    return results

peptide_num_to_contig_id_to_contig = {}
for peptide_num_path in sorted(glob("../cellranger-vdj-outputs/*"), key=num_sort_key):
    peptide_num = peptide_num_path.split("/")[-1]
    print("Reading %s" % peptide_num)
    peptide_num_to_contig_id_to_contig[peptide_num] = parse_fasta(
        "../cellranger-vdj-outputs/%s/all_contig.fasta" % peptide_num)

Reading P1

100%|██████████████████████████████████████████████| 28719/28719 [00:00<00:00, 3621000.92it/s]

Reading P2

100%|██████████████████████████████████████████████| 28051/28051 [00:00<00:00, 3393942.81it/s]

Reading P3

100%|██████████████████████████████████████████████| 93527/93527 [00:00<00:00, 3369095.81it/s]

Reading P4

100%|██████████████████████████████████████████████| 17133/17133 [00:00<00:00, 3687827.69it/s]

Reading P5

100%|██████████████████████████████████████████████| 45037/45037 [00:00<00:00, 3432403.05it/s]

Reading P6

100%|██████████████████████████████████████████████| 34469/34469 [00:00<00:00, 3761799.14it/s]

Reading P7

100%|██████████████████████████████████████████████| 47543/47543 [00:00<00:00, 3378338.28it/s]

Reading P8

100%|██████████████████████████████████████████████| 20503/20503 [00:00<00:00, 3793542.50it/s]

Reading P9

100%|██████████████████████████████████████████████| 36605/36605 [00:00<00:00, 3597883.86it/s]

Reading P10

100%|██████████████████████████████████████████████| 26719/26719 [00:00<00:00, 3478092.19it/s]

Reading P11

100%|██████████████████████████████████████████████| 23749/23749 [00:00<00:00, 3488862.94it/s]

Reading P12

100%|██████████████████████████████████████████████| 72615/72615 [00:00<00:00, 3635130.21it/s]

Reading P13

100%|██████████████████████████████████████████████| 31059/31059 [00:00<00:00, 3506241.26it/s]

Reading P14

100%|██████████████████████████████████████████████| 63535/63535 [00:00<00:00, 3604218.52it/s]

Reading P15

100%|████████████████████████████████████████████| 117081/117081 [00:00<00:00, 3586466.26it/s]

In [336]:
df_selected_full_seqs

,CDR3_alpha,CDR3_beta,Peptide,VDJ_alpha_beta_aa,VDJ_alpha_aa,VDJ_beta_aa,Cell_Count,Cell_Barcodes,Alpha_Contig_IDs,Beta_Contig_IDs,...,CDR2_alpha,alpha_v_gene,alpha_j_gene,alpha_c_gene,CDR1_beta,CDR2_beta,beta_v_gene,beta_d_gene,beta_j_gene,beta_c_gene
0,CAAAYIDNLFF,CASSPDRVNTGELFF,P5,QKEVEQNSGPLSVPEGAIASLNCTYSDRGSQSFFWYRQYSGKSPEL...,QKEVEQNSGPLSVPEGAIASLNCTYSDRGSQSFFWYRQYSGKSPEL...,EAGVVQSPRYKIIEKKQPVAFWCNPISGHNTLYWYLQNLGQGPELL...,27,"[GTCACGGCAAGCCGTC-1, GTCAAGTTCCGCGTTT-1, GTCAA...","[GTCACGGCAAGCCGTC-1_contig_1, GTCAAGTTCCGCGTTT...","[GTCACGGCAAGCCGTC-1_contig_2, GTCAAGTTCCGCGTTT...",...,IYSNGD,TRAV12-2,TRAJ36,TRAC,SGHNT,YENEEA,TRBV11-3,None,TRBJ2-2,TRBC2
1,CAADNAGNMLTF,CASSSEYLGEQFF,P15,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,ETGVTQSPTHLIKTRGQQVTLRCSSQSGHNTVSWYQQALGQGPQFI...,3,"[TAAGTGCCATGTTCCC-1, AACTTTCAGTTGAGTA-1, CAACC...","[TAAGTGCCATGTTCCC-1_contig_1, AACTTTCAGTTGAGTA...","[TAAGTGCCATGTTCCC-1_contig_2, AACTTTCAGTTGAGTA...",...,ISSIKDK,TRAV29/DV5,TRAJ39,TRAC,SGHNT,YYREEE,TRBV5-4,None,TRBJ2-1,TRBC2
2,CAAIKNQFYF,CASSRAGGQETQYF,P11,GENVEQHPSTLSVQEGDSAVIKCTYSDSASNYFPWYKQELGKGPQL...,GENVEQHPSTLSVQEGDSAVIKCTYSDSASNYFPWYKQELGKGPQL...,GAGVSQTPSNKVTEKGKYVELRCDPISGHTALYWYRQSLGQGPEFL...,26,"[GTCTTCGCATCTCGCT-1, GTCCTCACAGGCGATA-1, TTGCG...","[GTCTTCGCATCTCGCT-1_contig_2, GTCCTCACAGGCGATA...","[GTCTTCGCATCTCGCT-1_contig_1, GTCCTCACAGGCGATA...",...,IRSNVGE,TRAV13-1,TRAJ49,TRAC,SGHTA,FQGTGA,TRBV7-3,None,TRBJ2-5,TRBC2
3,CAASARETSGSRLTF,CASSPIGAYEQYF,P15,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,NAGVMQNPRHLVRRRGQEARLRCSPMKGHSHVYWYRQLPEEGLKFM...,44,"[GTACTTTCAGGACCCT-1, GTAACGTTCCTGCAGG-1, GGTGT...","[GTACTTTCAGGACCCT-1_contig_2, GTAACGTTCCTGCAGG...","[GTACTTTCAGGACCCT-1_contig_1, GTAACGTTCCTGCAGG...",...,ISSIKDK,TRAV29/DV5,TRAJ58,TRAC,KGHSH,LQKENI,TRBV18,None,TRBJ2-7,TRBC2
4,CAASAWEGQNFVF,CASSLLDQPQHF,P5,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,EAQVTQNPRYLITVTGKKLTVTCSQNMNHEYMSWYRQDPGLGLRQI...,12,"[GTGCGGTAGCCACGTC-1, GCGCCAAAGTGTTGAA-1, GTTCA...","[GTGCGGTAGCCACGTC-1_contig_2, GCGCCAAAGTGTTGAA...","[GTGCGGTAGCCACGTC-1_contig_1, GCGCCAAAGTGTTGAA...",...,ISSIKDK,TRAV29/DV5,TRAJ26,TRAC,MNHEY,SMNVEV,TRBV27,None,TRBJ1-5,TRBC1
5,CAASDTGGFKTIF,CASSSRARGQETQYF,P15,GQQVMQIPQYQHVQEGEDFTTYCNSSTTLSNIQWYKQRPGGHPVFL...,GQQVMQIPQYQHVQEGEDFTTYCNSSTTLSNIQWYKQRPGGHPVFL...,GAGVSQSPSNKVTEKGKDVELRCDPISGHTALYWYRQSLGQGLEFL...,1,[AGTGTCAAGCTCAACT-1],[AGTGTCAAGCTCAACT-1_contig_2],[AGTGTCAAGCTCAACT-1_contig_1],...,LVKSGEV,TRAV25,TRAJ9,TRAC,SGHTA,FQGNSA,TRBV7-2,None,TRBJ2-5,TRBC2
6,CAATPGSYNTDKLIF,CAISGGTGKGTQYF,P15,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,DAGITQSPRHKVTETGTPVTLRCHQTENHRYMYWYRQDPGHGLRLI...,7,"[GGACATTCATTCTCAT-1, GCTCCTAAGTCCGGTC-1, TGTGT...","[GGACATTCATTCTCAT-1_contig_1, GCTCCTAAGTCCGGTC...","[GGACATTCATTCTCAT-1_contig_2, GCTCCTAAGTCCGGTC...",...,ISSIKDK,TRAV29/DV5,TRAJ34,TRAC,ENHRY,SYGVKD,TRBV10-3,None,TRBJ2-5,TRBC2
7,CAETGFSDGQKLLF,CASSLDAEEGHYEQYF,P2,GEDVEQSLFLSVREGDSSVINCTYTDSSSTYLYWYKQEPGAGLQLL...,GEDVEQSLFLSVREGDSSVINCTYTDSSSTYLYWYKQEPGAGLQLL...,KAGVTQTPRYLIKTRGQQVTLSCSPISGHRSVSWYQQTPGQGLQFL...,7,"[GTCGGGTTCAACACTG-1, TATTACCTCGGAGGTA-1, CTGTT...","[GTCGGGTTCAACACTG-1_contig_2, TATTACCTCGGAGGTA...","[GTCGGGTTCAACACTG-1_contig_1, TATTACCTCGGAGGTA...",...,IFSNMDM,TRAV5,TRAJ16,TRAC,SGHRS,YFSETQ,TRBV5-1,None,TRBJ2-7,TRBC2
8,CAGHSAGGTSYGKLTF,CASSLYAGAWSYTF,P11,GQQLNQSPQSMFIQEGEDVSMNCTSSSIFNTWLWYKQDPGEGPVLL...,GQQLNQSPQSMFIQEGEDVSMNCTSSSIFNTWLWYKQDPGEGPVLL...,EAQVTQNPRYLITVTGKKLTVTCSQNMNHEYMSWYRQDPGLGLRQI...,23,"[TACTCATAGATCGGGT-1, GTCACAATCGATAGAA-1, GACCA...","[TACTCATAGATCGGGT-1_contig_1, GTCACAATCGATAGAA...","[TACTCATAGATCGGGT-1_contig_2, GTCACAATCGATAGAA...",...,LYKAGEL,TRAV35,TRAJ52,TRAC,MNHEY,SMNVEV,TRBV27,None,TRBJ1-2,TRBC1
9,CAGQPGSSNYKLTF,CASSVQGATEAFF,P12,GQQLNQSPQSMFIQEGEDVSMNCTSSSIFNTWLWYKQDPGEGPVLL...,GQQLNQSPQSMFIQEGEDVSMNCTSSSIFNTWLWYKQDPGEGPVLL...,EPEVTQTPSHQVTQMGQEVILRCVPISNHLYFYWYRQILGQKVEFL...,43,"[GTCTTCGGTTAGTGGG-1, GTCGTAAAGTGGAGAA-1, GTACT...","[GTCTTCGGTTAGTGGG-1_contig_1, GTCGTAAAGTGGAGAA...","[GTCTTCGGTTAGTGGG-1_contig_2, GTCGTAAAGTGGAGAA...",...,LYKAGEL,TRAV35,TRAJ53,TRAC,SNHLY,FYNNEI,TRBV2,TRBD1,TRBJ1-1,TRBC1
10,CALDIDSNYQLIW,CAISERVNEQFF,P15,SQKIEQNSEALNIQEGKTATLTCNYTNYSPAYLQWYRQDPGRGPVF...,SQKIEQNSEALNIQEGKTATLTCNYTNYSPAYLQWYRQDPGRGPVF...,DAGITQSPRHKVTETGTPVTLRCHQTENHRYMYWYRQDPGHGLRLI...,11,"[GGCTCGATCTTGTCAT-1, GACTGCGCATTGGGCC-1, GAATG...","[GGCTCGATCTTGTCAT-1_contig_2, GACTGCGCATTGGGCC...","[GGCTCGATCTTGTCAT-1_contig_1, GACTGCGCATTGGGCC...",...,IRENEKE,TRAV6,TRAJ33,TRAC,ENHRY,SYGVKD,TRBV10-3,None,TRBJ2-1,TRBC2
11,CAMREGKGAGNMLTF,CASSRANSNQPQHF,P1,AQKITQTQPGMFVQEKEAVTLDCTYDTSDQSYGLFWYKQPSSGEMI...,AQKITQTQPGMFVQEKEAVTLDCTYDTSDQSYGLFWYKQPSSGEMI...,DTAVSQTPKYLVTQMGNDKSIKCEQNLGHDTMYWYKQDSKKFLKIM...,38,"[AACTCCCGTCGGGTCT-1, GGCGACTGTAGCGATG-1, GGCTG...","[AACTCCCGTCGGGTCT-1_contig_2, GGCGACTGTAGCGATG...","[AACTCCCGTCGGGTCT-1_contig_1, GGCGACTGTAGCGATG...",...,QGSYDEQN,TRAV14/DV4,TRAJ39,TRAC,LGHDT,YNNKEL,TRBV3-1,None,TRBJ1-5,TRBC1
12,CASERGSARQLTF,CASSFGTEDTQYF,P15,QKEVEQNSGPLSVPEGAIASLNCTYSDRGSQSFFWYRQYSGKSPEL...,QKEVEQNSGPLSVPEGAIASLNCTYSDRGSQSFFWYRQYSGKSPEL...,EAGVAQSPRYKIIEKRQSVAFWCNPISGHATLYWYQQILGQGPKLL...,6,"[GCGCCAAAGACTGGGT-1, GCAGCCATCCTCTAGC-1, CTTAG...","[GCGCCAAAGACTGGGT-1_contig_1, GCAGCCATCCTCTAGC...","[GCGCCAAAGACTGGGT-1_contig_2, GCAGCCATCCTCTAGC...",...,IYSNGD,TRAV12-2,TRAJ22,TRAC,SGHAT,FQNNGV,TRBV11-2,None,TRBJ2-3,TRBC2
13,CATDSGGYQKVTF,CASSEGGHTGELFF,P7,SQQGEEDPQALSIQEGENATMNCSYKTSINNLQWYRQNSGRGLVHL...,SQQGEEDPQALSIQEGENATMNCSYKTSINNLQWYRQNSGRGLVHL...,NAGVMQNPRHLVRRRGQEARLRCSPMKGHSHVYWYRQLPEEGLKFM...,41,"[GTAACTGGTGTGGCTC-1, GCTCTGTTCTTTACAC-1, GACAC...","[GTAACTGGTGTGGCTC-1_contig_2, GCTCTGTTCTTTACAC...","[GTAACTGGTGTGGCTC-1_contig_1, GCTCTGTTCTTTACAC...",...,IRSNERE,TRAV17,TRAJ13,TRAC,KGHSH,LQKENI,TRBV18,TRBD1,TRBJ2-2,TRBC2
14,CATVSVGGFGNVLHC,CASSPDRVNTGELFF,P5,GENVEQHPSTLSVQEGDSAVIKCTYSDSASNYFPWYKQELGKGPQL...,GENVEQHPSTLSVQEGDSAVIKCTYSDSASNYFPWYKQELGKGPQL...,EAGVVQSPRYKIIEKKQPVAFWCNPISGHNTLYWYLQNLGQGPELL...,21,"[GTACTCCTCCAAGTAC-1, GGTGTTATCTTGTACT-1, GCTTG...","[GTACTCCTCCAAGTAC-1_contig_3, GGTGTTATCTTGTACT...","[GTACTCCTCCAAGTAC-1_contig_2, GGTGTTATCTTGTACT...",...,IRSNVGE,TRAV13-1,TRAJ35,TRAC,SGHNT,YENEEA,TRBV11-3,None,TRBJ2-2,TRBC2
15,CAVGASNAGGTSYGKLTF,CASSLARYDEQYF,P15,AQSVTQPDIHITVSEGASLELRCNYSYGATPYLFWYVQSPGQGLQL...,AQSVTQPDIHITVSEGASLELRCNYSYGATPYLFWYVQSPGQGLQL...,DTGVSQNPRHKITKRGQNVTFRCDPISEHNRLYWYRQTLGQGPEFL...,2,"[TACCTTACACTGTCGG-1, ATCACGATCATCTGTT-1]","[TACCTTACACTGTCGG-1_contig_2, ATCACGATCATCTGTT...","[TACCTTACACTGTCGG-1_contig_1, ATCACGATCATCTGTT...",...,YFSGDTLV,TRAV8-3,TRAJ52,TRAC,SEHNR,FQNEAQ,TRBV7-9,None,TRBJ2-7,TRBC2
16,CAVLYNTDKLIF,CASSSTRGYGANVLTF,P15,KQEVTQIPAALSVPEGENLVLNCSFTDSAIYNLQWFRQDPGKGLTS...,KQEVTQIPAALSVPEGENLVLNCSFTDSAIYNLQWFRQDPGKGLTS...,GAGVSQSPSNKVTEKGKDVELRCDPISGHTALYWYRQSLGQGLEFL...,3,"[GCTGGGTCATTGTGCA-1, GCTGCGATCATCGCTC-1, CCGGG...","[GCTGGGTCATTGTGCA-1_contig_2, GCTGCGATCATCGCTC...","[GCTGGGTCATTGTGCA-1_contig_1, GCTGCGATCATCGCTC...",...,IQSSQRE,TRAV21,TRAJ34,TRAC,SGHTA,FQGNSA,TRBV7-2,TRBD1,TRBJ2-6,TRBC2
17,CAVRDGKAAGNKLTF,CASSLVTGAFDEQFF,P13,AQSVAQPEDQVNVAEGNPLTVKCTYSVSGNPYLFWYVQYPNRGLQF...,AQSVAQPEDQVNVAEGNPLTVKCTYSVSGNPYLFWYVQYPNRGLQF...,DTGVSQNPRHKITKRGQNVTFRCDPISEHNRLYWYRQTLGQGPEFL...,66,"[GGATTACTCATTTGGG-1, GGACAAGTCATCGATG-1, GGACA...","[GGATTACTCATTTGGG-1_contig_1, GGACAAGTCATCGATG...","[GGATTACTCATTTGGG-1_contig_2, GGACAAGTCATCGATG...",...,YITGDNLV,TRAV3,TRAJ17,TRAC,SEHNR,FQNEAQ,TRBV7-9,TRBD1,TRBJ2-1,TRBC2
18,CAVSVRRGGGSQGNLIF,CASSYSRGYEQYF,P15,AQSVTQLDSQVPVFEEAPVELRCNYSSSVSVYLFWYVQYPNQGLQL...,AQSVTQLDSQVPVFEEAPVELRCNYSSSVSVYLFWYVQYPNQGLQL...,NAGVTQTPKFQVLKTGQSMTLQCAQDMNHEYMSWYRQDPGMGLRLI...,2,"[ATCTGCCTCAGTGCAT-1, CTCACACAGGGAACGG-1]","[ATCTGCCTCAGTGCAT-1_contig_1, CTCACACAGGGAACGG...","[ATCTGCCTCAGTGCAT-1_contig_2, CTCACACAGGGAACGG...",...,YLSGSTLV,TRAV8-6,TRAJ42,TRAC,MNHEY,SVGAGI,TRBV6-5,None,TRBJ2-7,TRBC2
19,CAVVRGNDYKLSF,CASSPRQDSYEQYF,P3,EDQVTQSPEALRLQEGESSSLNCSYTVSGLRGLFWYRQDPGKGPEF...,EDQVTQSPEALRLQEGESSSLNCSYTVSGLRGLFWYRQDPGKGPEF...,NAGVMQNPRHLVRRRGQEARLRCSPMKGHSHVYWYRQLPEEGLKFM...,1,[GGACAAGGTGCACGAA-1],[GGACAAGGTGCACGAA-1_contig_2],[GGACAAGGTGCACGAA-1_contig_1],...,LYSAGEE,TRAV20,TRAJ20,TRAC,KGHSH,LQKENI,TRBV18,None,TRBJ2-7,TRBC2
20,CAVYNNARLMF,CASLGRGGLAKNIQYF,P12,GQQVMQIPQYQHVQEGEDFTTYCNSSTTLSNIQWYKQRPGGHPVFL...,GQQVMQIPQYQHVQEGEDFTTYCNSSTTLSNIQWYKQRPGGHPVFL...,EPEVTQTPSHQVTQMGQEVILRCVPISNHLYFYWYRQILGQKVEFL...,12,"[GGGAATGGTAGCTAAA-1, CTTACCGAGCTCAACT-1, TCTGA...","[GGGAATGGTAGCTAAA-1_contig_2, CTTACCGAGCTCAACT...","[GGGAATGGTAGCTAAA-1_contig_1, CTTACCGAGCTCAACT...",...,LVKSGEV,TRAV25,TRAJ31,TRAC,SNHLY,FYNNEI,TRBV2,None,TRBJ2-4,TRBC2
21,CAYRDSNYQLIW,CASSPTGDSGNTIYF,P10,AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMI...,AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMI...,NAGVMQNPRHLVRRRGQEARLRCSPMKGHSHVYWYRQLPEEGLKFM...,41,"[GGTGCGTTCGGAAATA-1, GGCTGGTGTTCGCTAA-1, GCTTC...","[GGTGCGTTCGGAAATA-1_contig_2, GGCTGGTGTTCGCTAA...","[GGTGCGTTCGGAAATA-1_contig_1, GGCTGGTGTTCGCTAA...",...,QEAYKQQN,TRAV38-2/DV8,TRAJ33,TRAC,KGHSH,LQKENI,TRBV18,None,TRBJ1-3,TRBC1
22,CAYRSAKGNDMRF,CASSFYFGQGYEQYF,P15,AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMI...,AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMI...,GAGVSQSPSNKVTEKGKDVELRCDPISGHTALYWYRQSLGQGLEFL...,3,"[ACACCGGGTTCGGCAC-1, AACCGCGAGTAACCCT-1, CGAGA...","[ACACCGGGTTCGGCAC-1_contig_2, AACCGCGAGTAACCCT...","[ACACCGGGTTCGGCAC-1_contig_1, AACCGCGAGTAACCCT...",...,QEAYKQQN,TRAV38-2/DV8,TRAJ43,TRAC,SGHTA,FQGNSA,TRBV7-2,None,TRBJ2-7,TRBC2
23,CAYWVGGGGADGLTF,CASSLTPGGVKETQYF,P12,AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMI...,AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMI...,GAGVSQSPRYKVAKRGQDVALRCDPISGHVSLFWYQQALGQGPEFL...,33,"[GTGCATATCCGATATG-1, GACGTTACAGGTCGTC-1, GACGC...","[GTGCATATCCGATATG-1_contig_1, GACGTTACAGGTCGTC...","[GTGCATATCCGATATG-1_contig_2, GACGTTACAGGTCGTC...",...,QEAYKQQN,TRAV38-2/DV8,TRAJ45,TRAC,SGHVS,FQNEAQ,TRBV7-8,None,TRBJ2-5,TRBC2
24,CGADTNFGNEKLTF,CASSPGLATQYF,P7,SQELEQSPQSLIVQEGKNLTINCTSSKTLYGLYWYKQKYGEGLIFL...,SQELEQSPQSLIVQEGKNLTINCTSSKTLYGLYWYKQKYGEGLIFL...,EAGVAQSPRYKIIEKRQSVAFWCNPISGHATLYWYQQILGQGPKLL...,26,"[GGGTTGCTCCGTCATC-1, GGAATAACATGTAGTC-1, GCATG...","[GGGTTGCTCCGTCATC-1_contig_1, GGAATAACATGTAGTC...","[GGGTTGCTCCGTCATC-1_contig_2, GGAATAACATGTAGTC...",...,LQKGGEE,TRAV34,TRAJ48,TRAC,SGHAT,FQNNGV,TRBV11-2,None,TRBJ2-3,TRBC2
25,CGTETGNNRLAF,CASSKKGTGTDTQYF,P15,QQPVQSPQAVILREGEDAVINCSSSKALYSVHWYRQKHGEAPVFLM...,QQPVQSPQAVILREGEDAVINCSSSKALYSVHWYRQKHGEAPVFLM...,GAGVSQSPRYKVAKRGQDVALRCDPISGHVSLFWYQQALGQGPEFL...,1,[CGATGGCCATACCATG-1],[CGATGGCCATACCATG-1_contig_3],[CGATGGCCATACCATG-1_contig_1],...,LLKGGEQ,TRAV30,TRAJ7,TRAC,SGHVS,FQNEAQ,TRBV7-8,None,TRBJ2-3,TRBC2

In [337]:
from tqdm import tqdm
for _, row in tqdm(df_selected_full_seqs.iterrows()):
    
    for (barcode, alpha_contig_id, beta_contig_id) in zip(row.Cell_Barcodes, row.Alpha_Contig_IDs, row.Beta_Contig_IDs):
        alpha_contig = peptide_num_to_contig_id_to_contig[row.Peptide].get(alpha_contig_id)
        beta_contig = peptide_num_to_contig_id_to_contig[row.Peptide].get(beta_contig_id)
        
        
        assert barcode == alpha_contig_id.split("_")[0] == beta_contig_id.split("_")[0]
        if row.VDJ_alpha_dna not in alpha_contig:
            print("WARNING: alpha chain DNA sequence for cell %s in culture %s not contained in original assembly" % (
                barcode,
                row.Peptide
            ))
            print("Alpha AA:", row.VDJ_alpha_aa)
            print("> Alpha chain DNA:")
            print(row.VDJ_alpha_dna)
            print("> Assembly contig %s" % alpha_contig_id)
            print(alpha_contig)
        if row.VDJ_beta_dna not in beta_contig:
            print("WARNING: beta chain DNA sequence for cell %s in culture %s not contained in original assembly" % (
                barcode,
                row.Peptide
            ))
            print("Beta AA:", row.VDJ_beta_aa)
            print("> Beta chain DNA:")
            print(row.VDJ_beta_dna)
            print("> Assembly contig %s" % beta_contig_id)
            print(beta_contig)

26it [00:00, 1788.88it/s]

WARNING: alpha chain DNA sequence for cell TTGAACGGTTTAAGCC-1 in culture P15 not contained in original assembly
Alpha AA: DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTFLISISSIKDKNEDGRFTVFLNKSAKHLSLHIVPSQPGDSAVYFCAASARETSGSRLTFGEGTQLTVNP
> Alpha chain DNA:
GACCAGCAAGTTAAGCAAAATTCACCATCCCTGAGCGTCCAGGAAGGAAGAATTTCTATTCTGAACTGTGACTATACTAACAGCATGTTTGATTATTTCCTATGGTACAAAAAATACCCTGCTGAAGGTCCTACATTCCTGATATCTATAAGTTCCATTAAGGATAAAAATGAAGATGGAAGATTCACTGTCTTCTTAAACAAAAGTGCCAAGCACCTCTCTCTGCACATTGTGCCCTCCCAGCCTGGAGACTCTGCAGTGTACTTCTGTGCAGCAAGCGCTAGGGAAACCAGTGGCTCTAGGTTGACCTTTGGGGAAGGAACACAGCTCACAGTGAATCCTG
> Assembly contig TTGAACGGTTTAAGCC-1_contig_1
AAGACAATCTGCATCTTCACAGGAGGGATGGCCATGCTCCTGGGGGCATCAGTGCTGATTCTGTGGCTTCAGCCAGACTGGGTAAACAGTCAACAGAAGAATGATGACCAGCAAGTTAAGCAAAATTCACCATCCCTGAGCGTCCAGGAAGGAAGAATTTCTATTCTGAACTGTGACTATACTAACAGCATGTTTGATTATTTCCTATGGTACAAAAAATACCCTGCTGAAGGTCCTACATTCCTGATATCTATAAGTTCCATTAAGGATAAAAATGAAGATGGAAGATTCACTGTCTTCTTAAACAAAAGTGCCAAGCACCTCTCTCTGCACATTGTGCCCTCCCAGCCTGGAGACTCTGCAGTGTACTTCTGTGCAGCAAGCGCGAGAGAAACCAGTGGCTCTAGGTTGACCTTTGGGGAAGGAACACAGCTCACAGTGAATCCTGATATCCAGAACCCTGACCCTGCCGTGTACCAGCTGAGAGACT
WARNING: beta chain DNA sequence for cell TTGAACGGTTTAAGCC-1 in culture P15 not contained in original assembly
Beta AA: NAGVMQNPRHLVRRRGQEARLRCSPMKGHSHVYWYRQLPEEGLKFMVYLQKENIIDESGMPKERFSAEFPKEGPSILRIQQVVRGDSAAYFCASSPIGAYEQYFGPGTRLTVT
> Beta chain DNA:
AATGCCGGCGTCATGCAGAACCCAAGACACCTGGTCAGGAGGAGGGGACAGGAGGCAAGACTGAGATGCAGCCCAATGAAAGGACACAGTCATGTTTACTGGTATCGGCAGCTCCCAGAGGAAGGTCTGAAATTCATGGTTTATCTCCAGAAAGAAAATATCATAGATGAGTCAGGAATGCCAAAGGAACGATTTTCTGCTGAATTTCCCAAAGAGGGCCCCAGCATCCTGAGGATCCAGCAGGTAGTGCGAGGAGATTCGGCAGCTTATTTCTGTGCCAGCTCACCGATAGGAGCCTACGAGCAGTACTTCGGGCCGGGCACCAGGCTCACGGTCACAG
> Assembly contig TTGAACGGTTTAAGCC-1_contig_2
GGTTCCCCGACGTGCTGCAGCAAGTGCCTTTGCCCTGCCTGTGGGCTCCCTCCATGGCCAACTCTGCTATGGACACCAGACTACTCTGCTGTGCGGTCATCTGTCTTCTGGGGGCAGGTCTCTCAAATGCCGGCGTCATGCAGAACCCAAGACACCTGGTCAGGAGGAGGGGACAGGAGGCAAGACTGAGATGCAGCCCAATGAAAGGACACAGTCATGTTTACTGGTATCGGCAGCTCCCAGAGGAAGGTCTGAAATTCATGGTTTATCTCCAGAAAGAAAATATCATAGATGAGTCAGGAATGCCAAAGGAACGATTTTCTGCTGAATTTCCCAAAGAGGGCCCCAGCATCCTGAGGATCCAGCAGGTAGTGCGAGGAGATTCGGCAGCTTATTTCTGTGCCAGCTCACCGATTGGCGCCTACGAGCAGTACTTCGGGCCGGGCACCAGGCTCACGGTCACAGAGGACCTGAAAAACGTGTTCCCACCCGAGGTCGCTGTGTTTGAGCCATCAGA
WARNING: alpha chain DNA sequence for cell GTTCTCGCAGATGAGC-1 in culture P15 not contained in original assembly
Alpha AA: DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTFLISISSIKDKNEDGRFTVFLNKSAKHLSLHIVPSQPGDSAVYFCAASARETSGSRLTFGEGTQLTVNP
> Alpha chain DNA:
GACCAGCAAGTTAAGCAAAATTCACCATCCCTGAGCGTCCAGGAAGGAAGAATTTCTATTCTGAACTGTGACTATACTAACAGCATGTTTGATTATTTCCTATGGTACAAAAAATACCCTGCTGAAGGTCCTACATTCCTGATATCTATAAGTTCCATTAAGGATAAAAATGAAGATGGAAGATTCACTGTCTTCTTAAACAAAAGTGCCAAGCACCTCTCTCTGCACATTGTGCCCTCCCAGCCTGGAGACTCTGCAGTGTACTTCTGTGCAGCAAGCGCTAGGGAAACCAGTGGCTCTAGGTTGACCTTTGGGGAAGGAACACAGCTCACAGTGAATCCTG
> Assembly contig GTTCTCGCAGATGAGC-1_contig_2
AAGACAATCTGCATCTTCACAGGAGGGATGGCCATGCTCCTGGGGGCATCAGTGCTGATTCTGTGGCTTCAGCCAGACTGGGTAAACAGTCAACAGAAGAATGATGACCAGCAAGTTAAGCAAAATTCACCATCCCTGAGCGTCCAGGAAGGAAGAATTTCTATTCTGAACTGTGACTATACTAACAGCATGTTTGATTATTTCCTATGGTACAAAAAATACCCTGCTGAAGGTCCTACATTCCTGATATCTATAAGTTCCATTAAGGATAAAAATGAAGATGGAAGATTCACTGTCTTCTTAAACAAAAGTGCCAAGCACCTCTCTCTGCACATTGTGCCCTCCCAGCCTGGAGACTCTGCAGTGTACTTCTGTGCAGCAAGCGCGAGAGAAACCAGTGGCTCTAGGTTGACCTTTGGGGAAGGAACACAGCTCACAGTGAATCCTGATATCCAGAACCCTGACCCTGCCGTGTACCAGCTGAGAGACT
WARNING: beta chain DNA sequence for cell GTTCTCGCAGATGAGC-1 in culture P15 not contained in original assembly
Beta AA: NAGVMQNPRHLVRRRGQEARLRCSPMKGHSHVYWYRQLPEEGLKFMVYLQKENIIDESGMPKERFSAEFPKEGPSILRIQQVVRGDSAAYFCASSPIGAYEQYFGPGTRLTVT
> Beta chain DNA:
AATGCCGGCGTCATGCAGAACCCAAGACACCTGGTCAGGAGGAGGGGACAGGAGGCAAGACTGAGATGCAGCCCAATGAAAGGACACAGTCATGTTTACTGGTATCGGCAGCTCCCAGAGGAAGGTCTGAAATTCATGGTTTATCTCCAGAAAGAAAATATCATAGATGAGTCAGGAATGCCAAAGGAACGATTTTCTGCTGAATTTCCCAAAGAGGGCCCCAGCATCCTGAGGATCCAGCAGGTAGTGCGAGGAGATTCGGCAGCTTATTTCTGTGCCAGCTCACCGATAGGAGCCTACGAGCAGTACTTCGGGCCGGGCACCAGGCTCACGGTCACAG
> Assembly contig GTTCTCGCAGATGAGC-1_contig_1
AGCTGTGAGGTCTGGTTCCCCGACGTGCTGCAGCAAGTGCCTTTGCCCTGCCTGTGGGCTCCCTCCATGGCCAACTCTGCTATGGACACCAGACTACTCTGCTGTGCGGTCATCTGTCTTCTGGGGGCAGGTCTCTCAAATGCCGGCGTCATGCAGAACCCAAGACACCTGGTCAGGAGGAGGGGACAGGAGGCAAGACTGAGATGCAGCCCAATGAAAGGACACAGTCATGTTTACTGGTATCGGCAGCTCCCAGAGGAAGGTCTGAAATTCATGGTTTATCTCCAGAAAGAAAATATCATAGATGAGTCAGGAATGCCAAAGGAACGATTTTCTGCTGAATTTCCCAAAGAGGGCCCCAGCATCCTGAGGATCCAGCAGGTAGTGCGAGGAGATTCGGCAGCTTATTTCTGTGCCAGCTCACCGATTGGCGCCTACGAGCAGTACTTCGGGCCGGGCACCAGGCTCACGGTCACAGAGGACCTGAAAAACGTGTTCCCACCCGAGGTCGCTGTGTTTGAGCCATCAGA
WARNING: alpha chain DNA sequence for cell TGCGTGGTCAGGCGAA-1 in culture P15 not contained in original assembly
Alpha AA: DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTFLISISSIKDKNEDGRFTVFLNKSAKHLSLHIVPSQPGDSAVYFCAASARETSGSRLTFGEGTQLTVNP
> Alpha chain DNA:
GACCAGCAAGTTAAGCAAAATTCACCATCCCTGAGCGTCCAGGAAGGAAGAATTTCTATTCTGAACTGTGACTATACTAACAGCATGTTTGATTATTTCCTATGGTACAAAAAATACCCTGCTGAAGGTCCTACATTCCTGATATCTATAAGTTCCATTAAGGATAAAAATGAAGATGGAAGATTCACTGTCTTCTTAAACAAAAGTGCCAAGCACCTCTCTCTGCACATTGTGCCCTCCCAGCCTGGAGACTCTGCAGTGTACTTCTGTGCAGCAAGCGCTAGGGAAACCAGTGGCTCTAGGTTGACCTTTGGGGAAGGAACACAGCTCACAGTGAATCCTG
> Assembly contig TGCGTGGTCAGGCGAA-1_contig_2
AGATTTGCAGCTTTCTAGGCAGGAGACAAGACAATCTGCATCTTCACAGGAGGGATGGCCATGCTCCTGGGGGCATCAGTGCTGATTCTGTGGCTTCAGCCAGACTGGGTAAACAGTCAACAGAAGAATGATGACCAGCAAGTTAAGCAAAATTCACCATCCCTGAGCGTCCAGGAAGGAAGAATTTCTATTCTGAACTGTGACTATACTAACAGCATGTTTGATTATTTCCTATGGTACAAAAAATACCCTGCTGAAGGTCCTACATTCCTGATATCTATAAGTTCCATTAAGGATAAAAATGAAGATGGAAGATTCACTGTCTTCTTAAACAAAAGTGCCAAGCACCTCTCTCTGCACATTGTGCCCTCCCAGCCTGGAGACTCTGCAGTGTACTTCTGTGCAGCAAGCGCGAGAGAAACCAGTGGCTCTAGGTTGACCTTTGGGGAAGGAACACAGCTCACAGTGAATCCTGATATCCAGAACCCTGACCCTGCCGTGTACCAGCTGAGAGACT
WARNING: beta chain DNA sequence for cell TGCGTGGTCAGGCGAA-1 in culture P15 not contained in original assembly
Beta AA: NAGVMQNPRHLVRRRGQEARLRCSPMKGHSHVYWYRQLPEEGLKFMVYLQKENIIDESGMPKERFSAEFPKEGPSILRIQQVVRGDSAAYFCASSPIGAYEQYFGPGTRLTVT
> Beta chain DNA:
AATGCCGGCGTCATGCAGAACCCAAGACACCTGGTCAGGAGGAGGGGACAGGAGGCAAGACTGAGATGCAGCCCAATGAAAGGACACAGTCATGTTTACTGGTATCGGCAGCTCCCAGAGGAAGGTCTGAAATTCATGGTTTATCTCCAGAAAGAAAATATCATAGATGAGTCAGGAATGCCAAAGGAACGATTTTCTGCTGAATTTCCCAAAGAGGGCCCCAGCATCCTGAGGATCCAGCAGGTAGTGCGAGGAGATTCGGCAGCTTATTTCTGTGCCAGCTCACCGATAGGAGCCTACGAGCAGTACTTCGGGCCGGGCACCAGGCTCACGGTCACAG
> Assembly contig TGCGTGGTCAGGCGAA-1_contig_1
AGCTGTGAGGTCTGGTTCCCCGACGTGCTGCAGCAAGTGCCTTTGCCCTGCCTGTGGGCTCCCTCCATGGCCAACTCTGCTATGGACACCAGACTACTCTGCTGTGCGGTCATCTGTCTTCTGGGGGCAGGTCTCTCAAATGCCGGCGTCATGCAGAACCCAAGACACCTGGTCAGGAGGAGGGGACAGGAGGCAAGACTGAGATGCAGCCCAATGAAAGGACACAGTCATGTTTACTGGTATCGGCAGCTCCCAGAGGAAGGTCTGAAATTCATGGTTTATCTCCAGAAAGAAAATATCATAGATGAGTCAGGAATGCCAAAGGAACGATTTTCTGCTGAATTTCCCAAAGAGGGCCCCAGCATCCTGAGGATCCAGCAGGTAGTGCGAGGAGATTCGGCAGCTTATTTCTGTGCCAGCTCACCGATTGGCGCCTACGAGCAGTACTTCGGGCCGGGCACCAGGCTCACGGTCACAGAGGACCTGAAAAACGTGTTCCCACCCGAGGTCGCTGTGTTTGAGCCATCAGA
WARNING: alpha chain DNA sequence for cell TGCACCTGTCTAGTGT-1 in culture P15 not contained in original assembly
Alpha AA: DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTFLISISSIKDKNEDGRFTVFLNKSAKHLSLHIVPSQPGDSAVYFCAASARETSGSRLTFGEGTQLTVNP
> Alpha chain DNA:
GACCAGCAAGTTAAGCAAAATTCACCATCCCTGAGCGTCCAGGAAGGAAGAATTTCTATTCTGAACTGTGACTATACTAACAGCATGTTTGATTATTTCCTATGGTACAAAAAATACCCTGCTGAAGGTCCTACATTCCTGATATCTATAAGTTCCATTAAGGATAAAAATGAAGATGGAAGATTCACTGTCTTCTTAAACAAAAGTGCCAAGCACCTCTCTCTGCACATTGTGCCCTCCCAGCCTGGAGACTCTGCAGTGTACTTCTGTGCAGCAAGCGCTAGGGAAACCAGTGGCTCTAGGTTGACCTTTGGGGAAGGAACACAGCTCACAGTGAATCCTG
> Assembly contig TGCACCTGTCTAGTGT-1_contig_2
GCAGCTTTCTAGGCAGGAGACAAGACAATCTGCATCTTCACAGGAGGGATGGCCATGCTCCTGGGGGCATCAGTGCTGATTCTGTGGCTTCAGCCAGACTGGGTAAACAGTCAACAGAAGAATGATGACCAGCAAGTTAAGCAAAATTCACCATCCCTGAGCGTCCAGGAAGGAAGAATTTCTATTCTGAACTGTGACTATACTAACAGCATGTTTGATTATTTCCTATGGTACAAAAAATACCCTGCTGAAGGTCCTACATTCCTGATATCTATAAGTTCCATTAAGGATAAAAATGAAGATGGAAGATTCACTGTCTTCTTAAACAAAAGTGCCAAGCACCTCTCTCTGCACATTGTGCCCTCCCAGCCTGGAGACTCTGCAGTGTACTTCTGTGCAGCAAGCGCGAGAGAAACCAGTGGCTCTAGGTTGACCTTTGGGGAAGGAACACAGCTCACAGTGAATCCTGATATCCAGAACCCTGACCCTGCCGTGTACCAGCTGAGAGACT
WARNING: beta chain DNA sequence for cell TGCACCTGTCTAGTGT-1 in culture P15 not contained in original assembly
Beta AA: NAGVMQNPRHLVRRRGQEARLRCSPMKGHSHVYWYRQLPEEGLKFMVYLQKENIIDESGMPKERFSAEFPKEGPSILRIQQVVRGDSAAYFCASSPIGAYEQYFGPGTRLTVT
> Beta chain DNA:
AATGCCGGCGTCATGCAGAACCCAAGACACCTGGTCAGGAGGAGGGGACAGGAGGCAAGACTGAGATGCAGCCCAATGAAAGGACACAGTCATGTTTACTGGTATCGGCAGCTCCCAGAGGAAGGTCTGAAATTCATGGTTTATCTCCAGAAAGAAAATATCATAGATGAGTCAGGAATGCCAAAGGAACGATTTTCTGCTGAATTTCCCAAAGAGGGCCCCAGCATCCTGAGGATCCAGCAGGTAGTGCGAGGAGATTCGGCAGCTTATTTCTGTGCCAGCTCACCGATAGGAGCCTACGAGCAGTACTTCGGGCCGGGCACCAGGCTCACGGTCACAG
> Assembly contig TGCACCTGTCTAGTGT-1_contig_1
AGCTGTGAGGTCTGGTTCCCCGACGTGCTGCAGCAAGTGCCTTTGCCCTGCCTGTGGGCTCCCTCCATGGCCAACTCTGCTATGGACACCAGACTACTCTGCTGTGCGGTCATCTGTCTTCTGGGGGCAGGTCTCTCAAATGCCGGCGTCATGCAGAACCCAAGACACCTGGTCAGGAGGAGGGGACAGGAGGCAAGACTGAGATGCAGCCCAATGAAAGGACACAGTCATGTTTACTGGTATCGGCAGCTCCCAGAGGAAGGTCTGAAATTCATGGTTTATCTCCAGAAAGAAAATATCATAGATGAGTCAGGAATGCCAAAGGAACGATTTTCTGCTGAATTTCCCAAAGAGGGCCCCAGCATCCTGAGGATCCAGCAGGTAGTGCGAGGAGATTCGGCAGCTTATTTCTGTGCCAGCTCACCGATTGGCGCCTACGAGCAGTACTTCGGGCCGGGCACCAGGCTCACGGTCACAGAGGACCTGAAAAACGTGTTCCCACCCGAGGTCGCTGTGTTTGAGCCATCAGA
WARNING: alpha chain DNA sequence for cell CTACACCTCTAACGGT-1 in culture P15 not contained in original assembly
Alpha AA: DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTFLISISSIKDKNEDGRFTVFLNKSAKHLSLHIVPSQPGDSAVYFCAASARETSGSRLTFGEGTQLTVNP
> Alpha chain DNA:
GACCAGCAAGTTAAGCAAAATTCACCATCCCTGAGCGTCCAGGAAGGAAGAATTTCTATTCTGAACTGTGACTATACTAACAGCATGTTTGATTATTTCCTATGGTACAAAAAATACCCTGCTGAAGGTCCTACATTCCTGATATCTATAAGTTCCATTAAGGATAAAAATGAAGATGGAAGATTCACTGTCTTCTTAAACAAAAGTGCCAAGCACCTCTCTCTGCACATTGTGCCCTCCCAGCCTGGAGACTCTGCAGTGTACTTCTGTGCAGCAAGCGCTAGGGAAACCAGTGGCTCTAGGTTGACCTTTGGGGAAGGAACACAGCTCACAGTGAATCCTG
> Assembly contig CTACACCTCTAACGGT-1_contig_1
ATATGTAAAATGAAGGGTCTGTGGAAGGACATGAATAAAGCACAGGAGGTTGAAGTCAGATTTGCAGCTTTCTAGGCAGGAGACAAGACAATCTGCATCTTCACAGGAGGGATGGCCATGCTCCTGGGGGCATCAGTGCTGATTCTGTGGCTTCAGCCAGACTGGGTAAACAGTCAACAGAAGAATGATGACCAGCAAGTTAAGCAAAATTCACCATCCCTGAGCGTCCAGGAAGGAAGAATTTCTATTCTGAACTGTGACTATACTAACAGCATGTTTGATTATTTCCTATGGTACAAAAAATACCCTGCTGAAGGTCCTACATTCCTGATATCTATAAGTTCCATTAAGGATAAAAATGAAGATGGAAGATTCACTGTCTTCTTAAACAAAAGTGCCAAGCACCTCTCTCTGCACATTGTGCCCTCCCAGCCTGGAGACTCTGCAGTGTACTTCTGTGCAGCAAGCGCGAGAGAAACCAGTGGCTCTAGGTTGACCTTTGGGGAAGGAACACAGCTCACAGTGAATCCTGATATCCAGAACCCTGACCCTGCCGTGTACCAGCTGAGAGACT
WARNING: beta chain DNA sequence for cell CTACACCTCTAACGGT-1 in culture P15 not contained in original assembly
Beta AA: NAGVMQNPRHLVRRRGQEARLRCSPMKGHSHVYWYRQLPEEGLKFMVYLQKENIIDESGMPKERFSAEFPKEGPSILRIQQVVRGDSAAYFCASSPIGAYEQYFGPGTRLTVT
> Beta chain DNA:
AATGCCGGCGTCATGCAGAACCCAAGACACCTGGTCAGGAGGAGGGGACAGGAGGCAAGACTGAGATGCAGCCCAATGAAAGGACACAGTCATGTTTACTGGTATCGGCAGCTCCCAGAGGAAGGTCTGAAATTCATGGTTTATCTCCAGAAAGAAAATATCATAGATGAGTCAGGAATGCCAAAGGAACGATTTTCTGCTGAATTTCCCAAAGAGGGCCCCAGCATCCTGAGGATCCAGCAGGTAGTGCGAGGAGATTCGGCAGCTTATTTCTGTGCCAGCTCACCGATAGGAGCCTACGAGCAGTACTTCGGGCCGGGCACCAGGCTCACGGTCACAG
> Assembly contig CTACACCTCTAACGGT-1_contig_2
TCCCCGACGTGCTGCAGCAAGTGCCTTTGCCCTGCCTGTGGGCTCCCTCCATGGCCAACTCTGCTATGGACACCAGACTACTCTGCTGTGCGGTCATCTGTCTTCTGGGGGCAGGTCTCTCAAATGCCGGCGTCATGCAGAACCCAAGACACCTGGTCAGGAGGAGGGGACAGGAGGCAAGACTGAGATGCAGCCCAATGAAAGGACACAGTCATGTTTACTGGTATCGGCAGCTCCCAGAGGAAGGTCTGAAATTCATGGTTTATCTCCAGAAAGAAAATATCATAGATGAGTCAGGAATGCCAAAGGAACGATTTTCTGCTGAATTTCCCAAAGAGGGCCCCAGCATCCTGAGGATCCAGCAGGTAGTGCGAGGAGATTCGGCAGCTTATTTCTGTGCCAGCTCACCGATTGGCGCCTACGAGCAGTACTTCGGGCCGGGCACCAGGCTCACGGTCACAGAGGACCTGAAAAACGTGTTCCCACCCGAGGTCGCTGTGTTTGAGCCATCAGA
WARNING: alpha chain DNA sequence for cell GGTGCGTTCGGAAATA-1 in culture P10 not contained in original assembly
Alpha AA: AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMILVIRQEAYKQQNATENRFSVNFQKAAKSFSLKISDSQLGDAAMYFCAYRDSNYQLIWGAGTKLIIKP
> Alpha chain DNA:
GCTCAGACAGTCACTCAGTCTCAACCAGAGATGTCTGTGCAGGAGGCAGAGACCGTGACCCTGAGCTGCACATATGACACCAGTGAGAGTGATTATTATTTATTCTGGTACAAGCAGCCTCCCAGCAGGCAGATGATTCTCGTTATTCGCCAAGAAGCTTATAAGCAACAGAATGCAACAGAGAATCGTTTCTCTGTGAACTTCCAGAAAGCAGCCAAATCCTTCAGTCTCAAGATCTCAGACTCACAGCTGGGGGATGCCGCGATGTATTTCTGTGCTTATAGAGATAGCAACTATCAGTTAATCTGGGGCGCTGGGACCAAGCTAATTATAAAGCCAG
> Assembly contig GGTGCGTTCGGAAATA-1_contig_2
AGATCAGAAGAGGAGGCTTCTCACCCTGCAGCAGGGACCTGTGAGCATGGCATGCCCTGGCTTCCTGTGGGCACTTGTGATCTCCACCTGTCTTGAATTTAGCATGGCTCAGACAGTCACTCAGTCTCAACCAGAGATGTCTGTGCAGGAGGCAGAGACCGTGACCCTGAGCTGCACATATGACACCAGTGAGAGTGATTATTATTTATTCTGGTACAAGCAGCCTCCCAGCAGGCAGATGATTCTCGTTATTCGCCAAGAAGCTTATAAGCAACAGAATGCAACAGAGAATCGTTTCTCTGTGAACTTCCAGAAAGCAGCCAAATCCTTCAGTCTCAAGATCTCAGACTCACAGCTGGGGGATGCCGCGATGTATTTCTGTGCTTATCGGGATAGCAACTATCAGTTAATCTGGGGCGCTGGGACCAAGCTAATTATAAAGCCAGATATCCAGAACCCTGACCCTGCCGTGTACCAGCTGAGAGACT
WARNING: beta chain DNA sequence for cell GGTGCGTTCGGAAATA-1 in culture P10 not contained in original assembly
Beta AA: NAGVMQNPRHLVRRRGQEARLRCSPMKGHSHVYWYRQLPEEGLKFMVYLQKENIIDESGMPKERFSAEFPKEGPSILRIQQVVRGDSAAYFCASSPTGDSGNTIYFGEGSWLTVV
> Beta chain DNA:
AATGCCGGCGTCATGCAGAACCCAAGACACCTGGTCAGGAGGAGGGGACAGGAGGCAAGACTGAGATGCAGCCCAATGAAAGGACACAGTCATGTTTACTGGTATCGGCAGCTCCCAGAGGAAGGTCTGAAATTCATGGTTTATCTCCAGAAAGAAAATATCATAGATGAGTCAGGAATGCCAAAGGAACGATTTTCTGCTGAATTTCCCAAAGAGGGCCCCAGCATCCTGAGGATCCAGCAGGTAGTGCGAGGAGATTCGGCAGCTTATTTCTGTGCCAGCTCACCAACGGGTGACTCTGGAAACACCATATATTTTGGAGAGGGAAGTTGGCTCACTGTTGTAG
> Assembly contig GGTGCGTTCGGAAATA-1_contig_1
AGCTGTGAGGTCTGGTTCCCCGACGTGCTGCAGCAAGTGCCTTTGCCCTGCCTGTGGGCTCCCTCCATGGCCAACTCTGCTATGGACACCAGACTACTCTGCTGTGCGGTCATCTGTCTTCTGGGGGCAGGTCTCTCAAATGCCGGCGTCATGCAGAACCCAAGACACCTGGTCAGGAGGAGGGGACAGGAGGCAAGACTGAGATGCAGCCCAATGAAAGGACACAGTCATGTTTACTGGTATCGGCAGCTCCCAGAGGAAGGTCTGAAATTCATGGTTTATCTCCAGAAAGAAAATATCATAGATGAGTCAGGAATGCCAAAGGAACGATTTTCTGCTGAATTTCCCAAAGAGGGCCCCAGCATCCTGAGGATCCAGCAGGTAGTGCGAGGAGATTCGGCAGCTTATTTCTGTGCCAGCTCACCAACAGGAGACTCTGGAAACACCATATATTTTGGAGAGGGAAGTTGGCTCACTGTTGTAGAGGACCTGAACAAGGTGTTCCCACCCGAGGTCGCTGTGTTTGAGCCATCAGA
WARNING: alpha chain DNA sequence for cell GACTGCGAGCGCCTTG-1 in culture P10 not contained in original assembly
Alpha AA: AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMILVIRQEAYKQQNATENRFSVNFQKAAKSFSLKISDSQLGDAAMYFCAYRDSNYQLIWGAGTKLIIKP
> Alpha chain DNA:
GCTCAGACAGTCACTCAGTCTCAACCAGAGATGTCTGTGCAGGAGGCAGAGACCGTGACCCTGAGCTGCACATATGACACCAGTGAGAGTGATTATTATTTATTCTGGTACAAGCAGCCTCCCAGCAGGCAGATGATTCTCGTTATTCGCCAAGAAGCTTATAAGCAACAGAATGCAACAGAGAATCGTTTCTCTGTGAACTTCCAGAAAGCAGCCAAATCCTTCAGTCTCAAGATCTCAGACTCACAGCTGGGGGATGCCGCGATGTATTTCTGTGCTTATAGAGATAGCAACTATCAGTTAATCTGGGGCGCTGGGACCAAGCTAATTATAAAGCCAG
> Assembly contig GACTGCGAGCGCCTTG-1_contig_2
AGATCAGAAGAGGAGGCTTCTCACCCTGCAGCAGGGACCTGTGAGCATGGCATGCCCTGGCTTCCTGTGGGCACTTGTGATCTCCACCTGTCTTGAATTTAGCATGGCTCAGACAGTCACTCAGTCTCAACCAGAGATGTCTGTGCAGGAGGCAGAGACCGTGACCCTGAGCTGCACATATGACACCAGTGAGAGTGATTATTATTTATTCTGGTACAAGCAGCCTCCCAGCAGGCAGATGATTCTCGTTATTCGCCAAGAAGCTTATAAGCAACAGAATGCAACAGAGAATCGTTTCTCTGTGAACTTCCAGAAAGCAGCCAAATCCTTCAGTCTCAAGATCTCAGACTCACAGCTGGGGGATGCCGCGATGTATTTCTGTGCTTATCGGGATAGCAACTATCAGTTAATCTGGGGCGCTGGGACCAAGCTAATTATAAAGCCAGATATCCAGAACCCTGACCCTGCCGTGTACCAGCTGAGAGACT
WARNING: beta chain DNA sequence for cell GACTGCGAGCGCCTTG-1 in culture P10 not contained in original assembly
Beta AA: NAGVMQNPRHLVRRRGQEARLRCSPMKGHSHVYWYRQLPEEGLKFMVYLQKENIIDESGMPKERFSAEFPKEGPSILRIQQVVRGDSAAYFCASSPTGDSGNTIYFGEGSWLTVV
> Beta chain DNA:
AATGCCGGCGTCATGCAGAACCCAAGACACCTGGTCAGGAGGAGGGGACAGGAGGCAAGACTGAGATGCAGCCCAATGAAAGGACACAGTCATGTTTACTGGTATCGGCAGCTCCCAGAGGAAGGTCTGAAATTCATGGTTTATCTCCAGAAAGAAAATATCATAGATGAGTCAGGAATGCCAAAGGAACGATTTTCTGCTGAATTTCCCAAAGAGGGCCCCAGCATCCTGAGGATCCAGCAGGTAGTGCGAGGAGATTCGGCAGCTTATTTCTGTGCCAGCTCACCAACGGGTGACTCTGGAAACACCATATATTTTGGAGAGGGAAGTTGGCTCACTGTTGTAG
> Assembly contig GACTGCGAGCGCCTTG-1_contig_1
AGCTGTGAGGTCTGGTTCCCCGACGTGCTGCAGCAAGTGCCTTTGCCCTGCCTGTGGGCTCCCTCCATGGCCAACTCTGCTATGGACACCAGACTACTCTGCTGTGCGGTCATCTGTCTTCTGGGGGCAGGTCTCTCAAATGCCGGCGTCATGCAGAACCCAAGACACCTGGTCAGGAGGAGGGGACAGGAGGCAAGACTGAGATGCAGCCCAATGAAAGGACACAGTCATGTTTACTGGTATCGGCAGCTCCCAGAGGAAGGTCTGAAATTCATGGTTTATCTCCAGAAAGAAAATATCATAGATGAGTCAGGAATGCCAAAGGAACGATTTTCTGCTGAATTTCCCAAAGAGGGCCCCAGCATCCTGAGGATCCAGCAGGTAGTGCGAGGAGATTCGGCAGCTTATTTCTGTGCCAGCTCACCAACAGGAGACTCTGGAAACACCATATATTTTGGAGAGGGAAGTTGGCTCACTGTTGTAGAGGACCTGAACAAGGTGTTCCCACCCGAGGTCGCTGTGTTTGAGCCATCAGA
WARNING: alpha chain DNA sequence for cell CTGGTCTGTCGACTGC-1 in culture P10 not contained in original assembly
Alpha AA: AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMILVIRQEAYKQQNATENRFSVNFQKAAKSFSLKISDSQLGDAAMYFCAYRDSNYQLIWGAGTKLIIKP
> Alpha chain DNA:
GCTCAGACAGTCACTCAGTCTCAACCAGAGATGTCTGTGCAGGAGGCAGAGACCGTGACCCTGAGCTGCACATATGACACCAGTGAGAGTGATTATTATTTATTCTGGTACAAGCAGCCTCCCAGCAGGCAGATGATTCTCGTTATTCGCCAAGAAGCTTATAAGCAACAGAATGCAACAGAGAATCGTTTCTCTGTGAACTTCCAGAAAGCAGCCAAATCCTTCAGTCTCAAGATCTCAGACTCACAGCTGGGGGATGCCGCGATGTATTTCTGTGCTTATAGAGATAGCAACTATCAGTTAATCTGGGGCGCTGGGACCAAGCTAATTATAAAGCCAG
> Assembly contig CTGGTCTGTCGACTGC-1_contig_2
AGATCAGAAGAGGAGGCTTCTCACCCTGCAGCAGGGACCTGTGAGCATGGCATGCCCTGGCTTCCTGTGGGCACTTGTGATCTCCACCTGTCTTGAATTTAGCATGGCTCAGACAGTCACTCAGTCTCAACCAGAGATGTCTGTGCAGGAGGCAGAGACCGTGACCCTGAGCTGCACATATGACACCAGTGAGAGTGATTATTATTTATTCTGGTACAAGCAGCCTCCCAGCAGGCAGATGATTCTCGTTATTCGCCAAGAAGCTTATAAGCAACAGAATGCAACAGAGAATCGTTTCTCTGTGAACTTCCAGAAAGCAGCCAAATCCTTCAGTCTCAAGATCTCAGACTCACAGCTGGGGGATGCCGCGATGTATTTCTGTGCTTATCGGGATAGCAACTATCAGTTAATCTGGGGCGCTGGGACCAAGCTAATTATAAAGCCAGATATCCAGAACCCTGACCCTGCCGTGTACCAGCTGAGAGACT
WARNING: beta chain DNA sequence for cell CTGGTCTGTCGACTGC-1 in culture P10 not contained in original assembly
Beta AA: NAGVMQNPRHLVRRRGQEARLRCSPMKGHSHVYWYRQLPEEGLKFMVYLQKENIIDESGMPKERFSAEFPKEGPSILRIQQVVRGDSAAYFCASSPTGDSGNTIYFGEGSWLTVV
> Beta chain DNA:
AATGCCGGCGTCATGCAGAACCCAAGACACCTGGTCAGGAGGAGGGGACAGGAGGCAAGACTGAGATGCAGCCCAATGAAAGGACACAGTCATGTTTACTGGTATCGGCAGCTCCCAGAGGAAGGTCTGAAATTCATGGTTTATCTCCAGAAAGAAAATATCATAGATGAGTCAGGAATGCCAAAGGAACGATTTTCTGCTGAATTTCCCAAAGAGGGCCCCAGCATCCTGAGGATCCAGCAGGTAGTGCGAGGAGATTCGGCAGCTTATTTCTGTGCCAGCTCACCAACGGGTGACTCTGGAAACACCATATATTTTGGAGAGGGAAGTTGGCTCACTGTTGTAG
> Assembly contig CTGGTCTGTCGACTGC-1_contig_1
AGCTGTGAGGTCTGGTTCCCCGACGTGCTGCAGCAAGTGCCTTTGCCCTGCCTGTGGGCTCCCTCCATGGCCAACTCTGCTATGGACACCAGACTACTCTGCTGTGCGGTCATCTGTCTTCTGGGGGCAGGTCTCTCAAATGCCGGCGTCATGCAGAACCCAAGACACCTGGTCAGGAGGAGGGGACAGGAGGCAAGACTGAGATGCAGCCCAATGAAAGGACACAGTCATGTTTACTGGTATCGGCAGCTCCCAGAGGAAGGTCTGAAATTCATGGTTTATCTCCAGAAAGAAAATATCATAGATGAGTCAGGAATGCCAAAGGAACGATTTTCTGCTGAATTTCCCAAAGAGGGCCCCAGCATCCTGAGGATCCAGCAGGTAGTGCGAGGAGATTCGGCAGCTTATTTCTGTGCCAGCTCACCAACAGGAGACTCTGGAAACACCATATATTTTGGAGAGGGAAGTTGGCTCACTGTTGTAGAGGACCTGAACAAGGTGTTCCCACCCGAGGTCGCTGTGTTTGAGCCATCAGA
WARNING: alpha chain DNA sequence for cell GGTGTTATCAACGCTA-1 in culture P10 not contained in original assembly
Alpha AA: AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMILVIRQEAYKQQNATENRFSVNFQKAAKSFSLKISDSQLGDAAMYFCAYRDSNYQLIWGAGTKLIIKP
> Alpha chain DNA:
GCTCAGACAGTCACTCAGTCTCAACCAGAGATGTCTGTGCAGGAGGCAGAGACCGTGACCCTGAGCTGCACATATGACACCAGTGAGAGTGATTATTATTTATTCTGGTACAAGCAGCCTCCCAGCAGGCAGATGATTCTCGTTATTCGCCAAGAAGCTTATAAGCAACAGAATGCAACAGAGAATCGTTTCTCTGTGAACTTCCAGAAAGCAGCCAAATCCTTCAGTCTCAAGATCTCAGACTCACAGCTGGGGGATGCCGCGATGTATTTCTGTGCTTATAGAGATAGCAACTATCAGTTAATCTGGGGCGCTGGGACCAAGCTAATTATAAAGCCAG
> Assembly contig GGTGTTATCAACGCTA-1_contig_2
AGATCAGAAGAGGAGGCTTCTCACCCTGCAGCAGGGACCTGTGAGCATGGCATGCCCTGGCTTCCTGTGGGCACTTGTGATCTCCACCTGTCTTGAATTTAGCATGGCTCAGACAGTCACTCAGTCTCAACCAGAGATGTCTGTGCAGGAGGCAGAGACCGTGACCCTGAGCTGCACATATGACACCAGTGAGAGTGATTATTATTTATTCTGGTACAAGCAGCCTCCCAGCAGGCAGATGATTCTCGTTATTCGCCAAGAAGCTTATAAGCAACAGAATGCAACAGAGAATCGTTTCTCTGTGAACTTCCAGAAAGCAGCCAAATCCTTCAGTCTCAAGATCTCAGACTCACAGCTGGGGGATGCCGCGATGTATTTCTGTGCTTATCGGGATAGCAACTATCAGTTAATCTGGGGCGCTGGGACCAAGCTAATTATAAAGCCAGATATCCAGAACCCTGACCCTGCCGTGTACCAGCTGAGAGACT
WARNING: beta chain DNA sequence for cell GGTGTTATCAACGCTA-1 in culture P10 not contained in original assembly
Beta AA: NAGVMQNPRHLVRRRGQEARLRCSPMKGHSHVYWYRQLPEEGLKFMVYLQKENIIDESGMPKERFSAEFPKEGPSILRIQQVVRGDSAAYFCASSPTGDSGNTIYFGEGSWLTVV
> Beta chain DNA:

In [338]:
def find_all_start_offsets(dna_seq):
    return [i for i in range(len(dna_seq)) if dna_seq[i:i+3] == "ATG"]
    
def translate_longest_orf(dna_seq):
    longest_aa = None
    longest_offset = None
    longest_ragged_3p = None
    
    for start_offset in find_all_start_offsets(dna_seq):
        subseq = dna_seq[start_offset:]
        aa, ragged_nt = translate_dna(subseq)

        if longest_aa is None or len(aa) > len(longest_aa):
            longest_aa = aa
            longest_offset = start_offset
            longest_ragged_3p = ragged_nt
    return (longest_aa, longest_offset, longest_ragged_3p)

In [339]:
translate_longest_orf("AGATCAGAAGAGGAGGCTTCTCACCCTGCAGCAGGGACCTGTGAGCATGGCATGCCCTGGCTTCCTGTGGGCACTTGTGATCTCCACCTGTCTTGAATTTAGCATGGCTCAGACAGTCACTCAGTCTCAACCAGAGATGTCTGTGCAGGAGGCAGAGACCGTGACCCTGAGCTGCACATATGACACCAGTGAGAGTGATTATTATTTATTCTGGTACAAGCAGCCTCCCAGCAGGCAGATGATTCTCGTTATTCGCCAAGAAGCTTATAAGCAACAGAATGCAACAGAGAATCGTTTCTCTGTGAACTTCCAGAAAGCAGCCAAATCCTTCAGTCTCAAGATCTCAGACTCACAGCTGGGGGATGCCGCGATGTATTTCTGTGCTTATCGGGATAGCAACTATCAGTTAATCTGGGGCGCTGGGACCAAGCTAATTATAAAGCCAGATATCCAGAACCCTGACCCTGCCGTGTACCAGCTGAGAGACT")

('MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMILVIRQEAYKQQNATENRFSVNFQKAAKSFSLKISDSQLGDAAMYFCAYRDSNYQLIWGAGTKLIIKPDIQNPDPAVYQLRD',
 46,
 'T')

In [340]:
df_selected_full_seqs.Cell_Barcodes

0     [GTCACGGCAAGCCGTC-1, GTCAAGTTCCGCGTTT-1, GTCAA...
1     [TAAGTGCCATGTTCCC-1, AACTTTCAGTTGAGTA-1, CAACC...
2     [GTCTTCGCATCTCGCT-1, GTCCTCACAGGCGATA-1, TTGCG...
3     [GTACTTTCAGGACCCT-1, GTAACGTTCCTGCAGG-1, GGTGT...
4     [GTGCGGTAGCCACGTC-1, GCGCCAAAGTGTTGAA-1, GTTCA...
5                                  [AGTGTCAAGCTCAACT-1]
6     [GGACATTCATTCTCAT-1, GCTCCTAAGTCCGGTC-1, TGTGT...
7     [GTCGGGTTCAACACTG-1, TATTACCTCGGAGGTA-1, CTGTT...
8     [TACTCATAGATCGGGT-1, GTCACAATCGATAGAA-1, GACCA...
9     [GTCTTCGGTTAGTGGG-1, GTCGTAAAGTGGAGAA-1, GTACT...
10    [GGCTCGATCTTGTCAT-1, GACTGCGCATTGGGCC-1, GAATG...
11    [AACTCCCGTCGGGTCT-1, GGCGACTGTAGCGATG-1, GGCTG...
12    [GCGCCAAAGACTGGGT-1, GCAGCCATCCTCTAGC-1, CTTAG...
13    [GTAACTGGTGTGGCTC-1, GCTCTGTTCTTTACAC-1, GACAC...
14    [GTACTCCTCCAAGTAC-1, GGTGTTATCTTGTACT-1, GCTTG...
15             [TACCTTACACTGTCGG-1, ATCACGATCATCTGTT-1]
16    [GCTGGGTCATTGTGCA-1, GCTGCGATCATCGCTC-1, CCGGG...
17    [GGATTACTCATTTGGG-1, GGACAAGTCATCGATG-1, GGACA...
18             [ATCTGCCTCAGTGCAT-1, CTCACACAGGGAACGG-1]
19                                 [GGACAAGGTGCACGAA-1]
20    [GGGAATGGTAGCTAAA-1, CTTACCGAGCTCAACT-1, TCTGA...
21    [GGTGCGTTCGGAAATA-1, GGCTGGTGTTCGCTAA-1, GCTTC...
22    [ACACCGGGTTCGGCAC-1, AACCGCGAGTAACCCT-1, CGAGA...
23    [GTGCATATCCGATATG-1, GACGTTACAGGTCGTC-1, GACGC...
24    [GGGTTGCTCCGTCATC-1, GGAATAACATGTAGTC-1, GCATG...
25                                 [CGATGGCCATACCATG-1]
Name: Cell_Barcodes, dtype: object

In [341]:
from collections import Counter, defaultdict

extra_cols = defaultdict(list)
for _, row in df_selected_full_seqs.iterrows():
    alpha_leader_peptides = Counter()
    beta_leader_peptides = Counter()
    alpha_constant_peptides = Counter()
    beta_constant_peptides = Counter()
    
    ragged_alpha_3p_counts = Counter()
    ragged_beta_3p_counts = Counter()
    alpha_vdj_dna_counts = Counter()
    beta_vdj_dna_counts = Counter()
    
    aa_to_dna_counts = defaultdict(Counter)
    
    cell_barcodes = row.Cell_Barcodes
    if type(cell_barcodes) is str:
        cell_barcodes = cell_barcodes.split(";")

    alpha_contig_ids = row.Alpha_Contig_IDs
    if type(alpha_contig_ids) is str:
        alpha_contig_ids = alpha_contig_ids.split(";")

    beta_contig_ids = row.Beta_Contig_IDs
    if type(beta_contig_ids) is str:
        beta_contig_ids = beta_contig_ids.split(";")
    
    for (barcode, alpha_contig_id, beta_contig_id) in zip(cell_barcodes, alpha_contig_ids, beta_contig_ids):
        alpha_contig = peptide_num_to_contig_id_to_contig[row.Peptide].get(alpha_contig_id)
        beta_contig = peptide_num_to_contig_id_to_contig[row.Peptide].get(beta_contig_id)
        assert barcode == alpha_contig_id.split("_")[0] == beta_contig_id.split("_")[0]
        if not alpha_contig:
            print("No alpha sequence for %s!" % (barcode,))
        if not beta_contig:
            print("No beta sequence for %s!" % (barcode,))
            
        alpha_trans, alpha_trans_offset, alpha_trans_ragged_3p = translate_longest_orf(alpha_contig)
        beta_trans, beta_trans_offset, beta_trans_ragged_3p = translate_longest_orf(beta_contig)

        
        if row.VDJ_alpha_aa not in alpha_trans:
            print("WARNING: alpha chain for cell %s in culture %s not contained in translated assembly" % (
                barcode,
                row.Peptide
            ))
            print("Alpha AA:", row.VDJ_alpha_aa)
            print("Translation:", alpha_trans)
            
            print("> Alpha chain DNA:")
            print(row.VDJ_alpha_dna)
            print("> Assembly contig %s" % alpha_contig_id)
            print(alpha_contig)
        if row.VDJ_beta_aa not in beta_trans:
            print("WARNING: beta chain DNA sequence for cell %s in culture %s not contained in original assembly" % (
                barcode,
                row.Peptide
            ))
            print("Beta AA:", row.VDJ_beta_aa)
            print("Translation:", beta_trans)
            print("> Beta chain DNA:")
            print(row.VDJ_beta_dna)
            print("> Assembly contig %s" % beta_contig_id)
            print(beta_contig)
        
        alpha_contig_subseq = alpha_contig[alpha_trans_offset:]
        if alpha_dna_ragged_nt:
            alpha_contig_subseq = alpha_contig_subseq[:-len(alpha_dna_ragged_nt)]
        beta_contig_subseq = beta_contig[beta_trans_offset:]
        if beta_dna_ragged_nt:
            beta_contig_subseq = beta_contig_subseq[:-len(beta_dna_ragged_nt)]
        
        alpha_parts = alpha_trans.split(row.VDJ_alpha_aa)
        alpha_leader = alpha_parts[0]
        if len(alpha_parts) > 1:
            alpha_constant_fragment = alpha_parts[1]
        else:
            alpha_constant_fragment = ""
            
        
        beta_parts = beta_trans.split(row.VDJ_beta_aa)
        beta_leader = beta_parts[0]
        if len(beta_parts) > 1:
            beta_constant_fragment = beta_parts[1]
        else:
            beta_constant_fragment = ""
        
        
        alpha_leader_peptides[alpha_leader] += 1
        beta_leader_peptides[beta_leader] += 1
        alpha_constant_peptides[alpha_constant_fragment] += 1
        beta_constant_peptides[beta_constant_fragment] += 1
        
        alpha_leader_num_nt = 3 * len(alpha_leader)
        beta_leader_num_nt = 3 * len(beta_leader)
        alpha_vdj_num_nt = 3 * len(alpha_trans)
        assert alpha_vdj_num_nt % 3 == 0
        beta_vdj_num_nt = 3 * len(beta_trans)
        assert beta_vdj_num_nt % 3 == 0
        alpha_leader_dna = alpha_contig_subseq[:alpha_leader_num_nt]
        beta_leader_dna = beta_contig_subseq[:beta_leader_num_nt]
        
        # make sure leader sequence is in-frame and starts with start codon
        assert len(alpha_leader_dna) % 3 == 0, \
            "Leader peptide coding sequence in %s is length %d, not a multiple of 3" % (
                alpha_contig_id,
                len(alpha_leader_dna)    
            )
        assert len(beta_leader_dna) % 3 == 0, \
            "Leader peptide coding sequence in %s is length %d, not a multiple of 3" % (
                beta_contig_id,
                len(beta_leader_dna)    
            )
        
        
        assert alpha_leader_dna[:3] == "ATG", "Expected start codon"
        assert beta_leader_dna[:3] == "ATG", "Expected start codon"
        
        aa_to_dna_counts[alpha_leader][alpha_leader_dna] += 1
        aa_to_dna_counts[beta_leader][beta_leader_dna] += 1
        
        alpha_vdj_dna = alpha_contig_subseq[alpha_leader_num_nt:alpha_vdj_num_nt]
        
        beta_vdj_dna = beta_contig_subseq[beta_leader_num_nt:beta_vdj_num_nt]
        
        assert len(alpha_vdj_dna) % 3 == 0, \
            "VDJ alpha coding sequence in %s is length %d, not a multiple of 3" % (
                alpha_contig_id,
                len(alpha_vdj_dna)    
            )
        assert len(beta_vdj_dna) % 3 == 0, \
            "VDJ beta coding sequence in %s is length %d, not a multiple of 3" % (
                beta_contig_id,
                len(beta_vdj_dna)    
            )
        
        
        alpha_vdj_dna_counts[alpha_vdj_dna] += 1
        beta_vdj_dna_counts[beta_vdj_dna] += 1
        
        aa_to_dna_counts[row.VDJ_alpha_aa][alpha_vdj_dna] += 1
        aa_to_dna_counts[row.VDJ_beta_aa][beta_vdj_dna] += 1
        
        ragged_alpha_3p_counts[alpha_trans_ragged_3p] += 1
        ragged_beta_3p_counts[beta_trans_ragged_3p] += 1
        
    most_common_alpha_leader = alpha_leader_peptides.most_common(1)[0][0]
    extra_cols["assembly_alpha_leader_aa"].append(most_common_alpha_leader)
    
    most_common_beta_leader = beta_leader_peptides.most_common(1)[0][0]
    extra_cols["assembly_beta_leader_aa"].append(most_common_beta_leader)
    
    extra_cols["assembly_alpha_leader_dna"].append(
        aa_to_dna_counts[most_common_alpha_leader].most_common(1)[0][0])
    
    extra_cols["assembly_beta_leader_dna"].append(
        aa_to_dna_counts[most_common_beta_leader].most_common(1)[0][0])

    assembly_alpha_vdj_dna = alpha_vdj_dna_counts.most_common(1)[0][0]
    extra_cols["assembly_alpha_vdj_dna"].append(assembly_alpha_vdj_dna)
    assembly_beta_vdj_dna = beta_vdj_dna_counts.most_common(1)[0][0]
    extra_cols["assembly_beta_vdj_dna"].append(assembly_beta_vdj_dna)
    
    extra_cols["assembly_alpha_vdj_ragged_3p_dna"].append(ragged_alpha_3p_counts.most_common(1)[0][0])
    extra_cols["assembly_beta_vdj_ragged_3p_dna"].append(ragged_beta_3p_counts.most_common(1)[0][0])

    assembly_alpha_constant_fragment = alpha_constant_peptides.most_common(1)[0][0]
    extra_cols["assembly_alpha_constant_fragment"].append(assembly_alpha_constant_fragment)
    assembly_beta_constant_fragment = beta_constant_peptides.most_common(1)[0][0]
    extra_cols["assembly_beta_constant_fragment"].append(assembly_beta_constant_fragment)

    num_aa_assembly_alpha_constant_fragment = len(assembly_alpha_constant_fragment) 
    num_nt_assembly_alpha_constant_fragment = 3 * num_aa_assembly_alpha_constant_fragment

    num_aa_assembly_beta_constant_fragment = len(assembly_beta_constant_fragment) 
    num_nt_assembly_beta_constant_fragment = 3 * num_aa_assembly_beta_constant_fragment

    # the VDJ sequence has a few amino acids of the constant gene for both alpha and beta chains
    # so we need to split those off into their own dna sequence
    assembly_alpha_vdj_only_constant_fragment_dna = assembly_alpha_vdj_dna[-num_nt_assembly_alpha_constant_fragment:]
    assembly_alpha_vdj_without_constant_fragment_dna = assembly_alpha_vdj_dna[:-num_nt_assembly_alpha_constant_fragment]

    assembly_beta_vdj_without_constant_fragment_dna = assembly_beta_vdj_dna[:-num_nt_assembly_beta_constant_fragment]
    assembly_beta_vdj_only_constant_fragment_dna = assembly_beta_vdj_dna[-num_nt_assembly_beta_constant_fragment:]
    
    
    extra_cols["assembly_alpha_vdj_only_constant_fragment_dna"].append(assembly_alpha_vdj_only_constant_fragment_dna)
    extra_cols["assembly_alpha_vdj_without_constant_fragment_dna"].append(assembly_alpha_vdj_without_constant_fragment_dna)
    extra_cols["assembly_beta_vdj_only_constant_fragment_dna"].append(assembly_beta_vdj_only_constant_fragment_dna)
    extra_cols["assembly_beta_vdj_without_constant_fragment_dna"].append(assembly_beta_vdj_without_constant_fragment_dna)
    
    
for (col_name, col_values) in extra_cols.items():
    df_selected_full_seqs[col_name] = col_values

In [342]:
df_selected_full_seqs.assembly_alpha_vdj_ragged_3p_dna.value_counts()

assembly_alpha_vdj_ragged_3p_dna
T    26
Name: count, dtype: int64

In [343]:
from pyensembl import ensembl_grch38

In [344]:
def find_first_stop_codon(seq, offset=0):
    seq_slice = seq[offset:] if offset else seq
    for i in range(0, len(seq_slice), 3):
        codon = seq_slice[i:i+3]
        if codon in {"TAA", "TAG", "TGA"}:
            return offset + i
    return None

print(":: alpha constant ::")
trac = ensembl_grch38.genes_by_name("TRAC")[0]
trac_transcript = trac.transcripts[0]
trac_seq = trac_transcript.sequence 
trac_stop_codon_index = find_first_stop_codon(trac_seq, offset=2)
assert trac_stop_codon_index is not None 

trac_coding_seq = trac_seq[:trac_stop_codon_index + 3]
trbc1_3p_utr = trac_seq[trac_stop_codon_index + 3:]
print("--alpha seq-->")
print(trac_seq)
print("--alpha coding seq-->")
print(trac_coding_seq)

print(":: beta constant ::")
trbc_names = ["TRBC1", "TRBC2"]

trbc_name_to_gene = {name: ensembl_grch38.genes_by_name(name)[0] for name in trbc_names}
trbc_name_to_transcript = {name: gene.transcripts[0] for (name, gene) in trbc_name_to_gene.items()}
trbc_name_to_seq = {name: t.sequence for (name, t) in trbc_name_to_transcript.items()}
trbc_name_to_stop_codon_index = {name: find_first_stop_codon(seq, offset=2) for (name, seq) in trbc_name_to_seq.items()}
for (name, stop_codon_index) in trbc_name_to_stop_codon_index.items():
    print(name, stop_codon_index)
    assert stop_codon_index is not None 
trbc_name_to_coding_seq = {name: seq[:trbc_name_to_stop_codon_index[name] + 3] for (name, seq) in trbc_name_to_seq.items()}
trbc_name_to_3p_utr = {name:  seq[trbc_name_to_stop_codon_index[name] + 3:] for (name, seq) in trbc_name_to_seq.items()}

for name in trbc_names:
    
    print("--beta seq: %s-->" % name)
    print(trbc_name_to_seq[name])
    print("--beta coding seq: %s-->" % name)
    print(trbc_name_to_coding_seq[name])

:: alpha constant ::
--alpha seq-->
ATATCCAGAACCCTGACCCTGCCGTGTACCAGCTGAGAGACTCTAAATCCAGTGACAAGTCTGTCTGCCTATTCACCGATTTTGATTCTCAAACAAATGTGTCACAAAGTAAGGATTCTGATGTGTATATCACAGACAAAACTGTGCTAGACATGAGGTCTATGGACTTCAAGAGCAACAGTGCTGTGGCCTGGAGCAACAAATCTGACTTTGCATGTGCAAACGCCTTCAACAACAGCATTATTCCAGAAGACACCTTCTTCCCCAGCCCAGAAAGTTCCTGTGATGTCAAGCTGGTCGAGAAAAGCTTTGAAACAGATACGAACCTAAACTTTCAAAACCTGTCAGTGATTGGGTTCCGAATCCTCCTCCTGAAAGTGGCCGGGTTTAATCTGCTCATGACGCTGCGGCTGTGGTCCAGCTGAGATCTGCAAGATTGTAAGACAGCCTGTGCTCCCTCGCTCCTTCCTCTGCATTGCCCCTCTTCTCCCTCTCCAAACAGAGGGAACTCTCCTACCCCCAAGGAGGTGAAAGCTGCTACCACCTCTGTGCCCCCCCGGCAATGCCACCAACTGGATCCTACCCGAATTTATGATTAAGATTGCTGAAGAGCTGCCAAACACTGCTGCCACCCCCTCTGTTCCCTTATTGCTGCTTGTCACTGCCTGACATTCACGGCAGAGGCAAGGCTGCTGCAGCCTCCCCTGGCTGTGCACATTCCCTCCTGCTCCCCAGAGACTGCCTCCGCCATCCCACAGATGATGGATCTTCAGTGGGTTCTCTTGGGCTCTAGGTCCTGCAGAATGTTGTGAGGGGTTTATTTTTTTTTAATAGTGTTCATAAAGAAATACATAGTATTCTTCTTCTCAAGACGTGGGGGGAAATTATCTCATTATCGAGGCCCTGCTATGCTGTGTATCTGGGCGTGTTGTATGTCCTGCTGCCGATGCCTTCATTAAAATGATTTGGAAGAGCAGA
--alpha coding seq-->
ATATCCAGAACCCTGACCCTGCCGTGTACCAGCTGAGAGACTCTAAATCCAGTGACAAGTCTGTCTGCCTATTCACCGATTTTGATTCTCAAACAAATGTGTCACAAAGTAAGGATTCTGATGTGTATATCACAGACAAAACTGTGCTAGACATGAGGTCTATGGACTTCAAGAGCAACAGTGCTGTGGCCTGGAGCAACAAATCTGACTTTGCATGTGCAAACGCCTTCAACAACAGCATTATTCCAGAAGACACCTTCTTCCCCAGCCCAGAAAGTTCCTGTGATGTCAAGCTGGTCGAGAAAAGCTTTGAAACAGATACGAACCTAAACTTTCAAAACCTGTCAGTGATTGGGTTCCGAATCCTCCTCCTGAAAGTGGCCGGGTTTAATCTGCTCATGACGCTGCGGCTGTGGTCCAGCTGA
:: beta constant ::
TRBC1 530
TRBC2 536
--beta seq: TRBC1-->
AGGACCTGAACAAGGTGTTCCCACCCGAGGTCGCTGTGTTTGAGCCATCAGAAGCAGAGATCTCCCACACCCAAAAGGCCACACTGGTGTGCCTGGCCACAGGCTTCTTCCCTGACCACGTGGAGCTGAGCTGGTGGGTGAATGGGAAGGAGGTGCACAGTGGGGTCAGCACGGACCCGCAGCCCCTCAAGGAGCAGCCCGCCCTCAATGACTCCAGATACTGCCTGAGCAGCCGCCTGAGGGTCTCGGCCACCTTCTGGCAGAACCCCCGCAACCACTTCCGCTGTCAAGTCCAGTTCTACGGGCTCTCGGAGAATGACGAGTGGACCCAGGATAGGGCCAAACCCGTCACCCAGATCGTCAGCGCCGAGGCCTGGGGTAGAGCAGACTGTGGCTTTACCTCGGTGTCCTACCAGCAAGGGGTCCTGTCTGCCACCATCCTCTATGAGATCCTGCTAGGGAAGGCCACCCTGTATGCTGTGCTGGTCAGCGCCCTTGTGTTGATGGCCATGGTCAAGAGAAAGGATTTCTGAAGGCAGCCCTGGAAGTGGAGTTAGGAGCTTCTAACCCGTCATGGTTTCAATACACATTCTTCTTTTGCCAGCGCTTCTGAAGAGCTGCTCTCACCTCTCTGCATCCCAATAGATATCCCCCTATGTGCATGCACACCTGCACACTCACGGCTGAAATCTCCCTAACCCAGGGGGACCTTAGCATGCCTAAGTGACTAAACCAATAAAAATGTTCTGGTCTGGCCTGA
--beta coding seq: TRBC1-->
AGGACCTGAACAAGGTGTTCCCACCCGAGGTCGCTGTGTTTGAGCCATCAGAAGCAGAGATCTCCCACACCCAAAAGGCCACACTGGTGTGCCTGGCCACAGGCTTCTTCCCTGACCACGTGGAGCTGAGCTGGTGGGTGAATGGGAAGGAGGTGCACAGTGGGGTCAGCACGGACCCGCAGCCCCTCAAGGAGCAGCCCGCCCTCAATGACTCCAGATACTGCCTGAGCAGCCGCCTGAGGGTCTCGGCCACCTTCTGGCAGAACCCCCGCAACCACTTCCGCTGTCAAGTCCAGTTCTACGGGCTCTCGGAGAATGACGAGTGGACCCAGGATAGGGCCAAACCCGTCACCCAGATCGTCAGCGCCGAGGCCTGGGGTAGAGCAGACTGTGGCTTTACCTCGGTGTCCTACCAGCAAGGGGTCCTGTCTGCCACCATCCTCTATGAGATCCTGCTAGGGAAGGCCACCCTGTATGCTGTGCTGGTCAGCGCCCTTGTGTTGATGGCCATGGTCAAGAGAAAGGATTTCTGA
--beta seq: TRBC2-->
AGGACCTGAAAAACGTGTTCCCACCCAAGGTCGCTGTGTTTGAGCCATCAGAAGCAGAGATCTCCCACACCCAAAAGGCCACACTGGTGTGCCTGGCCACAGGCTTCTACCCCGACCACGTGGAGCTGAGCTGGTGGGTGAATGGGAAGGAGGTGCACAGTGGGGTCAGCACAGACCCGCAGCCCCTCAAGGAGCAGCCCGCCCTCAATGACTCCAGATACTGCCTGAGCAGCCGCCTGAGGGTCTCGGCCACCTTCTGGCAGAACCCCCGCAACCACTTCCGCTGTCAAGTCCAGTTCTACGGGCTCTCGGAGAATGACGAGTGGACCCAGGATAGGGCCAAACCTGTCACCCAGATCGTCAGCGCCGAGGCCTGGGGTAGAGCAGACTGTGGCTTCACCTCCGAGTCTTACCAGCAAGGGGTCCTGTCTGCCACCATCCTCTATGAGATCTTGCTAGGGAAGGCCACCTTGTATGCCGTGCTGGTCAGTGCCCTCGTGCTGATGGCCATGGTCAAGAGAAAGGATTCCAGAGGCTAGCTCCAAAACCATCCCAGGTCATTCTTCATCCTCACCCAGGATTCTCCTGTACCTGCTCCCAATCTGTGTTCCTAAAAGTGATTCTCACTCTGCTTCTCATCTCCTACTTACATGAATACTTCTCTCTTTTTTCTGTTTCCCTGAAGATTGAGCTCCCAACCCCCAAGTACGAAATAGGCTAAACCAATAAAAAATTGTGTGTTGGGCCTGGTTGCATTT
--beta coding seq: TRBC2-->
AGGACCTGAAAAACGTGTTCCCACCCAAGGTCGCTGTGTTTGAGCCATCAGAAGCAGAGATCTCCCACACCCAAAAGGCCACACTGGTGTGCCTGGCCACAGGCTTCTACCCCGACCACGTGGAGCTGAGCTGGTGGGTGAATGGGAAGGAGGTGCACAGTGGGGTCAGCACAGACCCGCAGCCCCTCAAGGAGCAGCCCGCCCTCAATGACTCCAGATACTGCCTGAGCAGCCGCCTGAGGGTCTCGGCCACCTTCTGGCAGAACCCCCGCAACCACTTCCGCTGTCAAGTCCAGTTCTACGGGCTCTCGGAGAATGACGAGTGGACCCAGGATAGGGCCAAACCTGTCACCCAGATCGTCAGCGCCGAGGCCTGGGGTAGAGCAGACTGTGGCTTCACCTCCGAGTCTTACCAGCAAGGGGTCCTGTCTGCCACCATCCTCTATGAGATCTTGCTAGGGAAGGCCACCTTGTATGCCGTGCTGGTCAGTGCCCTCGTGCTGATGGCCATGGTCAAGAGAAAGGATTCCAGAGGCTAG

In [345]:
translate_dna("G" + trbc_name_to_coding_seq["TRBC1"])

('EDLNKVFPPEVAVFEPSEAEISHTQKATLVCLATGFFPDHVELSWWVNGKEVHSGVSTDPQPLKEQPALNDSRYCLSSRLRVSATFWQNPRNHFRCQVQFYGLSENDEWTQDRAKPVTQIVSAEAWGRADCGFTSVSYQQGVLSATILYEILLGKATLYAVLVSALVLMAMVKRKDF',
 '')

In [346]:

df_selected_full_seqs["alpha_constant_dna_from_reference"] = [
    nt + trac_coding_seq
    for nt in df_selected_full_seqs.assembly_alpha_vdj_ragged_3p_dna.str.slice(0, 1)
]

df_selected_full_seqs["alpha_constant_dna"] = [
    constant_from_vdj_assembly + constant_from_reference[len(constant_from_vdj_assembly):]
    for (constant_from_vdj_assembly, constant_from_reference) in zip(
        df_selected_full_seqs.assembly_alpha_vdj_only_constant_fragment_dna,
        df_selected_full_seqs.alpha_constant_dna_from_reference)
    
]


df_selected_full_seqs["alpha_constant_translated"] = [
    translate_dna(dna)[0] for dna in df_selected_full_seqs["alpha_constant_dna"]
]
df_selected_full_seqs["beta_constant_dna_from_reference"] = [
    nt + trbc_name_to_coding_seq[trbc_gene_name] 
    for (nt, trbc_gene_name) in zip(
        df_selected_full_seqs.assembly_beta_vdj_ragged_3p_dna.str.slice(0, 1),
        df_selected_full_seqs.beta_c_gene)
        
]

df_selected_full_seqs["beta_constant_dna"] = [
    constant_from_vdj_assembly + constant_from_reference[len(constant_from_vdj_assembly):]
    for (constant_from_vdj_assembly, constant_from_reference) in zip(
        df_selected_full_seqs.assembly_beta_vdj_only_constant_fragment_dna,
        df_selected_full_seqs.beta_constant_dna_from_reference)
    
]


df_selected_full_seqs["beta_constant_translated"] = [
    translate_dna(dna)[0] for dna in df_selected_full_seqs["beta_constant_dna"]
]


df_selected_full_seqs["full_alpha_dna"] = df_selected_full_seqs[
    ["assembly_alpha_leader_dna", "assembly_alpha_vdj_without_constant_fragment_dna", "alpha_constant_dna"]].agg("".join, axis=1)

df_selected_full_seqs["full_alpha_translated"] = [
    translate_dna(dna)[0] for dna in df_selected_full_seqs["full_alpha_dna"]
]


df_selected_full_seqs["full_beta_dna"] = df_selected_full_seqs[
    ["assembly_beta_leader_dna", "assembly_beta_vdj_without_constant_fragment_dna", "beta_constant_dna"]].agg("".join, axis=1)


df_selected_full_seqs["full_beta_translated"] = [
    translate_dna(dna)[0] for dna in df_selected_full_seqs["full_beta_dna"]
]

# create versions of the coding sequence with stop codons so they can be concatenated

# make sure full sequences start with ATG, end with a stop codon, and are a multiple of 3 length

df_selected_full_seqs["full_alpha_dna_has_start_codon"] = \
    df_selected_full_seqs.full_alpha_dna.str.startswith("ATG")
df_selected_full_seqs["full_beta_dna_has_start_codon"] = \
    df_selected_full_seqs.full_beta_dna.str.startswith("ATG")

stop_codons = ("TGA", "TAG", "TAA")

df_selected_full_seqs["full_alpha_dna_ends_in_stop_codon"] = \
    df_selected_full_seqs.full_alpha_dna.str.endswith(stop_codons)
df_selected_full_seqs["full_beta_dna_ends_in_stop_codon"] = \
    df_selected_full_seqs.full_beta_dna.str.endswith(stop_codons)

df_selected_full_seqs["full_alpha_dna_frame"] = \
    df_selected_full_seqs.full_alpha_dna.str.len() % 3
df_selected_full_seqs["full_beta_dna_frame"] = \
    df_selected_full_seqs.full_beta_dna.str.len() % 3 

df_selected_full_seqs["full_alpha_dna_without_last_codon"] = \
    df_selected_full_seqs.full_alpha_dna.str.slice(0, -3)
df_selected_full_seqs["full_alpha_without_last_codon_translated"] = [translate_dna(s)[0] for s in df_selected_full_seqs.full_alpha_dna_without_last_codon]

df_selected_full_seqs["full_beta_dna_without_last_codon"] = df_selected_full_seqs.full_beta_dna.str.slice(0, -3)
df_selected_full_seqs["full_beta_without_last_codon_translated"] = [translate_dna(s)[0] for s in df_selected_full_seqs.full_beta_dna_without_last_codon]
# concatenate beta : linker : alpha chains
T2A_linker = "AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGGAAAATCCCGGGCCG"
df_selected_full_seqs["T2A_linker"] = T2A_linker
df_selected_full_seqs["T2A_linker_translated"] = translate_dna(T2A_linker)[0]



df_selected_full_seqs["single_chain_full_alpha_and_beta_with_linker"] = df_selected_full_seqs[
    ["full_beta_dna_without_last_codon", "T2A_linker", "full_alpha_dna"]].agg("".join, axis=1)

df_selected_full_seqs["single_chain_full_alpha_and_beta_with_linker_translated"] = [
    translate_dna(dna)[0] for dna in df_selected_full_seqs.single_chain_full_alpha_and_beta_with_linker
]
df_selected_full_seqs

,CDR3_alpha,CDR3_beta,Peptide,VDJ_alpha_beta_aa,VDJ_alpha_aa,VDJ_beta_aa,Cell_Count,Cell_Barcodes,Alpha_Contig_IDs,Beta_Contig_IDs,...,full_alpha_dna_frame,full_beta_dna_frame,full_alpha_dna_without_last_codon,full_alpha_without_last_codon_translated,full_beta_dna_without_last_codon,full_beta_without_last_codon_translated,T2A_linker,T2A_linker_translated,single_chain_full_alpha_and_beta_with_linker,single_chain_full_alpha_and_beta_with_linker_translated
0,CAAAYIDNLFF,CASSPDRVNTGELFF,P5,QKEVEQNSGPLSVPEGAIASLNCTYSDRGSQSFFWYRQYSGKSPEL...,QKEVEQNSGPLSVPEGAIASLNCTYSDRGSQSFFWYRQYSGKSPEL...,EAGVVQSPRYKIIEKKQPVAFWCNPISGHNTLYWYLQNLGQGPELL...,27,"[GTCACGGCAAGCCGTC-1, GTCAAGTTCCGCGTTT-1, GTCAA...","[GTCACGGCAAGCCGTC-1_contig_1, GTCAAGTTCCGCGTTT...","[GTCACGGCAAGCCGTC-1_contig_2, GTCAAGTTCCGCGTTT...",...,0,0,ATGATGAAATCCTTGAGAGTTTTACTAGTGATCCTGTGGCTTCAGT...,MMKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCT...,ATGGGTACCAGGCTCCTCTGCTGGGTGGCCTTCTGTCTCCTGGTGG...,MGTRLLCWVAFCLLVEELIEAGVVQSPRYKIIEKKQPVAFWCNPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGTACCAGGCTCCTCTGCTGGGTGGCCTTCTGTCTCCTGGTGG...,MGTRLLCWVAFCLLVEELIEAGVVQSPRYKIIEKKQPVAFWCNPIS...
1,CAADNAGNMLTF,CASSSEYLGEQFF,P15,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,ETGVTQSPTHLIKTRGQQVTLRCSSQSGHNTVSWYQQALGQGPQFI...,3,"[TAAGTGCCATGTTCCC-1, AACTTTCAGTTGAGTA-1, CAACC...","[TAAGTGCCATGTTCCC-1_contig_1, AACTTTCAGTTGAGTA...","[TAAGTGCCATGTTCCC-1_contig_2, AACTTTCAGTTGAGTA...",...,0,0,ATGGCCATGCTCCTGGGGGCATCAGTGCTGATTCTGTGGCTTCAGC...,MAMLLGASVLILWLQPDWVNSQQKNDDQQVKQNSPSLSVQEGRISI...,ATGGGCCCTGGGCTCCTCTGCTGGGTGCTGCTTTGTCTCCTGGGAG...,MGPGLLCWVLLCLLGAGSVETGVTQSPTHLIKTRGQQVTLRCSSQS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCCCTGGGCTCCTCTGCTGGGTGCTGCTTTGTCTCCTGGGAG...,MGPGLLCWVLLCLLGAGSVETGVTQSPTHLIKTRGQQVTLRCSSQS...
2,CAAIKNQFYF,CASSRAGGQETQYF,P11,GENVEQHPSTLSVQEGDSAVIKCTYSDSASNYFPWYKQELGKGPQL...,GENVEQHPSTLSVQEGDSAVIKCTYSDSASNYFPWYKQELGKGPQL...,GAGVSQTPSNKVTEKGKYVELRCDPISGHTALYWYRQSLGQGPEFL...,26,"[GTCTTCGCATCTCGCT-1, GTCCTCACAGGCGATA-1, TTGCG...","[GTCTTCGCATCTCGCT-1_contig_2, GTCCTCACAGGCGATA...","[GTCTTCGCATCTCGCT-1_contig_1, GTCCTCACAGGCGATA...",...,0,0,ATGACATCCATTCGAGCTGTATTTATATTCCTGTGGCTGCAGCTGG...,MTSIRAVFIFLWLQLDLVNGENVEQHPSTLSVQEGDSAVIKCTYSD...,ATGGGCACCAGGCTCCTCTGCTGGGCAGCCCTGTGCCTCCTGGGGG...,MGTRLLCWAALCLLGADHTGAGVSQTPSNKVTEKGKYVELRCDPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCACCAGGCTCCTCTGCTGGGCAGCCCTGTGCCTCCTGGGGG...,MGTRLLCWAALCLLGADHTGAGVSQTPSNKVTEKGKYVELRCDPIS...
3,CAASARETSGSRLTF,CASSPIGAYEQYF,P15,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,NAGVMQNPRHLVRRRGQEARLRCSPMKGHSHVYWYRQLPEEGLKFM...,44,"[GTACTTTCAGGACCCT-1, GTAACGTTCCTGCAGG-1, GGTGT...","[GTACTTTCAGGACCCT-1_contig_2, GTAACGTTCCTGCAGG...","[GTACTTTCAGGACCCT-1_contig_1, GTAACGTTCCTGCAGG...",...,0,0,ATGGCCATGCTCCTGGGGGCATCAGTGCTGATTCTGTGGCTTCAGC...,MAMLLGASVLILWLQPDWVNSQQKNDDQQVKQNSPSLSVQEGRISI...,ATGGCCAACTCTGCTATGGACACCAGAGTACTCTGCTGTGCGGTCA...,MANSAMDTRVLCCAVICLLGAGLSNAGVMQNPRHLVRRRGQEARLR...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGCCAACTCTGCTATGGACACCAGAGTACTCTGCTGTGCGGTCA...,MANSAMDTRVLCCAVICLLGAGLSNAGVMQNPRHLVRRRGQEARLR...
4,CAASAWEGQNFVF,CASSLLDQPQHF,P5,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,EAQVTQNPRYLITVTGKKLTVTCSQNMNHEYMSWYRQDPGLGLRQI...,12,"[GTGCGGTAGCCACGTC-1, GCGCCAAAGTGTTGAA-1, GTTCA...","[GTGCGGTAGCCACGTC-1_contig_2, GCGCCAAAGTGTTGAA...","[GTGCGGTAGCCACGTC-1_contig_1, GCGCCAAAGTGTTGAA...",...,0,0,ATGGCCATGCTCCTGGGGGCATCAGTGCTGATTCTGTGGCTTCAGC...,MAMLLGASVLILWLQPDWVNSQQKNDDQQVKQNSPSLSVQEGRISI...,ATGGGCCCCCAGCTCCTTGGCTATGTGGTCCTTTGCCTTCTAGGAG...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCCCCCAGCTCCTTGGCTATGTGGTCCTTTGCCTTCTAGGAG...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...
5,CAASDTGGFKTIF,CASSSRARGQETQYF,P15,GQQVMQIPQYQHVQEGEDFTTYCNSSTTLSNIQWYKQRPGGHPVFL...,GQQVMQIPQYQHVQEGEDFTTYCNSSTTLSNIQWYKQRPGGHPVFL...,GAGVSQSPSNKVTEKGKDVELRCDPISGHTALYWYRQSLGQGLEFL...,1,[AGTGTCAAGCTCAACT-1],[AGTGTCAAGCTCAACT-1_contig_2],[AGTGTCAAGCTCAACT-1_contig_1],...,0,0,ATGAAGAGGGAGAGGGAGATGCTACTCATCACATCAATGTTGGTCT...,MKREREMLLITSMLVLWMQLSQVNGQQVMQIPQYQHVQEGEDFTTY...,ATGGGCACCAGGCTCCTCTTCTGGGTGGCCTTCTGTCTCCTGGGGG...,MGTRLLFWVAFCLLGADHTGAGVSQSPSNKVTEKGKDVELRCDPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCACCAGGCTCCTCTTCTGGGTGGCCTTCTGTCTCCTGGGGG...,MGTRLLFWVAFCLLGADHTGAGVSQSPSNKVTEKGKDVELRCDPIS...
6,CAATPGSYNTDKLIF,CAISGGTGKGTQYF,P15,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,DAGITQSPRHKVTETGTPVTLRCHQTENHRYMYWYRQDPGHGLRLI...,7,"[GGACATTCATTCTCAT-1, GCTCCTAAGTCCGGTC-1, TGTGT...","[GGACATTCATTCTCAT-1_contig_1, GCTCCTAAGTCCGGTC...","[GGACATTCATTCTCAT-1_contig_2, GCTCCTAAGTCCGGTC...",...,0,0,ATGGCCATGCTCCTGGGGGCATCAGTGCTGATTCTGTGGCTTCAGC...,MAMLLGASVLILWLQPDWVNSQQKNDDQQVKQNSPSLSVQEGRISI...,ATGAGATCCTGGCCTGGACCTGAAATGGGCACAAGGTTGTTCTTCT...,MRSWPGPEMGTRLFFYVALCLLWTGHMDAGITQSPRHKVTETGTPV...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGAGATCCTGGCCTGGACCTGAAATGGGCACAAGGTTGTTCTTCT...,MRSWPGPEMGTRLFFYVALCLLWTGHMDAGITQSPRHKVTETGTPV...
7,CAETGFSDGQKLLF,CASSLDAEEGHYEQYF,P2,GEDVEQSLFLSVREGDSSVINCTYTDSSSTYLYWYKQEPGAGLQLL...,GEDVEQSLFLSVREGDSSVINCTYTDSSSTYLYWYKQEPGAGLQLL...,KAGVTQTPRYLIKTRGQQVTLSCSPISGHRSVSWYQQTPGQGLQFL...,7,"[GTCGGGTTCAACACTG-1, TATTACCTCGGAGGTA-1, CTGTT...","[GTCGGGTTCAACACTG-1_contig_2, TATTACCTCGGAGGTA...","[GTCGGGTTCAACACTG-1_contig_1, TATTACCTCGGAGGTA...",...,0,0,ATGAAGACATTTGCTGGATTTTCGTTCCTGTTTTTGTGGCTGCAGC...,MKTFAGFSFLFLWLQLDCMSRGEDVEQSLFLSVREGDSSVINCTYT...,ATGGGCTCCAGGCTGCTCTGTTGGGTGCTGCTTTGTCTCCTGGGAG...,MGSRLLCWVLLCLLGAGPVKAGVTQTPRYLIKTRGQQVTLSCSPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCTCCAGGCTGCTCTGTTGGGTGCTGCTTTGTCTCCTGGGAG...,MGSRLLCWVLLCLLGAGPVKAGVTQTPRYLIKTRGQQVTLSCSPIS...
8,CAGHSAGGTSYGKLTF,CASSLYAGAWSYTF,P11,GQQLNQSPQSMFIQEGEDVSMNCTSSSIFNTWLWYKQDPGEGPVLL...,GQQLNQSPQSMFIQEGEDVSMNCTSSSIFNTWLWYKQDPGEGPVLL...,EAQVTQNPRYLITVTGKKLTVTCSQNMNHEYMSWYRQDPGLGLRQI...,23,"[TACTCATAGATCGGGT-1, GTCACAATCGATAGAA-1, GACCA...","[TACTCATAGATCGGGT-1_contig_1, GTCACAATCGATAGAA...","[TACTCATAGATCGGGT-1_contig_2, GTCACAATCGATAGAA...",...,0,0,ATGCTCCTTGAACATTTATTAATAATCTTGTGGATGCAGCTGACAT...,MLLEHLLIILWMQLTWVSGQQLNQSPQSMFIQEGEDVSMNCTSSSI...,ATGGGCCCCCAGCTCCTTGGCTATGTGGTCCTTTGCCTTCTAGGAG...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCCCCCAGCTCCTTGGCTATGTGGTCCTTTGCCTTCTAGGAG...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...
9,CAGQPGSSNYKLTF,CASSVQGATEAFF,P12,GQQLNQSPQSMFIQEGEDVSMNCTSSSIFNTWLWYKQDPGEGPVLL...,GQQLNQSPQSMFIQEGEDVSMNCTSSSIFNTWLWYKQDPGEGPVLL...,EPEVTQTPSHQVTQMGQEVILRCVPISNHLYFYWYRQILGQKVEFL...,43,"[GTCTTCGGTTAGTGGG-1, GTCGTAAAGTGGAGAA-1, GTACT...","[GTCTTCGGTTAGTGGG-1_contig_1, GTCGTAAAGTGGAGAA...","[GTCTTCGGTTAGTGGG-1_contig_2, GTCGTAAAGTGGAGAA...",...,0,0,ATGCTCCTTGAACATTTATTAATAATCTTGTGGATGCAGCTGACAT...,MLLEHLLIILWMQLTWVSGQQLNQSPQSMFIQEGEDVSMNCTSSSI...,ATGGATACCTGGCTCGTATGCTGGGCAATTTTTAGTCTCTTGAAAG...,MDTWLVCWAIFSLLKAGLTEPEVTQTPSHQVTQMGQEVILRCVPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGATACCTGGCTCGTATGCTGGGCAATTTTTAGTCTCTTGAAAG...,MDTWLVCWAIFSLLKAGLTEPEVTQTPSHQVTQMGQEVILRCVPIS...
10,CALDIDSNYQLIW,CAISERVNEQFF,P15,SQKIEQNSEALNIQEGKTATLTCNYTNYSPAYLQWYRQDPGRGPVF...,SQKIEQNSEALNIQEGKTATLTCNYTNYSPAYLQWYRQDPGRGPVF...,DAGITQSPRHKVTETGTPVTLRCHQTENHRYMYWYRQDPGHGLRLI...,11,"[GGCTCGATCTTGTCAT-1, GACTGCGCATTGGGCC-1, GAATG...","[GGCTCGATCTTGTCAT-1_contig_2, GACTGCGCATTGGGCC...","[GGCTCGATCTTGTCAT-1_contig_1, GACTGCGCATTGGGCC...",...,0,0,ATGGCTTTTTGGCTGAGAAGCCTGGGTCTACATTTCAGGCCACATT...,MAFWLRSLGLHFRPHLGRRMESFLGGVLLILWLQVDWVKSQKIEQN...,ATGAGATCCTGGCCTGGACCTGAAATGGGCACAAGGTTGTTCTTCT...,MRSWPGPEMGTRLFFYVALCLLWTGHMDAGITQSPRHKVTETGTPV...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGAGATCCTGGCCTGGACCTGAAATGGGCACAAGGTTGTTCTTCT...,MRSWPGPEMGTRLFFYVALCLLWTGHMDAGITQSPRHKVTETGTPV...
11,CAMREGKGAGNMLTF,CASSRANSNQPQHF,P1,AQKITQTQPGMFVQEKEAVTLDCTYDTSDQSYGLFWYKQPSSGEMI...,AQKITQTQPGMFVQEKEAVTLDCTYDTSDQSYGLFWYKQPSSGEMI...,DTAVSQTPKYLVTQMGNDKSIKCEQNLGHDTMYWYKQDSKKFLKIM...,38,"[AACTCCCGTCGGGTCT-1, GGCGACTGTAGCGATG-1, GGCTG...","[AACTCCCGTCGGGTCT-1_contig_2, GGCGACTGTAGCGATG...","[AACTCCCGTCGGGTCT-1_contig_1, GGCGACTGTAGCGATG...",...,0,0,ATGTCACTTTCTAGCCTGCTGAAGGTGGTCACAGCTTCACTGTGGC...,MSLSSLLKVVTASLWLGPGIAQKITQTQPGMFVQEKEAVTLDCTYD...,ATGGGCTGCAGGCTCCTCTGCTGTGTGGTCTTCTGCCTCCTCCAAG...,MGCRLLCCVVFCLLQAGPLDTAVSQTPKYLVTQMGNDKSIKCEQNL...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCTGCAGGCTCCTCTGCTGTGTGGTCTTCTGCCTCCTCCAAG...,MGCRLLCCVVFCLLQAGPLDTAVSQTPKYLVTQMGNDKSIKCEQNL...
12,CASERGSARQLTF,CASSFGTEDTQYF,P15,QKEVEQNSGPLSVPEGAIASLNCTYSDRGSQSFFWYRQYSGKSPEL...,QKEVEQNSGPLSVPEGAIASLNCTYSDRGSQSFFWYRQYSGKSPEL...,EAGVAQSPRYKIIEKRQSVAFWCNPISGHATLYWYQQILGQGPKLL...,6,"[GCGCCAAAGACTGGGT-1, GCAGCCATCCTCTAGC-1, CTTAG...","[GCGCCAAAGACTGGGT-1_contig_1, GCAGCCATCCTCTAGC...","[GCGCCAAAGACTGGGT-1_contig_2, GCAGCCATCCTCTAGC...",...,0,0,ATGATGAAATCCTTGAGAGTTTTACTAGTGATCCTGTGGCTTCAGT...,MMKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCT...,ATGGGCACCAGGCTCCTCTGCTGGGCGGCCCTCTGTCTCCTGGGAG...,MGTRLLCWAALCLLGAELTEAGVAQSPRYKIIEKRQSVAFWCNPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCACCAGGCTCCTCTGCTGGGCGGCCCTCTGTCTCCTGGGAG...,MGTRLLCWAALCLLGAELTEAGVAQSPRYKIIEKRQSVAFWCNPIS...
13,CATDSGGYQKVTF,CASSEGGHTGELFF,P7,SQQGEEDPQALSIQEGENATMNCSYKTSINNLQWYRQNSGRGLVHL...,SQQGEEDPQALSIQEGENATMNCSYKTSINNLQWYRQNSGRGLVHL...,NAGVMQNPRHLVRRRGQEARLRCSPMKGHSHVYWYRQLPEEGLKFM...,41,"[GTAACTGGTGTGGCTC-1, GCTCTGTTCTTTACAC-1, GACAC...","[GTAACTGGTGTGGCTC-1_contig_2, GCTCTGTTCTTTACAC...","[GTAACTGGTGTGGCTC-1_contig_1, GCTCTGTTCTTTACAC...",...,0,0,ATGGAAACTCTCCTGGGAGTGTCTTTGGTGATTCTATGGCTTCAAC...,METLLGVSLVILWLQLARVNSQQGEEDPQALSIQEGENATMNCSYK...,ATGGCCAACTCTGCTATGGACACCAGAGTACTCTGCTGTGCGGTCA...,MANSAMDTRVLCCAVICLLGAGLSNAGVMQNPRHLVRRRGQEARLR...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGCCAACTCTGCTATGGACACCAGAGTACTCTGCTGTGCGGTCA...,MANSAMDTRVLCCAVICLLGAGLSNAGVMQNPRHLVRRRGQEARLR...
14,CATVSVGGFGNVLHC,CASSPDRVNTGELFF,P5,GENVEQHPSTLSVQEGDSAVIKCTYSDSASNYFPWYKQELGKGPQL...,GENVEQHPSTLSVQEGDSAVIKCTYSDSASNYFPWYKQELGKGPQL...,EAGVVQSPRYKIIEKKQPVAFWCNPISGHNTLYWYLQNLGQGPELL...,21,"[GTACTCCTCCAAGTAC-1, GGTGTTATCTTGTACT-1, GCTTG...","[GTACTCCTCCAAGTAC-1_contig_3, GGTGTTATCTTGTACT...","[GTACTCCTCCAAGTAC-1_contig_2, GGTGTTATCTTGTACT...",...,0,0,ATGACATCCATTCGAGCTGTATTTATATTCCTGTGGCTGCAGCTGG...,MTSIRAVFIFLWLQLDLVNGENVEQHPSTLSVQEGDSAVIKCTYSD...,ATGGGTACCAGGCTCCTCTGCTGGGTGGCCTTCTGTCTCCTGGTGG...,MGTRLLCWVAFCLLVEELIEAGVVQSPRYKIIEKKQPVAFWCNPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGTACCAGGCTCCTCTGCTGGGTGGCCTTCTGTCTCCTGGTGG...,MGTRLLCWVAFCLLVEELIEAGVVQSPRYKIIEKKQPVAFWCNPIS...
15,CAVGASNAGGTSYGKLTF,CASSLARYDEQYF,P15,AQSVTQPDIHITVSEGASLELRCNYSYGATPYLFWYVQSPGQGLQL...,AQSVTQPDIHITVSEGASLELRCNYSYGATPYLFWYVQSPGQGLQL...,DTGVSQNPRHKITKRGQNVTFRCDPISEHNRLYWYRQTLGQGPEFL...,2,"[TACCTTACACTGTCGG-1, ATCACGATCATCTGTT-1]","[TACCTTACACTGTCGG-1_contig_2, ATCACGATCATCTGTT...","[TACCTTACACTGTCGG-1_contig_1, ATCACGATCATCTGTT...",...,0,0,ATGCTCCTGGAGCTTATCCCACTGCTGGGGATACATTTTGTCCTGA...,MLLELIPLLGIHFVLRTARAQSVTQPDIHITVSEGASLELRCNYSY...,ATGGGCACCAGCCTCCTCTGCTGGATGGCCCTGTGTCTCCTGGGGG...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCACCAGCCTCCTCTGCTGGATGGCCCTGTGTCTCCTGGGGG...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...
16,CAVLYNTDKLIF,CASSSTRGYGANVLTF,P15,KQEVTQIPAALSVPEGENLVLNCSFTDSAIYNLQWFRQDPGKGLTS...,KQEVTQIPAALSVPEGENLVLNCSFTDSAIYNLQWFRQDPGKGLTS...,GAGVSQSPSNKVTEKGKDVELRCDPISGHTALYWYRQSLGQGLEFL...,3,"[GCTGGGTCATTGTGCA-1, GCTGCGATCATCGCTC-1, CCGGG...","[GCTGGGTCATTGTGCA-1_contig_2, GCTGCGATCATCGCTC...","[GCTGGGTCATTGTGCA-1_contig_1, GCTGCGATCATCGCTC...",...,0,0,ATGGAGACCCTCTTGGGCCTGCTTATCCTTTGGCTGCAGCTGCAAT...,METLLGLLILWLQLQWVSSKQEVTQIPAALSVPEGENLVLNCSFTD...,ATGGGCACCAGGCTCCTCTTCTGGGTGGCCTTCTGTCTCCTGGGGG...,MGTRLLFWVAFCLLGADHTGAGVSQSPSNKVTEKGKDVELRCDPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCACCAGGCTCCTCTTCTGGGTGGCCTTCTGTCTCCTGGGGG...,MGTRLLFWVAFCLLGADHTGAGVSQSPSNKVTEKGKDVELRCDPIS...
17,CAVRDGKAAGNKLTF,CASSLVTGAFDEQFF,P13,AQSVAQPEDQVNVAEGNPLTVKCTYSVSGNPYLFWYVQYPNRGLQF...,AQSVAQPEDQVNVAEGNPLTVKCTYSVSGNPYLFWYVQYPNRGLQF...,DTGVSQNPRHKITKRGQNVTFRCDPISEHNRLYWYRQTLGQGPEFL...,66,"[GGATTACTCATTTGGG-1, GGACAAGTCATCGATG-1, GGACA...","[GGATTACTCATTTGGG-1_contig_1, GGACAAGTCATCGATG...","[GGATTACTCATTTGGG-1_contig_2, GGACAAGTCATCGATG...",...,0,0,ATGGCCTCTGCACCCATCTCGATGCTTGCGATGCTCTTCACATTGA...,MASAPISMLAMLFTLSGLRAQSVAQPEDQVNVAEGNPLTVKCTYSV...,ATGGGCACCAGCCTCCTCTGCTGGATGGCCCTGTGTCTCCTGGGGG...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCACCAGCCTCCTCTGCTGGATGGCCCTGTGTCTCCTGGGGG...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...
18,CAVSVRRGGGSQGNLIF,CASSYSRGYEQYF,P15,AQSVTQLDSQVPVFEEAPVELRCNYSSSVSVYLFWYVQYPNQGLQL...,AQSVTQLDSQVPVFEEAPVELRCNYSSSVSVYLFWYVQYPNQGLQL...,NAGVTQTPKFQVLKTGQSMTLQCAQDMNHEYMSWYRQDPGMGLRLI...,2,"[ATCTGCCTCAGTGCAT-1, CTCACACAGGGAACGG-1]","[ATCTGCCTCAGTGCAT-1_contig_1, CTCACACAGGGAACGG...","[ATCTGCCTCAGTGCAT-1_contig_2, CTCACACAGGGAACGG...",...,0,0,ATGCTCCTGCTGCTCGTCCCAGCGTTCCAGGTGATTTTTACCCTGG...,MLLLLVPAFQVIFTLGGTRAQSVTQLDSQVPVFEEAPVELRCNYSS...,ATGAGCATCGGCCTCCTGTGCTGTGCAGCCTTGTCTCTCCTGTGGG...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGAGCATCGGCCTCCTGTGCTGTGCAGCCTTGTCTCTCCTGTGGG...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...
19,CAVVRGNDYKLSF,CASSPRQDSYEQYF,P3,EDQVTQSPEALRLQEGESSSLNCSYTVSGLRGLFWYRQDPGKGPEF...,EDQVTQSPEALRLQEGESSSLNCSYTVSGLRGLFWYRQDPGKGPEF...,NAGVMQNPRHLVRRRGQEARLRCSPMKGHSHVYWYRQLPEEGLKFM...,1,[GGACAAGGTGCACGAA-1],[GGACAAGGTGCACGAA-1_contig_2],[GGACAAGGTGCACGAA-1_contig_1],...,0,0,ATGGAGAAAATGTTGGAGTGTGCATTCATAGTCTTGTGGCTTCAGC...,MEKMLECAFIVLWLQLGWLSGEDQVTQSPEALRLQEGESSSLNCSY...,ATGGCCAACTCTGCTATGGACACCAGACTACTCTGCTGTGCGGTCA...,MANSAMDTRLLCCAVICLLGAGLSNAGVMQNPRHLVRRRGQEARLR...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGCCAACTCTGCTATGGACACCAGACTACTCTGCTGTGCGGTCA...,MANSAMDTRLLCCAVICLLGAGLSNAGVMQNPRHLVRRRGQEARLR...
20,CAVYNNARLMF,CASLGRGGLAKNIQYF,P12,GQQVMQIPQYQHVQEGEDFTTYCNSSTTLSNIQWYKQRPGGHPVFL...,GQQVMQIPQYQHVQEGEDFTTYCNSSTTLSNIQWYKQRPGGHPVFL...,EPEVTQTPSHQVTQMGQEVILRCVPISNHLYFYWYRQILGQKVEFL...,12,"[GGGAATGGTAGCTAAA-1, CTTACCGAGCTCAACT-1, TCTGA...","[GGGAATGGTAGCTAAA-1_contig_2, CTTACCGAGCTCAACT...","[GGGAATGGTAGCTAAA-1_contig_1, CTTACCGAGCTCAACT...",...,0,0,ATGAAGAGGGAGAGGGAGATGCTACTCATCACATCAATGTTGGTCT...,MKREREMLLITSMLVLWMQLSQVNGQQVMQIPQYQHVQEGEDFTTY...,ATGGATACCTGGCTCGTATGCTGGGCAATTTTTAGTCTCTTGAAAG...,MDTWLVCWAIFSLLKAGLTEPEVTQTPSHQVTQMGQEVILRCVPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGATACCTGGCTCGTATGCTGGGCAATTTTTAGTCTCTTGAAAG...,MDTWLVCWAIFSLLKAGLTEPEVTQTPSHQVTQMGQEVILRCVPIS...
21,CAYRDSNYQLIW,CASSPTGDSGNTIYF,P10,AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMI...,AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMI...,NAGVMQNPRHLVRRRGQEARLRCSPMKGHSHVYWYRQLPEEGLKFM...,41,"[GGTGCGTTCGGAAATA-1, GGCTGGTGTTCGCTAA-1, GCTTC...","[GGTGCGTTCGGAAATA-1_contig_2, GGCTGGTGTTCGCTAA...","[GGTGCGTTCGGAAATA-1_contig_1, GGCTGGTGTTCGCTAA...",...,0,0,ATGGCATGCCCTGGCTTCCTGTGGGCACTTGTGATCTCCACCTGTC...,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,ATGGCCAACTCTGCTATGGACACCAGACTACTCTGCTGTGCGGTCA...,MANSAMDTRLLCCAVICLLGAGLSNAGVMQNPRHLVRRRGQEARLR...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGCCAACTCTGCTATGGACACCAGACTACTCTGCTGTGCGGTCA...,MANSAMDTRLLCCAVICLLGAGLSNAGVMQNPRHLVRRRGQEARLR...
22,CAYRSAKGNDMRF,CASSFYFGQGYEQYF,P15,AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMI...,AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMI...,GAGVSQSPSNKVTEKGKDVELRCDPISGHTALYWYRQSLGQGLEFL...,3,"[ACACCGGGTTCGGCAC-1, AACCGCGAGTAACCCT-1, CGAGA...","[ACACCGGGTTCGGCAC-1_contig_2, AACCGCGAGTAACCCT...","[ACACCGGGTTCGGCAC-1_contig_1, AACCGCGAGTAACCCT...",...,0,0,ATGGCATGCCCTGGCTTCCTGTGGGCACTTGTGATCTCCACCTGTC...,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,ATGGGCACCAGGCTCCTCTTCTGGGTGGCCTTCTGTCTCCTGGGGG...,MGTRLLFWVAFCLLGADHTGAGVSQSPSNKVTEKGKDVELRCDPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCACCAGGCTCCTCTTCTGGGTGGCCTTCTGTCTCCTGGGGG...,MGTRLLFWVAFCLLGADHTGAGVSQSPSNKVTEKGKDVELRCDPIS...
23,CAYWVGGGGADGLTF,CASSLTPGGVKETQYF,P12,AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMI...,AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMI...,GAGVSQSPRYKVAKRGQDVALRCDPISGHVSLFWYQQALGQGPEFL...,33,"[GTGCATATCCGATATG-1, GACGTTACAGGTCGTC-1, GACGC...","[GTGCATATCCGATATG-1_contig_1, GACGTTACAGGTCGTC...","[GTGCATATCCGATATG-1_contig_2, GACGTTACAGGTCGTC...",...,0,0,ATGGCATGCCCTGGCTTCCTGTGGGCACTTGTGATCTCCACCTGTC...,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,ATGGGCACCAGGCTCCTCTGCTGGGTGGTCCTGGGTTTCCTAGGGA...,MGTRLLCWVVLGFLGTDHTGAGVSQSPRYKVAKRGQDVALRCDPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCACCAGGCTCCTCTGCTGGGTGGTCCTGGGTTTCCTAGGGA...,MGTRLLCWVVLGFLGTDHTGAGVSQSPRYKVAKRGQDVALRCDPIS...
24,CGADTNFGNEKLTF,CASSPGLATQYF,P7,SQELEQSPQSLIVQEGKNLTINCTSSKTLYGLYWYKQKYGEGLIFL...,SQELEQSPQSLIVQEGKNLTINCTSSKTLYGLYWYKQKYGEGLIFL...,EAGVAQSPRYKIIEKRQSVAFWCNPISGHATLYWYQQILGQGPKLL...,26,"[GGGTTGCTCCGTCATC-1, GGAATAACATGTAGTC-1, GCATG...","[GGGTTGCTCCGTCATC-1_contig_1, GGAATAACATGTAGTC...","[GGGTTGCTCCGTCATC-1_contig_2, GGAATAACATGTAGTC...",...,0,0,ATGGAGACTGTTCTGCAAGTACTCCTAGGGATATTGGGGTTCCAAG...,METVLQVLLGILGFQAAWVSSQELEQSPQSLIVQEGKNLTINCTSS...,ATGGGCACCAGGCTCCTCTGCTGGGCGGCCCTCTGTCTCCTGGGAG...,MGTRLLCWAALCLLGAELTEAGVAQSPRYKIIEKRQSVAFWCNPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCACCAGGCTCCTCTGCTGGGCGGCCCTCTGTCTCCTGGGAG...,MGTRLLCWAALCLLGAELTEAGVAQSPRYKIIEKRQSVAFWCNPIS...
25,CGTETGNNRLAF,CASSKKGTGTDTQYF,P15,QQPVQSPQAVILREGEDAVINCSSSKALYSVHWYRQKHGEAPVFLM...,QQPVQSPQAVILREGEDAVINCSSSKALYSVHWYRQKHGEAPVFLM...,GAGVSQSPRYKVAKRGQDVALRCDPISGHVSLFWYQQALGQGPEFL...,1,[CGATGGCCATACCATG-1],[CGATGGCCATACCATG-1_contig_3],[CGATGGCCATACCATG-1_contig_1],...,0,0,ATGGAGACTCTCCTGAAAGTGCTTTCAGGCACCTTGTTGTGGCAGT...,METLLKVLSGTLLWQLTWVRSQQPVQSPQAVILREGEDAVINCSSS...,ATGGGCACCAGGCTCCTCTGCTGGGTGGTCCTGGGTTTCCTAGGGA...,MGTRLLCWVVLGFLGTDHTGAGVSQSPRYKVAKRGQDVALRCDPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCACCAGGCTCCTCTGCTGGGTGGTCCTGGGTTTCCTAGGGA...,MGTRLLCWVVLGFLGTDHTGAGVSQSPRYKVAKRGQDVALRCDPIS...

In [347]:
df_selected_full_seqs.beta_constant_translated

0     EDLKNVFPPEVAVFEPSEAEISHTQKATLVCLATGFYPDHVELSWW...
1     EDLKNVFPPEVAVFEPSEAEISHTQKATLVCLATGFYPDHVELSWW...
2     EDLKNVFPPEVAVFEPSEAEISHTQKATLVCLATGFYPDHVELSWW...
3     EDLKNVFPPEVAVFEPSEAEISHTQKATLVCLATGFYPDHVELSWW...
4     EDLNKVFPPEVAVFEPSEAEISHTQKATLVCLATGFFPDHVELSWW...
5     EDLKNVFPPEVAVFEPSEAEISHTQKATLVCLATGFYPDHVELSWW...
6     EDLKNVFPPEVAVFEPSEAEISHTQKATLVCLATGFYPDHVELSWW...
7     EDLKNVFPPEVAVFEPSEAEISHTQKATLVCLATGFYPDHVELSWW...
8     EDLNKVFPPEVAVFEPSEAEISHTQKATLVCLATGFFPDHVELSWW...
9     EDLNKVFPPEVAVFEPSEAEISHTQKATLVCLATGFFPDHVELSWW...
10    EDLKNVFPPEVAVFEPSEAEISHTQKATLVCLATGFYPDHVELSWW...
11    EDLNKVFPPEVAVFEPSEAEISHTQKATLVCLATGFFPDHVELSWW...
12    EDLKNVFPPEVAVFEPSEAEISHTQKATLVCLATGFYPDHVELSWW...
13    EDLKNVFPPEVAVFEPSEAEISHTQKATLVCLATGFYPDHVELSWW...
14    EDLKNVFPPEVAVFEPSEAEISHTQKATLVCLATGFYPDHVELSWW...
15    EDLKNVFPPEVAVFEPSEAEISHTQKATLVCLATGFYPDHVELSWW...
16    EDLKNVFPPEVAVFEPSEAEISHTQKATLVCLATGFYPDHVELSWW...
17    EDLKNVFPPEVAVFEPSEAEISHTQKATLVCLATGFYPDHVELSWW...
18    EDLKNVFPPEVAVFEPSEAEISHTQKATLVCLATGFYPDHVELSWW...
19    EDLKNVFPPEVAVFEPSEAEISHTQKATLVCLATGFYPDHVELSWW...
20    EDLKNVFPPEVAVFEPSEAEISHTQKATLVCLATGFYPDHVELSWW...
21    EDLNKVFPPEVAVFEPSEAEISHTQKATLVCLATGFFPDHVELSWW...
22    EDLKNVFPPEVAVFEPSEAEISHTQKATLVCLATGFYPDHVELSWW...
23    EDLKNVFPPEVAVFEPSEAEISHTQKATLVCLATGFYPDHVELSWW...
24    EDLKNVFPPEVAVFEPSEAEISHTQKATLVCLATGFYPDHVELSWW...
25    EDLKNVFPPEVAVFEPSEAEISHTQKATLVCLATGFYPDHVELSWW...
Name: beta_constant_translated, dtype: object

In [348]:
df_selected_full_seqs.full_alpha_translated.str.len()

0     272
1     278
2     269
3     281
4     279
5     276
6     281
7     274
8     273
9     271
10    292
11    277
12    274
13    272
14    274
15    278
16    271
17    275
18    277
19    272
20    274
21    274
22    275
23    277
24    273
25    271
Name: full_alpha_translated, dtype: int64

In [349]:
df_selected_full_seqs.full_alpha_translated

0     MMKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCT...
1     MAMLLGASVLILWLQPDWVNSQQKNDDQQVKQNSPSLSVQEGRISI...
2     MTSIRAVFIFLWLQLDLVNGENVEQHPSTLSVQEGDSAVIKCTYSD...
3     MAMLLGASVLILWLQPDWVNSQQKNDDQQVKQNSPSLSVQEGRISI...
4     MAMLLGASVLILWLQPDWVNSQQKNDDQQVKQNSPSLSVQEGRISI...
5     MKREREMLLITSMLVLWMQLSQVNGQQVMQIPQYQHVQEGEDFTTY...
6     MAMLLGASVLILWLQPDWVNSQQKNDDQQVKQNSPSLSVQEGRISI...
7     MKTFAGFSFLFLWLQLDCMSRGEDVEQSLFLSVREGDSSVINCTYT...
8     MLLEHLLIILWMQLTWVSGQQLNQSPQSMFIQEGEDVSMNCTSSSI...
9     MLLEHLLIILWMQLTWVSGQQLNQSPQSMFIQEGEDVSMNCTSSSI...
10    MAFWLRSLGLHFRPHLGRRMESFLGGVLLILWLQVDWVKSQKIEQN...
11    MSLSSLLKVVTASLWLGPGIAQKITQTQPGMFVQEKEAVTLDCTYD...
12    MMKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCT...
13    METLLGVSLVILWLQLARVNSQQGEEDPQALSIQEGENATMNCSYK...
14    MTSIRAVFIFLWLQLDLVNGENVEQHPSTLSVQEGDSAVIKCTYSD...
15    MLLELIPLLGIHFVLRTARAQSVTQPDIHITVSEGASLELRCNYSY...
16    METLLGLLILWLQLQWVSSKQEVTQIPAALSVPEGENLVLNCSFTD...
17    MASAPISMLAMLFTLSGLRAQSVAQPEDQVNVAEGNPLTVKCTYSV...
18    MLLLLVPAFQVIFTLGGTRAQSVTQLDSQVPVFEEAPVELRCNYSS...
19    MEKMLECAFIVLWLQLGWLSGEDQVTQSPEALRLQEGESSSLNCSY...
20    MKREREMLLITSMLVLWMQLSQVNGQQVMQIPQYQHVQEGEDFTTY...
21    MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...
22    MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...
23    MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...
24    METVLQVLLGILGFQAAWVSSQELEQSPQSLIVQEGKNLTINCTSS...
25    METLLKVLSGTLLWQLTWVRSQQPVQSPQAVILREGEDAVINCSSS...
Name: full_alpha_translated, dtype: object

In [350]:
df_selected_full_seqs.assembly_beta_leader_aa

0             MGTRLLCWVAFCLLVEELI
1             MGPGLLCWVLLCLLGAGSV
2             MGTRLLCWAALCLLGADHT
3        MANSAMDTRVLCCAVICLLGAGLS
4             MGPQLLGYVVLCLLGAGPL
5             MGTRLLFWVAFCLLGADHT
6     MRSWPGPEMGTRLFFYVALCLLWTGHM
7             MGSRLLCWVLLCLLGAGPV
8             MGPQLLGYVVLCLLGAGPL
9             MDTWLVCWAIFSLLKAGLT
10    MRSWPGPEMGTRLFFYVALCLLWTGHM
11            MGCRLLCCVVFCLLQAGPL
12            MGTRLLCWAALCLLGAELT
13       MANSAMDTRVLCCAVICLLGAGLS
14            MGTRLLCWVAFCLLVEELI
15            MGTSLLCWMALCLLGADHA
16            MGTRLLFWVAFCLLGADHT
17            MGTSLLCWMALCLLGADHA
18            MSIGLLCCAALSLLWAGPV
19       MANSAMDTRLLCCAVICLLGAGLS
20            MDTWLVCWAIFSLLKAGLT
21       MANSAMDTRLLCCAVICLLGAGLS
22            MGTRLLFWVAFCLLGADHT
23            MGTRLLCWVVLGFLGTDHT
24            MGTRLLCWAALCLLGAELT
25            MGTRLLCWVVLGFLGTDHT
Name: assembly_beta_leader_aa, dtype: object

In [351]:
df_selected_full_seqs.full_beta_dna

0     ATGGGTACCAGGCTCCTCTGCTGGGTGGCCTTCTGTCTCCTGGTGG...
1     ATGGGCCCTGGGCTCCTCTGCTGGGTGCTGCTTTGTCTCCTGGGAG...
2     ATGGGCACCAGGCTCCTCTGCTGGGCAGCCCTGTGCCTCCTGGGGG...
3     ATGGCCAACTCTGCTATGGACACCAGAGTACTCTGCTGTGCGGTCA...
4     ATGGGCCCCCAGCTCCTTGGCTATGTGGTCCTTTGCCTTCTAGGAG...
5     ATGGGCACCAGGCTCCTCTTCTGGGTGGCCTTCTGTCTCCTGGGGG...
6     ATGAGATCCTGGCCTGGACCTGAAATGGGCACAAGGTTGTTCTTCT...
7     ATGGGCTCCAGGCTGCTCTGTTGGGTGCTGCTTTGTCTCCTGGGAG...
8     ATGGGCCCCCAGCTCCTTGGCTATGTGGTCCTTTGCCTTCTAGGAG...
9     ATGGATACCTGGCTCGTATGCTGGGCAATTTTTAGTCTCTTGAAAG...
10    ATGAGATCCTGGCCTGGACCTGAAATGGGCACAAGGTTGTTCTTCT...
11    ATGGGCTGCAGGCTCCTCTGCTGTGTGGTCTTCTGCCTCCTCCAAG...
12    ATGGGCACCAGGCTCCTCTGCTGGGCGGCCCTCTGTCTCCTGGGAG...
13    ATGGCCAACTCTGCTATGGACACCAGAGTACTCTGCTGTGCGGTCA...
14    ATGGGTACCAGGCTCCTCTGCTGGGTGGCCTTCTGTCTCCTGGTGG...
15    ATGGGCACCAGCCTCCTCTGCTGGATGGCCCTGTGTCTCCTGGGGG...
16    ATGGGCACCAGGCTCCTCTTCTGGGTGGCCTTCTGTCTCCTGGGGG...
17    ATGGGCACCAGCCTCCTCTGCTGGATGGCCCTGTGTCTCCTGGGGG...
18    ATGAGCATCGGCCTCCTGTGCTGTGCAGCCTTGTCTCTCCTGTGGG...
19    ATGGCCAACTCTGCTATGGACACCAGACTACTCTGCTGTGCGGTCA...
20    ATGGATACCTGGCTCGTATGCTGGGCAATTTTTAGTCTCTTGAAAG...
21    ATGGCCAACTCTGCTATGGACACCAGACTACTCTGCTGTGCGGTCA...
22    ATGGGCACCAGGCTCCTCTTCTGGGTGGCCTTCTGTCTCCTGGGGG...
23    ATGGGCACCAGGCTCCTCTGCTGGGTGGTCCTGGGTTTCCTAGGGA...
24    ATGGGCACCAGGCTCCTCTGCTGGGCGGCCCTCTGTCTCCTGGGAG...
25    ATGGGCACCAGGCTCCTCTGCTGGGTGGTCCTGGGTTTCCTAGGGA...
Name: full_beta_dna, dtype: object

In [352]:
df_selected_full_seqs.full_beta_translated

0     MGTRLLCWVAFCLLVEELIEAGVVQSPRYKIIEKKQPVAFWCNPIS...
1     MGPGLLCWVLLCLLGAGSVETGVTQSPTHLIKTRGQQVTLRCSSQS...
2     MGTRLLCWAALCLLGADHTGAGVSQTPSNKVTEKGKYVELRCDPIS...
3     MANSAMDTRVLCCAVICLLGAGLSNAGVMQNPRHLVRRRGQEARLR...
4     MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...
5     MGTRLLFWVAFCLLGADHTGAGVSQSPSNKVTEKGKDVELRCDPIS...
6     MRSWPGPEMGTRLFFYVALCLLWTGHMDAGITQSPRHKVTETGTPV...
7     MGSRLLCWVLLCLLGAGPVKAGVTQTPRYLIKTRGQQVTLSCSPIS...
8     MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...
9     MDTWLVCWAIFSLLKAGLTEPEVTQTPSHQVTQMGQEVILRCVPIS...
10    MRSWPGPEMGTRLFFYVALCLLWTGHMDAGITQSPRHKVTETGTPV...
11    MGCRLLCCVVFCLLQAGPLDTAVSQTPKYLVTQMGNDKSIKCEQNL...
12    MGTRLLCWAALCLLGAELTEAGVAQSPRYKIIEKRQSVAFWCNPIS...
13    MANSAMDTRVLCCAVICLLGAGLSNAGVMQNPRHLVRRRGQEARLR...
14    MGTRLLCWVAFCLLVEELIEAGVVQSPRYKIIEKKQPVAFWCNPIS...
15    MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...
16    MGTRLLFWVAFCLLGADHTGAGVSQSPSNKVTEKGKDVELRCDPIS...
17    MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...
18    MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...
19    MANSAMDTRLLCCAVICLLGAGLSNAGVMQNPRHLVRRRGQEARLR...
20    MDTWLVCWAIFSLLKAGLTEPEVTQTPSHQVTQMGQEVILRCVPIS...
21    MANSAMDTRLLCCAVICLLGAGLSNAGVMQNPRHLVRRRGQEARLR...
22    MGTRLLFWVAFCLLGADHTGAGVSQSPSNKVTEKGKDVELRCDPIS...
23    MGTRLLCWVVLGFLGTDHTGAGVSQSPRYKVAKRGQDVALRCDPIS...
24    MGTRLLCWAALCLLGAELTEAGVAQSPRYKIIEKRQSVAFWCNPIS...
25    MGTRLLCWVVLGFLGTDHTGAGVSQSPRYKVAKRGQDVALRCDPIS...
Name: full_beta_translated, dtype: object

In [353]:
df_selected_full_seqs.full_beta_translated.str.len()

0     313
1     310
2     312
3     316
4     307
5     313
6     319
7     313
8     309
9     309
10    317
11    309
12    311
13    317
14    313
15    311
16    314
17    313
18    310
19    317
20    314
21    316
22    313
23    314
24    310
25    313
Name: full_beta_translated, dtype: int64

In [354]:
df_selected_full_seqs.full_beta_dna.str.slice(-3, None)

0     TAG
1     TAG
2     TAG
3     TAG
4     TGA
5     TAG
6     TAG
7     TAG
8     TGA
9     TGA
10    TAG
11    TGA
12    TAG
13    TAG
14    TAG
15    TAG
16    TAG
17    TAG
18    TAG
19    TAG
20    TAG
21    TGA
22    TAG
23    TAG
24    TAG
25    TAG
Name: full_beta_dna, dtype: object

In [355]:
df_selected_full_seqs[["full_alpha_translated", "full_beta_translated", "single_chain_full_alpha_and_beta_with_linker_translated"]].map(len)

,full_alpha_translated,full_beta_translated,single_chain_full_alpha_and_beta_with_linker_translated
0,272,313,605
1,278,310,608
2,269,312,601
3,281,316,617
4,279,307,606
5,276,313,609
6,281,319,620
7,274,313,607
8,273,309,602
9,271,309,600
10,292,317,629
11,277,309,606
12,274,311,605
13,272,317,609
14,274,313,607
15,278,311,609
16,271,314,605
17,275,313,608
18,277,310,607
19,272,317,609
20,274,314,608
21,274,316,610
22,275,313,608
23,277,314,611
24,273,310,603
25,271,313,604

In [356]:
df_selected_full_seqs.full_beta_dna.str.len().map(lambda x: x%3)

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
Name: full_beta_dna, dtype: int64

In [357]:
for c in df_selected_full_seqs.columns:
    print(c)

CDR3_alpha
CDR3_beta
Peptide
VDJ_alpha_beta_aa
VDJ_alpha_aa
VDJ_beta_aa
Cell_Count
Cell_Barcodes
Alpha_Contig_IDs
Beta_Contig_IDs
Alpha_Reads_Mean
Beta_Reads_Mean
Alpha_UMIs_Mean
Beta_UMIs_Mean
VDJ_alpha_dna
VDJ_alpha_dna_ragged_3p_nt
VDJ_beta_dna
VDJ_beta_dna_ragged_3p_nt
CDR1_alpha
CDR2_alpha
alpha_v_gene
alpha_j_gene
alpha_c_gene
CDR1_beta
CDR2_beta
beta_v_gene
beta_d_gene
beta_j_gene
beta_c_gene
assembly_alpha_leader_aa
assembly_beta_leader_aa
assembly_alpha_leader_dna
assembly_beta_leader_dna
assembly_alpha_vdj_dna
assembly_beta_vdj_dna
assembly_alpha_vdj_ragged_3p_dna
assembly_beta_vdj_ragged_3p_dna
assembly_alpha_constant_fragment
assembly_beta_constant_fragment
assembly_alpha_vdj_only_constant_fragment_dna
assembly_alpha_vdj_without_constant_fragment_dna
assembly_beta_vdj_only_constant_fragment_dna
assembly_beta_vdj_without_constant_fragment_dna
alpha_constant_dna_from_reference
alpha_constant_dna
alpha_constant_translated
beta_constant_dna_from_reference
beta_constant_dna
beta_constant_translated
full_alpha_dna
full_alpha_translated
full_beta_dna
full_beta_translated
full_alpha_dna_has_start_codon
full_beta_dna_has_start_codon
full_alpha_dna_ends_in_stop_codon
full_beta_dna_ends_in_stop_codon
full_alpha_dna_frame
full_beta_dna_frame
full_alpha_dna_without_last_codon
full_alpha_without_last_codon_translated
full_beta_dna_without_last_codon
full_beta_without_last_codon_translated
T2A_linker
T2A_linker_translated
single_chain_full_alpha_and_beta_with_linker
single_chain_full_alpha_and_beta_with_linker_translated

In [358]:
for _, row in df_selected_full_seqs.iterrows():
    assert row.VDJ_alpha_aa in row.single_chain_full_alpha_and_beta_with_linker_translated
    assert row.VDJ_beta_aa in row.single_chain_full_alpha_and_beta_with_linker_translated

In [359]:
import pandas as pd
import numpy as np

df_selected_full_seqs = df_selected_full_seqs.map(
    lambda x: ";".join(map(str, x)) if isinstance(x, list) else x)

# sort by peptide number and cell count
df_selected_full_seqs["Peptide_Num"] = [
    num_sort_key(p) for p in list(df_selected_full_seqs.Peptide)
]

df_selected_full_seqs = df_selected_full_seqs.sort_values(by=["Peptide_Num", "Cell_Count"])
df_selected_full_seqs

,CDR3_alpha,CDR3_beta,Peptide,VDJ_alpha_beta_aa,VDJ_alpha_aa,VDJ_beta_aa,Cell_Count,Cell_Barcodes,Alpha_Contig_IDs,Beta_Contig_IDs,...,full_beta_dna_frame,full_alpha_dna_without_last_codon,full_alpha_without_last_codon_translated,full_beta_dna_without_last_codon,full_beta_without_last_codon_translated,T2A_linker,T2A_linker_translated,single_chain_full_alpha_and_beta_with_linker,single_chain_full_alpha_and_beta_with_linker_translated,Peptide_Num
11,CAMREGKGAGNMLTF,CASSRANSNQPQHF,P1,AQKITQTQPGMFVQEKEAVTLDCTYDTSDQSYGLFWYKQPSSGEMI...,AQKITQTQPGMFVQEKEAVTLDCTYDTSDQSYGLFWYKQPSSGEMI...,DTAVSQTPKYLVTQMGNDKSIKCEQNLGHDTMYWYKQDSKKFLKIM...,38,AACTCCCGTCGGGTCT-1;GGCGACTGTAGCGATG-1;GGCTGGTC...,AACTCCCGTCGGGTCT-1_contig_2;GGCGACTGTAGCGATG-1...,AACTCCCGTCGGGTCT-1_contig_1;GGCGACTGTAGCGATG-1...,...,0,ATGTCACTTTCTAGCCTGCTGAAGGTGGTCACAGCTTCACTGTGGC...,MSLSSLLKVVTASLWLGPGIAQKITQTQPGMFVQEKEAVTLDCTYD...,ATGGGCTGCAGGCTCCTCTGCTGTGTGGTCTTCTGCCTCCTCCAAG...,MGCRLLCCVVFCLLQAGPLDTAVSQTPKYLVTQMGNDKSIKCEQNL...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCTGCAGGCTCCTCTGCTGTGTGGTCTTCTGCCTCCTCCAAG...,MGCRLLCCVVFCLLQAGPLDTAVSQTPKYLVTQMGNDKSIKCEQNL...,1
7,CAETGFSDGQKLLF,CASSLDAEEGHYEQYF,P2,GEDVEQSLFLSVREGDSSVINCTYTDSSSTYLYWYKQEPGAGLQLL...,GEDVEQSLFLSVREGDSSVINCTYTDSSSTYLYWYKQEPGAGLQLL...,KAGVTQTPRYLIKTRGQQVTLSCSPISGHRSVSWYQQTPGQGLQFL...,7,GTCGGGTTCAACACTG-1;TATTACCTCGGAGGTA-1;CTGTTTAG...,GTCGGGTTCAACACTG-1_contig_2;TATTACCTCGGAGGTA-1...,GTCGGGTTCAACACTG-1_contig_1;TATTACCTCGGAGGTA-1...,...,0,ATGAAGACATTTGCTGGATTTTCGTTCCTGTTTTTGTGGCTGCAGC...,MKTFAGFSFLFLWLQLDCMSRGEDVEQSLFLSVREGDSSVINCTYT...,ATGGGCTCCAGGCTGCTCTGTTGGGTGCTGCTTTGTCTCCTGGGAG...,MGSRLLCWVLLCLLGAGPVKAGVTQTPRYLIKTRGQQVTLSCSPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCTCCAGGCTGCTCTGTTGGGTGCTGCTTTGTCTCCTGGGAG...,MGSRLLCWVLLCLLGAGPVKAGVTQTPRYLIKTRGQQVTLSCSPIS...,2
19,CAVVRGNDYKLSF,CASSPRQDSYEQYF,P3,EDQVTQSPEALRLQEGESSSLNCSYTVSGLRGLFWYRQDPGKGPEF...,EDQVTQSPEALRLQEGESSSLNCSYTVSGLRGLFWYRQDPGKGPEF...,NAGVMQNPRHLVRRRGQEARLRCSPMKGHSHVYWYRQLPEEGLKFM...,1,GGACAAGGTGCACGAA-1,GGACAAGGTGCACGAA-1_contig_2,GGACAAGGTGCACGAA-1_contig_1,...,0,ATGGAGAAAATGTTGGAGTGTGCATTCATAGTCTTGTGGCTTCAGC...,MEKMLECAFIVLWLQLGWLSGEDQVTQSPEALRLQEGESSSLNCSY...,ATGGCCAACTCTGCTATGGACACCAGACTACTCTGCTGTGCGGTCA...,MANSAMDTRLLCCAVICLLGAGLSNAGVMQNPRHLVRRRGQEARLR...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGCCAACTCTGCTATGGACACCAGACTACTCTGCTGTGCGGTCA...,MANSAMDTRLLCCAVICLLGAGLSNAGVMQNPRHLVRRRGQEARLR...,3
4,CAASAWEGQNFVF,CASSLLDQPQHF,P5,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,EAQVTQNPRYLITVTGKKLTVTCSQNMNHEYMSWYRQDPGLGLRQI...,12,GTGCGGTAGCCACGTC-1;GCGCCAAAGTGTTGAA-1;GTTCATTG...,GTGCGGTAGCCACGTC-1_contig_2;GCGCCAAAGTGTTGAA-1...,GTGCGGTAGCCACGTC-1_contig_1;GCGCCAAAGTGTTGAA-1...,...,0,ATGGCCATGCTCCTGGGGGCATCAGTGCTGATTCTGTGGCTTCAGC...,MAMLLGASVLILWLQPDWVNSQQKNDDQQVKQNSPSLSVQEGRISI...,ATGGGCCCCCAGCTCCTTGGCTATGTGGTCCTTTGCCTTCTAGGAG...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCCCCCAGCTCCTTGGCTATGTGGTCCTTTGCCTTCTAGGAG...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,5
14,CATVSVGGFGNVLHC,CASSPDRVNTGELFF,P5,GENVEQHPSTLSVQEGDSAVIKCTYSDSASNYFPWYKQELGKGPQL...,GENVEQHPSTLSVQEGDSAVIKCTYSDSASNYFPWYKQELGKGPQL...,EAGVVQSPRYKIIEKKQPVAFWCNPISGHNTLYWYLQNLGQGPELL...,21,GTACTCCTCCAAGTAC-1;GGTGTTATCTTGTACT-1;GCTTGAAC...,GTACTCCTCCAAGTAC-1_contig_3;GGTGTTATCTTGTACT-1...,GTACTCCTCCAAGTAC-1_contig_2;GGTGTTATCTTGTACT-1...,...,0,ATGACATCCATTCGAGCTGTATTTATATTCCTGTGGCTGCAGCTGG...,MTSIRAVFIFLWLQLDLVNGENVEQHPSTLSVQEGDSAVIKCTYSD...,ATGGGTACCAGGCTCCTCTGCTGGGTGGCCTTCTGTCTCCTGGTGG...,MGTRLLCWVAFCLLVEELIEAGVVQSPRYKIIEKKQPVAFWCNPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGTACCAGGCTCCTCTGCTGGGTGGCCTTCTGTCTCCTGGTGG...,MGTRLLCWVAFCLLVEELIEAGVVQSPRYKIIEKKQPVAFWCNPIS...,5
0,CAAAYIDNLFF,CASSPDRVNTGELFF,P5,QKEVEQNSGPLSVPEGAIASLNCTYSDRGSQSFFWYRQYSGKSPEL...,QKEVEQNSGPLSVPEGAIASLNCTYSDRGSQSFFWYRQYSGKSPEL...,EAGVVQSPRYKIIEKKQPVAFWCNPISGHNTLYWYLQNLGQGPELL...,27,GTCACGGCAAGCCGTC-1;GTCAAGTTCCGCGTTT-1;GTCAAGTG...,GTCACGGCAAGCCGTC-1_contig_1;GTCAAGTTCCGCGTTT-1...,GTCACGGCAAGCCGTC-1_contig_2;GTCAAGTTCCGCGTTT-1...,...,0,ATGATGAAATCCTTGAGAGTTTTACTAGTGATCCTGTGGCTTCAGT...,MMKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCT...,ATGGGTACCAGGCTCCTCTGCTGGGTGGCCTTCTGTCTCCTGGTGG...,MGTRLLCWVAFCLLVEELIEAGVVQSPRYKIIEKKQPVAFWCNPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGTACCAGGCTCCTCTGCTGGGTGGCCTTCTGTCTCCTGGTGG...,MGTRLLCWVAFCLLVEELIEAGVVQSPRYKIIEKKQPVAFWCNPIS...,5
24,CGADTNFGNEKLTF,CASSPGLATQYF,P7,SQELEQSPQSLIVQEGKNLTINCTSSKTLYGLYWYKQKYGEGLIFL...,SQELEQSPQSLIVQEGKNLTINCTSSKTLYGLYWYKQKYGEGLIFL...,EAGVAQSPRYKIIEKRQSVAFWCNPISGHATLYWYQQILGQGPKLL...,26,GGGTTGCTCCGTCATC-1;GGAATAACATGTAGTC-1;GCATGTAG...,GGGTTGCTCCGTCATC-1_contig_1;GGAATAACATGTAGTC-1...,GGGTTGCTCCGTCATC-1_contig_2;GGAATAACATGTAGTC-1...,...,0,ATGGAGACTGTTCTGCAAGTACTCCTAGGGATATTGGGGTTCCAAG...,METVLQVLLGILGFQAAWVSSQELEQSPQSLIVQEGKNLTINCTSS...,ATGGGCACCAGGCTCCTCTGCTGGGCGGCCCTCTGTCTCCTGGGAG...,MGTRLLCWAALCLLGAELTEAGVAQSPRYKIIEKRQSVAFWCNPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCACCAGGCTCCTCTGCTGGGCGGCCCTCTGTCTCCTGGGAG...,MGTRLLCWAALCLLGAELTEAGVAQSPRYKIIEKRQSVAFWCNPIS...,7
13,CATDSGGYQKVTF,CASSEGGHTGELFF,P7,SQQGEEDPQALSIQEGENATMNCSYKTSINNLQWYRQNSGRGLVHL...,SQQGEEDPQALSIQEGENATMNCSYKTSINNLQWYRQNSGRGLVHL...,NAGVMQNPRHLVRRRGQEARLRCSPMKGHSHVYWYRQLPEEGLKFM...,41,GTAACTGGTGTGGCTC-1;GCTCTGTTCTTTACAC-1;GACACGCT...,GTAACTGGTGTGGCTC-1_contig_2;GCTCTGTTCTTTACAC-1...,GTAACTGGTGTGGCTC-1_contig_1;GCTCTGTTCTTTACAC-1...,...,0,ATGGAAACTCTCCTGGGAGTGTCTTTGGTGATTCTATGGCTTCAAC...,METLLGVSLVILWLQLARVNSQQGEEDPQALSIQEGENATMNCSYK...,ATGGCCAACTCTGCTATGGACACCAGAGTACTCTGCTGTGCGGTCA...,MANSAMDTRVLCCAVICLLGAGLSNAGVMQNPRHLVRRRGQEARLR...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGCCAACTCTGCTATGGACACCAGAGTACTCTGCTGTGCGGTCA...,MANSAMDTRVLCCAVICLLGAGLSNAGVMQNPRHLVRRRGQEARLR...,7
21,CAYRDSNYQLIW,CASSPTGDSGNTIYF,P10,AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMI...,AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMI...,NAGVMQNPRHLVRRRGQEARLRCSPMKGHSHVYWYRQLPEEGLKFM...,41,GGTGCGTTCGGAAATA-1;GGCTGGTGTTCGCTAA-1;GCTTCCAC...,GGTGCGTTCGGAAATA-1_contig_2;GGCTGGTGTTCGCTAA-1...,GGTGCGTTCGGAAATA-1_contig_1;GGCTGGTGTTCGCTAA-1...,...,0,ATGGCATGCCCTGGCTTCCTGTGGGCACTTGTGATCTCCACCTGTC...,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,ATGGCCAACTCTGCTATGGACACCAGACTACTCTGCTGTGCGGTCA...,MANSAMDTRLLCCAVICLLGAGLSNAGVMQNPRHLVRRRGQEARLR...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGCCAACTCTGCTATGGACACCAGACTACTCTGCTGTGCGGTCA...,MANSAMDTRLLCCAVICLLGAGLSNAGVMQNPRHLVRRRGQEARLR...,10
8,CAGHSAGGTSYGKLTF,CASSLYAGAWSYTF,P11,GQQLNQSPQSMFIQEGEDVSMNCTSSSIFNTWLWYKQDPGEGPVLL...,GQQLNQSPQSMFIQEGEDVSMNCTSSSIFNTWLWYKQDPGEGPVLL...,EAQVTQNPRYLITVTGKKLTVTCSQNMNHEYMSWYRQDPGLGLRQI...,23,TACTCATAGATCGGGT-1;GTCACAATCGATAGAA-1;GACCAATA...,TACTCATAGATCGGGT-1_contig_1;GTCACAATCGATAGAA-1...,TACTCATAGATCGGGT-1_contig_2;GTCACAATCGATAGAA-1...,...,0,ATGCTCCTTGAACATTTATTAATAATCTTGTGGATGCAGCTGACAT...,MLLEHLLIILWMQLTWVSGQQLNQSPQSMFIQEGEDVSMNCTSSSI...,ATGGGCCCCCAGCTCCTTGGCTATGTGGTCCTTTGCCTTCTAGGAG...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCCCCCAGCTCCTTGGCTATGTGGTCCTTTGCCTTCTAGGAG...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,11
2,CAAIKNQFYF,CASSRAGGQETQYF,P11,GENVEQHPSTLSVQEGDSAVIKCTYSDSASNYFPWYKQELGKGPQL...,GENVEQHPSTLSVQEGDSAVIKCTYSDSASNYFPWYKQELGKGPQL...,GAGVSQTPSNKVTEKGKYVELRCDPISGHTALYWYRQSLGQGPEFL...,26,GTCTTCGCATCTCGCT-1;GTCCTCACAGGCGATA-1;TTGCGTCA...,GTCTTCGCATCTCGCT-1_contig_2;GTCCTCACAGGCGATA-1...,GTCTTCGCATCTCGCT-1_contig_1;GTCCTCACAGGCGATA-1...,...,0,ATGACATCCATTCGAGCTGTATTTATATTCCTGTGGCTGCAGCTGG...,MTSIRAVFIFLWLQLDLVNGENVEQHPSTLSVQEGDSAVIKCTYSD...,ATGGGCACCAGGCTCCTCTGCTGGGCAGCCCTGTGCCTCCTGGGGG...,MGTRLLCWAALCLLGADHTGAGVSQTPSNKVTEKGKYVELRCDPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCACCAGGCTCCTCTGCTGGGCAGCCCTGTGCCTCCTGGGGG...,MGTRLLCWAALCLLGADHTGAGVSQTPSNKVTEKGKYVELRCDPIS...,11
20,CAVYNNARLMF,CASLGRGGLAKNIQYF,P12,GQQVMQIPQYQHVQEGEDFTTYCNSSTTLSNIQWYKQRPGGHPVFL...,GQQVMQIPQYQHVQEGEDFTTYCNSSTTLSNIQWYKQRPGGHPVFL...,EPEVTQTPSHQVTQMGQEVILRCVPISNHLYFYWYRQILGQKVEFL...,12,GGGAATGGTAGCTAAA-1;CTTACCGAGCTCAACT-1;TCTGAGAT...,GGGAATGGTAGCTAAA-1_contig_2;CTTACCGAGCTCAACT-1...,GGGAATGGTAGCTAAA-1_contig_1;CTTACCGAGCTCAACT-1...,...,0,ATGAAGAGGGAGAGGGAGATGCTACTCATCACATCAATGTTGGTCT...,MKREREMLLITSMLVLWMQLSQVNGQQVMQIPQYQHVQEGEDFTTY...,ATGGATACCTGGCTCGTATGCTGGGCAATTTTTAGTCTCTTGAAAG...,MDTWLVCWAIFSLLKAGLTEPEVTQTPSHQVTQMGQEVILRCVPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGATACCTGGCTCGTATGCTGGGCAATTTTTAGTCTCTTGAAAG...,MDTWLVCWAIFSLLKAGLTEPEVTQTPSHQVTQMGQEVILRCVPIS...,12
23,CAYWVGGGGADGLTF,CASSLTPGGVKETQYF,P12,AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMI...,AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMI...,GAGVSQSPRYKVAKRGQDVALRCDPISGHVSLFWYQQALGQGPEFL...,33,GTGCATATCCGATATG-1;GACGTTACAGGTCGTC-1;GACGCGTG...,GTGCATATCCGATATG-1_contig_1;GACGTTACAGGTCGTC-1...,GTGCATATCCGATATG-1_contig_2;GACGTTACAGGTCGTC-1...,...,0,ATGGCATGCCCTGGCTTCCTGTGGGCACTTGTGATCTCCACCTGTC...,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,ATGGGCACCAGGCTCCTCTGCTGGGTGGTCCTGGGTTTCCTAGGGA...,MGTRLLCWVVLGFLGTDHTGAGVSQSPRYKVAKRGQDVALRCDPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCACCAGGCTCCTCTGCTGGGTGGTCCTGGGTTTCCTAGGGA...,MGTRLLCWVVLGFLGTDHTGAGVSQSPRYKVAKRGQDVALRCDPIS...,12
9,CAGQPGSSNYKLTF,CASSVQGATEAFF,P12,GQQLNQSPQSMFIQEGEDVSMNCTSSSIFNTWLWYKQDPGEGPVLL...,GQQLNQSPQSMFIQEGEDVSMNCTSSSIFNTWLWYKQDPGEGPVLL...,EPEVTQTPSHQVTQMGQEVILRCVPISNHLYFYWYRQILGQKVEFL...,43,GTCTTCGGTTAGTGGG-1;GTCGTAAAGTGGAGAA-1;GTACTTTT...,GTCTTCGGTTAGTGGG-1_contig_1;GTCGTAAAGTGGAGAA-1...,GTCTTCGGTTAGTGGG-1_contig_2;GTCGTAAAGTGGAGAA-1...,...,0,ATGCTCCTTGAACATTTATTAATAATCTTGTGGATGCAGCTGACAT...,MLLEHLLIILWMQLTWVSGQQLNQSPQSMFIQEGEDVSMNCTSSSI...,ATGGATACCTGGCTCGTATGCTGGGCAATTTTTAGTCTCTTGAAAG...,MDTWLVCWAIFSLLKAGLTEPEVTQTPSHQVTQMGQEVILRCVPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGATACCTGGCTCGTATGCTGGGCAATTTTTAGTCTCTTGAAAG...,MDTWLVCWAIFSLLKAGLTEPEVTQTPSHQVTQMGQEVILRCVPIS...,12
17,CAVRDGKAAGNKLTF,CASSLVTGAFDEQFF,P13,AQSVAQPEDQVNVAEGNPLTVKCTYSVSGNPYLFWYVQYPNRGLQF...,AQSVAQPEDQVNVAEGNPLTVKCTYSVSGNPYLFWYVQYPNRGLQF...,DTGVSQNPRHKITKRGQNVTFRCDPISEHNRLYWYRQTLGQGPEFL...,66,GGATTACTCATTTGGG-1;GGACAAGTCATCGATG-1;GGACAAGG...,GGATTACTCATTTGGG-1_contig_1;GGACAAGTCATCGATG-1...,GGATTACTCATTTGGG-1_contig_2;GGACAAGTCATCGATG-1...,...,0,ATGGCCTCTGCACCCATCTCGATGCTTGCGATGCTCTTCACATTGA...,MASAPISMLAMLFTLSGLRAQSVAQPEDQVNVAEGNPLTVKCTYSV...,ATGGGCACCAGCCTCCTCTGCTGGATGGCCCTGTGTCTCCTGGGGG...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCACCAGCCTCCTCTGCTGGATGGCCCTGTGTCTCCTGGGGG...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,13
5,CAASDTGGFKTIF,CASSSRARGQETQYF,P15,GQQVMQIPQYQHVQEGEDFTTYCNSSTTLSNIQWYKQRPGGHPVFL...,GQQVMQIPQYQHVQEGEDFTTYCNSSTTLSNIQWYKQRPGGHPVFL...,GAGVSQSPSNKVTEKGKDVELRCDPISGHTALYWYRQSLGQGLEFL...,1,AGTGTCAAGCTCAACT-1,AGTGTCAAGCTCAACT-1_contig_2,AGTGTCAAGCTCAACT-1_contig_1,...,0,ATGAAGAGGGAGAGGGAGATGCTACTCATCACATCAATGTTGGTCT...,MKREREMLLITSMLVLWMQLSQVNGQQVMQIPQYQHVQEGEDFTTY...,ATGGGCACCAGGCTCCTCTTCTGGGTGGCCTTCTGTCTCCTGGGGG...,MGTRLLFWVAFCLLGADHTGAGVSQSPSNKVTEKGKDVELRCDPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCACCAGGCTCCTCTTCTGGGTGGCCTTCTGTCTCCTGGGGG...,MGTRLLFWVAFCLLGADHTGAGVSQSPSNKVTEKGKDVELRCDPIS...,15
25,CGTETGNNRLAF,CASSKKGTGTDTQYF,P15,QQPVQSPQAVILREGEDAVINCSSSKALYSVHWYRQKHGEAPVFLM...,QQPVQSPQAVILREGEDAVINCSSSKALYSVHWYRQKHGEAPVFLM...,GAGVSQSPRYKVAKRGQDVALRCDPISGHVSLFWYQQALGQGPEFL...,1,CGATGGCCATACCATG-1,CGATGGCCATACCATG-1_contig_3,CGATGGCCATACCATG-1_contig_1,...,0,ATGGAGACTCTCCTGAAAGTGCTTTCAGGCACCTTGTTGTGGCAGT...,METLLKVLSGTLLWQLTWVRSQQPVQSPQAVILREGEDAVINCSSS...,ATGGGCACCAGGCTCCTCTGCTGGGTGGTCCTGGGTTTCCTAGGGA...,MGTRLLCWVVLGFLGTDHTGAGVSQSPRYKVAKRGQDVALRCDPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCACCAGGCTCCTCTGCTGGGTGGTCCTGGGTTTCCTAGGGA...,MGTRLLCWVVLGFLGTDHTGAGVSQSPRYKVAKRGQDVALRCDPIS...,15
15,CAVGASNAGGTSYGKLTF,CASSLARYDEQYF,P15,AQSVTQPDIHITVSEGASLELRCNYSYGATPYLFWYVQSPGQGLQL...,AQSVTQPDIHITVSEGASLELRCNYSYGATPYLFWYVQSPGQGLQL...,DTGVSQNPRHKITKRGQNVTFRCDPISEHNRLYWYRQTLGQGPEFL...,2,TACCTTACACTGTCGG-1;ATCACGATCATCTGTT-1,TACCTTACACTGTCGG-1_contig_2;ATCACGATCATCTGTT-1...,TACCTTACACTGTCGG-1_contig_1;ATCACGATCATCTGTT-1...,...,0,ATGCTCCTGGAGCTTATCCCACTGCTGGGGATACATTTTGTCCTGA...,MLLELIPLLGIHFVLRTARAQSVTQPDIHITVSEGASLELRCNYSY...,ATGGGCACCAGCCTCCTCTGCTGGATGGCCCTGTGTCTCCTGGGGG...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCACCAGCCTCCTCTGCTGGATGGCCCTGTGTCTCCTGGGGG...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,15
18,CAVSVRRGGGSQGNLIF,CASSYSRGYEQYF,P15,AQSVTQLDSQVPVFEEAPVELRCNYSSSVSVYLFWYVQYPNQGLQL...,AQSVTQLDSQVPVFEEAPVELRCNYSSSVSVYLFWYVQYPNQGLQL...,NAGVTQTPKFQVLKTGQSMTLQCAQDMNHEYMSWYRQDPGMGLRLI...,2,ATCTGCCTCAGTGCAT-1;CTCACACAGGGAACGG-1,ATCTGCCTCAGTGCAT-1_contig_1;CTCACACAGGGAACGG-1...,ATCTGCCTCAGTGCAT-1_contig_2;CTCACACAGGGAACGG-1...,...,0,ATGCTCCTGCTGCTCGTCCCAGCGTTCCAGGTGATTTTTACCCTGG...,MLLLLVPAFQVIFTLGGTRAQSVTQLDSQVPVFEEAPVELRCNYSS...,ATGAGCATCGGCCTCCTGTGCTGTGCAGCCTTGTCTCTCCTGTGGG...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGAGCATCGGCCTCCTGTGCTGTGCAGCCTTGTCTCTCCTGTGGG...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...,15
1,CAADNAGNMLTF,CASSSEYLGEQFF,P15,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,ETGVTQSPTHLIKTRGQQVTLRCSSQSGHNTVSWYQQALGQGPQFI...,3,TAAGTGCCATGTTCCC-1;AACTTTCAGTTGAGTA-1;CAACCAAT...,TAAGTGCCATGTTCCC-1_contig_1;AACTTTCAGTTGAGTA-1...,TAAGTGCCATGTTCCC-1_contig_2;AACTTTCAGTTGAGTA-1...,...,0,ATGGCCATGCTCCTGGGGGCATCAGTGCTGATTCTGTGGCTTCAGC...,MAMLLGASVLILWLQPDWVNSQQKNDDQQVKQNSPSLSVQEGRISI...,ATGGGCCCTGGGCTCCTCTGCTGGGTGCTGCTTTGTCTCCTGGGAG...,MGPGLLCWVLLCLLGAGSVETGVTQSPTHLIKTRGQQVTLRCSSQS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCCCTGGGCTCCTCTGCTGGGTGCTGCTTTGTCTCCTGGGAG...,MGPGLLCWVLLCLLGAGSVETGVTQSPTHLIKTRGQQVTLRCSSQS...,15
16,CAVLYNTDKLIF,CASSSTRGYGANVLTF,P15,KQEVTQIPAALSVPEGENLVLNCSFTDSAIYNLQWFRQDPGKGLTS...,KQEVTQIPAALSVPEGENLVLNCSFTDSAIYNLQWFRQDPGKGLTS...,GAGVSQSPSNKVTEKGKDVELRCDPISGHTALYWYRQSLGQGLEFL...,3,GCTGGGTCATTGTGCA-1;GCTGCGATCATCGCTC-1;CCGGGATG...,GCTGGGTCATTGTGCA-1_contig_2;GCTGCGATCATCGCTC-1...,GCTGGGTCATTGTGCA-1_contig_1;GCTGCGATCATCGCTC-1...,...,0,ATGGAGACCCTCTTGGGCCTGCTTATCCTTTGGCTGCAGCTGCAAT...,METLLGLLILWLQLQWVSSKQEVTQIPAALSVPEGENLVLNCSFTD...,ATGGGCACCAGGCTCCTCTTCTGGGTGGCCTTCTGTCTCCTGGGGG...,MGTRLLFWVAFCLLGADHTGAGVSQSPSNKVTEKGKDVELRCDPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCACCAGGCTCCTCTTCTGGGTGGCCTTCTGTCTCCTGGGGG...,MGTRLLFWVAFCLLGADHTGAGVSQSPSNKVTEKGKDVELRCDPIS...,15
22,CAYRSAKGNDMRF,CASSFYFGQGYEQYF,P15,AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMI...,AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMI...,GAGVSQSPSNKVTEKGKDVELRCDPISGHTALYWYRQSLGQGLEFL...,3,ACACCGGGTTCGGCAC-1;AACCGCGAGTAACCCT-1;CGAGAAGA...,ACACCGGGTTCGGCAC-1_contig_2;AACCGCGAGTAACCCT-1...,ACACCGGGTTCGGCAC-1_contig_1;AACCGCGAGTAACCCT-1...,...,0,ATGGCATGCCCTGGCTTCCTGTGGGCACTTGTGATCTCCACCTGTC...,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,ATGGGCACCAGGCTCCTCTTCTGGGTGGCCTTCTGTCTCCTGGGGG...,MGTRLLFWVAFCLLGADHTGAGVSQSPSNKVTEKGKDVELRCDPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCACCAGGCTCCTCTTCTGGGTGGCCTTCTGTCTCCTGGGGG...,MGTRLLFWVAFCLLGADHTGAGVSQSPSNKVTEKGKDVELRCDPIS...,15
12,CASERGSARQLTF,CASSFGTEDTQYF,P15,QKEVEQNSGPLSVPEGAIASLNCTYSDRGSQSFFWYRQYSGKSPEL...,QKEVEQNSGPLSVPEGAIASLNCTYSDRGSQSFFWYRQYSGKSPEL...,EAGVAQSPRYKIIEKRQSVAFWCNPISGHATLYWYQQILGQGPKLL...,6,GCGCCAAAGACTGGGT-1;GCAGCCATCCTCTAGC-1;CTTAGGAA...,GCGCCAAAGACTGGGT-1_contig_1;GCAGCCATCCTCTAGC-1...,GCGCCAAAGACTGGGT-1_contig_2;GCAGCCATCCTCTAGC-1...,...,0,ATGATGAAATCCTTGAGAGTTTTACTAGTGATCCTGTGGCTTCAGT...,MMKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCT...,ATGGGCACCAGGCTCCTCTGCTGGGCGGCCCTCTGTCTCCTGGGAG...,MGTRLLCWAALCLLGAELTEAGVAQSPRYKIIEKRQSVAFWCNPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCACCAGGCTCCTCTGCTGGGCGGCCCTCTGTCTCCTGGGAG...,MGTRLLCWAALCLLGAELTEAGVAQSPRYKIIEKRQSVAFWCNPIS...,15
6,CAATPGSYNTDKLIF,CAISGGTGKGTQYF,P15,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,DAGITQSPRHKVTETGTPVTLRCHQTENHRYMYWYRQDPGHGLRLI...,7,GGACATTCATTCTCAT-1;GCTCCTAAGTCCGGTC-1;TGTGTTTC...,GGACATTCATTCTCAT-1_contig_1;GCTCCTAAGTCCGGTC-1...,GGACATTCATTCTCAT-1_contig_2;GCTCCTAAGTCCGGTC-1...,...,0,ATGGCCATGCTCCTGGGGGCATCAGTGCTGATTCTGTGGCTTCAGC...,MAMLLGASVLILWLQPDWVNSQQKNDDQQVKQNSPSLSVQEGRISI...,ATGAGATCCTGGCCTGGACCTGAAATGGGCACAAGGTTGTTCTTCT...,MRSWPGPEMGTRLFFYVALCLLWTGHMDAGITQSPRHKVTETGTPV...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGAGATCCTGGCCTGGACCTGAAATGGGCACAAGGTTGTTCTTCT...,MRSWPGPEMGTRLFFYVALCLLWTGHMDAGITQSPRHKVTETGTPV...,15
10,CALDIDSNYQLIW,CAISERVNEQFF,P15,SQKIEQNSEALNIQEGKTATLTCNYTNYSPAYLQWYRQDPGRGPVF...,SQKIEQNSEALNIQEGKTATLTCNYTNYSPAYLQWYRQDPGRGPVF...,DAGITQSPRHKVTETGTPVTLRCHQTENHRYMYWYRQDPGHGLRLI...,11,GGCTCGATCTTGTCAT-1;GACTGCGCATTGGGCC-1;GAATGAAC...,GGCTCGATCTTGTCAT-1_contig_2;GACTGCGCATTGGGCC-1...,GGCTCGATCTTGTCAT-1_contig_1;GACTGCGCATTGGGCC-1...,...,0,ATGGCTTTTTGGCTGAGAAGCCTGGGTCTACATTTCAGGCCACATT...,MAFWLRSLGLHFRPHLGRRMESFLGGVLLILWLQVDWVKSQKIEQN...,ATGAGATCCTGGCCTGGACCTGAAATGGGCACAAGGTTGTTCTTCT...,MRSWPGPEMGTRLFFYVALCLLWTGHMDAGITQSPRHKVTETGTPV...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGAGATCCTGGCCTGGACCTGAAATGGGCACAAGGTTGTTCTTCT...,MRSWPGPEMGTRLFFYVALCLLWTGHMDAGITQSPRHKVTETGTPV...,15
3,CAASARETSGSRLTF,CASSPIGAYEQYF,P15,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,NAGVMQNPRHLVRRRGQEARLRCSPMKGHSHVYWYRQLPEEGLKFM...,44,GTACTTTCAGGACCCT-1;GTAACGTTCCTGCAGG-1;GGTGTTAT...,GTACTTTCAGGACCCT-1_contig_2;GTAACGTTCCTGCAGG-1...,GTACTTTCAGGACCCT-1_contig_1;GTAACGTTCCTGCAGG-1...,...,0,ATGGCCATGCTCCTGGGGGCATCAGTGCTGATTCTGTGGCTTCAGC...,MAMLLGASVLILWLQPDWVNSQQKNDDQQVKQNSPSLSVQEGRISI...,ATGGCCAACTCTGCTATGGACACCAGAGTACTCTGCTGTGCGGTCA...,MANSAMDTRVLCCAVICLLGAGLSNAGVMQNPRHLVRRRGQEARLR...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGCCAACTCTGCTATGGACACCAGAGTACTCTGCTGTGCGGTCA...,MANSAMDTRVLCCAVICLLGAGLSNAGVMQNPRHLVRRRGQEARLR...,15

In [360]:
df_selected_full_seqs.columns

Index(['CDR3_alpha', 'CDR3_beta', 'Peptide', 'VDJ_alpha_beta_aa',
       'VDJ_alpha_aa', 'VDJ_beta_aa', 'Cell_Count', 'Cell_Barcodes',
       'Alpha_Contig_IDs', 'Beta_Contig_IDs', 'Alpha_Reads_Mean',
       'Beta_Reads_Mean', 'Alpha_UMIs_Mean', 'Beta_UMIs_Mean', 'VDJ_alpha_dna',
       'VDJ_alpha_dna_ragged_3p_nt', 'VDJ_beta_dna',
       'VDJ_beta_dna_ragged_3p_nt', 'CDR1_alpha', 'CDR2_alpha', 'alpha_v_gene',
       'alpha_j_gene', 'alpha_c_gene', 'CDR1_beta', 'CDR2_beta', 'beta_v_gene',
       'beta_d_gene', 'beta_j_gene', 'beta_c_gene', 'assembly_alpha_leader_aa',
       'assembly_beta_leader_aa', 'assembly_alpha_leader_dna',
       'assembly_beta_leader_dna', 'assembly_alpha_vdj_dna',
       'assembly_beta_vdj_dna', 'assembly_alpha_vdj_ragged_3p_dna',
       'assembly_beta_vdj_ragged_3p_dna', 'assembly_alpha_constant_fragment',
       'assembly_beta_constant_fragment',
       'assembly_alpha_vdj_only_constant_fragment_dna',
       'assembly_alpha_vdj_without_constant_fragment_dna',
       'assembly_beta_vdj_only_constant_fragment_dna',
       'assembly_beta_vdj_without_constant_fragment_dna',
       'alpha_constant_dna_from_reference', 'alpha_constant_dna',
       'alpha_constant_translated', 'beta_constant_dna_from_reference',
       'beta_constant_dna', 'beta_constant_translated', 'full_alpha_dna',
       'full_alpha_translated', 'full_beta_dna', 'full_beta_translated',
       'full_alpha_dna_has_start_codon', 'full_beta_dna_has_start_codon',
       'full_alpha_dna_ends_in_stop_codon', 'full_beta_dna_ends_in_stop_codon',
       'full_alpha_dna_frame', 'full_beta_dna_frame',
       'full_alpha_dna_without_last_codon',
       'full_alpha_without_last_codon_translated',
       'full_beta_dna_without_last_codon',
       'full_beta_without_last_codon_translated', 'T2A_linker',
       'T2A_linker_translated', 'single_chain_full_alpha_and_beta_with_linker',
       'single_chain_full_alpha_and_beta_with_linker_translated',
       'Peptide_Num'],
      dtype='object')

In [361]:
SEQUENCE_COLUMNS = ["full_beta_without_last_codon_translated", "T2A_linker_translated", "full_alpha_translated"]
KEY_COLUMNS = ["Peptide_Num", "CDR3_alpha", "CDR3_beta"]
QC_KMER_SIZE = 10
MIN_REPEAT = 2
MIN_CDR3_LENGTH = 5
MAX_CDR3_LENGTH = 40
MIN_CHAIN_LENGTH = 200
MAX_CHAIN_LENGTH = 450
MIN_READS = 20

def extract_full_seq(row, sequence_columns=SEQUENCE_COLUMNS):
    return "".join([row[col] for col in sequence_columns])


def repeated_kmers_in_seq(seq, k=QC_KMER_SIZE, min_repeat=MIN_REPEAT):
    kmer_counts = Counter()
    for i in range(len(seq) - k + 1):
        kmer = seq[i:i+k]
        kmer_counts[kmer] += 1
    return [(kmer, c) for (kmer, c) in kmer_counts.most_common() if c >= min_repeat]

def repeated_kmers_in_row(row, sequence_columns=SEQUENCE_COLUMNS, k=QC_KMER_SIZE, min_repeat=MIN_REPEAT):
    concat_seq = extract_full_seq(row, sequence_columns=sequence_columns)
    return repeated_kmers_in_seq(concat_seq, k=k, min_repeat=min_repeat)

def repeated_kmers_in_df(df, key_columns=KEY_COLUMNS, sequence_columns=SEQUENCE_COLUMNS, k=QC_KMER_SIZE, min_repeat=MIN_REPEAT):
    result = {}
    for _, row in df.iterrows():
        key = tuple(row[key_columns].values)
        kmers = repeated_kmers_in_row(row, sequence_columns=sequence_columns, k=k, min_repeat=min_repeat)
        if kmers:
            result[key] = kmers
    return result



def qc_check(df, key_columns=KEY_COLUMNS, sequence_columns=SEQUENCE_COLUMNS, k=QC_KMER_SIZE, min_repeat=MIN_REPEAT):

   
    qc_cols = ["full_alpha_dna_has_start_codon", "full_beta_dna_has_start_codon", "full_alpha_dna_ends_in_stop_codon", "full_beta_dna_ends_in_stop_codon"]
    for col in qc_cols:
        print("Checking %s..." % col)
        values = df[col]
        if not values.all():
            raise ValueError("Found False value in %s" % (col,))

    nonzero_cols = ["Cell_Count", "Alpha_UMIs_Mean", "Beta_UMIs_Mean"]
    for col in nonzero_cols:
        
        print("Checking % s > 0..." % col)
        values = df[col]
        if not (values > 0).all():
            raise ValueError("Found 0 value in %s" % (col,))

    read_count_cols = ["Alpha_Reads_Mean", "Beta_Reads_Mean"]
    for col in read_count_cols:
        
        print("Checking % s > %d..." % (col, MIN_READS))
        values = df[col]
        if not (values > MIN_READS).all():
            raise ValueError("Found value < %d in %s" % (MIN_READS, col,))

    for chain in ["alpha", "beta"]:
        for cdr in ["CDR1", "CDR2", "CDR3"]:
            col_name = "%s_%s" % (cdr, chain)
            print("Checking %s in full construct..." % (col_name))
            for _, row in df.iterrows():
                seq = extract_full_seq(row, sequence_columns=sequence_columns)
                if row[col_name] not in seq:
                    raise ValueError("%s not in full sequence!" % col_name)
                if seq.count(row[col_name]) > 1:
                    raise ValueError("%s occurs more than once!" % col_name)
            
    print("Checking CDR3_alpha length...")
    for _, row in df.iterrows():
        cdr3a = row["CDR3_alpha"]
        if len(cdr3a) < MIN_CDR3_LENGTH:
            raise ValueError("CDR3_alpha too short!")
        if len(cdr3a) > MAX_CDR3_LENGTH:
            raise ValueError("CDR3_alpha too long!")
    
    print("Checking CDR3_beta length...")
    for _, row in df.iterrows():
        cdr3b = row["CDR3_beta"]
        if len(cdr3b) < MIN_CDR3_LENGTH:
            raise ValueError("CDR3_beta too short!")
        if len(cdr3b) > MAX_CDR3_LENGTH:
            raise ValueError("CDR3_beta too long!")
    
    print("Checking for repeated kmers (k=%d)..." % (k,))
    if repeated_kmers_in_df(df, key_columns=key_columns, sequence_columns=sequence_columns, k=k, min_repeat=min_repeat):
        raise ValueError("Repeated kmers in amino acid sequences!")
    
    print("Checking full chain length...")
    for chain in ["alpha", "beta"]:
        col_name = "full_%s_translated" % chain
        for seq in df[col_name]:
            if len(seq) < MIN_CHAIN_LENGTH:
                raise ValueError("%s chain too short!" % chain)
            if len(seq) > MAX_CHAIN_LENGTH:
                raise ValueError("%s chain too long!" % chain)

    for chain in ["alpha", "beta"]:
        print("Checking %s constant chain sequence..." % chain)
        gene_col_name = "%s_c_gene" % chain
        constant_seq_col_name = "%s_constant_translated" % chain
        full_seq_col_name = "full_%s_translated" % chain
        for gene_name, constant_seq, chain_seq, full_seq  in zip(df[gene_col_name], df[constant_seq_col_name], df[full_seq_col_name], df['single_chain_full_alpha_and_beta_with_linker_translated']):
            expected = None

            expected = {"TRAC": "LLMTLRLWSS", "TRBC1": "VKRKDF", "TRBC2": "VKRKDSRG"}.get(gene_name)
            if not constant_seq.endswith(expected):
                raise ValueError("Wrong constant sequence for %s (%s) in translated constant sequence" % (chain, gene_name))
            if not chain_seq.endswith(expected):
                raise ValueError("Wrong constant sequence for %s (%s) in full chain sequence" % (chain, gene_name))
            if not expected:
                raise ValueError("Unrecognized constant gene: %s" % gene_name)
            if expected not in full_seq:
                raise ValueError("Constant sequence for %s not in single_chain_full_alpha_and_beta_with_linker_translated" % gene_name) 
                
            
    print("---")
    print("QC check: OK")

In [362]:
qc_check(df_selected_full_seqs)

Checking full_alpha_dna_has_start_codon...
Checking full_beta_dna_has_start_codon...
Checking full_alpha_dna_ends_in_stop_codon...
Checking full_beta_dna_ends_in_stop_codon...
Checking Cell_Count > 0...
Checking Alpha_UMIs_Mean > 0...
Checking Beta_UMIs_Mean > 0...
Checking Alpha_Reads_Mean > 20...
Checking Beta_Reads_Mean > 20...
Checking CDR1_alpha in full construct...
Checking CDR2_alpha in full construct...
Checking CDR3_alpha in full construct...
Checking CDR1_beta in full construct...
Checking CDR2_beta in full construct...
Checking CDR3_beta in full construct...
Checking CDR3_alpha length...
Checking CDR3_beta length...
Checking for repeated kmers (k=10)...
Checking full chain length...
Checking alpha constant chain sequence...
Checking beta constant chain sequence...
---
QC check: OK

In [366]:
df_selected_full_seqs.Beta_UMIs_Mean

11    30.000000
7     26.571429
19     4.000000
4     17.916667
14    29.142857
0     33.666667
24    76.576923
13    17.097561
21    30.829268
8     26.652174
2     58.230769
20    16.333333
23    76.818182
9     29.302326
17    28.848485
5      8.000000
25    27.000000
15     7.500000
18     2.500000
1      7.333333
16     6.000000
22    10.000000
12     7.000000
6      4.142857
10     8.636364
3      4.840909
Name: Beta_UMIs_Mean, dtype: float64

In [372]:
# order the 
SORT_COLUMNS = ["Peptide_Num", "Cell_Count", "CDR3_alpha", "CDR3_beta", "Beta_UMIs_Mean", "Alpha_UMIs_Mean"]
df_selected_full_seqs = df_selected_full_seqs.sort_values(by=SORT_COLUMNS).reset_index().drop(columns=["index"])
df_selected_full_seqs["TCR_Num"] = np.arange(len(df_selected_full_seqs)) + 1
print(df_selected_full_seqs[["Peptide_Num", "CDR3_alpha", "CDR3_beta", "Cell_Count"]])
df_selected_full_seqs.to_csv("PFO004.selected.full-tcr-sequences.v5.csv", index=False)
df_selected_full_seqs

    Peptide_Num          CDR3_alpha         CDR3_beta  Cell_Count
0             1     CAMREGKGAGNMLTF    CASSRANSNQPQHF          38
1             2      CAETGFSDGQKLLF  CASSLDAEEGHYEQYF           7
2             3       CAVVRGNDYKLSF    CASSPRQDSYEQYF           1
3             5       CAASAWEGQNFVF      CASSLLDQPQHF          12
4             5     CATVSVGGFGNVLHC   CASSPDRVNTGELFF          21
5             5         CAAAYIDNLFF   CASSPDRVNTGELFF          27
6             7      CGADTNFGNEKLTF      CASSPGLATQYF          26
7             7       CATDSGGYQKVTF    CASSEGGHTGELFF          41
8            10        CAYRDSNYQLIW   CASSPTGDSGNTIYF          41
9            11    CAGHSAGGTSYGKLTF    CASSLYAGAWSYTF          23
10           11          CAAIKNQFYF    CASSRAGGQETQYF          26
11           12         CAVYNNARLMF  CASLGRGGLAKNIQYF          12
12           12     CAYWVGGGGADGLTF  CASSLTPGGVKETQYF          33
13           12      CAGQPGSSNYKLTF     CASSVQGATEAFF          43
14           13     CAVRDGKAAGNKLTF   CASSLVTGAFDEQFF          66
15           15       CAASDTGGFKTIF   CASSSRARGQETQYF           1
16           15        CGTETGNNRLAF   CASSKKGTGTDTQYF           1
17           15  CAVGASNAGGTSYGKLTF     CASSLARYDEQYF           2
18           15   CAVSVRRGGGSQGNLIF     CASSYSRGYEQYF           2
19           15        CAADNAGNMLTF     CASSSEYLGEQFF           3
20           15        CAVLYNTDKLIF  CASSSTRGYGANVLTF           3
21           15       CAYRSAKGNDMRF   CASSFYFGQGYEQYF           3
22           15       CASERGSARQLTF     CASSFGTEDTQYF           6
23           15     CAATPGSYNTDKLIF    CAISGGTGKGTQYF           7
24           15       CALDIDSNYQLIW      CAISERVNEQFF          11
25           15     CAASARETSGSRLTF     CASSPIGAYEQYF          44

,CDR3_alpha,CDR3_beta,Peptide,VDJ_alpha_beta_aa,VDJ_alpha_aa,VDJ_beta_aa,Cell_Count,Cell_Barcodes,Alpha_Contig_IDs,Beta_Contig_IDs,...,full_alpha_dna_without_last_codon,full_alpha_without_last_codon_translated,full_beta_dna_without_last_codon,full_beta_without_last_codon_translated,T2A_linker,T2A_linker_translated,single_chain_full_alpha_and_beta_with_linker,single_chain_full_alpha_and_beta_with_linker_translated,Peptide_Num,TCR_Num
0,CAMREGKGAGNMLTF,CASSRANSNQPQHF,P1,AQKITQTQPGMFVQEKEAVTLDCTYDTSDQSYGLFWYKQPSSGEMI...,AQKITQTQPGMFVQEKEAVTLDCTYDTSDQSYGLFWYKQPSSGEMI...,DTAVSQTPKYLVTQMGNDKSIKCEQNLGHDTMYWYKQDSKKFLKIM...,38,AACTCCCGTCGGGTCT-1;GGCGACTGTAGCGATG-1;GGCTGGTC...,AACTCCCGTCGGGTCT-1_contig_2;GGCGACTGTAGCGATG-1...,AACTCCCGTCGGGTCT-1_contig_1;GGCGACTGTAGCGATG-1...,...,ATGTCACTTTCTAGCCTGCTGAAGGTGGTCACAGCTTCACTGTGGC...,MSLSSLLKVVTASLWLGPGIAQKITQTQPGMFVQEKEAVTLDCTYD...,ATGGGCTGCAGGCTCCTCTGCTGTGTGGTCTTCTGCCTCCTCCAAG...,MGCRLLCCVVFCLLQAGPLDTAVSQTPKYLVTQMGNDKSIKCEQNL...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCTGCAGGCTCCTCTGCTGTGTGGTCTTCTGCCTCCTCCAAG...,MGCRLLCCVVFCLLQAGPLDTAVSQTPKYLVTQMGNDKSIKCEQNL...,1,1
1,CAETGFSDGQKLLF,CASSLDAEEGHYEQYF,P2,GEDVEQSLFLSVREGDSSVINCTYTDSSSTYLYWYKQEPGAGLQLL...,GEDVEQSLFLSVREGDSSVINCTYTDSSSTYLYWYKQEPGAGLQLL...,KAGVTQTPRYLIKTRGQQVTLSCSPISGHRSVSWYQQTPGQGLQFL...,7,GTCGGGTTCAACACTG-1;TATTACCTCGGAGGTA-1;CTGTTTAG...,GTCGGGTTCAACACTG-1_contig_2;TATTACCTCGGAGGTA-1...,GTCGGGTTCAACACTG-1_contig_1;TATTACCTCGGAGGTA-1...,...,ATGAAGACATTTGCTGGATTTTCGTTCCTGTTTTTGTGGCTGCAGC...,MKTFAGFSFLFLWLQLDCMSRGEDVEQSLFLSVREGDSSVINCTYT...,ATGGGCTCCAGGCTGCTCTGTTGGGTGCTGCTTTGTCTCCTGGGAG...,MGSRLLCWVLLCLLGAGPVKAGVTQTPRYLIKTRGQQVTLSCSPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCTCCAGGCTGCTCTGTTGGGTGCTGCTTTGTCTCCTGGGAG...,MGSRLLCWVLLCLLGAGPVKAGVTQTPRYLIKTRGQQVTLSCSPIS...,2,2
2,CAVVRGNDYKLSF,CASSPRQDSYEQYF,P3,EDQVTQSPEALRLQEGESSSLNCSYTVSGLRGLFWYRQDPGKGPEF...,EDQVTQSPEALRLQEGESSSLNCSYTVSGLRGLFWYRQDPGKGPEF...,NAGVMQNPRHLVRRRGQEARLRCSPMKGHSHVYWYRQLPEEGLKFM...,1,GGACAAGGTGCACGAA-1,GGACAAGGTGCACGAA-1_contig_2,GGACAAGGTGCACGAA-1_contig_1,...,ATGGAGAAAATGTTGGAGTGTGCATTCATAGTCTTGTGGCTTCAGC...,MEKMLECAFIVLWLQLGWLSGEDQVTQSPEALRLQEGESSSLNCSY...,ATGGCCAACTCTGCTATGGACACCAGACTACTCTGCTGTGCGGTCA...,MANSAMDTRLLCCAVICLLGAGLSNAGVMQNPRHLVRRRGQEARLR...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGCCAACTCTGCTATGGACACCAGACTACTCTGCTGTGCGGTCA...,MANSAMDTRLLCCAVICLLGAGLSNAGVMQNPRHLVRRRGQEARLR...,3,3
3,CAASAWEGQNFVF,CASSLLDQPQHF,P5,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,EAQVTQNPRYLITVTGKKLTVTCSQNMNHEYMSWYRQDPGLGLRQI...,12,GTGCGGTAGCCACGTC-1;GCGCCAAAGTGTTGAA-1;GTTCATTG...,GTGCGGTAGCCACGTC-1_contig_2;GCGCCAAAGTGTTGAA-1...,GTGCGGTAGCCACGTC-1_contig_1;GCGCCAAAGTGTTGAA-1...,...,ATGGCCATGCTCCTGGGGGCATCAGTGCTGATTCTGTGGCTTCAGC...,MAMLLGASVLILWLQPDWVNSQQKNDDQQVKQNSPSLSVQEGRISI...,ATGGGCCCCCAGCTCCTTGGCTATGTGGTCCTTTGCCTTCTAGGAG...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCCCCCAGCTCCTTGGCTATGTGGTCCTTTGCCTTCTAGGAG...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,5,4
4,CATVSVGGFGNVLHC,CASSPDRVNTGELFF,P5,GENVEQHPSTLSVQEGDSAVIKCTYSDSASNYFPWYKQELGKGPQL...,GENVEQHPSTLSVQEGDSAVIKCTYSDSASNYFPWYKQELGKGPQL...,EAGVVQSPRYKIIEKKQPVAFWCNPISGHNTLYWYLQNLGQGPELL...,21,GTACTCCTCCAAGTAC-1;GGTGTTATCTTGTACT-1;GCTTGAAC...,GTACTCCTCCAAGTAC-1_contig_3;GGTGTTATCTTGTACT-1...,GTACTCCTCCAAGTAC-1_contig_2;GGTGTTATCTTGTACT-1...,...,ATGACATCCATTCGAGCTGTATTTATATTCCTGTGGCTGCAGCTGG...,MTSIRAVFIFLWLQLDLVNGENVEQHPSTLSVQEGDSAVIKCTYSD...,ATGGGTACCAGGCTCCTCTGCTGGGTGGCCTTCTGTCTCCTGGTGG...,MGTRLLCWVAFCLLVEELIEAGVVQSPRYKIIEKKQPVAFWCNPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGTACCAGGCTCCTCTGCTGGGTGGCCTTCTGTCTCCTGGTGG...,MGTRLLCWVAFCLLVEELIEAGVVQSPRYKIIEKKQPVAFWCNPIS...,5,5
5,CAAAYIDNLFF,CASSPDRVNTGELFF,P5,QKEVEQNSGPLSVPEGAIASLNCTYSDRGSQSFFWYRQYSGKSPEL...,QKEVEQNSGPLSVPEGAIASLNCTYSDRGSQSFFWYRQYSGKSPEL...,EAGVVQSPRYKIIEKKQPVAFWCNPISGHNTLYWYLQNLGQGPELL...,27,GTCACGGCAAGCCGTC-1;GTCAAGTTCCGCGTTT-1;GTCAAGTG...,GTCACGGCAAGCCGTC-1_contig_1;GTCAAGTTCCGCGTTT-1...,GTCACGGCAAGCCGTC-1_contig_2;GTCAAGTTCCGCGTTT-1...,...,ATGATGAAATCCTTGAGAGTTTTACTAGTGATCCTGTGGCTTCAGT...,MMKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCT...,ATGGGTACCAGGCTCCTCTGCTGGGTGGCCTTCTGTCTCCTGGTGG...,MGTRLLCWVAFCLLVEELIEAGVVQSPRYKIIEKKQPVAFWCNPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGTACCAGGCTCCTCTGCTGGGTGGCCTTCTGTCTCCTGGTGG...,MGTRLLCWVAFCLLVEELIEAGVVQSPRYKIIEKKQPVAFWCNPIS...,5,6
6,CGADTNFGNEKLTF,CASSPGLATQYF,P7,SQELEQSPQSLIVQEGKNLTINCTSSKTLYGLYWYKQKYGEGLIFL...,SQELEQSPQSLIVQEGKNLTINCTSSKTLYGLYWYKQKYGEGLIFL...,EAGVAQSPRYKIIEKRQSVAFWCNPISGHATLYWYQQILGQGPKLL...,26,GGGTTGCTCCGTCATC-1;GGAATAACATGTAGTC-1;GCATGTAG...,GGGTTGCTCCGTCATC-1_contig_1;GGAATAACATGTAGTC-1...,GGGTTGCTCCGTCATC-1_contig_2;GGAATAACATGTAGTC-1...,...,ATGGAGACTGTTCTGCAAGTACTCCTAGGGATATTGGGGTTCCAAG...,METVLQVLLGILGFQAAWVSSQELEQSPQSLIVQEGKNLTINCTSS...,ATGGGCACCAGGCTCCTCTGCTGGGCGGCCCTCTGTCTCCTGGGAG...,MGTRLLCWAALCLLGAELTEAGVAQSPRYKIIEKRQSVAFWCNPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCACCAGGCTCCTCTGCTGGGCGGCCCTCTGTCTCCTGGGAG...,MGTRLLCWAALCLLGAELTEAGVAQSPRYKIIEKRQSVAFWCNPIS...,7,7
7,CATDSGGYQKVTF,CASSEGGHTGELFF,P7,SQQGEEDPQALSIQEGENATMNCSYKTSINNLQWYRQNSGRGLVHL...,SQQGEEDPQALSIQEGENATMNCSYKTSINNLQWYRQNSGRGLVHL...,NAGVMQNPRHLVRRRGQEARLRCSPMKGHSHVYWYRQLPEEGLKFM...,41,GTAACTGGTGTGGCTC-1;GCTCTGTTCTTTACAC-1;GACACGCT...,GTAACTGGTGTGGCTC-1_contig_2;GCTCTGTTCTTTACAC-1...,GTAACTGGTGTGGCTC-1_contig_1;GCTCTGTTCTTTACAC-1...,...,ATGGAAACTCTCCTGGGAGTGTCTTTGGTGATTCTATGGCTTCAAC...,METLLGVSLVILWLQLARVNSQQGEEDPQALSIQEGENATMNCSYK...,ATGGCCAACTCTGCTATGGACACCAGAGTACTCTGCTGTGCGGTCA...,MANSAMDTRVLCCAVICLLGAGLSNAGVMQNPRHLVRRRGQEARLR...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGCCAACTCTGCTATGGACACCAGAGTACTCTGCTGTGCGGTCA...,MANSAMDTRVLCCAVICLLGAGLSNAGVMQNPRHLVRRRGQEARLR...,7,8
8,CAYRDSNYQLIW,CASSPTGDSGNTIYF,P10,AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMI...,AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMI...,NAGVMQNPRHLVRRRGQEARLRCSPMKGHSHVYWYRQLPEEGLKFM...,41,GGTGCGTTCGGAAATA-1;GGCTGGTGTTCGCTAA-1;GCTTCCAC...,GGTGCGTTCGGAAATA-1_contig_2;GGCTGGTGTTCGCTAA-1...,GGTGCGTTCGGAAATA-1_contig_1;GGCTGGTGTTCGCTAA-1...,...,ATGGCATGCCCTGGCTTCCTGTGGGCACTTGTGATCTCCACCTGTC...,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,ATGGCCAACTCTGCTATGGACACCAGACTACTCTGCTGTGCGGTCA...,MANSAMDTRLLCCAVICLLGAGLSNAGVMQNPRHLVRRRGQEARLR...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGCCAACTCTGCTATGGACACCAGACTACTCTGCTGTGCGGTCA...,MANSAMDTRLLCCAVICLLGAGLSNAGVMQNPRHLVRRRGQEARLR...,10,9
9,CAGHSAGGTSYGKLTF,CASSLYAGAWSYTF,P11,GQQLNQSPQSMFIQEGEDVSMNCTSSSIFNTWLWYKQDPGEGPVLL...,GQQLNQSPQSMFIQEGEDVSMNCTSSSIFNTWLWYKQDPGEGPVLL...,EAQVTQNPRYLITVTGKKLTVTCSQNMNHEYMSWYRQDPGLGLRQI...,23,TACTCATAGATCGGGT-1;GTCACAATCGATAGAA-1;GACCAATA...,TACTCATAGATCGGGT-1_contig_1;GTCACAATCGATAGAA-1...,TACTCATAGATCGGGT-1_contig_2;GTCACAATCGATAGAA-1...,...,ATGCTCCTTGAACATTTATTAATAATCTTGTGGATGCAGCTGACAT...,MLLEHLLIILWMQLTWVSGQQLNQSPQSMFIQEGEDVSMNCTSSSI...,ATGGGCCCCCAGCTCCTTGGCTATGTGGTCCTTTGCCTTCTAGGAG...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCCCCCAGCTCCTTGGCTATGTGGTCCTTTGCCTTCTAGGAG...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,11,10
10,CAAIKNQFYF,CASSRAGGQETQYF,P11,GENVEQHPSTLSVQEGDSAVIKCTYSDSASNYFPWYKQELGKGPQL...,GENVEQHPSTLSVQEGDSAVIKCTYSDSASNYFPWYKQELGKGPQL...,GAGVSQTPSNKVTEKGKYVELRCDPISGHTALYWYRQSLGQGPEFL...,26,GTCTTCGCATCTCGCT-1;GTCCTCACAGGCGATA-1;TTGCGTCA...,GTCTTCGCATCTCGCT-1_contig_2;GTCCTCACAGGCGATA-1...,GTCTTCGCATCTCGCT-1_contig_1;GTCCTCACAGGCGATA-1...,...,ATGACATCCATTCGAGCTGTATTTATATTCCTGTGGCTGCAGCTGG...,MTSIRAVFIFLWLQLDLVNGENVEQHPSTLSVQEGDSAVIKCTYSD...,ATGGGCACCAGGCTCCTCTGCTGGGCAGCCCTGTGCCTCCTGGGGG...,MGTRLLCWAALCLLGADHTGAGVSQTPSNKVTEKGKYVELRCDPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCACCAGGCTCCTCTGCTGGGCAGCCCTGTGCCTCCTGGGGG...,MGTRLLCWAALCLLGADHTGAGVSQTPSNKVTEKGKYVELRCDPIS...,11,11
11,CAVYNNARLMF,CASLGRGGLAKNIQYF,P12,GQQVMQIPQYQHVQEGEDFTTYCNSSTTLSNIQWYKQRPGGHPVFL...,GQQVMQIPQYQHVQEGEDFTTYCNSSTTLSNIQWYKQRPGGHPVFL...,EPEVTQTPSHQVTQMGQEVILRCVPISNHLYFYWYRQILGQKVEFL...,12,GGGAATGGTAGCTAAA-1;CTTACCGAGCTCAACT-1;TCTGAGAT...,GGGAATGGTAGCTAAA-1_contig_2;CTTACCGAGCTCAACT-1...,GGGAATGGTAGCTAAA-1_contig_1;CTTACCGAGCTCAACT-1...,...,ATGAAGAGGGAGAGGGAGATGCTACTCATCACATCAATGTTGGTCT...,MKREREMLLITSMLVLWMQLSQVNGQQVMQIPQYQHVQEGEDFTTY...,ATGGATACCTGGCTCGTATGCTGGGCAATTTTTAGTCTCTTGAAAG...,MDTWLVCWAIFSLLKAGLTEPEVTQTPSHQVTQMGQEVILRCVPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGATACCTGGCTCGTATGCTGGGCAATTTTTAGTCTCTTGAAAG...,MDTWLVCWAIFSLLKAGLTEPEVTQTPSHQVTQMGQEVILRCVPIS...,12,12
12,CAYWVGGGGADGLTF,CASSLTPGGVKETQYF,P12,AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMI...,AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMI...,GAGVSQSPRYKVAKRGQDVALRCDPISGHVSLFWYQQALGQGPEFL...,33,GTGCATATCCGATATG-1;GACGTTACAGGTCGTC-1;GACGCGTG...,GTGCATATCCGATATG-1_contig_1;GACGTTACAGGTCGTC-1...,GTGCATATCCGATATG-1_contig_2;GACGTTACAGGTCGTC-1...,...,ATGGCATGCCCTGGCTTCCTGTGGGCACTTGTGATCTCCACCTGTC...,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,ATGGGCACCAGGCTCCTCTGCTGGGTGGTCCTGGGTTTCCTAGGGA...,MGTRLLCWVVLGFLGTDHTGAGVSQSPRYKVAKRGQDVALRCDPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCACCAGGCTCCTCTGCTGGGTGGTCCTGGGTTTCCTAGGGA...,MGTRLLCWVVLGFLGTDHTGAGVSQSPRYKVAKRGQDVALRCDPIS...,12,13
13,CAGQPGSSNYKLTF,CASSVQGATEAFF,P12,GQQLNQSPQSMFIQEGEDVSMNCTSSSIFNTWLWYKQDPGEGPVLL...,GQQLNQSPQSMFIQEGEDVSMNCTSSSIFNTWLWYKQDPGEGPVLL...,EPEVTQTPSHQVTQMGQEVILRCVPISNHLYFYWYRQILGQKVEFL...,43,GTCTTCGGTTAGTGGG-1;GTCGTAAAGTGGAGAA-1;GTACTTTT...,GTCTTCGGTTAGTGGG-1_contig_1;GTCGTAAAGTGGAGAA-1...,GTCTTCGGTTAGTGGG-1_contig_2;GTCGTAAAGTGGAGAA-1...,...,ATGCTCCTTGAACATTTATTAATAATCTTGTGGATGCAGCTGACAT...,MLLEHLLIILWMQLTWVSGQQLNQSPQSMFIQEGEDVSMNCTSSSI...,ATGGATACCTGGCTCGTATGCTGGGCAATTTTTAGTCTCTTGAAAG...,MDTWLVCWAIFSLLKAGLTEPEVTQTPSHQVTQMGQEVILRCVPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGATACCTGGCTCGTATGCTGGGCAATTTTTAGTCTCTTGAAAG...,MDTWLVCWAIFSLLKAGLTEPEVTQTPSHQVTQMGQEVILRCVPIS...,12,14
14,CAVRDGKAAGNKLTF,CASSLVTGAFDEQFF,P13,AQSVAQPEDQVNVAEGNPLTVKCTYSVSGNPYLFWYVQYPNRGLQF...,AQSVAQPEDQVNVAEGNPLTVKCTYSVSGNPYLFWYVQYPNRGLQF...,DTGVSQNPRHKITKRGQNVTFRCDPISEHNRLYWYRQTLGQGPEFL...,66,GGATTACTCATTTGGG-1;GGACAAGTCATCGATG-1;GGACAAGG...,GGATTACTCATTTGGG-1_contig_1;GGACAAGTCATCGATG-1...,GGATTACTCATTTGGG-1_contig_2;GGACAAGTCATCGATG-1...,...,ATGGCCTCTGCACCCATCTCGATGCTTGCGATGCTCTTCACATTGA...,MASAPISMLAMLFTLSGLRAQSVAQPEDQVNVAEGNPLTVKCTYSV...,ATGGGCACCAGCCTCCTCTGCTGGATGGCCCTGTGTCTCCTGGGGG...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCACCAGCCTCCTCTGCTGGATGGCCCTGTGTCTCCTGGGGG...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,13,15
15,CAASDTGGFKTIF,CASSSRARGQETQYF,P15,GQQVMQIPQYQHVQEGEDFTTYCNSSTTLSNIQWYKQRPGGHPVFL...,GQQVMQIPQYQHVQEGEDFTTYCNSSTTLSNIQWYKQRPGGHPVFL...,GAGVSQSPSNKVTEKGKDVELRCDPISGHTALYWYRQSLGQGLEFL...,1,AGTGTCAAGCTCAACT-1,AGTGTCAAGCTCAACT-1_contig_2,AGTGTCAAGCTCAACT-1_contig_1,...,ATGAAGAGGGAGAGGGAGATGCTACTCATCACATCAATGTTGGTCT...,MKREREMLLITSMLVLWMQLSQVNGQQVMQIPQYQHVQEGEDFTTY...,ATGGGCACCAGGCTCCTCTTCTGGGTGGCCTTCTGTCTCCTGGGGG...,MGTRLLFWVAFCLLGADHTGAGVSQSPSNKVTEKGKDVELRCDPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCACCAGGCTCCTCTTCTGGGTGGCCTTCTGTCTCCTGGGGG...,MGTRLLFWVAFCLLGADHTGAGVSQSPSNKVTEKGKDVELRCDPIS...,15,16
16,CGTETGNNRLAF,CASSKKGTGTDTQYF,P15,QQPVQSPQAVILREGEDAVINCSSSKALYSVHWYRQKHGEAPVFLM...,QQPVQSPQAVILREGEDAVINCSSSKALYSVHWYRQKHGEAPVFLM...,GAGVSQSPRYKVAKRGQDVALRCDPISGHVSLFWYQQALGQGPEFL...,1,CGATGGCCATACCATG-1,CGATGGCCATACCATG-1_contig_3,CGATGGCCATACCATG-1_contig_1,...,ATGGAGACTCTCCTGAAAGTGCTTTCAGGCACCTTGTTGTGGCAGT...,METLLKVLSGTLLWQLTWVRSQQPVQSPQAVILREGEDAVINCSSS...,ATGGGCACCAGGCTCCTCTGCTGGGTGGTCCTGGGTTTCCTAGGGA...,MGTRLLCWVVLGFLGTDHTGAGVSQSPRYKVAKRGQDVALRCDPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCACCAGGCTCCTCTGCTGGGTGGTCCTGGGTTTCCTAGGGA...,MGTRLLCWVVLGFLGTDHTGAGVSQSPRYKVAKRGQDVALRCDPIS...,15,17
17,CAVGASNAGGTSYGKLTF,CASSLARYDEQYF,P15,AQSVTQPDIHITVSEGASLELRCNYSYGATPYLFWYVQSPGQGLQL...,AQSVTQPDIHITVSEGASLELRCNYSYGATPYLFWYVQSPGQGLQL...,DTGVSQNPRHKITKRGQNVTFRCDPISEHNRLYWYRQTLGQGPEFL...,2,TACCTTACACTGTCGG-1;ATCACGATCATCTGTT-1,TACCTTACACTGTCGG-1_contig_2;ATCACGATCATCTGTT-1...,TACCTTACACTGTCGG-1_contig_1;ATCACGATCATCTGTT-1...,...,ATGCTCCTGGAGCTTATCCCACTGCTGGGGATACATTTTGTCCTGA...,MLLELIPLLGIHFVLRTARAQSVTQPDIHITVSEGASLELRCNYSY...,ATGGGCACCAGCCTCCTCTGCTGGATGGCCCTGTGTCTCCTGGGGG...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCACCAGCCTCCTCTGCTGGATGGCCCTGTGTCTCCTGGGGG...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,15,18
18,CAVSVRRGGGSQGNLIF,CASSYSRGYEQYF,P15,AQSVTQLDSQVPVFEEAPVELRCNYSSSVSVYLFWYVQYPNQGLQL...,AQSVTQLDSQVPVFEEAPVELRCNYSSSVSVYLFWYVQYPNQGLQL...,NAGVTQTPKFQVLKTGQSMTLQCAQDMNHEYMSWYRQDPGMGLRLI...,2,ATCTGCCTCAGTGCAT-1;CTCACACAGGGAACGG-1,ATCTGCCTCAGTGCAT-1_contig_1;CTCACACAGGGAACGG-1...,ATCTGCCTCAGTGCAT-1_contig_2;CTCACACAGGGAACGG-1...,...,ATGCTCCTGCTGCTCGTCCCAGCGTTCCAGGTGATTTTTACCCTGG...,MLLLLVPAFQVIFTLGGTRAQSVTQLDSQVPVFEEAPVELRCNYSS...,ATGAGCATCGGCCTCCTGTGCTGTGCAGCCTTGTCTCTCCTGTGGG...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGAGCATCGGCCTCCTGTGCTGTGCAGCCTTGTCTCTCCTGTGGG...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...,15,19
19,CAADNAGNMLTF,CASSSEYLGEQFF,P15,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,ETGVTQSPTHLIKTRGQQVTLRCSSQSGHNTVSWYQQALGQGPQFI...,3,TAAGTGCCATGTTCCC-1;AACTTTCAGTTGAGTA-1;CAACCAAT...,TAAGTGCCATGTTCCC-1_contig_1;AACTTTCAGTTGAGTA-1...,TAAGTGCCATGTTCCC-1_contig_2;AACTTTCAGTTGAGTA-1...,...,ATGGCCATGCTCCTGGGGGCATCAGTGCTGATTCTGTGGCTTCAGC...,MAMLLGASVLILWLQPDWVNSQQKNDDQQVKQNSPSLSVQEGRISI...,ATGGGCCCTGGGCTCCTCTGCTGGGTGCTGCTTTGTCTCCTGGGAG...,MGPGLLCWVLLCLLGAGSVETGVTQSPTHLIKTRGQQVTLRCSSQS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCCCTGGGCTCCTCTGCTGGGTGCTGCTTTGTCTCCTGGGAG...,MGPGLLCWVLLCLLGAGSVETGVTQSPTHLIKTRGQQVTLRCSSQS...,15,20
20,CAVLYNTDKLIF,CASSSTRGYGANVLTF,P15,KQEVTQIPAALSVPEGENLVLNCSFTDSAIYNLQWFRQDPGKGLTS...,KQEVTQIPAALSVPEGENLVLNCSFTDSAIYNLQWFRQDPGKGLTS...,GAGVSQSPSNKVTEKGKDVELRCDPISGHTALYWYRQSLGQGLEFL...,3,GCTGGGTCATTGTGCA-1;GCTGCGATCATCGCTC-1;CCGGGATG...,GCTGGGTCATTGTGCA-1_contig_2;GCTGCGATCATCGCTC-1...,GCTGGGTCATTGTGCA-1_contig_1;GCTGCGATCATCGCTC-1...,...,ATGGAGACCCTCTTGGGCCTGCTTATCCTTTGGCTGCAGCTGCAAT...,METLLGLLILWLQLQWVSSKQEVTQIPAALSVPEGENLVLNCSFTD...,ATGGGCACCAGGCTCCTCTTCTGGGTGGCCTTCTGTCTCCTGGGGG...,MGTRLLFWVAFCLLGADHTGAGVSQSPSNKVTEKGKDVELRCDPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCACCAGGCTCCTCTTCTGGGTGGCCTTCTGTCTCCTGGGGG...,MGTRLLFWVAFCLLGADHTGAGVSQSPSNKVTEKGKDVELRCDPIS...,15,21
21,CAYRSAKGNDMRF,CASSFYFGQGYEQYF,P15,AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMI...,AQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMI...,GAGVSQSPSNKVTEKGKDVELRCDPISGHTALYWYRQSLGQGLEFL...,3,ACACCGGGTTCGGCAC-1;AACCGCGAGTAACCCT-1;CGAGAAGA...,ACACCGGGTTCGGCAC-1_contig_2;AACCGCGAGTAACCCT-1...,ACACCGGGTTCGGCAC-1_contig_1;AACCGCGAGTAACCCT-1...,...,ATGGCATGCCCTGGCTTCCTGTGGGCACTTGTGATCTCCACCTGTC...,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,ATGGGCACCAGGCTCCTCTTCTGGGTGGCCTTCTGTCTCCTGGGGG...,MGTRLLFWVAFCLLGADHTGAGVSQSPSNKVTEKGKDVELRCDPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCACCAGGCTCCTCTTCTGGGTGGCCTTCTGTCTCCTGGGGG...,MGTRLLFWVAFCLLGADHTGAGVSQSPSNKVTEKGKDVELRCDPIS...,15,22
22,CASERGSARQLTF,CASSFGTEDTQYF,P15,QKEVEQNSGPLSVPEGAIASLNCTYSDRGSQSFFWYRQYSGKSPEL...,QKEVEQNSGPLSVPEGAIASLNCTYSDRGSQSFFWYRQYSGKSPEL...,EAGVAQSPRYKIIEKRQSVAFWCNPISGHATLYWYQQILGQGPKLL...,6,GCGCCAAAGACTGGGT-1;GCAGCCATCCTCTAGC-1;CTTAGGAA...,GCGCCAAAGACTGGGT-1_contig_1;GCAGCCATCCTCTAGC-1...,GCGCCAAAGACTGGGT-1_contig_2;GCAGCCATCCTCTAGC-1...,...,ATGATGAAATCCTTGAGAGTTTTACTAGTGATCCTGTGGCTTCAGT...,MMKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCT...,ATGGGCACCAGGCTCCTCTGCTGGGCGGCCCTCTGTCTCCTGGGAG...,MGTRLLCWAALCLLGAELTEAGVAQSPRYKIIEKRQSVAFWCNPIS...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGGCACCAGGCTCCTCTGCTGGGCGGCCCTCTGTCTCCTGGGAG...,MGTRLLCWAALCLLGAELTEAGVAQSPRYKIIEKRQSVAFWCNPIS...,15,23
23,CAATPGSYNTDKLIF,CAISGGTGKGTQYF,P15,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,DAGITQSPRHKVTETGTPVTLRCHQTENHRYMYWYRQDPGHGLRLI...,7,GGACATTCATTCTCAT-1;GCTCCTAAGTCCGGTC-1;TGTGTTTC...,GGACATTCATTCTCAT-1_contig_1;GCTCCTAAGTCCGGTC-1...,GGACATTCATTCTCAT-1_contig_2;GCTCCTAAGTCCGGTC-1...,...,ATGGCCATGCTCCTGGGGGCATCAGTGCTGATTCTGTGGCTTCAGC...,MAMLLGASVLILWLQPDWVNSQQKNDDQQVKQNSPSLSVQEGRISI...,ATGAGATCCTGGCCTGGACCTGAAATGGGCACAAGGTTGTTCTTCT...,MRSWPGPEMGTRLFFYVALCLLWTGHMDAGITQSPRHKVTETGTPV...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGAGATCCTGGCCTGGACCTGAAATGGGCACAAGGTTGTTCTTCT...,MRSWPGPEMGTRLFFYVALCLLWTGHMDAGITQSPRHKVTETGTPV...,15,24
24,CALDIDSNYQLIW,CAISERVNEQFF,P15,SQKIEQNSEALNIQEGKTATLTCNYTNYSPAYLQWYRQDPGRGPVF...,SQKIEQNSEALNIQEGKTATLTCNYTNYSPAYLQWYRQDPGRGPVF...,DAGITQSPRHKVTETGTPVTLRCHQTENHRYMYWYRQDPGHGLRLI...,11,GGCTCGATCTTGTCAT-1;GACTGCGCATTGGGCC-1;GAATGAAC...,GGCTCGATCTTGTCAT-1_contig_2;GACTGCGCATTGGGCC-1...,GGCTCGATCTTGTCAT-1_contig_1;GACTGCGCATTGGGCC-1...,...,ATGGCTTTTTGGCTGAGAAGCCTGGGTCTACATTTCAGGCCACATT...,MAFWLRSLGLHFRPHLGRRMESFLGGVLLILWLQVDWVKSQKIEQN...,ATGAGATCCTGGCCTGGACCTGAAATGGGCACAAGGTTGTTCTTCT...,MRSWPGPEMGTRLFFYVALCLLWTGHMDAGITQSPRHKVTETGTPV...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGAGATCCTGGCCTGGACCTGAAATGGGCACAAGGTTGTTCTTCT...,MRSWPGPEMGTRLFFYVALCLLWTGHMDAGITQSPRHKVTETGTPV...,15,25
25,CAASARETSGSRLTF,CASSPIGAYEQYF,P15,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,DQQVKQNSPSLSVQEGRISILNCDYTNSMFDYFLWYKKYPAEGPTF...,NAGVMQNPRHLVRRRGQEARLRCSPMKGHSHVYWYRQLPEEGLKFM...,44,GTACTTTCAGGACCCT-1;GTAACGTTCCTGCAGG-1;GGTGTTAT...,GTACTTTCAGGACCCT-1_contig_2;GTAACGTTCCTGCAGG-1...,GTACTTTCAGGACCCT-1_contig_1;GTAACGTTCCTGCAGG-1...,...,ATGGCCATGCTCCTGGGGGCATCAGTGCTGATTCTGTGGCTTCAGC...,MAMLLGASVLILWLQPDWVNSQQKNDDQQVKQNSPSLSVQEGRISI...,ATGGCCAACTCTGCTATGGACACCAGAGTACTCTGCTGTGCGGTCA...,MANSAMDTRVLCCAVICLLGAGLSNAGVMQNPRHLVRRRGQEARLR...,AGAGCCGAGGGCAGGGGAAGTCTTCTAACATGCGGGGACGTGGAGG...,RAEGRGSLLTCGDVEENPGP,ATGGCCAACTCTGCTATGGACACCAGAGTACTCTGCTGTGCGGTCA...,MANSAMDTRVLCCAVICLLGAGLSNAGVMQNPRHLVRRRGQEARLR...,15,26

    Peptide_Num          CDR3_alpha         CDR3_beta  Cell_Count
0             1     CAMREGKGAGNMLTF    CASSRANSNQPQHF          38
1             2      CAETGFSDGQKLLF  CASSLDAEEGHYEQYF           7
2             3       CAVVRGNDYKLSF    CASSPRQDSYEQYF           1
3             5       CAASAWEGQNFVF      CASSLLDQPQHF          12
4             5     CATVSVGGFGNVLHC   CASSPDRVNTGELFF          21
5             5         CAAAYIDNLFF   CASSPDRVNTGELFF          27
6             7      CGADTNFGNEKLTF      CASSPGLATQYF          26
7             7       CATDSGGYQKVTF    CASSEGGHTGELFF          41
8            10        CAYRDSNYQLIW   CASSPTGDSGNTIYF          41
9            11    CAGHSAGGTSYGKLTF    CASSLYAGAWSYTF          23
10           11          CAAIKNQFYF    CASSRAGGQETQYF          26
11           12         CAVYNNARLMF  CASLGRGGLAKNIQYF          12
12           12     CAYWVGGGGADGLTF  CASSLTPGGVKETQYF          33
13           12      CAGQPGSSNYKLTF     CASSVQGATEAFF          43
14           13     CAVRDGKAAGNKLTF   CASSLVTGAFDEQFF          66
15           15       CAASDTGGFKTIF   CASSSRARGQETQYF           1
16           15        CGTETGNNRLAF   CASSKKGTGTDTQYF           1
17           15  CAVGASNAGGTSYGKLTF     CASSLARYDEQYF           2
18           15   CAVSVRRGGGSQGNLIF     CASSYSRGYEQYF           2
19           15        CAADNAGNMLTF     CASSSEYLGEQFF           3
20           15        CAVLYNTDKLIF  CASSSTRGYGANVLTF           3
21           15       CAYRSAKGNDMRF   CASSFYFGQGYEQYF           3
22           15       CASERGSARQLTF     CASSFGTEDTQYF           6
23           15     CAATPGSYNTDKLIF    CAISGGTGKGTQYF           7
24           15       CALDIDSNYQLIW      CAISERVNEQFF          11
25           15     CAASARETSGSRLTF     CASSPIGAYEQYF          44

In [373]:
from collections import defaultdict
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from itertools import cycle
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from collections import Counter


def create_tcr_pdf(df, output_path, sequence_font_size = 18, label_font_size = 12, title_font_size = 14, chars_per_line = 45,
                   color_list = [colors.darkblue, colors.blue, colors.lightblue, 
                                 colors.orange, 
                                 colors.darkgreen, colors.green, colors.lightgreen, 
                                 colors.purple, colors.brown, colors.pink, colors.darkgray, colors.red],
                   sequence_columns={
                        "assembly_beta_leader_aa": "beta_leader",
                        "VDJ_beta_aa": "beta_VDJ",
                        "beta_constant_translated": "beta_constant",
                        "T2A_linker_translated": "T2A_linker",
                        "assembly_alpha_leader_aa": "alpha_leader",
                        "VDJ_alpha_aa": "alpha_VDJ",
                        "alpha_constant_translated": "alpha_constant"}):
    """
    Creates a PDF with color-coded TCR sequences using monospaced font.
    """
    # Register Courier as our monospaced font
    pdfmetrics.getFont('Courier')
    
   
    color_cycle = cycle(color_list)
    color_map = defaultdict(lambda: next(color_cycle))
    
    c = canvas.Canvas(output_path, pagesize=letter)
    width, height = letter
    

    char_width = sequence_font_size * 0.6  # Fixed width for monospaced font

        
    for _, row in df.iterrows():
        y_position = height - 50
        def write(s, x=20, y_offset=20):
            nonlocal y_position
            c.drawString(x, y_position, s)
            y_position -= y_offset
        def blank():
            nonlocal y_position
            y_position -= 30
            
        # TCR identifier
        c.setFont("Helvetica-Bold", title_font_size)
        c.setFillColor("red")
        write(f"TCR #{row.TCR_Num}")
        c.setFillColor("black")
        write(f"Peptide {row.Peptide}")
        write(f"CDR3 alpha = {row.CDR3_alpha}")
        write(f"CDR3 beta = {row.CDR3_beta}")

        # normal font weight for smaller bits of information
        c.setFont("Helvetica", title_font_size)
        write(f"Length = {sum([len(row[col]) for col in sequence_columns])}", x=40)
    
        for col in df.columns:
            if col.endswith("_gene"):
                write(f"{col} = {row[col]}", x=40)
        
        blank()
        
        # Color legend
        legend_x = width - 200
        legend_y = height - 50
        c.setFont("Helvetica", label_font_size)
        for col, alias in sequence_columns.items():
            color = color_map[col]
            c.setFillColor(color)
            c.drawString(legend_x, legend_y, alias)
            legend_y -= label_font_size * 1.5
        
        # Write wrapped sequence with color coding
        x_position = 50
        current_line_width = 0

        combined = ""
    
        for col in sequence_columns.keys():
            
            sequence = row[col]
            color = color_map[col]
            
            for char in sequence:
                combined += char
                if current_line_width >= chars_per_line:
                    y_position -= sequence_font_size * 1.2
                    current_line_width = 0
                    x_position = 50
                
                c.setFont("Courier", sequence_font_size)
                c.setFillColor(color)
                c.drawString(x_position, y_position, char)
                x_position += char_width
                current_line_width += 1
        if combined != row['single_chain_full_alpha_and_beta_with_linker_translated']:
            raise ValueError("Expected '%s' but got '%s'" % (row['single_chain_full_alpha_and_beta_with_linker'], combined))
        
        repeated_kmers_with_counts = repeated_kmers_in_row(row, sequence_columns)
        if repeated_kmers_with_counts and repeated_kmers_with_counts[0][1] > 1:
            y_position -= 50
            for kmer, count in repeated_kmers_with_counts[:10]:
                c.setFont("Helvetica", title_font_size)
                c.setFillColor("red")
                message = "Warning! Repeated k-mer (n=%d): %s" % (count, kmer)
                c.drawString(20, y_position, message)
                print(message)
                y_position -= 20
        c.showPage()
    
    c.save()

In [374]:
create_tcr_pdf(
    df_selected_full_seqs, 
    output_path="PFO004.selected.report.v5.pdf", 
   )

In [375]:
df_selected_full_seqs.columns

Index(['CDR3_alpha', 'CDR3_beta', 'Peptide', 'VDJ_alpha_beta_aa',
       'VDJ_alpha_aa', 'VDJ_beta_aa', 'Cell_Count', 'Cell_Barcodes',
       'Alpha_Contig_IDs', 'Beta_Contig_IDs', 'Alpha_Reads_Mean',
       'Beta_Reads_Mean', 'Alpha_UMIs_Mean', 'Beta_UMIs_Mean', 'VDJ_alpha_dna',
       'VDJ_alpha_dna_ragged_3p_nt', 'VDJ_beta_dna',
       'VDJ_beta_dna_ragged_3p_nt', 'CDR1_alpha', 'CDR2_alpha', 'alpha_v_gene',
       'alpha_j_gene', 'alpha_c_gene', 'CDR1_beta', 'CDR2_beta', 'beta_v_gene',
       'beta_d_gene', 'beta_j_gene', 'beta_c_gene', 'assembly_alpha_leader_aa',
       'assembly_beta_leader_aa', 'assembly_alpha_leader_dna',
       'assembly_beta_leader_dna', 'assembly_alpha_vdj_dna',
       'assembly_beta_vdj_dna', 'assembly_alpha_vdj_ragged_3p_dna',
       'assembly_beta_vdj_ragged_3p_dna', 'assembly_alpha_constant_fragment',
       'assembly_beta_constant_fragment',
       'assembly_alpha_vdj_only_constant_fragment_dna',
       'assembly_alpha_vdj_without_constant_fragment_dna',
       'assembly_beta_vdj_only_constant_fragment_dna',
       'assembly_beta_vdj_without_constant_fragment_dna',
       'alpha_constant_dna_from_reference', 'alpha_constant_dna',
       'alpha_constant_translated', 'beta_constant_dna_from_reference',
       'beta_constant_dna', 'beta_constant_translated', 'full_alpha_dna',
       'full_alpha_translated', 'full_beta_dna', 'full_beta_translated',
       'full_alpha_dna_has_start_codon', 'full_beta_dna_has_start_codon',
       'full_alpha_dna_ends_in_stop_codon', 'full_beta_dna_ends_in_stop_codon',
       'full_alpha_dna_frame', 'full_beta_dna_frame',
       'full_alpha_dna_without_last_codon',
       'full_alpha_without_last_codon_translated',
       'full_beta_dna_without_last_codon',
       'full_beta_without_last_codon_translated', 'T2A_linker',
       'T2A_linker_translated', 'single_chain_full_alpha_and_beta_with_linker',
       'single_chain_full_alpha_and_beta_with_linker_translated',
       'Peptide_Num', 'TCR_Num'],
      dtype='object')

In [376]:
[c for c in df_selected_full_seqs.columns if "constant" in c]

['assembly_alpha_constant_fragment',
 'assembly_beta_constant_fragment',
 'assembly_alpha_vdj_only_constant_fragment_dna',
 'assembly_alpha_vdj_without_constant_fragment_dna',
 'assembly_beta_vdj_only_constant_fragment_dna',
 'assembly_beta_vdj_without_constant_fragment_dna',
 'alpha_constant_dna_from_reference',
 'alpha_constant_dna',
 'alpha_constant_translated',
 'beta_constant_dna_from_reference',
 'beta_constant_dna',
 'beta_constant_translated']